"use client";
import Link from "next/link";
import {useState} from "react";

export default function CandidatePortalClient({sampleCandidateId}:{sampleCandidateId:string}){
  const[candidateId,setCandidateId]=useState("");
  const selected=candidateId.trim()||sampleCandidateId;
  const selfConfirmUrl=selected?`/candidate/self-confirm/${encodeURIComponent(selected)}`:"";
  return <main className="min-h-screen bg-[#05070A] text-slate-100">
    <header className="border-b border-slate-800 bg-[#070A0F] px-6 py-10"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-amber-500/30 bg-amber-500/10 px-3 py-1 text-xs text-amber-100">Preview only</span><span className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-300">No changes saved yet</span></div><h1 className="mt-5 text-4xl font-semibold">Candidate Portal</h1><p className="mt-2 text-xl text-cyan-100">Review and confirm your profile</p><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Check the information available to your recruiter, fill important gaps, and preview what would be sent for review. This demo does not save profile changes.</p></div></header>
    <section className="mx-auto max-w-5xl space-y-6 px-6 py-8">
      <div className="grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-6"><h2 className="text-lg font-semibold">What you can review</h2><ul className="mt-4 space-y-3 text-sm text-slate-300">{["Personal and contact information","Current title, company, and location","Missing profile details","Experience, skills, and SAP modules","Accuracy before recruiter submission"].map(item=><li key={item} className="flex gap-3"><span className="text-cyan-300">&check;</span><span>{item}</span></li>)}</ul></article><article className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-6"><h2 className="text-lg font-semibold">Current preview limitations</h2><ul className="mt-4 space-y-3 text-sm text-slate-300">{["Sign-in is not enabled yet","Submit remains preview-only","Changes are not saved","Conflicting edits may require recruiter review"].map(item=><li key={item} className="flex gap-3"><span className="text-amber-300">&bull;</span><span>{item}</span></li>)}</ul></article></div>
      <article className="rounded-2xl border border-slate-800 bg-[#0B0F16] p-6"><h2 className="text-lg font-semibold">Open your profile preview</h2><p className="mt-2 text-sm text-slate-400">Enter the candidate ID supplied by your recruiter. For this internal demo, a safe sample profile is available.</p><label className="mt-5 block text-sm text-slate-300">Candidate ID<input value={candidateId} onChange={event=>setCandidateId(event.target.value)} placeholder={sampleCandidateId||"Enter candidate ID"} className="mt-2 w-full rounded-lg border border-slate-700 bg-[#05070A] px-4 py-3 outline-none focus:border-cyan-400"/></label><div className="mt-4 flex flex-wrap items-center gap-3">{selfConfirmUrl?<Link href={selfConfirmUrl} className="rounded-lg bg-cyan-400 px-5 py-3 text-sm font-semibold text-slate-950">Review profile</Link>:<button disabled className="rounded-lg bg-slate-800 px-5 py-3 text-sm text-slate-500">Candidate ID required</button>}{!candidateId&&sampleCandidateId?<span className="text-xs text-slate-500">Using sample candidate: {sampleCandidateId}</span>:null}</div></article>
      <article className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6"><h2 className="font-semibold text-emerald-100">Candidate-facing safety</h2><div className="mt-3 grid gap-3 text-sm text-slate-300 md:grid-cols-3"><div>Only the candidate profile preview is shown.</div><div>Recruiter and admin tools are not linked here.</div><div>No database writes occur in preview.</div></div></article>
    </section>
  </main>;
}
