'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { buildConfirmedGuidedSearchHandoff } from '@/lib/guidedSourcingHandoff';
import { buildCompactGuidedReview,type CompactReviewItem } from '@/lib/guidedSourcingReview';
import type { GuidedCriterion,GuidedCriterionType,GuidedIntentResponse,GuidedSearchHandoff,GuidedSourcingPlan } from '@/lib/guidedSourcingTypes';
type SourceMode='paste'|'posted_job_jd'|'uploaded_jd';
type WorkspaceState='idle'|'source'|'review'|'prepared';
type JobOption={id:string;title:string;location:string;status:string;updatedDate:string|null;hasUsableJd:boolean};
type PlanBinding={sourceMode:SourceMode;sourceId:string;contentHash:string;requestId:number;identityVersion:number};
const TYPES:GuidedCriterionType[]=['target_role','sap_concept','must_have','nice_to_have','location','work_preference','seniority','minimum_years','preferred_years','industry','certification','project_context','exclusion','unresolved'];
const typeLabel=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
const preview=(v:string)=>v.length>700?`${v.slice(0,700)}...`:v;
function contentHash(v:string){let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(36);}
export default function GuidedSourcingPanel({onConfirm,onManualFallback,onWorkspaceStateChange}:{onConfirm:(handoff:GuidedSearchHandoff)=>void;onManualFallback:(brief:string)=>void;onWorkspaceStateChange?:(state:WorkspaceState)=>void}){
 const[open,setOpen]=useState(false),[editingMode,setEditingMode]=useState(false),[sourceMode,setSourceMode]=useState<SourceMode>('paste'),[pasteBrief,setPasteBrief]=useState(''),[jobs,setJobs]=useState<JobOption[]>([]),[selectedJobId,setSelectedJobId]=useState(''),[postedJobBrief,setPostedJobBrief]=useState(''),[postedJobLoading,setPostedJobLoading]=useState(false),[uploadedFile,setUploadedFile]=useState<File|null>(null),[uploadedBrief,setUploadedBrief]=useState(''),[uploadLoading,setUploadLoading]=useState(false),[plan,setPlan]=useState<GuidedSourcingPlan|null>(null),[planBinding,setPlanBinding]=useState<PlanBinding|null>(null),[loading,setLoading]=useState(false),[progress,setProgress]=useState(false),[error,setError]=useState(''),[sourceError,setSourceError]=useState(''),[editingId,setEditingId]=useState<string|null>(null),[whyId,setWhyId]=useState<string|null>(null);
 const latestRequest=useRef(0),identityVersion=useRef(0),modeRef=useRef<SourceMode>('paste'),active=useRef<AbortController|null>(null),generating=useRef(false);
 useEffect(()=>{if(!open)return;void fetch('/api/recruiter/search-v2/guided-source',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(p=>{if(Array.isArray(p?.jobs))setJobs(p.jobs);}).catch(()=>{});},[open]);
 useEffect(()=>()=>active.current?.abort(),[]);
 const invalidate=()=>{identityVersion.current+=1;latestRequest.current+=1;active.current?.abort();active.current=null;generating.current=false;setLoading(false);setProgress(false);setPlan(null);setPlanBinding(null);setEditingMode(false);setEditingId(null);setWhyId(null);setError('');setSourceError('');};
 function changeSource(next:SourceMode){if(next===modeRef.current)return;invalidate();modeRef.current=next;setSourceMode(next);}
 function closePanel(){invalidate();setOpen(false);onWorkspaceStateChange?.('idle');}
 const activeBrief=sourceMode==='paste'?pasteBrief:sourceMode==='posted_job_jd'?postedJobBrief:uploadedBrief;
 const activeSourceId=sourceMode==='paste'?'paste':sourceMode==='posted_job_jd'?selectedJobId:uploadedFile?`${uploadedFile.name}:${uploadedFile.size}:${uploadedFile.lastModified}`:'';
 const selectedJob=jobs.find(j=>j.id===selectedJobId);const canGenerate=Boolean(activeBrief.trim()&&activeSourceId&&!postedJobLoading&&!uploadLoading&&!loading);
 async function chooseJob(jobId:string){invalidate();setSelectedJobId(jobId);setPostedJobBrief('');if(!jobId)return;const requestId=++latestRequest.current,version=identityVersion.current,controller=new AbortController();active.current=controller;setPostedJobLoading(true);try{const r=await fetch('/api/recruiter/search-v2/guided-source',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId}),signal:controller.signal}),p=await r.json();if(controller.signal.aborted||modeRef.current!=='posted_job_jd'||requestId!==latestRequest.current||version!==identityVersion.current)return;if(!r.ok||typeof p.brief!=='string')throw new Error();setPostedJobBrief(p.brief);}catch{if(!controller.signal.aborted&&requestId===latestRequest.current)setSourceError('The selected job JD could not be loaded. Choose another job.');}finally{if(requestId===latestRequest.current){setPostedJobLoading(false);active.current=null;}}}
 async function chooseUpload(file:File|null){invalidate();setUploadedFile(file);setUploadedBrief('');if(!file)return;const requestId=++latestRequest.current,version=identityVersion.current,controller=new AbortController();active.current=controller;setUploadLoading(true);try{const data=new FormData();data.set('file',file);const r=await fetch('/api/recruiter/search-v2/guided-source',{method:'POST',body:data,signal:controller.signal}),p=await r.json();if(controller.signal.aborted||modeRef.current!=='uploaded_jd'||requestId!==latestRequest.current||version!==identityVersion.current)return;if(!r.ok||typeof p.brief!=='string')throw new Error();setUploadedBrief(p.brief);}catch{if(!controller.signal.aborted&&requestId===latestRequest.current)setSourceError('The uploaded JD could not be extracted safely. Choose a valid PDF, DOCX, or TXT file.');}finally{if(requestId===latestRequest.current){setUploadLoading(false);active.current=null;}}}
 function failureMessage(code:string){if(sourceMode==='posted_job_jd')return code==='GUIDED_UPSTREAM_TIMEOUT'?'AI guidance timed out. Your selected job is preserved.':'We couldn\'t prepare a plan from this job. Your selected job is preserved.';if(sourceMode==='uploaded_jd')return code==='GUIDED_UPSTREAM_TIMEOUT'?'AI guidance timed out. Your uploaded JD is preserved.':'We couldn\'t prepare a plan from this file. Your uploaded JD is preserved.';if(code==='GUIDED_UPSTREAM_TIMEOUT')return'AI guidance timed out. Your brief is preserved.';return'We couldn\'t prepare a plan from this brief. Your brief is preserved.';}
 async function generate(){if(!canGenerate||generating.current)return;generating.current=true;const submittedBrief=activeBrief.trim(),binding:PlanBinding={sourceMode,sourceId:activeSourceId,contentHash:contentHash(submittedBrief),requestId:++latestRequest.current,identityVersion:identityVersion.current};active.current?.abort();const controller=new AbortController();active.current=controller;setLoading(true);setProgress(false);setError('');setPlan(null);setPlanBinding(null);const timer=window.setTimeout(()=>setProgress(true),1000);try{const r=await fetch('/api/recruiter/search-v2/guided-intent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({brief:submittedBrief}),signal:controller.signal}),p=await r.json() as GuidedIntentResponse;const current=!controller.signal.aborted&&binding.requestId===latestRequest.current&&binding.identityVersion===identityVersion.current&&binding.sourceMode===modeRef.current&&binding.sourceId===activeSourceId&&binding.contentHash===contentHash(activeBrief.trim());if(!current)return;if(!r.ok||!p.ok){const code=!p.ok?p.error.code:'GUIDED_INTERNAL_ERROR';throw Object.assign(new Error(failureMessage(code)),{code});}setPlan(p.plan);setPlanBinding(binding);onWorkspaceStateChange?.('review');}catch(reason){if(!controller.signal.aborted&&binding.requestId===latestRequest.current)setError(reason instanceof Error?reason.message:failureMessage('GUIDED_INTERNAL_ERROR'));}finally{window.clearTimeout(timer);if(binding.requestId===latestRequest.current){generating.current=false;setLoading(false);setProgress(false);active.current=null;}}}
 function update(item:CompactReviewItem,patch:Partial<GuidedCriterion>,newValue?:string){setPlan(current=>current?{...current,criteria:current.criteria.map(c=>{if(!item.memberIds.includes(c.id))return c;if(newValue!==undefined&&c.id!==item.memberIds[0])return{...c,status:'removed'};return{...c,...patch,...(newValue!==undefined?{value:newValue}:{}),status:patch.status??'edited'};})}:current);}
 function add(){if(!plan)return;const id=`manual-${Date.now()}`;setPlan({...plan,criteria:[...plan.criteria,{id,type:'must_have',value:'',supportingExcerpt:'Recruiter-added criterion',reason:'Added during recruiter review.',confidence:1,status:'edited'}]});setEditingId(id);}
 const compact=useMemo(()=>plan?buildCompactGuidedReview(plan.criteria):null,[plan]);const allRows=compact?[...compact.summary,...compact.mustHave,...compact.niceToHave,...compact.additional,...compact.attention]:[];const editing=allRows.find(x=>x.id===editingId)||null;
 function confirm(){if(!plan||!planBinding||!compact||planBinding.identityVersion!==identityVersion.current||planBinding.sourceMode!==sourceMode)return setError('Generate a fresh plan for the active source.');if(compact.attention.length)return setError('Resolve or remove every item that needs attention before preparing Search.');try{const confirmed={...plan,criteria:plan.criteria.map(c=>c.status==='proposed'?{...c,status:'confirmed' as const}:c)};const handoff=buildConfirmedGuidedSearchHandoff(confirmed);handoff.provenance.sourceType=sourceMode==='paste'?'guided':sourceMode;onConfirm(handoff);setPlan(null);setPlanBinding(null);setOpen(false);onWorkspaceStateChange?.('prepared');setError('');}catch(e){setError(e instanceof Error?e.message:'Resolve every criterion before continuing.');}}
 const sourceLabel=sourceMode==='paste'?'Paste brief':sourceMode==='posted_job_jd'?`${selectedJob?.title||'Posted job'}${selectedJob?.location?' - '+selectedJob.location:''}`:uploadedFile?.name||'Uploaded JD';
 const summaryValue=(type:GuidedCriterionType)=>compact?.summary.find(x=>x.type===type)?.value;const role=summaryValue('target_role')||'Role needs review',location=summaryValue('location'),seniority=summaryValue('seniority'),years=summaryValue('minimum_years');
 const row=(item:CompactReviewItem,attention=false)=><div key={item.id} className='py-3 first:pt-2 last:pb-2'><div className='flex items-start gap-3'><span aria-hidden='true' className={attention?'mt-0.5 text-amber-300':'mt-0.5 text-emerald-300'}>{attention?'!':'\u2713'}</span><div className='min-w-0 flex-1'><p className='text-sm font-medium text-slate-100'>{item.value}</p>{item.capabilityChips?.length?<div className='mt-2 flex flex-wrap gap-1.5'>{item.capabilityChips.map(c=><span key={c} className='rounded-full bg-slate-800 px-2.5 py-1 text-xs text-slate-300'>{c}</span>)}</div>:null}{attention?<p className='mt-1 text-xs text-amber-200'>{item.ambiguityExplanation||'Recruiter review is required.'}</p>:null}<div className='mt-2 flex gap-3 text-xs'>{editingMode?<><button type='button' onClick={()=>setEditingId(item.id)} className='font-medium text-violet-300'>Edit</button><button type='button' onClick={()=>update(item,{status:'removed'})} className='text-slate-400 hover:text-rose-300'>Remove</button></>:null}<button type='button' aria-expanded={whyId===item.id} onClick={()=>setWhyId(whyId===item.id?null:item.id)} className='text-slate-500 hover:text-slate-300'>Why was this included?</button></div>{whyId===item.id?<div className='mt-2 border-l-2 border-slate-700 pl-3 text-xs text-slate-400'><p>{item.reason}</p><p className='mt-1'>Confidence {Math.round(item.confidence*100)}%</p>{item.supportingExcerpt?<p className='mt-1 text-slate-500'>&quot;{item.supportingExcerpt}&quot;</p>:<p className='mt-1 text-amber-300'>No verbatim supporting excerpt was verified.</p>}</div>:null}</div></div></div>;
 const group=(title:string,items:CompactReviewItem[],attention=false)=>items.length?<section className={attention?'border-t border-amber-700/30 pt-4':'border-t border-slate-800 pt-4'}><div className='mb-1 flex items-center gap-2'><h3 className='text-sm font-semibold text-slate-200'>{title}</h3><span className='rounded-full bg-slate-800 px-2 py-0.5 text-[11px] text-slate-400'>{items.length}</span></div><div className='divide-y divide-slate-800/70'>{items.map(i=>row(i,attention))}</div></section>:null;
 return <section className='mb-6 overflow-hidden rounded-2xl border border-violet-500/30 bg-slate-900/45'>
  <header className='flex flex-wrap items-center justify-between gap-3 px-5 py-4'><div><h2 className='text-base font-semibold text-white'>AI Guided Search <span className='ml-2 text-xs font-medium text-violet-300'>Optional preparation assistant</span></h2><p className='mt-1 text-sm text-slate-400'>Prepare criteria for the same deterministic Search V2 workspace.</p></div><button type='button' onClick={()=>open?closePanel():(setOpen(true),onWorkspaceStateChange?.('source'))} className='rounded-lg border border-violet-500/50 px-3 py-2 text-sm font-medium text-violet-100'>{open?'Close':'Start guided search'}</button></header>
  {open&&!plan?<div className='border-t border-slate-800 px-5 py-5'><p className='text-xs font-semibold uppercase tracking-wider text-violet-300'>Source</p><div className='mt-3 flex flex-wrap gap-2'>{([['paste','Paste brief'],['posted_job_jd','From posted job'],['uploaded_jd','Upload JD']] as const).map(([v,t])=><button key={v} type='button' aria-pressed={sourceMode===v} onClick={()=>changeSource(v)} className={sourceMode===v?'rounded-lg bg-violet-300 px-3 py-2 text-sm font-semibold text-slate-950':'rounded-lg bg-slate-800 px-3 py-2 text-sm text-slate-300'}>{t}</button>)}</div>
   <div className='mt-4'>{sourceMode==='paste'?<textarea aria-label='Paste brief' value={pasteBrief} onChange={e=>{invalidate();setPasteBrief(e.target.value);}} maxLength={12000} rows={7} placeholder='Paste a job description or hiring brief...' className='w-full rounded-xl border border-slate-700 bg-slate-950 p-4 text-sm text-white outline-none focus:border-violet-400'/>:null}{sourceMode==='posted_job_jd'?<div><select aria-label='Posted job JD' value={selectedJobId} onChange={e=>void chooseJob(e.target.value)} className='w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm'><option value=''>Select a posted job</option>{jobs.map(j=><option key={j.id} value={j.id} disabled={!j.hasUsableJd}>{j.title} - {j.location} - {j.status}{j.hasUsableJd?'':' - no usable JD'}</option>)}</select>{postedJobLoading?<p role='status' className='mt-2 text-sm text-violet-200'>Loading authorized job JD...</p>:postedJobBrief?<details className='mt-3 text-sm'><summary className='cursor-pointer text-slate-300'>View JD preview</summary><p className='mt-2 rounded-lg bg-slate-950/60 p-3 text-xs text-slate-400'>{preview(postedJobBrief)}</p></details>:null}</div>:null}{sourceMode==='uploaded_jd'?<div><input aria-label='Upload JD' type='file' accept='.pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain' onChange={e=>void chooseUpload(e.target.files?.[0]||null)} className='block w-full text-sm text-slate-300'/>{uploadLoading?<p role='status' className='mt-2 text-sm text-violet-200'>Extracting JD securely...</p>:uploadedBrief&&uploadedFile?<details className='mt-3 text-sm'><summary className='cursor-pointer text-slate-300'>{uploadedFile.name} - View extracted text</summary><p className='mt-2 rounded-lg bg-slate-950/60 p-3 text-xs text-slate-400'>{preview(uploadedBrief)}</p></details>:null}</div>:null}</div>
   {sourceError?<p role='alert' className='mt-3 text-sm text-rose-200'>{sourceError}</p>:null}{error?<p role='alert' className='mt-3 text-sm text-rose-200'>{error}</p>:null}<div className='mt-4 flex flex-wrap items-center gap-4'><button type='button' onClick={generate} disabled={!canGenerate} className='rounded-lg bg-violet-300 px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-40'>{loading?'Generating proposed plan...':error?'Retry generation':'Generate proposed plan'}</button><button type='button' onClick={()=>onManualFallback(activeBrief)} disabled={!activeBrief.trim()} className='text-sm text-cyan-300 disabled:opacity-40'>Use deterministic manual search</button></div>{loading?<p role='status' className='mt-2 text-sm text-violet-200'>{progress?'Reviewing the source and structuring criteria. Search has not started.':'Generating proposed plan...'}</p>:null}
  </div>:null}
  {open&&plan&&compact?<div className='border-t border-slate-800'><div className='px-5 py-5'><div className='flex flex-wrap items-center justify-between gap-3'><p className='text-xs font-semibold uppercase tracking-wider text-violet-300'>Review</p><details className='text-xs text-slate-400'><summary className='cursor-pointer'>Based on: {sourceLabel} - View source</summary><p className='mt-2 max-w-3xl rounded-lg bg-slate-950/70 p-3'>{preview(activeBrief)}</p></details></div><div className='mt-4'><h2 className='text-2xl font-semibold text-white'>{role}</h2><p className='mt-2 text-sm text-slate-300'>{[location,seniority,years?`${years}+ years`:null,`Based on ${sourceMode==='paste'?'pasted brief':sourceMode==='posted_job_jd'?'posted job':'uploaded JD'}`].filter(Boolean).join(' \u00B7 ')}</p></div>
   <div className='mt-6 space-y-5'>{group('Must have',compact.mustHave)}{group('Nice to have',compact.niceToHave)}{group('Additional filters',compact.additional)}{group('Needs attention',compact.attention,true)}</div><p className='mt-5 text-xs text-slate-400'>{compact.countBreakdown}</p>
   {editing?<aside aria-label='Edit selected criterion' className='mt-5 rounded-xl bg-slate-950/70 p-4'><div className='flex items-center justify-between'><h3 className='font-semibold text-white'>Edit criterion</h3><button type='button' onClick={()=>setEditingId(null)} className='text-sm text-slate-400'>Done</button></div><div className='mt-3 grid gap-3 md:grid-cols-[12rem_minmax(0,1fr)]'><label className='text-xs text-slate-400'>Criterion type<select aria-label='Edit criterion type' value={editing.type} onChange={e=>update(editing,{type:e.target.value as GuidedCriterionType,ambiguityExplanation:undefined})} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-2.5 text-sm text-white'>{TYPES.map(t=><option key={t} value={t}>{typeLabel(t)}</option>)}</select></label><label className='text-xs text-slate-400'>Criterion value<input aria-label='Edit criterion value' value={editing.value} onChange={e=>update(editing,{ambiguityExplanation:undefined},e.target.value)} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-2.5 text-sm text-white'/></label></div></aside>:null}
   {error?<p role='alert' className='mt-4 text-sm text-rose-200'>{error}</p>:null}</div><footer className='sticky bottom-0 z-20 flex flex-wrap items-center justify-between gap-3 border-t border-slate-700 bg-slate-950/95 px-5 py-4 shadow-2xl'><button type='button' onClick={()=>{setPlan(null);setPlanBinding(null);setEditingMode(false);setEditingId(null);setWhyId(null);setError('');onWorkspaceStateChange?.('source');}} className='text-sm font-medium text-slate-300'>Back / change source</button><div className='flex flex-wrap items-center gap-3'>{compact.attention.length?<span role='status' className='text-sm text-amber-200'>Resolve {compact.attention.length} {compact.attention.length===1?'item':'items'} to continue</span>:null}{editingMode?<button type='button' onClick={add} className='rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200'>Add criterion</button>:null}<button type='button' onClick={()=>{setEditingMode(current=>!current);setEditingId(null);}} className='rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200'>{editingMode?'Finish editing':compact.attention.length?'Review issues':'Edit criteria'}</button><button type='button' onClick={confirm} disabled={compact.attention.length>0||compact.includedCount===0} className='rounded-lg bg-violet-300 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-40'>Confirm {compact.includedCount} criteria and prepare Search</button></div></footer></div>:null}
 </section>;
}
