"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { buildCandidateHiringOpinion, type HiringDecisionState } from "@/lib/candidate360Opinion";
import type { Candidate360Profile } from "@/lib/candidate360Types";

const action = "inline-flex min-h-10 items-center justify-center rounded-lg border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-200 transition hover:border-slate-500 hover:bg-slate-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-300";
const recruiterActions: HiringDecisionState[] = ["Interview", "Hold", "Reject", "Need Validation"];

export default function ExecutiveHiringDecision({ profile, job }: { profile: Candidate360Profile; job: Record<string, unknown> | null }) {
  const [shared, setShared] = useState(false);
  const [recruiterDecision, setRecruiterDecision] = useState<string | null>(null);
  const opinion = useMemo(() => buildCandidateHiringOpinion(profile, job), [profile, job]);
  const enterprise = profile.enterpriseProfile;
  const decision = opinion.jobDecision;
  const roles = Array.from(new Set(enterprise.intelligence.insights.idealRoles.filter(Boolean)));
  const bestFit = roles[0] || enterprise.identity.currentTitle || "Role evidence requires validation";
  const query = `candidateId=${encodeURIComponent(profile.candidateId)}${decision?.job.id ? `&jobId=${encodeURIComponent(decision.job.id)}` : ""}`;
  const share = async () => {
    const data = { title: `${enterprise.identity.name || "Candidate"} hiring decision`, text: `${opinion.finalDecision} · Confidence ${opinion.confidence}% · ${opinion.headline}`, url: window.location.href };
    if (navigator.share) await navigator.share(data); else await navigator.clipboard.writeText(`${data.title}\n${data.text}\n${data.url}`);
    setShared(true); window.setTimeout(() => setShared(false), 1800);
  };
  const displayedDecision = opinion.mode === "job_fit" ? opinion.roleFit.decision : opinion.candidateReadiness.decision;
  const displayedConfidence = opinion.mode === "job_fit" ? opinion.roleFit.confidence : opinion.candidateReadiness.confidence;
  const tone = displayedDecision === "Interview" || displayedDecision === "Proceed to Recruiter Screening" ? "text-emerald-300" : displayedDecision === "Hold" ? "text-blue-300" : displayedDecision === "Reject" ? "text-rose-300" : "text-amber-300";
  return <section aria-labelledby="executive-hiring-decision-title" className="flex max-h-[calc(100vh-8rem)] min-h-[560px] flex-col overflow-hidden rounded-2xl border border-slate-700/90 bg-[#0B0F16] shadow-2xl shadow-black/30">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 px-5 py-4"><div><div className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-400">{opinion.mode === "job_fit" ? "Role-specific decision" : "Candidate readiness opinion"}</div><h2 id="executive-hiring-decision-title" className="mt-1 text-xl font-semibold text-white">Executive Opinion</h2></div>{decision ? <div className="text-right"><div className="text-[10px] uppercase tracking-wide text-slate-500">Selected Job</div><div className="mt-1 text-sm font-medium text-slate-200">{decision.job.title}</div></div> : <span className="rounded-lg border border-blue-600/30 bg-blue-950/20 px-3 py-2 text-xs text-blue-200">Role fit: Job Required</span>}</header>
    <div className="min-h-0 flex-1 overflow-y-auto p-5"><div className="grid gap-3 lg:grid-cols-[1.25fr_.75fr]"><article className="rounded-xl border border-slate-700 bg-black/20 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{opinion.mode === "job_fit" ? "Role-fit recommendation" : "Candidate readiness"}</div><div className={`mt-2 text-2xl font-semibold ${tone}`}>{displayedDecision}</div><p className="mt-1 text-sm font-medium text-slate-200">{opinion.headline}</p></div><div className="text-right"><div className="text-[10px] uppercase tracking-wide text-slate-500">Confidence</div><div className="mt-1 text-lg font-semibold text-white">{displayedConfidence === null ? "Not assessed" : `${displayedConfidence}%`}</div></div></div><div className="mt-3 space-y-1">{opinion.opinion.map((line) => <p key={line} className="text-xs leading-5 text-slate-400">{line}</p>)}</div></article><div className="grid grid-cols-2 gap-3"><Metric label="Role-fit risk" value={opinion.roleFit.hiringRisk}/><Metric label="Role fit" value={opinion.roleFit.decision}/><Metric label="Role-fit confidence" value={opinion.roleFit.confidence === null ? "Not assessed" : `${opinion.roleFit.confidence}%`}/><Metric label="Best fit" value={bestFit}/></div></div>
      <div className="mt-3 grid gap-3 lg:grid-cols-3"><CompactList title="Why AI recommends this" items={opinion.strengths} empty="Not enough verified positive signals for a recommendation."/><CompactList title="Primary concerns" items={opinion.risks} empty="No confirmed mismatch or material risk is established."/><CompactList title="Missing evidence" items={opinion.missingEvidence} empty="No material evidence gap is currently registered."/></div>
      <details className="mt-3 rounded-xl border border-slate-800 bg-black/20 p-4"><summary className="cursor-pointer text-xs font-semibold text-cyan-300">View reasoning, evidence and next action</summary><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><h3 className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Next action</h3><p className="mt-2 text-sm leading-6 text-slate-300">{opinion.nextAction}</p><h3 className="mt-4 text-[10px] font-semibold uppercase tracking-wide text-slate-500">Validation focus</h3>{opinion.validationFocus.length ? <ul className="mt-2 space-y-1">{opinion.validationFocus.map((item) => <li key={item} className="text-xs leading-5 text-slate-300">• {item}</li>)}</ul> : <p className="mt-2 text-xs text-slate-400">No additional validation focus is established.</p>}</div><div><h3 className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">Explainability audit</h3><div className="mt-2 space-y-2">{opinion.dimensions.slice(0, 5).map((item) => <details key={item.label} className="rounded-lg border border-slate-800 p-3"><summary className="cursor-pointer text-xs font-medium text-slate-200">{item.label} · {item.score === null ? "Evidence limited" : `${item.score}/100`} · {item.confidence === null ? "Confidence requires evidence" : `${item.confidence}% confidence`}</summary><p className="mt-2 text-xs leading-5 text-slate-400">{item.conclusion}</p>{item.evidence.length ? <ul className="mt-2 space-y-1">{item.evidence.slice(0, 3).map((evidence) => <li key={`${evidence.sourceRef}-${evidence.label}`} className="text-xs text-slate-300">• {evidence.label}<span className="ml-1 rounded border border-slate-700 px-1 py-0.5 text-[10px] text-slate-500" title={evidence.provenance?.limitations.join(" ")}>{evidence.provenance?.sourceLabel || evidence.sourceType} · {evidence.provenance?.strength || "unrated"}</span></li>)}</ul> : null}<p className="mt-2 text-xs text-cyan-300">Next: {item.nextAction}</p></details>)}</div></div></div></details>
    </div>
    <footer className="border-t border-slate-800 bg-[#080C12] px-4 py-3"><div className="flex flex-wrap items-center gap-2">{opinion.mode === "job_fit" ? <div className="flex gap-1" role="group" aria-label="Role-fit recruiter decision">{recruiterActions.map((value) => <button key={value} type="button" aria-pressed={recruiterDecision === value} onClick={() => setRecruiterDecision(value)} className={`${action} ${recruiterDecision === value ? "border-cyan-400 bg-cyan-950/30 text-cyan-200" : ""}`}>{value}</button>)}</div> : <button type="button" aria-pressed={recruiterDecision === "Proceed to Recruiter Screening"} onClick={() => setRecruiterDecision("Proceed to Recruiter Screening")} className={`${action} ${recruiterDecision ? "border-cyan-400 bg-cyan-950/30 text-cyan-200" : ""}`}>Proceed to Recruiter Screening</button>}<Link href={`/recruiter/submission-generator?${query}`} className="inline-flex min-h-10 items-center justify-center rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-white">Generate Submission</Link><Link href={`/recruiter/client-report?${query}`} className={action}>Export Hiring Report</Link><Link href={`/recruiter/interview-prep?${query}`} className={action}>Generate Interview Questions</Link><button type="button" onClick={share} className={action}>Share</button><span aria-live="polite" className="ml-auto text-xs text-emerald-300">{shared ? "Decision link copied" : recruiterDecision ? `${recruiterDecision} selected locally` : ""}</span></div></footer>
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-800 bg-black/20 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-2 text-xs font-semibold leading-5 text-slate-100">{value}</div></div>; }
function CompactList({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <article className="rounded-xl border border-slate-800 bg-black/20 p-4"><h3 className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{title}</h3>{items.length ? <ul className="mt-2 space-y-1">{items.slice(0, 4).map((item) => <li key={item} className="line-clamp-1 text-xs leading-5 text-slate-300">• {item}</li>)}</ul> : <p className="mt-2 text-xs leading-5 text-slate-400">{empty}</p>}</article>; }


