import Link from "next/link";import {buildStagingEvidenceApprovalPack} from "../../../lib/stagingEvidenceApproval";
const card="rounded-2xl border border-slate-800 bg-[#0B0F16] p-5",badge="rounded-full border border-slate-700 px-3 py-1 text-xs";
export default function StagingEvidencePage(){const p=buildStagingEvidenceApprovalPack(),count=(s:string)=>p.evidenceItems.filter(x=>x.status===s).length;return <main className="min-h-screen bg-[#05070A] text-slate-100"><header className="border-b border-slate-800 px-6 py-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap gap-2">{["Read-only","Manual approval required","No secret values","No Supabase calls","Production blocked"].map(x=><span className={badge} key={x}>{x}</span>)}</div><h1 className="mt-5 text-4xl font-semibold">Staging Evidence &amp; Approval</h1><p className="mt-2 text-slate-300">Review the evidence, fingerprints, ownership rules, rollback requirements, and manual approvals required before staging auth implementation.</p></div></header><div className="mx-auto max-w-7xl space-y-8 px-6 py-8">
<section className={card}><h2 className="text-xl font-semibold">Staging Auth Preflight CLI available</h2><p className="mt-3">Execution gate remains authoritative � Implementation not started � Production blocked</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-execution-gate">Open preflight guidance</Link></section><section className={card}><h2 className="text-xl font-semibold">Execution gate available</h2><p className="mt-3">Locked by default � No capabilities enabled.</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-execution-gate">Open Execution Gate</Link></section><section className={card}><h2 className="text-xl font-semibold">Runbook available</h2><p className="mt-3">Status: blocked pending evidence � Commands executed: 0</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-runbook">Open Staging Runbook</Link></section><section className={card}><h2 className="text-xl font-semibold">Executive status</h2><p className="mt-3">Overall: {p.status} · Evidence available: {p.evidenceItems.length-p.blockingEvidence.length} · Blocking/manual evidence: {p.blockingEvidence.length} · Approvals pending: {p.approvals.filter(x=>x.status!=="approved_preview").length} · Staging implementation approved: no · Production blocked: yes</p></section>
<section><h2 className="text-xl font-semibold">Evidence progress</h2><div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Total",p.evidenceItems.length],["Verified",count("verified_preview")],["Available",count("available_for_review")],["Manual",count("requires_manual_confirmation")],["Missing",count("missing")],["Blocked",count("blocked")]].map(([a,b])=><div className={card} key={a}><p className="text-xs text-slate-500">{a}</p><p className="mt-2 text-2xl">{b}</p></div>)}</div></section>
<section><h2 className="text-xl font-semibold">Environment and secret evidence</h2><p className="mt-2 text-amber-200">Values are intentionally never inspected or shown. Documented variable names: {p.environmentEvidence.requiredVariableNamesDocumented.join(", ")}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{p.evidenceItems.filter(x=>x.category==="environment"||x.category==="secrets").map(x=><article className={card} key={x.evidenceKey}><h3>{x.label}</h3><p className="text-sm text-slate-400">{x.status} · {x.sourceType}</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Migration and RLS evidence</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{[["Migration",p.sqlEvidence.migrationPreviewRoute,p.sqlEvidence.migrationFingerprint,p.sqlEvidence.migrationArtifactAvailable],["RLS",p.sqlEvidence.rlsPreviewRoute,p.sqlEvidence.rlsFingerprint,p.sqlEvidence.rlsArtifactAvailable]].map(([label,route,fingerprint,available])=><article className={card} key={String(label)}><h3 className="font-semibold">{label}</h3><p className="mt-2">Preview available: {available?"yes":"no"} · Manually reviewed: no · Execution: Not executed</p><p className="mt-2 break-all text-xs text-slate-500">SHA-256: {String(fingerprint)}</p><Link className="text-cyan-300" href={String(route)}>Open source preview</Link></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Ownership evidence</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{p.ownershipEvidence.roles.map(role=><article className={card} key={role}><h3>{role}</h3><p className="text-sm text-slate-400">Defined for review · Manual approval pending</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Backup and rollback evidence</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{p.evidenceItems.filter(x=>x.category==="backup"||x.category==="rollback").map(x=><article className={card} key={x.evidenceKey}><h3>{x.label}</h3><p className="text-sm text-slate-400">{x.status}</p></article>)}</div></section>
<section className={card}><h2 className="text-xl font-semibold">Smoke-test evidence</h2><p className="mt-3">Expected: {p.smokeTestEvidence.expectedTestCount} · Executed: 0 · Passed: 0 · Failed: 0 · Roles: {p.smokeTestEvidence.roleCoverage.join(", ")} · Isolation: {p.smokeTestEvidence.ownershipCoverage.join(", ")} · Status: not executed</p></section>
<section><h2 className="text-xl font-semibold">Approval matrix</h2><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Approval","Required role","Required evidence","Status","Approved by","Approved at"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{p.approvals.map(x=><tr className="border-t border-slate-800" key={x.approvalKey}><td className="p-3">{x.label}</td><td>{x.requiredRole}</td><td>{x.requiredEvidenceKeys.join(", ")||"All required evidence"}</td><td>{x.status}</td><td>—</td><td>—</td></tr>)}</tbody></table></div></section>
<section><h2 className="text-xl font-semibold">Blocking evidence</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{p.blockingEvidence.map(x=><article className={card} key={x.evidenceKey}><span className={badge}>{x.status}</span><h3 className="mt-3">{x.label}</h3><p className="text-sm text-slate-400">{x.nextAction}</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Next actions</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{p.nextActions.map(x=><article className={card} key={x.actionKey}><span className={badge}>{x.priority}</span><h3 className="mt-3">{x.label}</h3><p className="text-sm text-slate-400">{x.reason}</p>{x.route&&<Link className="text-cyan-300" href={x.route}>Open preview</Link>}</article>)}</div></section>
<section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-semibold">Safety panel</h2><p className="mt-2 text-sm">No secret values inspected · No environment files modified · No approval DB writes · No SQL/migration/RLS executed · No middleware · No sessions/cookies · No DB writes · No email sends · No OpenAI calls · Production blocked</p></section></div></main>}

