"use server";
import {executeGetProfile,executeGetSession,executeGetUser,executeInvitationAccept,executePasswordReset,executeRefreshSession,executeSignIn,executeSignOut} from "../../lib/stagingAuthOperationServiceServer";import {buildStagingAuthUiActionState} from "../../lib/stagingAuthUiBinding";import type {StagingAuthUiActionState} from "../../lib/stagingAuthUiBindingTypes";
const base=<T extends "sign_in"|"sign_out"|"request_password_reset"|"accept_invitation"|"get_session"|"get_user"|"get_profile"|"refresh_session">(operation:T)=>({requestId:`ui-binding-preview-${operation}`,operation,source:"auth_ui_future" as const,requestedAt:"1970-01-01T00:00:00.000Z",simulationOnly:true,productionAllowed:false as const});
export async function previewStagingSignInAction(_previousState:StagingAuthUiActionState,formData:FormData){return buildStagingAuthUiActionState(executeSignIn({...base("sign_in"),email:String(formData.get("email")||""),password:String(formData.get("password")||"")}))}
export async function previewStagingSignOutAction(_previousState?:StagingAuthUiActionState,_formData?:FormData){return buildStagingAuthUiActionState(executeSignOut(base("sign_out")))}
export async function previewStagingPasswordResetAction(_previousState:StagingAuthUiActionState,formData:FormData){return buildStagingAuthUiActionState(executePasswordReset({...base("request_password_reset"),email:String(formData.get("email")||"")}))}
export async function previewStagingInvitationAction(_previousState:StagingAuthUiActionState,formData:FormData){return buildStagingAuthUiActionState(executeInvitationAccept({...base("accept_invitation"),invitationToken:String(formData.get("invitationToken")||"")}))}
export async function previewStagingSessionAction(_previousState?:StagingAuthUiActionState,_formData?:FormData){return buildStagingAuthUiActionState(executeGetSession(base("get_session")))}
export async function previewStagingUserAction(_previousState?:StagingAuthUiActionState,_formData?:FormData){return buildStagingAuthUiActionState(executeGetUser(base("get_user")))}
export async function previewStagingProfileAction(_previousState?:StagingAuthUiActionState,_formData?:FormData){return buildStagingAuthUiActionState(executeGetProfile(base("get_profile")))}
export async function previewStagingRefreshAction(_previousState?:StagingAuthUiActionState,_formData?:FormData){return buildStagingAuthUiActionState(executeRefreshSession(base("refresh_session")))}
