"use client";
import {useActionState,useEffect,useRef} from "react";import {buildInitialStagingAuthUiActionState} from "../../lib/stagingAuthUiBinding";import {previewStagingInvitationAction,previewStagingPasswordResetAction,previewStagingProfileAction,previewStagingRefreshAction,previewStagingSessionAction,previewStagingSignInAction,previewStagingSignOutAction,previewStagingUserAction} from "./staging-actions";import {StagingAuthResultPanel} from "./StagingAuthResultPanel";
const card="rounded-2xl border border-slate-800 bg-[#0B0F16] p-6",input="w-full rounded-lg border border-slate-700 bg-slate-950 p-3",button="mt-5 w-full rounded-lg bg-cyan-300 px-4 py-3 font-semibold text-slate-950 disabled:opacity-50";
function Warning(){return <p className="mb-4 rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-amber-100">Preview only. Do not enter real credentials.</p>}
export function StagingSignInPreviewForm(){const [state,action,pending]=useActionState(previewStagingSignInAction,buildInitialStagingAuthUiActionState("sign_in")),ref=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.submitted)ref.current?.reset()},[state]);return <section className={card}><Warning/><form action={action} ref={ref}><label className="block text-sm">Email<input autoComplete="off" className={input+" mt-2"} name="email" type="email" required/></label><label className="mt-4 block text-sm">Password<input autoComplete="new-password" className={input+" mt-2"} name="password" type="password" required/></label><button className={button} disabled={pending}>{pending?"Running safe preview…":"Run sign-in preview"}</button></form><StagingAuthResultPanel state={state}/></section>}
export function StagingPasswordResetPreviewForm(){const [state,action,pending]=useActionState(previewStagingPasswordResetAction,buildInitialStagingAuthUiActionState("request_password_reset")),ref=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.submitted)ref.current?.reset()},[state]);return <section className={card}><Warning/><p className="mb-4 text-sm text-slate-400">No password-reset email will be sent.</p><form action={action} ref={ref}><label className="block text-sm">Email<input autoComplete="off" className={input+" mt-2"} name="email" type="email" required/></label><button className={button} disabled={pending}>{pending?"Running safe preview…":"Run reset preview"}</button></form><StagingAuthResultPanel state={state}/></section>}
export function StagingInvitationPreviewForm(){const [state,action,pending]=useActionState(previewStagingInvitationAction,buildInitialStagingAuthUiActionState("accept_invitation")),ref=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.submitted)ref.current?.reset()},[state]);return <section className={card}><Warning/><p className="mb-4 text-sm text-slate-400">Invitation tokens are never validated or stored in this preview.</p><form action={action} ref={ref}><label className="block text-sm">Invitation token<input autoComplete="off" className={input+" mt-2"} name="invitationToken" type="password" required/></label><button className={button} disabled={pending}>{pending?"Running safe preview…":"Run invitation preview"}</button></form><StagingAuthResultPanel state={state}/></section>}
export function StagingSignOutPreviewForm(){const [state,action,pending]=useActionState(previewStagingSignOutAction,buildInitialStagingAuthUiActionState("sign_out"));return <section className={card}><Warning/><form action={action}><button className={button} disabled={pending}>{pending?"Running safe preview…":"Run sign-out preview"}</button></form><p className="mt-3 text-sm text-slate-400">No cookie is read or cleared and no session is invalidated.</p><StagingAuthResultPanel state={state}/></section>}
function DiagnosticButton({label,operation,action}:{label:string;operation:"get_session"|"get_user"|"get_profile"|"refresh_session";action:(previousState:ReturnType<typeof buildInitialStagingAuthUiActionState>,formData:FormData)=>Promise<ReturnType<typeof buildInitialStagingAuthUiActionState>>}){const [state,formAction,pending]=useActionState(action,buildInitialStagingAuthUiActionState(operation));return <article className={card}><form action={formAction}><button className={button+" mt-0"} disabled={pending}>{pending?"Running safe preview…":label}</button></form><StagingAuthResultPanel state={state}/></article>}
export function StagingAuthDiagnosticPreview(){return <section><h2 className="text-xl font-semibold">Auth Diagnostic Preview</h2><p className="mt-2 text-sm text-slate-400">No session, cookie, database, or real identity operation occurs.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><DiagnosticButton action={previewStagingSessionAction} label="Get Session" operation="get_session"/><DiagnosticButton action={previewStagingUserAction} label="Get User" operation="get_user"/><DiagnosticButton action={previewStagingProfileAction} label="Get Profile" operation="get_profile"/><DiagnosticButton action={previewStagingRefreshAction} label="Refresh Session" operation="refresh_session"/></div></section>}
