import {buildRecruiterDashboard} from "./recruiterDashboard";
import type {AdminAuditCenterPreview,AdminAuthSecurityCenterPreview,AdminCandidateConfirmationQueuePreview,AdminDataOperationPreview,AdminNextBestActionPreview,AdminPortalMvpPreview,AdminPortalMvpSafety,AdminPortalSummaryPreview,AdminProductHealthPreview,AdminSafetyControlPreview,AdminWorkflowOversightPreview} from "./adminPortalMvpTypes";
type Params={adminName?:string;adminRole?:string;baseDir?:string};
const SAFETY:AdminPortalMvpSafety={candidateDbWrites:0,jobDbWrites:0,clientDbWrites:0,userDbWrites:0,workflowWrites:0,importApplyWrites:0,mergeApplyWrites:0,quickFixApplyWrites:0,authCalls:0,migrationExecuted:0,rlsExecuted:0,emailSends:0,openAiCalls:0,middlewareEnforced:false};
const dashboard=(params:Params={})=>buildRecruiterDashboard(params.baseDir);
export function buildAdminProductHealthPreview(params:Params={}):AdminProductHealthPreview{const data=dashboard(params);return{status:"healthy",totalCandidates:data.summary.totalCandidates,readyForShortlist:data.summary.readyForShortlist,needsRepair:data.summary.needsRepair,routeAuditPassed:true,safetyPolicyPresent:true,manualCleanupFrozen:true,mainDbDeletionAllowed:false,fullReuploadAllowed:false,openAiCalls:0,candidateDbWrites:0};}
export function buildAdminSafetyControlsPreview():AdminSafetyControlPreview[]{return[["delete_main_db","Delete main candidate DB","Protected production data cannot be deleted.","/recruiter/dashboard#product-health"],["full_reupload","Full reupload into main DB","All uploads must remain staged.","/recruiter/import-staging"],["apply_import_merge","Apply import merge","Merge apply requires a separately approved workflow.","/recruiter/import-merge"],["apply_quick_fix","Apply quick fix","Quick-fix apply is outside this preview.","/recruiter/workflow"],["apply_self_confirm","Apply candidate self-confirm","Candidate changes require recruiter review and an enabled apply workflow.","/recruiter/candidate-self-confirm-review"],["run_migration","Run migration","Migration SQL is review-only.","/auth/migrations"],["enable_middleware","Enable middleware","Route decisions remain advisory.","/auth/middleware"],["send_emails","Send emails","Email delivery is disabled.","/auth/staging"]].map(([controlKey,label,reason,relatedRoute])=>({controlKey,label,reason,relatedRoute,enabledNow:false,blocked:true}));}
export function buildAdminPortalSummaryPreview(params:Params={}):AdminPortalSummaryPreview{const health=buildAdminProductHealthPreview(params);return{totalCandidates:health.totalCandidates,readyForShortlist:health.readyForShortlist,needsRepair:health.needsRepair,routeAuditPassed:health.routeAuditPassed,productHealthStatus:health.status,featureAuditsPassed:9,adminDataRoutes:4,authPlanningRoutes:8,pendingCandidateConfirmations:dashboard(params).summary.needsCandidateConfirmation,dataQualityAlertCount:health.needsRepair,destructiveActionsBlocked:buildAdminSafetyControlsPreview().length};}
export function buildAdminDataOperationsPreview():AdminDataOperationPreview[]{return[["import-staging","Import Staging","/recruiter/import-staging","Inspect staged uploads before merge.","medium",true],["merge-review","Merge Review","/recruiter/import-merge","Review deterministic merge proposals.","high",true],["workflow","Data Workflow","/recruiter/workflow","Inspect quality and workflow state.","medium",false],["candidate-confirmation","Candidate Confirmation Review","/recruiter/candidate-self-confirm-review","Review candidate-submitted preview changes.","high",true],["repair-queue","Repair Queue / Quality Alerts","/recruiter/workflow","Prioritize profiles needing repair.","high",true],["product-health","Product Health","/recruiter/dashboard#product-health","Review route, audit, and safety status.","low",false]].map(([id,label,route,purpose,riskLevel,requiresApproval])=>({id:id as string,label:label as string,route:route as string,purpose:purpose as string,status:"available_preview",riskLevel:riskLevel as AdminDataOperationPreview["riskLevel"],dbWritesEnabled:false,requiresApproval:Boolean(requiresApproval),safetyNotes:["Read-only preview.","Apply and write actions remain disabled."]}));}
export function buildAdminWorkflowOversightPreview(params:Params={}):AdminWorkflowOversightPreview{const data=dashboard(params);return{workflowRoute:"/recruiter/workflow",needsRepair:data.summary.needsRepair,readyForShortlist:data.summary.readyForShortlist,repairQueuePreview:"available_preview",importStagingPreview:"available_preview",mergeReviewPreview:"available_preview",applyActionsDisabled:true};}
export function buildAdminCandidateConfirmationQueuePreview(params:Params={}):AdminCandidateConfirmationQueuePreview{return{route:"/recruiter/candidate-self-confirm-review",pendingPreviewCount:dashboard(params).summary.needsCandidateConfirmation,recruiterReviewRequired:true,candidateApplyDisabled:true,safetyNotes:["Recruiter review is required.","No candidate update is applied."]};}
export function buildAdminAuthSecurityCenterPreview():AdminAuthSecurityCenterPreview{return{roleAccessRoute:"/auth/preview",authSetupRoute:"/auth/setup",migrationPreviewRoute:"/auth/migrations",rlsPreviewRoute:"/auth/rls",authHelpersRoute:"/auth/helpers",middlewareRoute:"/auth/middleware",mockSessionRoute:"/auth/mock-session",stagingPlanRoute:"/auth/staging",realAuthEnabled:false,middlewareEnforced:false,productionBlocked:true};}
export function buildAdminAuditCenterPreview():AdminAuditCenterPreview{return{audits:["Product health","UI routes","Role-based UX","Recruiter portal","Client portal","Candidate portal","Auth/security","Data import/merge","Candidate quality"],lastRunStatus:"preview_only",reportsDirectory:"reports/",routeAuditPassed:true,productHealthHealthy:true,noUnsafeRoutes:true};}
export function buildAdminNextBestActionsPreview():AdminNextBestActionPreview[]{return[["health","Review product health","Confirm route and safety signals.","/recruiter/dashboard#product-health"],["quality","Review data quality alerts","Prioritize profiles needing repair.","/recruiter/workflow"],["confirmations","Review candidate confirmations","Inspect pending candidate updates.","/recruiter/candidate-self-confirm-review"],["imports","Review import and merge queues","Keep incoming changes staged.","/recruiter/import-staging"],["auth","Review auth staging plan","Confirm production remains blocked.","/auth/staging"],["audits","Run audit suite before release","Verify safety and route compatibility.","/admin/portal#audit-center"]].map(([id,label,reason,href])=>({id,label,reason,href,enabledNow:false,status:"preview_only"}));}
export function buildAdminPortalMvpPreview(params:Params={}):AdminPortalMvpPreview{return{adminName:params.adminName?.trim()||"Admin Preview",adminRole:params.adminRole?.trim()||"admin",summary:buildAdminPortalSummaryPreview(params),productHealth:buildAdminProductHealthPreview(params),dataOperations:buildAdminDataOperationsPreview(),workflowOversight:buildAdminWorkflowOversightPreview(params),candidateConfirmationQueue:buildAdminCandidateConfirmationQueuePreview(params),authSecurityCenter:buildAdminAuthSecurityCenterPreview(),auditCenter:buildAdminAuditCenterPreview(),safetyControls:buildAdminSafetyControlsPreview(),nextBestActions:buildAdminNextBestActionsPreview(),safety:{...SAFETY}};}
export function validateAdminPortalMvpPreview(params:Params={}){const preview=buildAdminPortalMvpPreview(params);return{valid:preview.adminRole==="admin"&&preview.dataOperations.length===6&&preview.safetyControls.every(item=>item.blocked&&!item.enabledNow)&&Object.values(preview.safety).every(value=>value===0||value===false),preview};}
