import type {AuthEnvironmentCheck,AuthReadinessCategory,AuthSetupPreviewState,InviteFlowPreview,OrganizationOwnershipPreview,OwnershipModelPreview,RoleMappingPreview,UserProfileSchemaPreview} from "./authSetupTypes";import type {AccessArea,UserRole} from "./roleAccessTypes";
const ENVIRONMENT=[["NEXT_PUBLIC_SUPABASE_URL",true,"Public Supabase project URL."],["NEXT_PUBLIC_SUPABASE_ANON_KEY",true,"Public anonymous key; value remains hidden."],["SUPABASE_SERVICE_ROLE_KEY",true,"Server-only service key; value is never returned or printed."],["NEXT_PUBLIC_APP_URL",true,"Public application base URL."],["AUTH_REDIRECT_URL",false,"Future authentication redirect URL."],["AUTH_INVITE_SECRET",false,"Future server-only invite token secret."]] as const;
const placeholder=(value:string)=>!value.trim()||/^(your_|replace|placeholder|changeme|example|https?:\/\/your-|xxx)/i.test(value.trim());
export function buildAuthEnvironmentChecks(env:Record<string,string|undefined>=process.env):AuthEnvironmentCheck[]{return ENVIRONMENT.map(([key,requiredEventually,description])=>{const value=env[key],present=typeof value==="string"&&value.trim().length>0,status:AuthEnvironmentCheck["status"]=!present?"missing":placeholder(value)?"placeholder":"configured";return{key,requiredEventually,present,safeToPrint:false,status,description};});}
export function buildUserProfileSchemaPreview():UserProfileSchemaPreview{const optional=new Set(["client_id","candidate_id","invited_by"]);return{tableName:"user_profiles",fields:["id","auth_user_id","email","full_name","role","organization_id","client_id","candidate_id","status","invited_by","created_at","updated_at"].map(name=>({name:name as UserProfileSchemaPreview["fields"][number]["name"],required:!optional.has(name),description:`Planned ${name.replaceAll("_"," ")} field.`})),rlsRequiredEventually:true,migrationStatus:"preview_only"};}
const allAreas:AccessArea[]=["recruiter","admin_data","client","candidate","public","legacy"],mapping=(role:UserRole,description:string,defaultLandingRoute:string,allowedRouteAreas:AccessArea[],ownership:[boolean,boolean,boolean]):RoleMappingPreview=>({role,description,defaultLandingRoute,allowedRouteAreas,deniedRouteAreas:allAreas.filter(area=>!allowedRouteAreas.includes(area)),requiresOrganization:ownership[0],requiresClientOwnership:ownership[1],requiresCandidateOwnership:ownership[2]});
export function buildRoleMappingPreview():RoleMappingPreview[]{return[mapping("admin","Internal administrator preview.","/recruiter/dashboard",allAreas,[true,false,false]),mapping("recruiter_manager","Recruiter team and reporting preview.","/recruiter/dashboard",["recruiter","public"],[true,false,false]),mapping("recruiter","Recruiter workflow preview.","/recruiter/dashboard",["recruiter","public"],[true,false,false]),mapping("client","Client-owned portal preview.","/client/portal",["client","public"],[true,true,false]),mapping("candidate","Candidate-owned profile preview.","/candidate/portal",["candidate","public"],[false,false,true]),mapping("guest","Public landing preview only.","/auth/preview",["public"],[false,false,false])];}
const ownership=(key:OwnershipModelPreview["key"],label:string,organization:OrganizationOwnershipPreview,description:string):OwnershipModelPreview=>({key,label,organization,description});
export function buildOwnershipPreview():OwnershipModelPreview[]{return[ownership("internal_organization","Internal Primus organization",{organization_id:"org_primus_preview",organization_type:"internal",allowedRoles:["admin","recruiter_manager","recruiter"],ownershipRule:"Internal users belong to one recruiter organization."},"Owns recruiter teams and internal workflows."),ownership("client_organization","Client organization",{organization_id:"org_client_preview",organization_type:"client",allowedRoles:["admin","client"],ownershipRule:"Client users may view only their organization's jobs and submissions."},"Scopes client portal data."),ownership("candidate_ownership","Candidate ownership",{organization_id:"org_candidate_preview",organization_type:"candidate",allowedRoles:["admin","candidate"],ownershipRule:"A candidate profile maps to its owning auth profile."},"Scopes candidate portal and self-confirm views."),ownership("job_ownership","Job ownership",{organization_id:"org_job_owner_preview",organization_type:"internal",allowedRoles:["admin","recruiter_manager","recruiter"],ownershipRule:"Jobs belong to the recruiter organization and reference a client organization."},"Connects jobs to internal and client ownership."),ownership("report_submission_ownership","Report/submission ownership",{organization_id:"org_report_owner_preview",organization_type:"client",allowedRoles:["admin","recruiter_manager","recruiter","client"],ownershipRule:"Reports and submissions inherit job and client organization scope."},"Prevents cross-client report visibility.")];}
export function buildInviteFlowPreview():InviteFlowPreview[]{return[["recruiter","recruiter","/auth/invite/recruiter"],["client","client","/auth/invite/client"],["candidate","candidate","/auth/invite/candidate"],["admin","admin","/auth/invite/admin"]].map(([inviteType,invitedRole,inviteRoutePreview])=>({inviteType:inviteType as InviteFlowPreview["inviteType"],invitedRole:invitedRole as UserRole,inviteRoutePreview,emailSendEnabled:false,tokenStorageEnabled:false,status:"disabled_preview"}));}
export function validateAuthSetupReadiness(environment=buildAuthEnvironmentChecks()){const categories:AuthReadinessCategory[]=["ready_for_preview"];if(environment.some(item=>item.requiredEventually&&item.status!=="configured"))categories.push("missing_env");categories.push("needs_schema_migration","needs_rls_policy","needs_middleware","needs_invite_flow","blocked_for_real_auth");return{readyForPreview:true,readyForRealAuth:false,categories};}
export function getAuthImplementationRoadmap(){return["Add migrations","Add RLS policies","Add Supabase Auth client/server helpers","Add login/signup pages","Add invite flow","Add middleware","Add route guard enforcement","Add audit logs"];}
export function buildAuthSetupPreview():AuthSetupPreviewState{return{provider:{provider:"supabase",enabledNow:false,authCallsEnabled:false,middlewareEnabled:false,notes:["Configuration preview only.","No Supabase client is created or called."]},environment:buildAuthEnvironmentChecks(),userProfileSchema:buildUserProfileSchemaPreview(),roleMappings:buildRoleMappingPreview(),ownershipModels:buildOwnershipPreview(),inviteFlows:buildInviteFlowPreview(),safety:{noSupabaseAuthCalls:true,middlewareEnforced:false,userDbWrites:0,candidateDbWrites:0,clientDbWrites:0,emailSends:0,openAiCalls:0}};}
