import {canRoleAccessRoute,getVisibleNavForRole} from "./roleAccessPreview";import {getDefaultLandingRouteForRole} from "./loginUiPreview";import type {AuthClientServerBoundaryPreview,AuthHelperSafetyPreview,AuthRedirectPreview,AuthRoleResolutionPreview,AuthRouteGuardDecisionPreview,AuthSessionPreview,AuthUserProfilePreview} from "./authHelperPreviewTypes";import type {AccessArea,UserRole} from "./roleAccessTypes";
const ROLES:UserRole[]=["admin","recruiter_manager","recruiter","client","candidate","guest"],AREAS:AccessArea[]=["recruiter","admin_data","client","candidate","public","legacy"],SAFETY:AuthHelperSafetyPreview={supabaseAuthCalls:0,sessionReads:0,sessionsCreated:0,cookiesRead:0,cookiesSet:0,userDbReads:0,userDbWrites:0,middlewareEnforced:false,emailSends:0,openAiCalls:0};
type Params=Record<string,string|string[]|undefined>;
const stringValue=(value:string|string[]|undefined)=>typeof value==="string"&&value.trim()?value.trim():undefined;
export function resolveRolePreview(inputRole:unknown):AuthRoleResolutionPreview{const input=typeof inputRole==="string"?inputRole:"",resolvedRole=ROLES.includes(input as UserRole)?input as UserRole:"guest",allowed:AccessArea[]=resolvedRole==="admin"?[...AREAS]:resolvedRole==="recruiter_manager"||resolvedRole==="recruiter"?["recruiter","public"]:resolvedRole==="client"?["client","public"]:resolvedRole==="candidate"?["candidate","public"]:["public"];return{inputRole:input||"guest",resolvedRole,defaultLandingRoute:getDefaultLandingRouteForRole(resolvedRole),allowedAreas:allowed,deniedAreas:AREAS.filter(area=>!allowed.includes(area)),warnings:input&&input!==resolvedRole?[`Unknown role "${input}" defaulted safely to guest.`]:[]};}
export function buildAuthSessionPreview(params:Params={}):AuthSessionPreview{const resolution=resolveRolePreview(stringValue(params.role)),email=stringValue(params.email),userId=stringValue(params.userId);return{status:resolution.resolvedRole==="guest"?"unauthenticated_preview":"authenticated_preview",userId,email,role:resolution.resolvedRole,organizationId:stringValue(params.organizationId),clientId:stringValue(params.clientId),candidateId:stringValue(params.candidateId),sessionSource:"preview_only",expiresAt:undefined,safety:{...SAFETY}};}
export function buildUserProfilePreview(params:Params={}):AuthUserProfilePreview{const role=resolveRolePreview(stringValue(params.role)).resolvedRole,email=stringValue(params.email)||"preview@example.invalid";return{id:stringValue(params.profileId)||`profile-${role}-preview`,authUserId:stringValue(params.userId),email,fullName:stringValue(params.fullName),role,organizationId:stringValue(params.organizationId),clientId:stringValue(params.clientId),candidateId:stringValue(params.candidateId),status:"preview_only",source:"preview_only"};}
export function buildRouteGuardDecisionPreview(role:UserRole,pathname:string):AuthRouteGuardDecisionPreview{const resolved=resolveRolePreview(role).resolvedRole,path=pathname.trim()||"/recruiter/dashboard",allowed=canRoleAccessRoute(resolved,path);return{pathname:path,role:resolved,allowed,reason:allowed?"Role access matrix advises access.":"Role access matrix advises denial; no route is actually blocked.",redirectTo:allowed?undefined:resolved==="guest"?"/auth/login":getDefaultLandingRouteForRole(resolved),advisoryOnly:true,middlewareEnforced:false};}
export function buildRedirectPreview(role:UserRole,fromRoute:string):AuthRedirectPreview{const resolved=resolveRolePreview(role).resolvedRole,target=getDefaultLandingRouteForRole(resolved);return{role:resolved,fromRoute,defaultLandingRoute:target,redirectTarget:target,reason:"Future post-auth landing derived from the deterministic role map.",enabledNow:false};}
const boundary=(helperName:string,intendedRuntime:AuthClientServerBoundaryPreview["intendedRuntime"],notes:string[]):AuthClientServerBoundaryPreview=>({helperName,intendedRuntime,enabledNow:false,supabaseCalls:0,cookieReads:0,cookieWrites:0,dbReads:0,dbWrites:0,notes});
export function getAuthClientServerBoundaryPreview():AuthClientServerBoundaryPreview[]{return[boundary("createBrowserAuthClientPreview","client",["Future browser client boundary; no client is initialized."]),boundary("createServerAuthClientPreview","server",["Future server client boundary; no secrets or cookies are accessed."]),boundary("getCurrentSessionPreview","server",["Returns deterministic preview shape; does not read a session."]),boundary("getCurrentUserProfilePreview","server",["Returns deterministic profile shape; does not query user_profiles."]),boundary("requireRolePreview","server",["Advisory role decision only; never blocks a request."]),boundary("buildMiddlewareDecisionPreview","middleware",["Planning metadata only; no middleware is installed or enforced."])];}
export function getAuthHelperImplementationRoadmap(){return["Add Supabase client packages/config validation","Create browser/server Supabase clients","Add session reading","Add user_profiles lookup","Add role guard","Add middleware","Add redirects","Add tests with mocked Supabase","Enable only on staging first"];}
export function validateAuthHelperPreview(){const session=buildAuthSessionPreview(),profile=buildUserProfilePreview(),resolution=resolveRolePreview("invalid_role"),guard=buildRouteGuardDecisionPreview("guest","/recruiter/dashboard"),boundaries=getAuthClientServerBoundaryPreview();return{valid:session.role==="guest"&&profile.source==="preview_only"&&resolution.resolvedRole==="guest"&&resolution.warnings.length>0&&guard.advisoryOnly&&!guard.middlewareEnforced&&boundaries.every(item=>!item.enabledNow&&!item.supabaseCalls&&!item.cookieReads&&!item.cookieWrites&&!item.dbReads&&!item.dbWrites),session,profile,resolution,guard,boundaries,safety:{...SAFETY},visibleGuestNav:getVisibleNavForRole("guest")};}
