import { Candidate360FieldSource, Candidate360VerificationStatus, type Candidate360Field } from "./candidate360Types";

export type EvidenceSourceType = "candidate_field" | "parsed_resume" | "employment" | "project" | "candidate_confirmation" | "recruiter_confirmation" | "job_requirement" | "recruiter_note" | "system_derived";
export type EvidenceVerificationLevel = "mentioned" | "resume_extracted" | "structured" | "candidate_confirmed" | "recruiter_confirmed" | "derived";
export type EvidenceStrength = "weak" | "moderate" | "strong" | "verified";
export type EvidenceProvenance = { id: string; claim: string; sourceType: EvidenceSourceType; verificationLevel: EvidenceVerificationLevel; strength: EvidenceStrength; sourceLabel: string; sourceRef?: string; fieldPath?: string; quotedValue?: string; candidateConfirmed: boolean; recruiterConfirmed: boolean; extractedAt?: string | null; confirmedAt?: string | null; supports: string[]; limitations: string[]; confidenceContribution: number };
export type EvidenceItem = { label: string; value?: string; sourceType: EvidenceSourceType; sourceRef?: string; provenance?: EvidenceProvenance };

const aliases: Array<[RegExp, string]> = [
  [/^(education|educational background|academic background)$/i, "Education"], [/^(certification|certifications|certificate|certificates)$/i, "Certifications"], [/^(leadership|leadership evidence|leadership ownership|team leadership|team size or leadership accountability)$/i, "Leadership ownership"], [/^(availability|candidate availability)$/i, "Availability"], [/^(salary|salary expectation|salary expectations|expected salary)$/i, "Salary expectations"], [/^(notice|notice period)$/i, "Notice period"], [/^(visa|work rights|work authorization|visa or work rights)$/i, "Visa / work authorization"], [/^(currentcompany|current company|identity currentcompany)$/i, "Current employer"], [/^(workexperience|work experience|employmenttimeline|employment history)$/i, "Employment history"],
];
export function recruiterLabel(value: string) { const cleaned = String(value || "").replace(/[_\.]+/g, " ").replace(/\s+/g, " ").trim().replace(/^confirmed\s+/i, "").replace(/^candidate evidence for\s+/i, ""); if (!cleaned) return ""; for (const [pattern, label] of aliases) if (pattern.test(cleaned)) return label; return cleaned.charAt(0).toUpperCase() + cleaned.slice(1); }
export function normalizeEvidenceLabels(values: string[]) { const output: string[] = []; const seen = new Set<string>(); for (const value of values) { const label = recruiterLabel(value); const key = label.toLocaleLowerCase(); if (!label || seen.has(key)) continue; seen.add(key); output.push(label); } return output; }
export function normalizeEvidenceItems(items: EvidenceItem[]) { const output: EvidenceItem[] = []; const seen = new Set<string>(); for (const item of items) { const label = recruiterLabel(item.label); const value = item.value?.trim(); const key = `${label}|${value || ""}`.toLocaleLowerCase(); if (!label || seen.has(key)) continue; seen.add(key); output.push({ ...item, label, ...(value ? { value } : {}), provenance: item.provenance || createEvidenceProvenance({ claim: label, sourceType: item.sourceType, sourceRef: item.sourceRef, quotedValue: value, supports: [label] }) }); } return output; }

const contribution: Record<EvidenceStrength, number> = { weak: 25, moderate: 50, strong: 75, verified: 100 };
function stableId(value: string) { let hash = 2166136261; for (let index = 0; index < value.length; index += 1) { hash ^= value.charCodeAt(index); hash = Math.imul(hash, 16777619); } return `ev-${(hash >>> 0).toString(36)}`; }
export function createEvidenceProvenance(input: { claim: string; sourceType: EvidenceSourceType; sourceRef?: string; fieldPath?: string; quotedValue?: string; supports?: string[]; verificationLevel?: EvidenceVerificationLevel; strength?: EvidenceStrength; sourceLabel?: string; candidateConfirmed?: boolean; recruiterConfirmed?: boolean; extractedAt?: string | null; confirmedAt?: string | null; limitations?: string[] }): EvidenceProvenance {
  const candidateConfirmed = Boolean(input.candidateConfirmed || input.verificationLevel === "candidate_confirmed"); const recruiterConfirmed = Boolean(input.recruiterConfirmed || input.verificationLevel === "recruiter_confirmed");
  const verificationLevel = recruiterConfirmed ? "recruiter_confirmed" : candidateConfirmed ? "candidate_confirmed" : input.verificationLevel || (input.sourceType === "project" || input.sourceType === "employment" ? "structured" : input.sourceType === "system_derived" ? "derived" : input.sourceType === "parsed_resume" ? "resume_extracted" : "mentioned");
  const strength = input.strength || (recruiterConfirmed || candidateConfirmed ? "verified" : verificationLevel === "structured" ? "strong" : verificationLevel === "resume_extracted" || verificationLevel === "derived" ? "moderate" : "weak");
  const limitations = input.limitations || (strength === "verified" ? [] : verificationLevel === "structured" ? ["Structured resume evidence; not independently confirmed."] : verificationLevel === "derived" ? ["System-derived conclusion; inspect supporting evidence."] : ["Resume mention only; delivery depth is not verified."]);
  const identity = [input.claim, input.sourceType, input.sourceRef, input.quotedValue].filter(Boolean).join("|");
  return { id: stableId(identity), claim: recruiterLabel(input.claim), sourceType: input.sourceType, verificationLevel, strength, sourceLabel: input.sourceLabel || sourceLabelFor(input.sourceType, verificationLevel), ...(input.sourceRef ? { sourceRef: input.sourceRef } : {}), ...(input.fieldPath ? { fieldPath: input.fieldPath } : {}), ...(input.quotedValue ? { quotedValue: input.quotedValue } : {}), candidateConfirmed, recruiterConfirmed, extractedAt: input.extractedAt ?? null, confirmedAt: input.confirmedAt ?? null, supports: normalizeEvidenceLabels(input.supports || [input.claim]), limitations, confidenceContribution: contribution[strength] };
}
export function sourceLabelFor(sourceType: EvidenceSourceType, level?: EvidenceVerificationLevel) { if (level === "recruiter_confirmed" || sourceType === "recruiter_confirmation") return "Recruiter confirmed"; if (level === "candidate_confirmed" || sourceType === "candidate_confirmation") return "Candidate confirmed"; const labels: Record<EvidenceSourceType, string> = { candidate_field: "Candidate profile field", parsed_resume: "Parsed resume", employment: "Structured employment", project: "Structured project", candidate_confirmation: "Candidate confirmed", recruiter_confirmation: "Recruiter confirmed", job_requirement: "Job requirement", recruiter_note: "Recruiter note", system_derived: "System derived" }; return labels[sourceType]; }
export function provenanceForField<T>(claim: string, field: Candidate360Field<T>, supports: string[] = [claim]): EvidenceProvenance {
  const recruiterConfirmed = field.verificationStatus === Candidate360VerificationStatus.RecruiterVerified || field.source === Candidate360FieldSource.RecruiterApproved;
  const candidateConfirmed = field.verificationStatus === Candidate360VerificationStatus.CandidateConfirmed || field.source === Candidate360FieldSource.CandidateConfirmed;
  const sourceType: EvidenceSourceType = recruiterConfirmed ? "recruiter_confirmation" : candidateConfirmed ? "candidate_confirmation" : field.source === Candidate360FieldSource.ParserExtracted || field.source === Candidate360FieldSource.AiExtracted ? "parsed_resume" : "candidate_field";
  return createEvidenceProvenance({ claim, sourceType, sourceRef: field.fieldName, fieldPath: field.fieldName, quotedValue: String(field.value ?? ""), supports, candidateConfirmed, recruiterConfirmed, extractedAt: recruiterConfirmed || candidateConfirmed ? null : field.lastConfirmedAt, confirmedAt: field.lastConfirmedAt, limitations: field.conflictReason ? [field.conflictReason] : undefined });
}
export function provenanceForEvidenceItem(item: EvidenceItem): EvidenceProvenance { return item.provenance || createEvidenceProvenance({ claim: item.label, sourceType: item.sourceType, sourceRef: item.sourceRef, quotedValue: item.value, supports: [item.label] }); }

