import type {CandidateAvailabilityPreview,CandidateConfirmationStatusPreview,CandidateConsentPreview,CandidateCvUploadPreview,CandidatePortalPreview,CandidatePortalSafety,CandidateRolePreferencesPreview,CandidateSalaryExpectationPreview,CandidateWorkPreferencesPreview} from "./candidatePortalTypes";
type Params=Record<string,string|string[]|undefined>;const SAFETY:CandidatePortalSafety={candidateDbWrites:0,userDbWrites:0,storageWrites:0,emailSends:0,openAiCalls:0,authCalls:0,middlewareEnforced:false};
const value=(input:string|string[]|undefined)=>typeof input==="string"&&input.trim()?input.trim():undefined,list=(input:string|string[]|undefined)=>{const values=Array.isArray(input)?input:typeof input==="string"?input.split(","):[];return[...new Set(values.map(item=>item.trim()).filter(Boolean))];},numberValue=(input:string|string[]|undefined)=>{const raw=value(input),parsed=raw?Number(raw):NaN;return Number.isFinite(parsed)&&parsed>=0?parsed:undefined;};
export function buildCandidateConfirmationStatusPreview(params:Params={}):CandidateConfirmationStatusPreview{const candidateId=value(params.candidateId),allowed=["not_started","in_progress_preview","submitted_preview","recruiter_review_preview","confirmed_preview"],raw=value(params.confirmationStatus),status=(raw&&allowed.includes(raw)?raw:candidateId?"in_progress_preview":"not_started") as CandidateConfirmationStatusPreview["status"];return{status,lastUpdated:value(params.lastUpdated),pendingFields:list(params.pendingFields).length?list(params.pendingFields):["availability","salary expectation","role preferences","consent"],recruiterReviewRequired:status==="submitted_preview"||status==="recruiter_review_preview",selfConfirmUrl:candidateId?"/candidate/self-confirm/"+encodeURIComponent(candidateId):undefined,recruiterReviewUrl:candidateId?"/recruiter/candidate360/"+encodeURIComponent(candidateId):undefined};}
export function buildCandidateAvailabilityPreview(params:Params={}):CandidateAvailabilityPreview{const allowed=["immediately_available","available_from_date","employed_not_looking","open_to_discuss","unknown"],raw=value(params.availability);return{status:(raw&&allowed.includes(raw)?raw:"unknown") as CandidateAvailabilityPreview["status"],availableFrom:value(params.availableFrom),noticePeriod:value(params.noticePeriod),notes:value(params.availabilityNotes),previewOnly:true};}
export function buildCandidateSalaryExpectationPreview(params:Params={}):CandidateSalaryExpectationPreview{return{currency:value(params.currency)||"USD",expectedMonthlyGross:numberValue(params.expectedMonthlyGross),expectedAnnualGross:numberValue(params.expectedAnnualGross),expectedHourlyRate:numberValue(params.expectedHourlyRate),negotiable:value(params.negotiable)!=="false",notes:value(params.salaryNotes),previewOnly:true};}
export function buildCandidateRolePreferencesPreview(params:Params={}):CandidateRolePreferencesPreview{return{preferredRoles:list(params.preferredRoles),preferredModules:list(params.preferredModules),preferredIndustries:list(params.preferredIndustries),preferredCountries:list(params.preferredCountries),preferredCities:list(params.preferredCities),contractTypes:list(params.contractTypes),seniorityPreference:value(params.seniorityPreference),previewOnly:true};}
export function buildCandidateWorkPreferencesPreview(params:Params={}):CandidateWorkPreferencesPreview{const allowed=["onsite","hybrid","remote","flexible","unknown"],raw=value(params.workMode);return{workMode:(raw&&allowed.includes(raw)?raw:"unknown") as CandidateWorkPreferencesPreview["workMode"],travelWillingness:value(params.travelWillingness),relocationWillingness:value(params.relocationWillingness),timezonePreference:value(params.timezonePreference),previewOnly:true};}
export function buildCandidateCvUploadPreview():CandidateCvUploadPreview{return{uploadEnabledNow:false,acceptedFormats:["PDF","DOC","DOCX"],maxSizeMb:10,storageWrites:0,status:"disabled_preview"};}
export function buildCandidateConsentPreview():CandidateConsentPreview{return{dataProcessingConsentRequired:true,profileSubmissionConsentRequired:true,consentCapturedNow:false,status:"preview_only"};}
export function buildCandidatePortalNextSteps(params:Params={}){return[value(params.candidateId)?"Complete profile confirmation":"Open a candidate-linked profile confirmation","Recruiter reviews changes","Profile becomes ready for submission","Recruiter may contact candidate for clarification"];}
export function buildCandidatePortalPreview(params:Params={}):CandidatePortalPreview{const candidateId=value(params.candidateId),completeness=Math.min(100,numberValue(params.profileCompleteness)??(candidateId?65:35));return{candidateId,candidateName:value(params.candidateName)||"Candidate Preview",email:value(params.email),currentTitle:value(params.title),currentCompany:value(params.company),location:value(params.location),profileCompleteness:completeness,confirmationStatus:buildCandidateConfirmationStatusPreview(params),availability:buildCandidateAvailabilityPreview(params),salaryExpectation:buildCandidateSalaryExpectationPreview(params),rolePreferences:buildCandidateRolePreferencesPreview(params),workPreferences:buildCandidateWorkPreferencesPreview(params),cvUploadPreview:buildCandidateCvUploadPreview(),consentPreview:buildCandidateConsentPreview(),nextSteps:buildCandidatePortalNextSteps(params),safety:{...SAFETY}};}
export function validateCandidatePortalPreview(){const empty=buildCandidatePortalPreview(),linked=buildCandidatePortalPreview({candidateId:"candidate-001"});return{valid:empty.candidateName==="Candidate Preview"&&linked.confirmationStatus.selfConfirmUrl==="/candidate/self-confirm/candidate-001"&&!linked.cvUploadPreview.uploadEnabledNow&&!linked.consentPreview.consentCapturedNow&&Object.values(linked.safety).every(value=>value===0||value===false),empty,linked};}
