import { buildCandidate360TrustSummary, candidate360Fields } from "./candidate360UiModel";
import { Candidate360FieldSource as Source } from "./candidate360Types";
import type { Candidate360Profile } from "./candidate360Types";
import type { CandidateCompareCandidateScore, CandidateCompareDimension, CandidateCompareDimensionScore, CandidateCompareEvidence, CandidateCompareRequest, CandidateCompareResult } from "./candidateCompareTypes";

const clean=(value:unknown)=>String(value??"").trim(); const norm=(value:unknown)=>clean(value).toLowerCase();
const has=(haystack:string[],needle:string)=>haystack.some(value=>value===needle||value.includes(needle)||needle.includes(value));
function dimension(dimension:CandidateCompareDimension,score:number,weight:number,neutral:boolean,explanation:string,matched:string[]=[],missing:string[]=[]):CandidateCompareDimensionScore{return{dimension,score:Math.max(0,Math.min(100,Math.round(score))),weight,neutral,explanation,matched,missing};}
function matchDimension(dimensionName:CandidateCompareDimension,required:string[],available:string[],weight:number,label:string,bonus:string[]=[]){if(!required.length&&!bonus.length)return dimension(dimensionName,100,weight,true,`No ${label} requirement supplied; neutral.`);const matched=required.filter(item=>has(available,item)),missing=required.filter(item=>!has(available,item)),nice=bonus.filter(item=>has(available,item));const base=required.length?(matched.length/required.length)*100:75;return dimension(dimensionName,Math.min(100,base+nice.length*5),weight,false,`${matched.length}/${required.length} required ${label} matched${nice.length?`; ${nice.length} nice-to-have matched`:""}.`,matched,missing);}
function evidence(profile:Candidate360Profile,dimensionName:CandidateCompareDimension,fieldName:string,value:unknown,source:string,explanation:string):CandidateCompareEvidence|undefined{return clean(value)?{dimension:dimensionName,fieldName,value:clean(value),source,explanation}:undefined;}
function score(profile:Candidate360Profile,request:CandidateCompareRequest):CandidateCompareCandidateScore{
  const skills=profile.techSkills.map(item=>norm(item.name.value)),modules=profile.sapModules.map(item=>norm(item.name.value));
  const languages=profile.languages.map(item=>norm(item.language.value)); const title=norm(profile.currentTitle.value),location=norm(profile.location.value);
  const skillScore=matchDimension("skills_match",request.mustHaveSkills,[...skills,...modules],15,"skills",request.niceToHaveSkills);
  const moduleScore=matchDimension("module_match",request.requiredModules,modules,15,"modules");
  const years=profile.yearsOfExperience.value; const experienceScore=request.minYearsExperience===null?dimension("experience_match",100,10,true,"No minimum experience supplied; neutral."):dimension("experience_match",years===null?25:Math.min(100,(years/request.minYearsExperience)*100),10,false,years===null?"Years of experience are missing.":`${years} years compared with ${request.minYearsExperience} required.`,years!==null&&years>=request.minYearsExperience?[`${years} years`]:[],years===null?["years of experience"]:years<request.minYearsExperience?[`${request.minYearsExperience-years} years below minimum`]:[]);
  const seniorityTerms=request.roleSeniority?request.roleSeniority.toLowerCase().split(/\s+/).filter(Boolean):[];
  const seniorityScore=!seniorityTerms.length?dimension("seniority_match",100,10,true,"No seniority requirement supplied; neutral."):dimension("seniority_match",seniorityTerms.some(term=>title.includes(term))?100:45,10,false,seniorityTerms.some(term=>title.includes(term))?"Title contains the requested seniority.":"Requested seniority is not explicit in the current title.",seniorityTerms.filter(term=>title.includes(term)),seniorityTerms.filter(term=>!title.includes(term)));
  const locationRequirement=[request.roleLocation,request.workMode||""].map(norm).filter(Boolean);const locationScore=!locationRequirement.length?dimension("location_match",100,10,true,"No location or work-mode requirement supplied; neutral."):dimension("location_match",locationRequirement.some(item=>item==="remote"||location.includes(item))?100:location?40:20,10,false,location?`Candidate location: ${clean(profile.location.value)}.`:"Candidate location is missing.",locationRequirement.filter(item=>item==="remote"||location.includes(item)),locationRequirement.filter(item=>item!=="remote"&&!location.includes(item)));
  const industryScore=request.requiredIndustries.length?dimension("industry_match",25,10,false,"Candidate360 v1 has no structured industry evidence.",[],request.requiredIndustries):dimension("industry_match",100,10,true,"No industry requirement supplied; neutral.");
  const completenessScore=dimension("data_completeness",profile.completeness.score,10,false,`${profile.completeness.score}% profile completeness.`);
  const trust=buildCandidate360TrustSummary(profile);const present=candidate360Fields(profile).filter(field=>clean(field.value));const parserOnly=present.length>0&&present.every(field=>field.source===Source.ParserExtracted);const trustValue=Math.max(trust.trustScore,parserOnly?45:present.length?55:20);const trustScore=dimension("verification_trust",trustValue,10,false,`${trust.candidateConfirmed} candidate-confirmed and ${trust.recruiterApproved} recruiter-approved fields.`);
  const risks=[] as CandidateCompareCandidateScore["risks"];if(profile.readiness.needsCandidateConfirmation)risks.push({code:"needs_candidate_confirmation",severity:"medium",message:"Profile needs candidate confirmation."});if(profile.missingFields.length>=4)risks.push({code:"many_missing_fields",severity:"high",message:`${profile.missingFields.length} profile fields are missing.`});for(const field of ["currentTitle","currentCompany","location"]){if(profile.missingFields.includes(field))risks.push({code:`missing_${field}`,severity:"medium",message:`${field} is missing.`});}if(skillScore.missing.length)risks.push({code:"missing_must_have",severity:"high",message:`Missing must-have skills: ${skillScore.missing.join(", ")}.`});if(moduleScore.missing.length)risks.push({code:"missing_modules",severity:"high",message:`Missing required modules: ${moduleScore.missing.join(", ")}.`});
  const riskValue=Math.max(0,100-risks.reduce((sum,risk)=>sum+(risk.severity==="high"?25:risk.severity==="medium"?12:5),0));const riskScore=dimension("risk_flags",riskValue,10,false,risks.length?`${risks.length} evidence-based risk flag(s).`:"No comparison risk flags detected.");
  const availabilityScore=dimension("availability_match",100,0,true,"Availability is not structured in Candidate360 v1; neutral.");
  if(request.requiredLanguages.length){const missing=request.requiredLanguages.filter(item=>!has(languages,item));if(missing.length)risks.push({code:"missing_language_evidence",severity:"medium",message:`No evidence for required languages: ${missing.join(", ")}.`});}
  const dimensions=[skillScore,moduleScore,experienceScore,seniorityScore,industryScore,locationScore,availabilityScore,completenessScore,trustScore,riskScore];const weighted=dimensions.reduce((sum,item)=>sum+item.score*item.weight,0)/dimensions.reduce((sum,item)=>sum+item.weight,0);
  let overall=Math.round(weighted);if(skillScore.missing.length)overall=Math.max(0,overall-Math.min(20,skillScore.missing.length*10));if(moduleScore.missing.length)overall=Math.max(0,overall-Math.min(15,moduleScore.missing.length*5));
  const missingInfo=[...profile.missingFields];if(request.requiredIndustries.length)missingInfo.push("structured industry evidence");if(request.requiredLanguages.length&&!languages.length)missingInfo.push("language evidence");
  const recommendation=missingInfo.length>=4?"needs_more_info":overall>=85?"strong_match":overall>=70?"good_match":overall>=55?"partial_match":overall>=40?"weak_match":"not_recommended";
  const strengths=dimensions.filter(item=>!item.neutral&&item.score>=75).map(item=>item.explanation);const gaps=dimensions.filter(item=>!item.neutral&&item.score<60).map(item=>item.explanation);
  const ev=[evidence(profile,"skills_match","techSkills",skills.join(", "),profile.techSkills[0]?.name.source||"unknown","Skills listed in Candidate360."),evidence(profile,"module_match","sapModules",modules.join(", "),profile.sapModules[0]?.name.source||"unknown","SAP modules listed in Candidate360."),evidence(profile,"experience_match","yearsOfExperience",years,profile.yearsOfExperience.source,"Years stored in Candidate360."),evidence(profile,"seniority_match","currentTitle",profile.currentTitle.value,profile.currentTitle.source,"Current title stored in Candidate360."),evidence(profile,"location_match","location",profile.location.value,profile.location.source,"Location stored in Candidate360.")].filter(Boolean) as CandidateCompareEvidence[];
  return{candidateId:profile.candidateId,name:clean(profile.displayName.value)||profile.candidateId,currentTitle:clean(profile.currentTitle.value),currentCompany:clean(profile.currentCompany.value),location:clean(profile.location.value),overallScore:overall,ranking:0,recommendation,dimensionScores:dimensions,strengths,gaps,risks,evidence:ev,missingInfo:Array.from(new Set(missingInfo)),recruiterSummary:`${clean(profile.displayName.value)||"Candidate"} scores ${overall}/100 using deterministic Candidate360 evidence. ${gaps[0]||"No major evidence gap identified."}`,candidate360Href:`/recruiter/candidate360/${encodeURIComponent(profile.candidateId)}`,selfConfirmHref:`/candidate/self-confirm/${encodeURIComponent(profile.candidateId)}`};
}
export function buildCandidateCompareResult(request:CandidateCompareRequest,profiles:Candidate360Profile[]):CandidateCompareResult{const requested=new Set(request.candidateIds);const found=profiles.filter(profile=>requested.has(profile.candidateId));if(found.length!==request.candidateIds.length){const foundIds=new Set(found.map(profile=>profile.candidateId));throw new Error(`Candidate not found: ${request.candidateIds.filter(id=>!foundIds.has(id)).join(", ")}`);}const candidates=found.map(profile=>score(profile,request)).sort((a,b)=>b.overallScore-a.overallScore||a.name.localeCompare(b.name)).map((candidate,index)=>({...candidate,ranking:index+1}));return{generatedAt:new Date().toISOString(),mode:"local deterministic comparison only; no candidate DB writes; no OpenAI calls",request,candidates,provider:"deterministic_v1"};}

