import type { Candidate360Profile } from "./candidate360Types";import type { CandidateCompareResult } from "./candidateCompareTypes";import type { SubmissionDraft } from "./submissionGeneratorTypes";
export type ClientExecutiveReportFormat="executive_summary"|"shortlist_report"|"client_email_brief"|"comparison_matrix";export type ClientExecutiveReportRecommendation="recommended_for_review"|"consider_with_caveats"|"needs_more_information"|"not_recommended";
export type ClientExecutiveReportRoleContext={reportTitle:string;clientName?:string;roleTitle:string;roleSeniority?:string;roleLocation?:string;employmentType?:string;workMode?:string;mustHaveSkills:string[];niceToHaveSkills:string[];requiredModules:string[];requiredIndustries:string[];requiredLanguages:string[];minYearsExperience:number|null;jdNotes?:string;keywordHints:string[]};
export type ClientExecutiveReportRequest=ClientExecutiveReportRoleContext&{candidateIds:string[];format:ClientExecutiveReportFormat};export type ClientExecutiveReportCandidate={candidateId:string;profile:Candidate360Profile;submissionDraft?:SubmissionDraft};export type ClientExecutiveReportRisk={candidateId:string;severity:"low"|"medium"|"high";message:string};export type ClientExecutiveReportSection={id:string;title:string;content:string;items:string[]};
export type ClientExecutiveReportCandidateSummary={candidateId:string;rank:number;name:string;currentTitle:string;currentCompany:string;location:string;overallScore:number|null;recommendation:string;rankingBasis:"candidate_compare"|"preliminary_completeness_trust";fitHighlights:string[];relevantExperience:string;gaps:string[];risks:ClientExecutiveReportRisk[];evidenceCount:number;missingInfo:string[];candidate360Href:string;submissionGeneratorHref:string};
export type ClientExecutiveReportComparisonTable={columns:string[];rows:Array<{candidateId:string;cells:string[]}>};
export type ClientExecutiveReport={reportId:string;generatedAt:string;mode:"deterministic_read_only";format:ClientExecutiveReportFormat;clientName:string;roleContext:ClientExecutiveReportRoleContext;candidateCount:number;candidates:ClientExecutiveReportCandidateSummary[];ranking:string[];rankingPreliminary:boolean;executiveSummary:string;comparisonMatrix:ClientExecutiveReportComparisonTable;candidateHighlights:ClientExecutiveReportCandidateSummary[];keyRisks:ClientExecutiveReportRisk[];missingInformation:Array<{candidateId:string;items:string[]}>;recruiterNotes:string[];recommendedNextSteps:string[];clientEmailBrief:{subject:string;body:string};sections:ClientExecutiveReportSection[];safetyWarnings:string[];sourceSummary:{candidate360Profiles:number;compareResultUsed:boolean;submissionDraftsUsed:number;statement:string}};
export type ClientExecutiveReportCandidateInput=ClientExecutiveReportCandidate;

