import {normalizeSavedPackSize} from "./savedSearchPackPreview";import {buildRecruiterPackCompareUrl} from "./talentPackBuilder";import type {ClientFeedbackPreview,ClientPortalJobPreview,ClientPortalPreview,ClientSubmittedCandidatePreview,ClientSubmittedPackPreview,ClientPortalSafety} from "./clientPortalTypes";
type Params=URLSearchParams|Record<string,unknown>;const SAFETY:ClientPortalSafety={readOnly:true,clientDbWrites:0,candidateDbWrites:0,feedbackWrites:0,openAiCalls:0,emailSends:0};
const toParams=(input:Params)=>{if(input instanceof URLSearchParams)return new URLSearchParams(input);const query=new URLSearchParams();for(const[key,value]of Object.entries(input)){if(value===undefined||value===null||value==="")continue;if(Array.isArray(value))value.forEach(item=>query.append(key,String(item)));else query.set(key,String(value));}return query;};
const first=(query:URLSearchParams,...keys:string[])=>keys.map(key=>query.get(key)?.trim()).find(Boolean)||"";const ids=(query:URLSearchParams)=>query.getAll("candidateIds").flatMap(value=>value.split(",")).concat(query.getAll("candidateId")).map(value=>value.trim()).filter(Boolean).filter((value,index,all)=>all.indexOf(value)===index);
const stableId=(prefix:string,parts:string[])=>{let hash=2166136261;for(const char of parts.join("|").toLowerCase()){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}return `${prefix}-${(hash>>>0).toString(36)}`;};
const withCandidate=(query:URLSearchParams,candidateId:string)=>{const next=new URLSearchParams(query);next.set("candidateId",candidateId);return next;};
export function buildClientPortalUrl(params:Params){const query=toParams(params);return `/client/portal/preview${query.size?`?${query.toString()}`:""}`;}
export function buildClientJobUrl(params:Params){const query=toParams(params);return `/client/portal/preview${query.size?`?${query.toString()}`:""}#job-context`;}
export function buildClientPackUrl(params:Params){const query=toParams(params);query.set("packSize",String(normalizeSavedPackSize(query.get("packSize"))));return `/client/portal/preview?${query.toString()}#submitted-pack`;}
export function buildClientCandidateSubmissionUrl(params:Params){const query=toParams(params),candidateId=first(query,"candidateId")||ids(query)[0]||"candidate-preview";return `/client/candidates/${encodeURIComponent(candidateId)}?${query.toString()}`;}
export function buildDisabledFeedbackActions(candidateId:string,jobId?:string):ClientFeedbackPreview[]{return(["shortlist","request_interview","reject","request_more_info","hold"] as const).map(action=>({candidateId,jobId:jobId||undefined,action,status:"disabled_preview",reason:"Coming soon. Feedback is not saved in preview mode."}));}
export function buildClientPortalJobPreview(params:Params):ClientPortalJobPreview{const query=toParams(params),candidateIds=ids(query),jobTitle=first(query,"jobTitle","roleTitle")||"Role Preview",clientName=first(query,"clientName")||"Client Preview",jobId=first(query,"jobId")||stableId("client-job",[jobTitle,clientName]),reportQuery=new URLSearchParams(query);reportQuery.set("candidateIds",candidateIds.join(","));return{jobId,jobTitle,clientName,country:first(query,"country")||undefined,city:first(query,"city","location")||undefined,employmentType:first(query,"employmentType")||undefined,seniority:first(query,"seniority")||undefined,priority:(first(query,"priority")||undefined) as ClientPortalJobPreview["priority"],status:first(query,"status")==="closed_preview"?"closed_preview":first(query,"status")==="active_preview"?"active_preview":"preview_only",submittedCandidateCount:candidateIds.length,reportUrl:candidateIds.length?`/recruiter/client-report?${reportQuery.toString()}`:undefined,recruiterJobPreviewUrl:`/recruiter/jobs/preview?${query.toString()}`};}
export function buildClientSubmittedCandidatePreview(params:Params):ClientSubmittedCandidatePreview{const query=toParams(params),candidateId=first(query,"candidateId")||ids(query)[0]||"candidate-preview",scoreValue=Number(first(query,"score")),name=first(query,"candidateName","name")||`Candidate ${candidateId.slice(0,8)}`,submissionQuery=withCandidate(query,candidateId),reportQuery=new URLSearchParams(query);reportQuery.set("candidateIds",ids(query).length?ids(query).join(","):candidateId);return{candidateId,name,title:first(query,"candidateTitle","title")||undefined,currentCompany:first(query,"currentCompany","company")||undefined,location:first(query,"candidateLocation","location","city")||undefined,fitLabel:first(query,"fitLabel")||"Fit to be reviewed",score:Number.isFinite(scoreValue)&&scoreValue>=0?scoreValue:undefined,highlights:[first(query,"highlight")||"Submitted for client review preview."],risks:first(query,"risk")?[first(query,"risk")]:[],missingInfo:first(query,"missingInfo")?[first(query,"missingInfo")]:["Full client-facing profile details to be confirmed."],candidateSubmissionUrl:`/client/candidates/${encodeURIComponent(candidateId)}?${submissionQuery.toString()}`,candidateReportUrl:`/recruiter/client-report?${reportQuery.toString()}`,clientActionStatus:"pending_preview"};}
export function buildClientSubmittedPackPreview(params:Params):ClientSubmittedPackPreview{const query=toParams(params),candidateIds=ids(query),packSize=normalizeSavedPackSize(query.get("packSize")),jobId=first(query,"jobId")||undefined;query.set("packSize",String(packSize));return{packId:first(query,"packId")||stableId("client-pack",[jobId||"no-job",String(packSize),candidateIds.join(",")]),jobId,packSize,candidateIds,candidateCount:candidateIds.length,packCompareUrl:buildRecruiterPackCompareUrl(query,packSize),clientReportUrl:candidateIds.length?`/recruiter/client-report?${query.toString()}`:undefined,status:"preview_only"};}
export function buildClientPortalPreview(params:Params):ClientPortalPreview{const query=toParams(params),clientName=first(query,"clientName")||"Client Preview",job=buildClientPortalJobPreview(query),pack=buildClientSubmittedPackPreview(query),submittedCandidates=ids(query).map(candidateId=>buildClientSubmittedCandidatePreview(withCandidate(query,candidateId))),reportId=first(query,"reportId");return{id:stableId("client-portal",[clientName,job.jobId,pack.packId]),clientName,portalTitle:`${clientName} Candidate Review`,status:"preview_only",jobs:[job],submittedPacks:[pack],submittedCandidates,reports:pack.clientReportUrl?[{id:reportId||stableId("client-report",[job.jobId,pack.packId]),title:`${job.jobTitle} Executive Report Preview`,url:pack.clientReportUrl,status:"preview_only"}]:[],safety:SAFETY};}
