import type { GuidedCriterion } from "./guidedSourcingTypes";
export type CompactReviewItem={id:string;memberIds:string[];type:GuidedCriterion["type"];value:string;status:GuidedCriterion["status"];reason:string;supportingExcerpt:string;confidence:number;ambiguityExplanation?:string;capabilityChips?:string[]};
export type CompactGuidedReview={summary:CompactReviewItem[];mustHave:CompactReviewItem[];niceToHave:CompactReviewItem[];additional:CompactReviewItem[];attention:CompactReviewItem[];includedCount:number;summaryCount:number;reviewedCount:number;countBreakdown:string};
const normalize=(value:string)=>value.normalize("NFKC").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const capabilities=[['Sales order',/sales order(?: management)?/i],['Pricing',/\bpricing\b/i],['Delivery',/\bdeliver(?:y|ies)\b/i],['Billing',/\bbilling\b/i],['Credit',/credit management/i],['Returns',/\breturns?\b/i],['ATP',/\b(?:atp|available to promise)\b/i]] as const;
const otcPrimary=/(?:hands on )?(?:sap )?(?:order to cash|otc|o2c)(?: experience)?/i;
function itemFrom(c:GuidedCriterion):CompactReviewItem{return{id:c.id,memberIds:[c.id],type:c.type,value:c.value,status:c.status,reason:c.reason,supportingExcerpt:c.supportingExcerpt,confidence:c.confidence,ambiguityExplanation:c.ambiguityExplanation};}
export function buildCompactGuidedReview(criteria:GuidedCriterion[]):CompactGuidedReview{
 const unique:GuidedCriterion[]=[],seen=new Set<string>();
 for(const c of criteria){if(c.status==='removed')continue;const n=normalize(c.value),key=`${c.type}:${n}`;if(!n||seen.has(key))continue;seen.add(key);unique.push(c);}
 const process=unique.filter(c=>capabilities.some(([,pattern])=>pattern.test(c.value)));const primary=unique.find(c=>['must_have','sap_concept'].includes(c.type)&&otcPrimary.test(normalize(c.value)));const qualifiedYears=unique.find(c=>c.type==='minimum_years'&&otcPrimary.test(normalize(`${c.supportingExcerpt} ${c.reason}`)));const members=[...new Set([...(primary?[primary]:[]),...process,...(qualifiedYears?[qualifiedYears]:[])])];const consumed=new Set(members.map(c=>c.id));const rows=unique.filter(c=>!consumed.has(c.id)).map(itemFrom);
 if(members.length){const lead=primary||members[0],chips=capabilities.filter(([,pattern])=>members.some(c=>pattern.test(c.value)||pattern.test(c.supportingExcerpt))).map(([label])=>label),years=qualifiedYears?.value;rows.push({...itemFrom(lead),id:`otc-group-${lead.id}`,memberIds:members.map(c=>c.id),type:'must_have',value:`Order-to-Cash${years?` — minimum ${years} years`:''}`,capabilityChips:[...new Set(chips)]});}
 const summaryTypes=new Set<GuidedCriterion['type']>(['target_role','location','seniority','minimum_years']);const attention=rows.filter(r=>r.type==='unresolved'||r.status==='unresolved'||Boolean(r.ambiguityExplanation));const ready=rows.filter(r=>!attention.includes(r));
 const summary=ready.filter(r=>summaryTypes.has(r.type));const mustHave=ready.filter(r=>!summaryTypes.has(r.type)&&(r.type==='must_have'||r.type==='sap_concept'));const niceToHave=ready.filter(r=>r.type==='nice_to_have');const additional=ready.filter(r=>!summaryTypes.has(r.type)&&!['must_have','sap_concept','nice_to_have'].includes(r.type));
 const summaryLabels=summary.map(item=>item.type==='target_role'?'Role':item.type==='location'?'Location':item.type==='seniority'?'Seniority':'Experience'),reviewedCount=mustHave.length+niceToHave.length+additional.length,includedCount=summary.length+reviewedCount,countBreakdown=`${includedCount} search inputs: ${[...summaryLabels,reviewedCount?`${reviewedCount} reviewed ${reviewedCount===1?'criterion':'criteria'}`:null].filter(Boolean).join(', ')}`;return{summary,mustHave,niceToHave,additional,attention,includedCount,summaryCount:summary.length,reviewedCount,countBreakdown};
}
