import type { RecruiterJobOption } from "./recruiterJobsData";
export const GUIDED_UPLOAD_MAX_BYTES=5*1024*1024;
export const GUIDED_MODEL_INPUT_MAX=12000;
export function normalizeGuidedSourceText(value:unknown,max=GUIDED_MODEL_INPUT_MAX){return String(value??"").normalize("NFKC").replace(/\u00ad/g,"").replace(/\0/g,"").replace(/\s+/g," ").trim().slice(0,max);}
function readable(value:unknown):string{if(value==null||value===false)return"";if(value===true)return"Required";if(Array.isArray(value))return value.map(readable).filter(Boolean).join(", ");if(typeof value==="object")return Object.entries(value as Record<string,unknown>).map(([key,item])=>{const text=readable(item);return text?`${key.replaceAll("_"," ")}: ${text}`:"";}).filter(Boolean).join("; ");return normalizeGuidedSourceText(value);}
export function formatPostedJobBrief(job:RecruiterJobOption){const fields:[string,unknown][]=[["Role",job.title],["Location",job.location],["Requirements",job.requirements],["Skills",job.skills],["Modules",job.modules],["SAP modules",job.sap_modules],["Primary module",job.primary_module],["Languages",job.languages],["Seniority",job.level],["Minimum experience",job.years_required],["Project types",job.project_types],["Implementation",job.requires_implementation],["AMS support",job.requires_ams_support],["Rollout",job.requires_rollout],["Migration",job.requires_migration],["S/4HANA",job.requires_s4hana],["Consulting",job.requires_consulting]];return normalizeGuidedSourceText(fields.map(([label,value])=>{const text=readable(value);return text?`${label}: ${text}.`:"";}).filter(Boolean).join(" "),8000);}
export async function extractGuidedUpload(file:File,options:{parsePdf?:(bytes:Buffer)=>Promise<string>}={}){if(file.size<=0||file.size>GUIDED_UPLOAD_MAX_BYTES)throw Object.assign(new Error("invalid_size"),{code:"GUIDED_FILE_EXTRACTION_FAILED"});const name=file.name.toLowerCase(),bytes=Buffer.from(await file.arrayBuffer());let text="";
 if(name.endsWith(".txt")&&file.type==="text/plain"){if(bytes.includes(0))throw new Error("invalid_txt");text=bytes.toString("utf8");}
 else if(name.endsWith(".pdf")&&file.type==="application/pdf"&&bytes.subarray(0,5).toString()==="%PDF-"){if(bytes.includes(Buffer.from("/Encrypt")))throw new Error("encrypted_pdf");if(options.parsePdf)text=await options.parsePdf(bytes);else{const pdf=(await import("pdf-parse")).default;text=(await pdf(bytes)).text;}}
 else if(name.endsWith(".docx")&&["application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/octet-stream"].includes(file.type)&&bytes[0]===0x50&&bytes[1]===0x4b){const JSZip=(await import("jszip")).default,zip=await JSZip.loadAsync(bytes);if(!zip.file("[Content_Types].xml")||!zip.file("word/document.xml"))throw new Error("invalid_docx");const mammoth=await import("mammoth");text=(await mammoth.extractRawText({buffer:bytes})).value;}
 else throw new Error("unsupported_file");const brief=String(text??"").normalize("NFKC").replace(/\0/g,"").trim().slice(0,GUIDED_MODEL_INPUT_MAX);if(!brief)throw new Error("empty_file");return brief;}
