import {buildSavedPackPreviewUrl,buildSavedSearchPreviewUrl,normalizeSavedPackSize} from "./savedSearchPackPreview";
import {buildRecruiterPackCompareUrl,buildRecruiterResultsUrl} from "./talentPackBuilder";
import type {JobPackContext,JobPreview,JobPreviewState,JobPriority,JobSearchContext,JobPreviewStatus,JobSafety,JobWorkMode} from "./jobPreviewTypes";
type Params=URLSearchParams|Record<string,unknown>;const SAFETY:JobSafety={previewOnly:true,candidateDbWrites:0,jobDbWrites:0,supabaseWrites:0,workflowWrites:0,openAiCalls:0,databasePersistence:false};
const toParams=(input:Params|JobPreview)=>{const query=new URLSearchParams();if(input instanceof URLSearchParams)return new URLSearchParams(input);for(const[key,value]of Object.entries(input)){if(key==="safety"||value===undefined||value===null||value==="")continue;if(Array.isArray(value))query.set(key,value.join(","));else if(typeof value!=="object")query.set(key,String(value));}return query;};
const value=(query:URLSearchParams,...keys:string[])=>keys.map(key=>query.get(key)?.trim()).find(Boolean)||"";const number=(input:string)=>{const parsed=Number(input);return Number.isFinite(parsed)&&parsed>=0?parsed:undefined};
const stableId=(parts:string[])=>{const source=parts.join("|").toLowerCase();let hash=2166136261;for(let index=0;index<source.length;index++){hash^=source.charCodeAt(index);hash=Math.imul(hash,16777619)}return `job-preview-${(hash>>>0).toString(36)}`;};
const unique=(items:string[])=>items.filter((item,index,all)=>all.indexOf(item)===index);
const isJobPreview=(input:Params|JobPreview):input is JobPreview=>!(input instanceof URLSearchParams)&&typeof (input as JobPreview).id==="string"&&Array.isArray((input as JobPreview).modules);
export function parseSkillsInput(input:unknown){const values=Array.isArray(input)?input.flatMap(item=>String(item).split(/[,;|\n]/)):String(input||"").split(/[,;|\n]/);return unique(values.map(item=>item.trim()).filter(Boolean));}
export function parseTargetCompaniesInput(input:unknown){return parseSkillsInput(input);}
export function normalizeJobPriority(input:unknown):JobPriority{const value=String(input||"").toLowerCase();return value==="low"||value==="high"||value==="urgent"?value:"medium";}
export function normalizeJobStatus(input:unknown):JobPreviewStatus{const value=String(input||"").toLowerCase();return value==="draft"||value==="active_preview"||value==="closed_preview"?value:"preview_only";}
export function buildJobPreview(params:Params):JobPreview{const query=toParams(params),jobTitle=value(query,"jobTitle","roleTitle")||"Untitled Role Preview",clientName=value(query,"clientName")||"Client Preview",createdAt=value(query,"createdAt","demoSeed")||"preview-v1",work=value(query,"workMode").toLowerCase(),workMode:JobWorkMode=work==="onsite"||work==="hybrid"||work==="remote"?work:"unknown",creator=value(query,"createdByRole")==="admin"?"admin":"recruiter";return{id:stableId([jobTitle,clientName,createdAt]),jobTitle,clientName,employmentType:value(query,"employmentType")||undefined,seniority:value(query,"seniority")||undefined,country:value(query,"country","countries")||undefined,city:value(query,"city","location")||undefined,workMode,salaryMin:number(value(query,"salaryMin")),salaryMax:number(value(query,"salaryMax")),currency:value(query,"currency")||undefined,contractDuration:value(query,"contractDuration")||undefined,priority:normalizeJobPriority(query.get("priority")),status:normalizeJobStatus(query.get("status")),jdText:value(query,"jdText")||undefined,mustHaveSkills:parseSkillsInput(query.getAll("mustHave").concat(query.getAll("mustHaveSkills"))),niceToHaveSkills:parseSkillsInput(query.getAll("niceToHave").concat(query.getAll("niceToHaveSkills"))),modules:parseSkillsInput(query.getAll("modules").concat(query.getAll("module"))),industries:parseSkillsInput(query.getAll("industries")),targetCompanies:parseTargetCompaniesInput(query.getAll("targetCompanies")),notes:value(query,"notes"),createdAt,createdByRole:creator,safety:SAFETY};}
const jobParams=(job:JobPreview,params:Params=new URLSearchParams())=>{const query=toParams(params);query.set("jobId",job.id);query.set("jobTitle",job.jobTitle);query.set("roleTitle",job.jobTitle);query.set("clientName",job.clientName);if(job.country)query.set("country",job.country);if(job.city)query.set("location",job.city);if(job.modules[0])query.set("module",job.modules[0]);if(!query.get("q"))query.set("q",job.jobTitle);return query;};
const candidateIds=(query:URLSearchParams)=>query.getAll("candidateIds").flatMap(item=>item.split(",")).concat(query.getAll("candidateId")).map(item=>item.trim()).filter(Boolean).filter((item,index,all)=>all.indexOf(item)===index);
export function buildJobSearchContext(job:JobPreview,params:Params):JobSearchContext{const query=jobParams(job,params),years=number(value(query,"years","yearsMin","minYears"));return{jobId:job.id,jobTitle:job.jobTitle,clientName:job.clientName,keyword:value(query,"q","keyword")||job.jobTitle,module:value(query,"module"),country:value(query,"country"),location:value(query,"location","city"),yearsMin:years,searchParams:Object.fromEntries([...new Set(query.keys())].map(key=>{const values=query.getAll(key);return[key,values.length>1?values:values[0]||""]}))};}
export function buildJobPreviewUrl(jobOrParams:Params|JobPreview){const job=isJobPreview(jobOrParams)?jobOrParams:buildJobPreview(jobOrParams),query=jobParams(job,isJobPreview(jobOrParams)?new URLSearchParams():jobOrParams);return `/recruiter/jobs/preview?${query.toString()}`;}
export function buildJobTalentSearchUrl(jobOrParams:Params|JobPreview){const job=isJobPreview(jobOrParams)?jobOrParams:buildJobPreview(jobOrParams),query=jobParams(job,isJobPreview(jobOrParams)?new URLSearchParams():jobOrParams);return buildRecruiterResultsUrl(query);}
export function buildJobSavedSearchUrl(jobOrParams:Params|JobPreview){const job=isJobPreview(jobOrParams)?jobOrParams:buildJobPreview(jobOrParams),query=jobParams(job,isJobPreview(jobOrParams)?new URLSearchParams():jobOrParams);return buildSavedSearchPreviewUrl(query);}
export function buildJobPackCompareUrl(jobOrParams:Params|JobPreview,packSize:unknown){const job=isJobPreview(jobOrParams)?jobOrParams:buildJobPreview(jobOrParams),query=jobParams(job,isJobPreview(jobOrParams)?new URLSearchParams():jobOrParams);return buildRecruiterPackCompareUrl(query,normalizeSavedPackSize(packSize));}
export function buildJobClientReportUrl(jobOrParams:Params|JobPreview,ids:string[]){const job=isJobPreview(jobOrParams)?jobOrParams:buildJobPreview(jobOrParams),query=jobParams(job,isJobPreview(jobOrParams)?new URLSearchParams():jobOrParams),unique=ids.map(item=>item.trim()).filter(Boolean).filter((item,index,all)=>all.indexOf(item)===index);query.set("candidateIds",unique.join(","));query.set("preview","job");return `/recruiter/client-report?${query.toString()}`;}
export function buildJobPackContext(job:JobPreview,params:Params):JobPackContext{const query=jobParams(job,params),packSize=normalizeSavedPackSize(query.get("packSize")),ids=candidateIds(query);query.set("packSize",String(packSize));return{jobId:job.id,savedSearchId:value(query,"savedSearchId")||undefined,packSize,candidateIds:ids,packCompareUrl:buildRecruiterPackCompareUrl(query,packSize),savedPackUrl:buildSavedPackPreviewUrl(query),reportUrl:ids.length?buildJobClientReportUrl(query,ids):undefined};}
export function buildJobPreviewState(params:Params):JobPreviewState{const activeJob=buildJobPreview(params);return{jobs:[activeJob],activeJob,safety:SAFETY};}
