import type {AuthFormFieldPreview,AuthFormPreview,AuthUiRoutePreview,InviteAcceptPreview,LoginUiPreviewState,RoleLandingRoutePreview} from "./loginUiPreviewTypes";import type {UserRole} from "./roleAccessTypes";
const ROLES:UserRole[]=["admin","recruiter_manager","recruiter","client","candidate","guest"],landing:Record<UserRole,string>={admin:"/recruiter/dashboard",recruiter_manager:"/recruiter/dashboard",recruiter:"/recruiter/dashboard",client:"/client/portal",candidate:"/candidate/portal",guest:"/auth/login"};
const field=(name:string,label:string,type:string,requiredEventually=true,sensitive=false):AuthFormFieldPreview=>({name,label,type,requiredEventually,sensitive,valuePrinted:false});
const definitions:Record<string,{label:string;fields:AuthFormFieldPreview[];helperText:string}>={login:{label:"Sign in",fields:[field("email","Email","email",true,true),field("password","Password","password",true,true),field("role","Role preview","select")],helperText:"Sign in is disabled until Supabase Auth is enabled."},signup:{label:"Request access",fields:[field("fullName","Full name","text"),field("email","Work email","email",true,true),field("organization","Company / organization","text"),field("requestedRole","Requested role","select"),field("message","Message","textarea",false)],helperText:"No account is created and no approval request is stored."},forgot_password:{label:"Forgot password",fields:[field("email","Email","email",true,true)],helperText:"No password reset email is sent."},invite:{label:"Accept invite",fields:[field("email","Email","email",false,true),field("role","Invited role","text"),field("tokenStatus","Token status","hidden",false,true)],helperText:"The invite token is neither printed nor validated."},logout:{label:"Sign out",fields:[],helperText:"No session exists and no cookies are cleared."}};
export function buildAuthUiRoutesPreview():AuthUiRoutePreview[]{return[["/auth/login","Login Preview","Preview sign in.",ROLES],["/auth/signup","Request Access","Preview signup and access requests.",ROLES],["/auth/forgot-password","Forgot Password","Preview password reset request.",ROLES],["/auth/invite","Invite Accept","Preview invite acceptance.",ROLES],["/auth/logout","Logout Preview","Preview sign out.",ROLES],["/auth/landing-preview","Role Landing Preview","Preview post-login landing.",ROLES]].map(([route,label,purpose,intendedUsers])=>({route:route as string,label:label as string,purpose:purpose as string,intendedUsers:intendedUsers as UserRole[],enabledNow:false,previewOnly:true,supabaseAuthCalls:0,dbWrites:0,emailSends:0}));}
export function buildAuthFormPreview(formKey:string):AuthFormPreview{const item=definitions[formKey]||definitions.login;return{formKey,label:item.label,fields:item.fields,submitEnabled:false,submitMode:"disabled_preview",helperText:item.helperText,safety:{supabaseAuthCalls:0,dbWrites:0,emailSends:0,sessionsCreated:0,cookiesSet:0}};}
export function getDefaultLandingRouteForRole(role:UserRole){return landing[ROLES.includes(role)?role:"guest"];}
export function buildRoleLandingRoutesPreview():RoleLandingRoutePreview[]{return ROLES.map(role=>({role,defaultLandingRoute:getDefaultLandingRouteForRole(role),description:`After future authentication, ${role} would land on ${getDefaultLandingRouteForRole(role)}.`,requiresAuthEventually:true}));}
export function buildInviteAcceptPreview(params:Record<string,string|string[]|undefined>={}):InviteAcceptPreview{const rawRole=typeof params.role==="string"?params.role:"guest",invitedRole=ROLES.includes(rawRole as UserRole)?rawRole as UserRole:"guest";return{inviteType:typeof params.inviteType==="string"?params.inviteType:"access",invitedRole,tokenHandling:"disabled_preview",tokenPrinted:false,emailSendEnabled:false,dbWrites:0,status:"preview_only"};}
export function buildLoginRedirectPreview(role:UserRole){return{role,redirectTo:getDefaultLandingRouteForRole(role),wouldRedirectAfterFutureLogin:true,redirectedNow:false};}
export function buildLoginUiPreviewState():LoginUiPreviewState{return{routes:buildAuthUiRoutesPreview(),forms:Object.keys(definitions).map(buildAuthFormPreview),roleLandingRoutes:buildRoleLandingRoutesPreview(),invitePreview:buildInviteAcceptPreview(),safety:{realAuthEnabled:false,supabaseAuthCalls:0,sessionsCreated:0,cookiesSet:0,userDbWrites:0,emailSends:0,openAiCalls:0}};}
export function validateLoginUiPreview(state=buildLoginUiPreviewState()){return{valid:state.routes.length===6&&state.forms.every(form=>!form.submitEnabled)&&state.roleLandingRoutes.length===6&&!state.invitePreview.tokenPrinted&&!state.safety.realAuthEnabled,allRoutesPresent:state.routes.length===6,allSubmitsDisabled:state.forms.every(form=>!form.submitEnabled),allRolesMapped:ROLES.every(role=>state.roleLandingRoutes.some(item=>item.role===role)),inviteTokenHidden:!state.invitePreview.tokenPrinted};}
