import {getDefaultLandingRouteForRole} from "./loginUiPreview";import {buildMiddlewareDecisionPreview} from "./middlewareGuardPreview";import {getVisibleNavForRole} from "./roleAccessPreview";import type {MockAuthSessionPreview,MockAuthUserPreview,MockRoleSwitcherPreview,MockSessionRouteContext,MockSessionSafety} from "./mockAuthSessionTypes";import type {UserRole} from "./roleAccessTypes";
type Params=Record<string,string|string[]|undefined>;const ROLES:UserRole[]=["admin","recruiter_manager","recruiter","client","candidate","guest"],EMAILS:Record<UserRole,string>={admin:"admin@primus.preview",recruiter_manager:"recruiter.manager@primus.preview",recruiter:"recruiter@primus.preview",client:"client@client.preview",candidate:"candidate@candidate.preview",guest:"guest@preview.local"},NAMES:Record<UserRole,string>={admin:"Admin Preview",recruiter_manager:"Recruiter Manager Preview",recruiter:"Recruiter Preview",client:"Client User Preview",candidate:"Candidate Preview",guest:"Guest Preview"},SAFETY:MockSessionSafety={realAuthEnabled:false,supabaseAuthCalls:0,sessionsCreated:0,cookiesRead:0,cookiesSet:0,localStorageWrites:0,userDbReads:0,userDbWrites:0,middlewareEnforced:false,emailSends:0,openAiCalls:0};
const value=(input:string|string[]|undefined)=>typeof input==="string"&&input.trim()?input.trim():undefined,resolve=(input:unknown)=>{const raw=typeof input==="string"?input.trim():"",role=ROLES.includes(raw as UserRole)?raw as UserRole:"guest";return{role,warnings:raw&&raw!==role?["Unknown role "+raw+" defaulted safely to guest."]:[]};};
export function buildMockAuthUserPreview(inputRole:UserRole|string,params:Params={}):MockAuthUserPreview{const {role}=resolve(inputRole);return{id:value(params.userId)||"mock-user-"+role,email:value(params.email)||EMAILS[role],fullName:value(params.fullName)||NAMES[role],role,organizationId:value(params.organizationId)||(role==="admin"||role==="recruiter_manager"||role==="recruiter"?"org-primus-preview":role==="client"?"org-client-preview":undefined),clientId:value(params.clientId)||(role==="client"?"client-preview":undefined),candidateId:value(params.candidateId)||(role==="candidate"?"candidate-preview":undefined),source:"mock_preview",realAuthUser:false};}
export function buildMockVisibleNav(inputRole:UserRole|string){return getVisibleNavForRole(resolve(inputRole).role);}
export function buildMockLandingUrl(inputRole:UserRole|string){const role=resolve(inputRole).role;return getDefaultLandingRouteForRole(role)+"?role="+encodeURIComponent(role)+(role==="candidate"?"&candidateId=candidate-preview":role==="client"?"&clientName=Client%20Preview":"");}
export function buildMockSessionRouteContext(inputRole:UserRole|string,pathname:string):MockSessionRouteContext{const resolution=resolve(inputRole),decision=buildMiddlewareDecisionPreview(resolution.role,pathname||getDefaultLandingRouteForRole(resolution.role),resolution.role==="guest"?"unauthenticated_preview":"authenticated_preview");return{pathname:decision.pathname,role:decision.role,allowed:decision.allowed,redirectPreview:decision.redirectTo,reason:decision.reason,advisoryOnly:true,middlewareEnforced:false,warnings:resolution.warnings};}
export function buildMockRoleSwitcherPreview(params:Params={}):MockRoleSwitcherPreview{const role=resolve(value(params.role)).role,user=buildMockAuthUserPreview(role,params);return{roles:[...ROLES],selectedRole:role,selectedUser:user,roleSwitchUrl:"/auth/mock-session?role="+encodeURIComponent(role),landingUrl:buildMockLandingUrl(role),safety:{...SAFETY}};}
export function buildMockAuthSessionPreview(params:Params={}):MockAuthSessionPreview{const resolution=resolve(value(params.role)),user=buildMockAuthUserPreview(resolution.role,params),pathname=value(params.pathname)||getDefaultLandingRouteForRole(resolution.role),context=buildMockSessionRouteContext(value(params.role)||resolution.role,pathname);return{id:"mock-session-"+resolution.role+"-preview",status:"preview_only",role:resolution.role,email:user.email,fullName:user.fullName,organizationId:user.organizationId,clientId:user.clientId,candidateId:user.candidateId,defaultLandingRoute:getDefaultLandingRouteForRole(resolution.role),visibleNav:buildMockVisibleNav(resolution.role),routeAccessSummary:{...context,warnings:resolution.warnings},safety:{...SAFETY}};}
export function validateMockAuthSessionPreview(){const preview=buildMockAuthSessionPreview(),invalid=buildMockAuthSessionPreview({role:"invalid_role"}),switcher=buildMockRoleSwitcherPreview({role:"recruiter"});return{valid:preview.role==="guest"&&invalid.role==="guest"&&invalid.routeAccessSummary.warnings.length>0&&switcher.roles.length===6&&!preview.safety.realAuthEnabled&&!preview.safety.supabaseAuthCalls&&!preview.safety.sessionsCreated&&!preview.safety.cookiesRead&&!preview.safety.cookiesSet&&!preview.safety.localStorageWrites&&!preview.safety.userDbReads&&!preview.safety.userDbWrites&&!preview.safety.middlewareEnforced,preview,invalid,switcher};}
