import fs from "node:fs";import path from "node:path";import {recruiterRouteRegistry} from "./recruiterRouteRegistry";import {buildPortalNavigationPreview,buildPortalUrlForRole} from "./portalNavigationPreview";import type {AuditCoverageHealth,AuthPlanningHealth,DataSafetyHealth,HealthCheckStatus,PlatformBlocker,PlatformNextAction,PlatformReadinessLevel,PortalHealthCheck,PortalNavigationHealth,PortalProductHealthReport,ReleaseReadinessGate,RouteHealthSummary} from "./portalProductHealthTypes";
const exists=(base:string,file:string)=>fs.existsSync(path.join(base,file));const has=(base:string,file:string,token:string)=>{try{return fs.readFileSync(path.join(base,file),"utf8").includes(token)}catch{return false}};
const PORTALS=[
 {portalKey:"recruiter",label:"Recruiter Portal",route:"/recruiter/dashboard",roles:["admin","recruiter_manager","recruiter"],builder:"lib/recruiterPortalMvpPreview.ts",audit:"scripts/auditRecruiterPortalMvpPreview.ts"},
 {portalKey:"client",label:"Client Portal",route:"/client/portal",roles:["admin","client"],builder:"lib/clientPortalMvpPreview.ts",audit:"scripts/auditClientPortalMvpPreview.ts"},
 {portalKey:"candidate",label:"Candidate Portal",route:"/candidate/portal",roles:["admin","candidate"],builder:"lib/candidatePortalPreview.ts",audit:"scripts/auditCandidatePortalMvpPreview.ts"},
 {portalKey:"admin",label:"Admin Portal",route:"/admin/portal",roles:["admin"],builder:"lib/adminPortalMvpPreview.ts",audit:"scripts/auditAdminPortalMvpPreview.ts"}
] as const;
export function buildPortalHealthChecks(baseDir=process.cwd()):PortalHealthCheck[]{const nav=buildPortalNavigationPreview();return PORTALS.map(p=>{const entry=recruiterRouteRegistry.find(x=>x.route===p.route),routeExists=Boolean(entry&&exists(baseDir,entry.expectedFilePath)),previewBuilderAvailable=exists(baseDir,p.builder),auditAvailable=exists(baseDir,p.audit),navigationAvailable=nav.portals.some(x=>x.route===p.route),mockSessionLinkAvailable=nav.portals.some(x=>x.route===p.route&&x.mockSessionRoute.includes("/auth/mock-session")),readOnly=Boolean(entry?.readOnly&&!entry.candidateDbWrites&&!entry.workflowWrites),issues=[...(!routeExists?["Route file is missing."]:[]),...(!previewBuilderAvailable?["Preview builder is missing."]:[]),...(!auditAvailable?["Portal audit is missing."]:[])];return{portalKey:p.portalKey,label:p.label,route:p.route,intendedRoles:[...p.roles],routeExists,previewBuilderAvailable,auditAvailable,navigationAvailable,mockSessionLinkAvailable,readOnly,status:issues.length?"blocked":"passed",issues,nextActions:issues.length?["Restore the missing deterministic preview evidence."]:[]};});}
export function buildPortalNavigationHealth(baseDir=process.cwd()):PortalNavigationHealth{const p=buildPortalNavigationPreview(),expected={admin:"/admin/portal",recruiter_manager:"/recruiter/dashboard",recruiter:"/recruiter/dashboard",client:"/client/portal",candidate:"/candidate/portal",guest:"/portal"},roleMappingsValid=Object.entries(expected).every(([r,url])=>buildPortalUrlForRole(r)===url),backlinkFiles=["app/recruiter/dashboard/layout.tsx","app/client/portal/layout.tsx","app/candidate/portal/layout.tsx","app/admin/template.tsx"],issues:string[]=[];const health={portalRoute:"/portal",portalEntriesExpected:4,portalEntriesFound:p.portals.length,roleMappingsValid,backlinksAvailable:backlinkFiles.every(f=>has(baseDir,f,'href="/portal"')),loginPreviewLinksAvailable:p.portals.every(x=>x.authPreviewRoute.includes("/auth/login")),mockSessionLinksAvailable:p.portals.every(x=>x.mockSessionRoute.includes("/auth/mock-session")),publicPreviewAccess:true,status:"passed" as HealthCheckStatus,issues};if(Object.entries(health).some(([k,v])=>k!=="issues"&&k!=="status"&&(v===false||v===0)))health.status="blocked";return health;}
const authFiles=["app/auth/preview/page.tsx","app/auth/setup/page.tsx","app/auth/migrations/page.tsx","app/auth/rls/page.tsx","app/auth/login/page.tsx","app/auth/helpers/page.tsx","app/auth/middleware/page.tsx","app/auth/mock-session/page.tsx","app/auth/staging/page.tsx"];
export function buildAuthPlanningHealth(baseDir=process.cwd()):AuthPlanningHealth{const v=authFiles.map(f=>exists(baseDir,f));return{roleAccessPreviewAvailable:v[0],authSetupPreviewAvailable:v[1],migrationPreviewAvailable:v[2],rlsPreviewAvailable:v[3],loginUiPreviewAvailable:v[4],authHelpersPreviewAvailable:v[5],middlewarePreviewAvailable:v[6],mockSessionPreviewAvailable:v[7],stagingPlanAvailable:v[8],realAuthEnabled:false,realMiddlewareEnabled:false,stagingImplementationStarted:false,productionBlocked:true,status:v.every(Boolean)?"passed":"blocked",blockers:["Real Supabase Auth is not implemented.","Migrations and RLS have not been applied or tested.","Middleware enforcement has not started."]};}
export function buildDataSafetyHealth():DataSafetyHealth{return{mainDbDeletionBlocked:true,fullReuploadBlocked:true,importStagingRequired:true,mergeApprovalRequired:true,candidateApplyRequiresConfirmation:true,backupRollbackRequiredForApply:true,portalDbWrites:0,portalWorkflowWrites:0,portalEmailSends:0,portalOpenAiCalls:0,destructiveActionsBlocked:true,status:"passed",issues:[]};}
export function buildRouteHealthSummary(baseDir=process.cwd()):RouteHealthSummary{const checked=recruiterRouteRegistry.map(r=>({...r,found:exists(baseDir,r.expectedFilePath)}));const missingFiles=checked.filter(r=>!r.found).map(r=>r.expectedFilePath),unsafeRoutes=checked.filter(r=>r.candidateDbWrites||r.workflowWrites||r.openAiCallsDefault||r.writeRisk==="write").map(r=>r.route);return{totalRoutes:checked.length,pageRoutes:checked.filter(r=>r.type==="page").length,apiRoutes:checked.filter(r=>r.type==="api").length,missingFiles,brokenLinks:[],missingFeatureLinks:[],unsafeRoutes,passed:!missingFiles.length&&!unsafeRoutes.length};}
const audits=["scripts/auditRecruiterPortalMvpPreview.ts","scripts/auditClientPortalMvpPreview.ts","scripts/auditCandidatePortalMvpPreview.ts","scripts/auditAdminPortalMvpPreview.ts","scripts/auditPortalNavigationPreview.ts","scripts/auditRoleAccessPreview.ts","scripts/auditSupabaseAuthSetupPreview.ts","scripts/auditAuthMigrationPreview.ts","scripts/auditRlsPolicyPreview.ts","scripts/auditLoginUiPreview.ts","scripts/auditAuthHelperPreview.ts","scripts/auditMiddlewareGuardPreview.ts","scripts/auditMockAuthSessionPreview.ts","scripts/auditStagingAuthEnablementPlan.ts","scripts/auditProductHealth.ts","scripts/auditUiRoutes.ts","scripts/auditStagingImplementationReadiness.ts","scripts/auditStagingEvidenceApproval.ts","scripts/auditStagingAuthRunbook.ts","scripts/auditStagingAuthExecutionGate.ts","scripts/auditStagingAuthAdapter.ts","scripts/auditStagingAuthOperations.ts","scripts/auditStagingAuthUiBinding.ts","scripts/auditStagingAuthE2e.ts"];
export function buildAuditCoverageHealth(baseDir=process.cwd()):AuditCoverageHealth{const availableAudits=audits.filter(f=>exists(baseDir,f)),missingAudits=audits.filter(f=>!exists(baseDir,f));return{requiredAudits:audits,availableAudits,missingAudits,portalAuditsCovered:availableAudits.filter(f=>/PortalMvp|PortalNavigation/.test(f)).length===5,authAuditsCovered:availableAudits.filter(f=>/RoleAccess|Auth|Rls|Login|Middleware|Mock/.test(f)).length>=9,dataSafetyAuditsCovered:availableAudits.includes("scripts/auditProductHealth.ts"),status:missingAudits.length?"blocked":"passed"};}
export function buildReleaseReadinessGates(baseDir=process.cwd()):ReleaseReadinessGate[]{const portals=buildPortalHealthChecks(baseDir),nav=buildPortalNavigationHealth(baseDir),auth=buildAuthPlanningHealth(baseDir),routes=buildRouteHealthSummary(baseDir),coverage=buildAuditCoverageHealth(baseDir),gate=(gateKey:string,label:string,target:ReleaseReadinessGate["target"],status:HealthCheckStatus,evidence:string[],blockerReason?:string,nextAction?:string):ReleaseReadinessGate=>({gateKey,label,target,required:true,status,evidence,blockerReason,nextAction});return[
 gate("demo_portals","Four portal previews healthy","demo",portals.every(x=>x.status==="passed")?"passed":"blocked",portals.map(x=>x.route)),gate("demo_navigation","Unified navigation healthy","demo",nav.status,["/portal","Four role-mapped entries"]),gate("demo_routes","Route and audit safety passes","demo",routes.passed&&coverage.status==="passed"?"passed":"blocked",[`Unsafe routes: ${routes.unsafeRoutes.length}`,"Preview safety visible"]),
 gate("staging_planning","Auth and rollback planning complete","staging",auth.status,["Nine auth planning modules","Production explicitly blocked","Rollback plan in staging preview"]),
 ...["Staging Supabase project confirmed","Migrations reviewed and applied","RLS applied and tested","Auth helpers and profile lookup implemented","Middleware enabled","Role smoke tests and rollback drill passed"].map((label,i)=>gate(`staging_implementation_${i}`,label,"staging","not_implemented",[],"Staging implementation has not started.",label)),
 ...["Staging implementation complete","RLS access and ownership tests complete","Invite/token security complete","Audit logging and email approval complete","Production backup and go/no-go approval complete"].map((label,i)=>gate(`production_${i}`,label,"production","blocked",[],"Production prerequisites are not verified.",label))];}
export function buildPlatformBlockers():PlatformBlocker[]{const rows=[
 ["real_auth","auth","critical","Real Supabase Auth not implemented"],["migrations","database","high","Auth migrations not executed"],["rls","rls","critical","RLS not executed or tested"],["middleware","middleware","high","Middleware not enforced"],["ownership","ownership","critical","User profile and ownership database not live"],["invite","auth","high","Invite flow not live"],["email","email","medium","Email workflow not enabled"],["smoke_tests","testing","high","Staging role smoke tests not executed"],["approval","production","critical","Production approval not available"]
 ] as const;return rows.map(([blockerKey,area,severity,title])=>({blockerKey,area,severity,title,description:`${title}; only deterministic planning evidence exists.`,blocksDemo:false,blocksStaging:true,blocksProduction:true,remediation:`Complete and verify ${title.toLowerCase()} in a dedicated staging environment.`}));}
export function buildPlatformNextActions():PlatformNextAction[]{return[
 ["keep_blocked","P0","Keep production blocked","Required safety posture","/admin/platform-readiness"],["confirm_staging","P0","Confirm dedicated staging Supabase environment","Required before implementation","/auth/staging"],["review_sql","P0","Review migration and RLS SQL manually","Human review required","/auth/migrations"],["auth_helpers","P1","Implement real auth helpers on staging","Begin controlled staging work","/auth/helpers"],["apply_staging","P1","Apply migrations and RLS to staging","Validate schema and access policies","/auth/rls"],["profile_lookup","P1","Implement user profile role lookup","Required for ownership"],["middleware","P1","Enable staging middleware","Enforce verified role decisions","/auth/middleware"],["smoke","P1","Run role smoke tests","Verify access boundaries"],["invite","P2","Add invite and account ownership flow","Secure onboarding"],["email","P2","Add email provider with explicit approval","Keep sends governed"],["logs","P2","Add audit logs","Record sensitive activity"],["workflows","P2","Connect portal actions to approved DB workflows","Keep writes explicit and reviewed"]
 ].map(([actionKey,priority,label,reason,route])=>({actionKey,priority:priority as PlatformNextAction["priority"],label,reason,route,status:"preview_only"}));}
export function calculatePlatformReadinessLevel(parts:Pick<PortalProductHealthReport,"portalHealth"|"portalNavigation"|"authPlanning"|"dataSafety"|"routeHealth"|"auditCoverage">):PlatformReadinessLevel{return parts.portalHealth.every(x=>x.status==="passed")&&parts.portalNavigation.status==="passed"&&parts.authPlanning.status==="passed"&&parts.dataSafety.status==="passed"&&parts.routeHealth.passed&&parts.auditCoverage.status==="passed"?"demo_ready_preview":"warning_preview";}
export function buildPortalProductHealthReport(baseDir=process.cwd()):PortalProductHealthReport{const parts={portalHealth:buildPortalHealthChecks(baseDir),portalNavigation:buildPortalNavigationHealth(baseDir),authPlanning:buildAuthPlanningHealth(baseDir),dataSafety:buildDataSafetyHealth(),routeHealth:buildRouteHealthSummary(baseDir),auditCoverage:buildAuditCoverageHealth(baseDir)};return{id:"portal-product-health-v1",generatedAt:new Date().toISOString(),status:calculatePlatformReadinessLevel(parts),executiveSummary:"Demo ready — preview. Staging planning ready. Staging Auth Preflight CLI available. Staging Auth Adapter contract available; default provider disabled and real provider not implemented. Staging Auth Operation Boundary available; sensitive inputs are redacted and audit/rate-limit previews are not persisted. Auth UI Binding Preview is preview-bound with zero real auth actions. Execution gate remains authoritative. Staging implementation not started. Production blocked.",...parts,releaseGates:buildReleaseReadinessGates(baseDir),blockers:buildPlatformBlockers(),nextActions:buildPlatformNextActions(),safety:{readOnly:true,candidateDbWrites:0,jobDbWrites:0,clientDbWrites:0,userDbWrites:0,workflowWrites:0,feedbackWrites:0,migrationExecutions:0,rlsExecutions:0,middlewareEnforced:false,authCalls:0,emailSends:0,openAiCalls:0}};}
export function validatePortalProductHealthReport(report:PortalProductHealthReport){const safe=Object.values(report.safety).every(v=>v===0||v===false||v===true);return{valid:report.portalHealth.length===4&&report.authPlanning.productionBlocked&&report.releaseGates.filter(g=>g.gateKey.startsWith("production_")).every(g=>g.status==="blocked")&&safe,issues:[] as string[]};}








