import fs from "node:fs";
import path from "node:path";
import type { QuickFixApplyDecisionFile, QuickFixApplyDecisionRecord, QuickFixApplyReviewBoard, QuickFixApplyReviewItem } from "./quickFixApplyReviewTypes";
import { buildQuickFixApplyReviewBoard } from "./quickFixApplyReviewBoard";

function clean(value: any) {
  return String(Array.isArray(value) ? value.join(", ") : value ?? "").replace(/\s+/g, " ").trim();
}

export function quickFixApplyDecisionPath(baseDir = process.cwd()) {
  return path.join(baseDir, "reports", "quick-fix-apply-decisions.json");
}

export function loadQuickFixApplyDecisions(decisionsPath = quickFixApplyDecisionPath()): QuickFixApplyDecisionFile {
  const fullPath = path.resolve(decisionsPath);
  if (!fs.existsSync(fullPath)) return { mode: "local quick fix apply decisions only; no candidate DB writes", updatedAt: "", decisions: [] };
  try {
    const parsed = JSON.parse(fs.readFileSync(fullPath, "utf8"));
    return { mode: parsed?.mode || "local quick fix apply decisions only; no candidate DB writes", updatedAt: parsed?.updatedAt || "", decisions: Array.isArray(parsed?.decisions) ? parsed.decisions : [] };
  } catch {
    return { mode: "malformed quick fix apply decisions ignored; no candidate DB writes", updatedAt: "", decisions: [] };
  }
}

export function itemToDecision(item: QuickFixApplyReviewItem, decisionMode: "suggested" | "manual" = "suggested"): QuickFixApplyDecisionRecord {
  const now = new Date().toISOString();
  return {
    decisionId: item.stagingId || `${item.candidateId}:${item.fieldName}`,
    stagingId: item.stagingId,
    candidateId: item.candidateId,
    fieldName: item.fieldName,
    dbFieldName: item.dbFieldName,
    suggestedValue: item.suggestedValue,
    decision: item.reviewRecommendation,
    reviewerNote: decisionMode === "suggested" ? "Suggested decision generated by quick fix apply review board." : "Manual recruiter decision.",
    safetyReasons: item.safetyReasons,
    source: "quick_fix_apply_review",
    decisionMode,
    createdAt: now,
    updatedAt: now,
  };
}

export function buildSuggestedQuickFixApplyDecisions(board: QuickFixApplyReviewBoard): QuickFixApplyDecisionRecord[] {
  return board.items.map((item) => itemToDecision(item, "suggested"));
}

export function writeQuickFixApplyDecisions(options: { board?: QuickFixApplyReviewBoard; decisionMode?: "suggested" | "manual"; writeDecisionFile?: boolean; decisionsPath?: string; preserveExisting?: boolean } = {}) {
  const board = options.board || buildQuickFixApplyReviewBoard();
  const decisionsPath = options.decisionsPath || quickFixApplyDecisionPath();
  const incoming = buildSuggestedQuickFixApplyDecisions(board);
  const existing = loadQuickFixApplyDecisions(decisionsPath).decisions;
  const byId = new Map((options.preserveExisting === false ? [] : existing).map((decision) => [clean(decision.decisionId), decision]));
  for (const decision of incoming) if (!byId.has(clean(decision.decisionId))) byId.set(clean(decision.decisionId), decision);
  const decisions = Array.from(byId.values());
  const file: QuickFixApplyDecisionFile = { mode: "local quick fix apply decisions only; no candidate DB writes; no staging writes; no apply; no delete", updatedAt: new Date().toISOString(), decisions };
  if (options.writeDecisionFile) {
    fs.mkdirSync(path.dirname(path.resolve(decisionsPath)), { recursive: true });
    fs.writeFileSync(path.resolve(decisionsPath), `${JSON.stringify(file, null, 2)}\n`);
  }
  return { file, decisionsWritten: incoming.length, outputPath: decisionsPath };
}
