import {buildLegacyPackCompareUrl,buildRecruiterResultsUrl,normalizeTalentPackSize} from "./talentPackBuilder";
import type {TalentPackSize} from "./talentPackTypes";
export type RecruiterPackCompareMode="top5"|"top10"|"top20"|"executive";
const toParams=(input:URLSearchParams|Record<string,unknown>)=>{const query=new URLSearchParams();if(input instanceof URLSearchParams)return new URLSearchParams(input);for(const[key,value]of Object.entries(input)){if(value===undefined||value===null||value==="")continue;if(Array.isArray(value))value.forEach(item=>query.append(key,String(item)));else query.set(key,String(value));}return query;};
const candidateIds=(query:URLSearchParams)=>[...query.getAll("candidateId"),...query.getAll("candidateIds").flatMap(value=>value.split(","))].map(value=>value.trim()).filter(Boolean).filter((value,index,all)=>all.indexOf(value)===index);
export function buildRecruiterPackCompareView(params:URLSearchParams|Record<string,unknown>){
 const query=toParams(params),rawPackSize=query.get("packSize"),requestedMode=query.get("mode"),validMode=requestedMode==="top5"||requestedMode==="top10"||requestedMode==="top20"||requestedMode==="executive",mode=(validMode?requestedMode:`top${normalizeTalentPackSize(rawPackSize)}`) as RecruiterPackCompareMode;
 const selectedPackSize:TalentPackSize=mode==="top5"?5:mode==="top10"?10:mode==="top20"?20:normalizeTalentPackSize(rawPackSize);query.set("packSize",String(selectedPackSize));query.set("mode",mode);
 const ids=candidateIds(query),encoded=ids.map(encodeURIComponent).join(","),context=(...keys:string[])=>keys.map(key=>query.get(key)).find(Boolean)||undefined;
 const choices=[{packSize:5,mode:"top5",label:"Top 5 Cards",description:"Best shortlist to review first."},{packSize:10,mode:"top10",label:"Top 10 Matrix",description:"Deeper shortlist matrix."},{packSize:20,mode:"top20",label:"Top 20 Matrix",description:"Longlist and market mapping."},{packSize:selectedPackSize,mode:"executive",label:"Executive Compare",description:"Client-ready comparison view."}] as const;
 return{searchContext:{keyword:context("q","keyword"),module:context("module","background"),location:context("location","city"),country:context("country","countries"),company:context("company"),years:context("years")},selectedPackSize,selectedMode:mode,packOptions:choices.map(option=>{const next=new URLSearchParams(query);next.set("packSize",String(option.packSize));next.set("mode",option.mode);return{...option,url:`/recruiter/pack-compare?${next.toString()}`}}),recruiterResultsUrl:buildRecruiterResultsUrl(query),legacyCompareUrl:(()=>{const url=new URL(buildLegacyPackCompareUrl(query,selectedPackSize),"http://local");url.searchParams.set("mode",mode);return `${url.pathname}?${url.searchParams.toString()}`})(),quickCompareUrl:ids.length?`/recruiter/candidate-compare?candidateIds=${encoded}`:undefined,clientReportUrl:ids.length?`/recruiter/client-report?candidateIds=${encoded}`:undefined,warnings:[...(requestedMode&&!validMode?["Unsupported mode defaulted safely."]:[]),...(rawPackSize&&!['5','10','20'].includes(rawPackSize)?["Invalid pack size defaulted to Top 5."]:[]),...(!ids.length?["No candidate IDs selected; Quick Compare and client report remain preview-only."]:[])],safety:{readOnly:true,candidateDbWrites:0,workflowWrites:0,openAiCalls:0,shortlistPreviewOnly:true,clientReportDraftOnly:true}};
}
