import {buildPackCompareUrlFromSearchParams,buildTalentPackSummary,normalizeTalentPackSize} from "./talentPackBuilder";
import type {TalentPackCandidate,TalentPackSize} from "./talentPackTypes";
export const TALENT_SEARCH_INITIAL_RENDER_LIMIT=30;
export type RecruiterTalentSearchResult={candidateId:string;name:string;title:string;currentCompany:string;previousCompany:string;location:string;totalYearsExperience:number|null;modules:string[];skills:string[];matchScore:number|null;confidence:number|null;missingInfo:boolean;reasonMatched:string;links:{candidate360:string;legacyProfile:string;submission:string;packCompare:string}};
export type RecruiterTalentSearchResults={query:string;filters:Record<string,string|string[]>;totalResults:number;results:RecruiterTalentSearchResult[];topCandidates:RecruiterTalentSearchResult[];packSummaries:ReturnType<typeof buildTalentPackSummary>[];searchId?:string;searchSessionId?:string;legacySearchUrl:string;packCompareUrl:string;warnings:string[];packSize:TalentPackSize};
const text=(value:unknown)=>typeof value==="string"?value.trim():"";
const numberOrNull=(value:unknown)=>{if(value===undefined||value===null||value==="")return null;const parsed=Number(value);return Number.isFinite(parsed)?parsed:null};
const list=(value:unknown)=>Array.isArray(value)?value.map(text).filter(Boolean):text(value).split(/[,;|]/).map(item=>item.trim()).filter(Boolean);
const first=(record:Record<string,unknown>,keys:string[])=>{for(const key of keys){const value=record[key];if(value!==undefined&&value!==null&&value!=="")return value}};
export function normalizeRecruiterTalentSearchQuery(input:URLSearchParams|Record<string,unknown>){
 const query=input instanceof URLSearchParams?new URLSearchParams(input):new URLSearchParams();
 if(!(input instanceof URLSearchParams))for(const[key,value]of Object.entries(input)){if(value===undefined||value===null||value==="")continue;if(Array.isArray(value))value.forEach(item=>query.append(key,String(item)));else query.set(key,String(value))}
 if(!query.get("q")&&query.get("keyword"))query.set("q",query.get("keyword")!);
 if(!query.get("country")&&query.get("countries"))query.set("country",query.get("countries")!);
 if(!query.get("location")&&query.get("city"))query.set("location",query.get("city")!);
 if(!query.get("minYears")&&query.get("years"))query.set("minYears",query.get("years")!);
 return query;
}
export function buildRecruiterTalentSearchResults(queryParams:URLSearchParams|Record<string,unknown>,payload:Record<string,unknown>={}):RecruiterTalentSearchResults{
 const query=normalizeRecruiterTalentSearchQuery(queryParams),raw=first(payload,["items","candidates","results"]),rows=Array.isArray(raw)?raw:[],packSize=normalizeTalentPackSize(query.get("packSize")),packCompareUrl=buildPackCompareUrlFromSearchParams(query,packSize);
 const results:RecruiterTalentSearchResult[]=rows.map((item,index)=>{const row=(item&&typeof item==="object"?item:{}) as Record<string,unknown>,candidateId=text(first(row,["candidateId","candidate_id","id","candidate_uuid"]))||`unmapped-${index+1}`,name=text(first(row,["name","fullName","full_name","candidateName"]))||"Name to be confirmed",title=text(first(row,["title","currentTitle","current_title","headline","role"])),currentCompany=text(first(row,["currentCompany","current_company","company"])),previousCompany=text(first(row,["previousCompany","previous_company"])),location=text(first(row,["location","city","country"])),modules=list(first(row,["modules","sapModules","sap_modules"])),skills=list(first(row,["skills","technicalSkills","technical_skills"])),matchScore=numberOrNull(first(row,["matchScore","match_score","score","searchFit","search_fit"])),confidence=numberOrNull(first(row,["confidence","matchConfidence","match_confidence"])),reasons=list(first(row,["reasonMatched","reason_matched","reasons","matchReasons"]));return{candidateId,name,title,currentCompany,previousCompany,location,totalYearsExperience:numberOrNull(first(row,["totalYearsExperience","total_years_experience","yearsExperience","years_experience"])),modules,skills,matchScore,confidence,missingInfo:!title||!currentCompany||!location,reasonMatched:reasons.join(" | ")||"Matched by the existing talent search engine.",links:{candidate360:`/recruiter/candidate360/${encodeURIComponent(candidateId)}`,legacyProfile:`/candidates/${encodeURIComponent(candidateId)}`,submission:`/recruiter/submission-generator?candidateId=${encodeURIComponent(candidateId)}`,packCompare:packCompareUrl}}});
 const candidates:TalentPackCandidate[]=results.map((candidate,index)=>({candidateId:candidate.candidateId,name:candidate.name,ranking:index+1,score:candidate.matchScore??undefined}));
 const total=numberOrNull(first(payload,["total","totalResults","count"])),legacyQuery=new URLSearchParams(query);legacyQuery.delete("packSize");
 return{query:query.get("q")||query.get("keyword")||"",filters:Object.fromEntries([...new Set([...query.keys()])].map(key=>{const values=query.getAll(key);return[key,values.length>1?values:values[0]||""]})),totalResults:total??results.length,results,topCandidates:results.slice(0,20),packSummaries:[5,10,20].map(size=>buildTalentPackSummary(candidates,size)),searchId:query.get("searchId")||undefined,searchSessionId:query.get("searchSessionId")||undefined,legacySearchUrl:`/search?${legacyQuery.toString()}`,packCompareUrl,warnings:results.length?[]:["No matching candidates were returned by the existing search engine."],packSize};
}
