export type RecruiterRouteEntry={route:string;type:"page"|"api";feature:string;readOnly:boolean;writeRisk:"none"|"preview"|"write";expectedFilePath:string;requiresCandidateId:boolean;requiresCandidateSelection:boolean;linkedFrom:string[];safetyNotes:string[];candidateDbWrites:boolean;workflowWrites:boolean;openAiCallsDefault:boolean};
const page=(route:string,feature:string,file:string,linkedFrom:string[]=[],candidate=false,selection=false):RecruiterRouteEntry=>({route,type:"page",feature,readOnly:true,writeRisk:"none",expectedFilePath:file,requiresCandidateId:candidate,requiresCandidateSelection:selection,linkedFrom,safetyNotes:["UI/read-only route; no candidate DB writes."],candidateDbWrites:false,workflowWrites:false,openAiCallsDefault:false});
const api=(route:string,feature:string,file:string,risk:"none"|"preview"="none",candidate=false,selection=false):RecruiterRouteEntry=>({route,type:"api",feature,readOnly:true,writeRisk:risk,expectedFilePath:file,requiresCandidateId:candidate,requiresCandidateSelection:selection,linkedFrom:[],safetyNotes:[risk==="preview"?"POST preview only; no persistence.":"Read-only API; no persistence."],candidateDbWrites:false,workflowWrites:false,openAiCallsDefault:false});
export const recruiterRouteRegistry:RecruiterRouteEntry[]=[
page("/recruiter/talent-search","Talent Search","app/recruiter/talent-search/page.tsx",["/recruiter/dashboard"]),
page("/recruiter/compare","Unified Compare","app/recruiter/compare/page.tsx",["/recruiter/dashboard","/recruiter/talent-search","/recruiter/smart-shortlist"]),
page("/search","Legacy Talent Search","app/search/page.tsx",["/recruiter/talent-search"]),
page("/compare","Legacy Pack Compare","app/compare/page.tsx",["/recruiter/talent-search","/recruiter/compare"]),
page("/candidate/portal","Candidate Portal","app/candidate/portal/page.tsx",[]),
page("/recruiter/candidate-self-confirm-review","Candidate Confirmations","app/recruiter/candidate-self-confirm-review/page.tsx",["/recruiter/dashboard"]),
page("/recruiter/dashboard","Recruiter Dashboard","app/recruiter/dashboard/page.tsx"),page("/recruiter/workflow","Data Workflow","app/recruiter/workflow/page.tsx",["/recruiter/dashboard"]),page("/recruiter/smart-shortlist","Shortlist","app/recruiter/smart-shortlist/page.tsx",["/recruiter/dashboard","/recruiter/workflow"]),page("/recruiter/candidate360/[candidateId]","Candidate360","app/recruiter/candidate360/[candidateId]/page.tsx",["/recruiter/smart-shortlist"],true),page("/candidate/self-confirm/[candidateId]","Candidate Self-confirm Preview","app/candidate/self-confirm/[candidateId]/page.tsx",["/recruiter/smart-shortlist","/recruiter/candidate360/[candidateId]"],true),page("/recruiter/candidate-compare","Compare","app/recruiter/candidate-compare/page.tsx",["/recruiter/compare","/recruiter/smart-shortlist","/recruiter/candidate360/[candidateId]"],false,true),page("/recruiter/submission-generator","Submissions","app/recruiter/submission-generator/page.tsx",["/recruiter/dashboard","/recruiter/smart-shortlist","/recruiter/candidate360/[candidateId]","/recruiter/candidate-compare"],true),page("/recruiter/client-report","Reports","app/recruiter/client-report/page.tsx",["/recruiter/dashboard","/recruiter/smart-shortlist","/recruiter/candidate-compare","/recruiter/submission-generator"],false,true),page("/recruiter/import-staging","Data Import","app/recruiter/import-staging/page.tsx",["/recruiter/dashboard"]),page("/recruiter/import-merge","Merge Review","app/recruiter/import-merge/page.tsx",["/recruiter/dashboard"]),
api("/api/recruiter/candidate-self-confirm/review","Candidate Confirmations","app/api/recruiter/candidate-self-confirm/review/route.ts"),api("/api/recruiter/dashboard","Recruiter Dashboard","app/api/recruiter/dashboard/route.ts"),api("/api/recruiter/smart-shortlist","Shortlist","app/api/recruiter/smart-shortlist/route.ts"),api("/api/candidate360/[candidateId]","Candidate360","app/api/candidate360/[candidateId]/route.ts","none",true),api("/api/candidate360/[candidateId]/self-confirm/preview","Candidate Self-confirm Preview","app/api/candidate360/[candidateId]/self-confirm/preview/route.ts","preview",true),api("/api/recruiter/candidate-compare","Compare","app/api/recruiter/candidate-compare/route.ts","preview",false,true),api("/api/recruiter/submission-generator","Submissions","app/api/recruiter/submission-generator/route.ts","preview",true),api("/api/recruiter/client-report","Reports","app/api/recruiter/client-report/route.ts","preview",false,true),api("/api/import-staging","Data Import","app/api/import-staging/route.ts"),api("/api/import-staging/preview","Data Import","app/api/import-staging/preview/route.ts","preview"),api("/api/import-merge/proposals","Merge Review","app/api/import-merge/proposals/route.ts"),api("/api/import-merge/preview","Merge Review","app/api/import-merge/preview/route.ts","preview")];
