import fs from "node:fs";
import path from "node:path";

type Source={name:string;path:string;found:boolean;generatedAt:string|null};
const MILESTONES=["manual-cleanup-v1-freeze","candidate360-self-confirm-foundation-v1","import-staging-v1","import-merge-approval-workflow-v1","candidate360-smart-shortlist-v1","candidate-compare-v1","submission-generator-v1","client-executive-report-v1"];
const RECRUITER_WORKSPACE=[
  {id:"auth-preview",title:"Auth & Access",description:"Preview Staging Auth Plan (/auth/staging), Login (/auth/login), Mock Session (/auth/mock-session), Role Access (/auth/preview), Setup (/auth/setup), Helpers (/auth/helpers), Middleware (/auth/middleware), Migration (/auth/migrations), and RLS (/auth/rls).",href:"/auth/preview"},
  {id:"client-portal",title:"Client Portal MVP Preview",description:"Preview how clients review jobs, packs, candidates, reports, and feedback actions.",href:"/client/portal"},
  {id:"jobs",title:"Jobs",description:"Create job previews and connect role requirements to search packs.",href:"/recruiter/jobs"},
  {id:"talent-search",title:"Talent Search",description:"Open search results, build Pack 5/10/20, and continue to Pack Compare.",href:"/recruiter/talent-search"},
  {id:"saved-searches",title:"Saved Searches & Packs",description:"Preview saved search sessions and Pack 5/10/20 contexts.",href:"/recruiter/saved-searches"},
  {id:"shortlist",title:"Shortlist",description:"Browse profiles ready for recruiter review.",href:"/recruiter/smart-shortlist"},
  {id:"compare",title:"Compare",description:"Quick Compare selected candidates or Pack Compare 5/10/20.",href:"/recruiter/compare"},
  {id:"submissions",title:"Submissions",description:"Generate editable candidate submission drafts.",href:"/recruiter/submission-generator"},
  {id:"reports",title:"Reports",description:"Generate client-ready shortlist reports.",href:"/recruiter/client-report"},
  {id:"candidate360",title:"Candidate360",description:"Review profile trust, completeness, and missing information.",href:"/recruiter/smart-shortlist"},
];
const ADMIN_DATA_TOOLS=[
  {id:"data-import",title:"Data Import",description:"Stage uploads and reuploads before merge.",href:"/recruiter/import-staging"},
  {id:"merge-review",title:"Merge Review",description:"Review imported data before any merge.",href:"/recruiter/import-merge"},
  {id:"data-workflow",title:"Data Workflow",description:"Review internal data quality and workflow state.",href:"/recruiter/workflow"},
  {id:"product-health",title:"Admin Portal",description:"Review product health, data operations, auth planning, audits, and safety controls.",href:"/admin/portal"},
];
const CANDIDATE_QUALITY_TOOLS=[
  {id:"candidate-portal",title:"Candidate Portal MVP Preview",description:"Preview candidate profile preferences, availability, consent, and CV upload placeholder.",href:"/candidate/portal",status:"Preview only"},
  {id:"candidate-confirmations",title:"Candidate Confirmations",description:"Review candidate-submitted profile confirmations before applying to the main database.",href:"/recruiter/candidate-self-confirm-review",status:"Preview / review only"},
];
function read(base:string,relative:string){const full=path.join(base,"reports",relative);try{const data=JSON.parse(fs.readFileSync(full,"utf8"));return{data,source:{name:relative,path:full,found:true,generatedAt:data.generatedAt||null} as Source};}catch{return{data:null,source:{name:relative,path:full,found:false,generatedAt:null} as Source};}}

export function buildRecruiterDashboard(baseDir=process.cwd()){
  const files=["recruiter-workflow-audit.json","recruiter-workflow-state.json","repair-queue-audit.json","smart-shortlist-audit.json","candidate360-audit.json","import/import-staging-audit.json","import/import-merge-plan-preview.json","client-executive-report-audit.json","submission-generator-audit.json","candidate-compare-audit.json","manual-cleanup-v1-freeze.json"].map(name=>read(baseDir,name));
  const get=(name:string)=>files.find(item=>item.source.name===name)?.data;
  const workflow=get("recruiter-workflow-state.json"),audit=get("recruiter-workflow-audit.json"),repair=get("repair-queue-audit.json"),shortlist=get("smart-shortlist-audit.json"),candidate360=get("candidate360-audit.json"),staging=get("import/import-staging-audit.json"),merge=get("import/import-merge-plan-preview.json"),client=get("client-executive-report-audit.json"),submission=get("submission-generator-audit.json"),compare=get("candidate-compare-audit.json");
  const total=Number(shortlist?.totalCandidates??workflow?.totalCandidates??audit?.totalCandidates??970),ready=Number(shortlist?.readyForShortlist??workflow?.summary?.readyForShortlist??audit?.summary?.readyForShortlist??277),needsRepair=Number(shortlist?.needsRepair??repair?.needsRepairCandidates??workflow?.summary?.needsRepair??617),confirmation=Number(shortlist?.needsCandidateConfirmation??candidate360?.needsCandidateConfirmation??0),needsValidation=Number(workflow?.summary?.needsValidation??audit?.summary?.needsValidation??0),mergeReady=staging?.summary?.readyForMergePreview??null;
  const generated=files.filter(item=>item.source.generatedAt).map(item=>item.source.generatedAt as string).sort().at(-1)||null;
  return{candidateQualityTools:CANDIDATE_QUALITY_TOOLS,generatedAt:new Date().toISOString(),lastUpdatedAt:generated,mode:"read-only Recruiter Dashboard; no candidate DB writes; no workflow writes; no OpenAI calls",dashboardRoute:"/recruiter/dashboard",summary:{totalCandidates:total,readyForShortlist:ready,needsRepair,needsCandidateConfirmation:confirmation,needsValidation},kpis:[{label:"Total candidates",value:total,status:"available"},{label:"Ready for shortlist",value:ready,status:"available"},{label:"Needs repair",value:needsRepair,status:"available"},{label:"Needs candidate confirmation",value:confirmation,status:candidate360||shortlist?"available":"not available yet"},{label:"Data Import ready",value:mergeReady??"Not available yet",status:mergeReady===null?"not available yet":"available"},{label:"Reports",value:client?.reportGenerated?"Available":"Not available yet",status:client?"available":"not available yet"},{label:"Compare",value:compare?.resultsGenerated?"Available":"Not available yet",status:compare?"available":"not available yet"},{label:"Submissions",value:submission?.draftGenerated?"Available":"Not available yet",status:submission?"available":"not available yet"}],workflowCards:[{title:"Ready for Shortlist",count:ready,description:"Profiles ready for recruiter review.",href:"/recruiter/smart-shortlist",status:"ready"},{title:"Needs Repair",count:needsRepair,description:"Profile quality work remains non-blocking.",href:"/recruiter/workflow",status:"attention"},{title:"Needs Validation",count:needsValidation,description:"Profiles awaiting validation.",href:"/recruiter/workflow",status:"attention"},{title:"Candidate Confirmation Needed",count:confirmation,description:"Candidate self-confirm remains preview-only.",href:"/recruiter/smart-shortlist",status:"attention"},{title:"Data Import",count:staging?.importedCandidates??"Not available",description:"New uploads enter staging first.",href:"/recruiter/import-staging",status:staging?"available":"not available"},{title:"Merge Review",count:merge?.approvedMerges??"Not available",description:"Merge proposals remain preview-only.",href:"/recruiter/import-merge",status:merge?"available":"not available"},{title:"Reports",count:[client,submission,compare].filter(Boolean).length,description:"Deterministic recruiter tools available.",href:"/recruiter/client-report",status:"available"}],recruiterWorkspace:RECRUITER_WORKSPACE,adminDataTools:ADMIN_DATA_TOOLS,featureCards:[...RECRUITER_WORKSPACE,...ADMIN_DATA_TOOLS],recommendedFlow:["Job","Search","Pack Compare","Saved Pack","Submission","Report"],safetyPolicy:{mainDbDeletionAllowed:false,fullReuploadIntoMainDbAllowed:false,importStagingRequired:true,candidateConfirmationRecommended:true,mergeRequiresApproval:true,openAiCallsInDeterministicV1:false},milestones:MILESTONES,warnings:files.filter(item=>!item.source.found).map(item=>`${item.source.name}: not available yet`),sourceFreshness:files.map(item=>item.source)};
}
