import type {AccessArea,ActionPermission,RoleAccessMatrix,RouteAccessRule,UserRole} from "./roleAccessTypes";
const ROLES:UserRole[]=["admin","recruiter_manager","recruiter","client","candidate","guest"],RECRUITER:UserRole[]=["admin","recruiter_manager","recruiter"],ADMIN:UserRole[]=["admin"],CLIENT:UserRole[]=["admin","client"],CANDIDATE:UserRole[]=["admin","candidate"],ALL:UserRole[]=[...ROLES];
const rule=(routePattern:string,label:string,area:AccessArea,allowedRoles:UserRole[],accessLevel:RouteAccessRule["accessLevel"],description:string,sensitive=false):RouteAccessRule=>({routePattern,label,area,allowedRoles,deniedRoles:ROLES.filter(role=>!allowedRoles.includes(role)),accessLevel,description,previewOnly:true,requiresAuthEventually:accessLevel!=="public_preview",sensitive,safetyNotes:["Advisory preview only; no route is blocked.","No authentication or middleware enforcement is active."]});
const ROUTES:RouteAccessRule[]=[
 rule("/auth/preview","Auth & Role Access Preview","public",ALL,"public_preview","Public preview of future access rules."),
 ...[["/recruiter/dashboard","Recruiter Dashboard"],["/recruiter/jobs","Jobs"],["/recruiter/jobs/preview","Job Preview"],["/recruiter/talent-search","Talent Search"],["/recruiter/talent-search/results","Talent Search Results"],["/recruiter/pack-compare","Pack Compare"],["/recruiter/saved-searches","Saved Searches & Packs"],["/recruiter/compare","Compare"],["/recruiter/candidate-compare","Candidate Compare"],["/recruiter/submission-generator","Submission Draft"],["/recruiter/client-report","Client Report"],["/recruiter/candidate360/[candidateId]","Candidate360"]].map(([route,label])=>rule(route,label,"recruiter",RECRUITER,"role_restricted_preview","Recruiter workflow preview.",route.includes("candidate360"))),
 ...[["/recruiter/import-staging","Import Staging"],["/recruiter/import-merge","Import Merge"],["/recruiter/workflow","Data Workflow"],["/recruiter/candidate-self-confirm-review","Candidate Confirm Review"],["/recruiter/dashboard#product-health","Product Health"]].map(([route,label])=>rule(route,label,"admin_data",ADMIN,"admin_only_preview","Admin/data preview only.",true)),
 ...[["/client/portal","Client Portal"],["/client/portal/preview","Client Portal Preview"],["/client/candidates/[candidateId]","Client Candidate Submission"]].map(([route,label])=>rule(route,label,"client",CLIENT,"role_restricted_preview","Client-facing preview.",true)),
 ...[["/candidate/portal","Candidate Portal"],["/candidate/self-confirm/[candidateId]","Candidate Self-confirm Preview"]].map(([route,label])=>rule(route,label,"candidate",CANDIDATE,"role_restricted_preview","Candidate-owned preview.",true)),
 rule("/search","Legacy Search","legacy",ADMIN,"internal_only_preview","Backward-compatible legacy internal route."),rule("/compare","Legacy Compare","legacy",ADMIN,"internal_only_preview","Backward-compatible legacy internal route."),rule("/candidates/[candidateId]","Legacy Candidate Profile","legacy",ADMIN,"internal_only_preview","Backward-compatible legacy internal route.",true)
];
const action=(actionKey:string,label:string,area:AccessArea,allowedRoles:UserRole[],enabledNow:boolean,description:string):ActionPermission=>({actionKey,label,area,allowedRoles,previewOnly:true,enabledNow,requiresAuthEventually:true,dbWrites:0,emailSends:0,openAiCalls:0,description});
const ACTIONS:ActionPermission[]=[action("view_candidate360","View Candidate360","recruiter",RECRUITER,true,"Read-only profile review."),action("search_talent_pool","Search talent pool","recruiter",RECRUITER,true,"Read-only deterministic search."),action("build_pack","Build pack 5/10/20","recruiter",RECRUITER,true,"URL-backed pack preview."),action("save_search_preview","Save search preview","recruiter",RECRUITER,true,"Preview only; no persistence."),action("generate_submission_draft","Generate submission draft","recruiter",RECRUITER,true,"Draft generation only."),action("generate_client_report_draft","Generate client report draft","recruiter",RECRUITER,true,"Draft generation only."),action("view_client_portal_preview","View client portal preview","client",CLIENT,true,"Read-only client portal preview."),action("candidate_self_confirm_preview","Candidate self-confirm preview","candidate",CANDIDATE,true,"Preview candidate confirmation."),action("candidate_self_confirm_apply","Candidate self-confirm apply","candidate",ADMIN,false,"Disabled until authenticated approval and persistence exist."),action("import_staging","Import staging","admin_data",ADMIN,true,"Read-only staging preview."),action("import_merge_apply","Import merge apply","admin_data",ADMIN,false,"Destructive apply remains disabled."),action("quick_fix_apply","Quick fix apply","admin_data",ADMIN,false,"Destructive apply remains disabled."),action("send_email","Send email","public",ADMIN,false,"Email sending remains disabled."),action("submit_client_feedback","Submit client feedback","client",CLIENT,false,"Feedback remains disabled and unsaved.")];
const primary=["Dashboard","Jobs","Search","Shortlist","Compare","Submissions","Reports"],adminData=["Data Import","Merge Review","Data Workflow","Product Health"],client=["Client Portal","Submitted Candidates","Reports"],candidate=["Candidate Portal","Self-confirm Preview"],publicLegacy=["Auth Preview","Legacy Search","Legacy Compare"];
const nav=(role:UserRole)=>({primary:RECRUITER.includes(role)?primary:[],adminData:role==="admin"?adminData:[],client:CLIENT.includes(role)?client:[],candidate:CANDIDATE.includes(role)?candidate:[],publicLegacy:role==="admin"?[...publicLegacy]:["Auth Preview"]});
const MATRIX:RoleAccessMatrix={roles:ROLES,routeRules:ROUTES,actionPermissions:ACTIONS,navVisibility:Object.fromEntries(ROLES.map(role=>[role,nav(role)])) as RoleAccessMatrix["navVisibility"],safety:{previewOnly:true,authCalls:0,middlewareEnforcement:false,userDbWrites:0,candidateDbWrites:0,openAiCalls:0,emailSends:0}};
const normalizePath=(pathname:string)=>{const url=pathname.split("?")[0];return url.length>1&&url.endsWith("/")?url.slice(0,-1):url};
const matches=(pattern:string,pathname:string)=>{const path=normalizePath(pathname),base=pattern.split("#")[0],regex=new RegExp(`^${base.replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/\\\[[^/]+\\\]/g,"[^/]+")}$`);return regex.test(path)};
export function getRoleAccessMatrix(){return MATRIX;}
export function getRouteAccessRule(pathname:string){return ROUTES.find(item=>matches(item.routePattern,pathname));}
export function canRoleAccessRoute(role:UserRole,pathname:string){const access=getRouteAccessRule(pathname);return Boolean(access&&access.allowedRoles.includes(role)&&!access.deniedRoles?.includes(role));}
export function getVisibleNavForRole(role:UserRole){return MATRIX.navVisibility[role]||MATRIX.navVisibility.guest;}
export function getActionPermission(actionKey:string){return ACTIONS.find(item=>item.actionKey===actionKey);}
export function canRolePerformAction(role:UserRole,actionKey:string){const permission=getActionPermission(actionKey);return Boolean(permission?.enabledNow&&permission.allowedRoles.includes(role));}
export function buildRoleAccessPreview(role:UserRole,pathname:string){const selectedRole=ROLES.includes(role)?role:"guest",routeRule=getRouteAccessRule(pathname);return{role:selectedRole,pathname,routeRule,advisoryAccess:canRoleAccessRoute(selectedRole,pathname),visibleNav:getVisibleNavForRole(selectedRole),actions:ACTIONS.map(permission=>({...permission,advisoryAllowed:canRolePerformAction(selectedRole,permission.actionKey)})),previewOnly:true,enforced:false,safety:MATRIX.safety};}
export function buildRoleAccessSummary(){return{roles:ROLES,routeRuleCount:ROUTES.length,actionPermissionCount:ACTIONS.length,areas:[...new Set(ROUTES.map(item=>item.area))],adminOnlyRoutes:ROUTES.filter(item=>item.accessLevel==="admin_only_preview").map(item=>item.routePattern),disabledActions:ACTIONS.filter(item=>!item.enabledNow).map(item=>item.actionKey),safety:MATRIX.safety};}
