export type SearchConceptDefinition = {
  id: string; label: string; aliases: string[]; roleAliases?: string[];
  contextAliases?: string[]; parent?: string; related?: string[];
  stronglyRelated?: string[]; weaklyRelated?: string[]; incompatible?: string[];
  supporting?: string[]; ecosystem?: "SAP";
  semanticEvidence?: {
    strong?: string[];
    partial?: string[];
    minimumPartialMatches?: number;
  };
};

const sap = (definition: Omit<SearchConceptDefinition, "ecosystem">): SearchConceptDefinition => ({ ...definition, ecosystem: "SAP" });

// Declarative SAP ontology. Unambiguous aliases are safe globally;
// contextAliases require surrounding SAP language in free text.
export const SAP_SEARCH_CONCEPTS: SearchConceptDefinition[] = [
  sap({ id: "FICO", label: "SAP FICO", aliases: ["sap fico", "fico", "fi/co", "fi co", "finance and controlling"], roleAliases: ["fico consultant", "fico lead", "sap finance consultant"], related: ["FI", "CO", "RTR", "TRM", "FSCM", "CFIN", "GROUP_REPORTING"], supporting: ["FICO", "FI", "CO", "GL", "AP", "AR", "AA", "FI/CO", "Finance & Controlling"] }),
  sap({ id: "FI", label: "SAP FI", aliases: ["sap fi", "sap financial accounting", "financial accounting"], roleAliases: ["fi consultant", "financial accounting consultant"], contextAliases: ["fi", "finance"], parent: "FICO", supporting: ["FI", "Financial Accounting", "GL", "AP", "AR", "AA"] }),
  sap({ id: "CO", label: "SAP CO", aliases: ["sap co", "sap controlling"], roleAliases: ["co consultant", "controlling consultant"], contextAliases: ["co", "controlling"], parent: "FICO", supporting: ["CO", "Controlling", "CO-PA", "Product Costing"] }),
  sap({ id: "GL", label: "SAP General Ledger", aliases: ["general ledger", "sap gl"], contextAliases: ["gl"], parent: "FI" }),
  sap({ id: "AP", label: "SAP Accounts Payable", aliases: ["accounts payable", "sap ap"], contextAliases: ["ap"], parent: "FI" }),
  sap({ id: "AR", label: "SAP Accounts Receivable", aliases: ["accounts receivable", "sap ar"], contextAliases: ["ar"], parent: "FI" }),
  sap({ id: "AA", label: "SAP Asset Accounting", aliases: ["asset accounting", "sap aa"], contextAliases: ["aa"], parent: "FI" }),
  sap({ id: "RTR", label: "SAP Record-to-Report / RTR / R2R", aliases: ["sap rtr", "sap r2r", "record to report", "record-to-report"], roleAliases: ["rtr consultant", "r2r consultant", "record to report lead"], contextAliases: ["rtr", "r2r"], parent: "FI", supporting: ["RTR", "R2R", "Record to Report", "Financial Close", "Month-End Close", "Period-End Closing", "Year-End Close", "Closing Activities", "General Ledger Accounting", "GL Close", "Financial Reporting", "Statutory Reporting", "Intercompany Accounting", "Intercompany Reconciliation", "Consolidation", "Journal Entries", "Accruals", "Balance-Sheet Reconciliation", "Fixed Assets"], semanticEvidence: {
    strong: ["financial close", "month-end close", "month end close", "month-end closing", "month end closing", "period-end close", "period end close", "period-end closing", "period end closing", "year-end close", "year end close", "gl close", "end-to-end fi close", "end to end fi close"],
    partial: ["closing activities", "general ledger accounting", "financial reporting", "statutory reporting", "intercompany accounting", "intercompany reconciliation", "consolidation", "journal entries", "accruals", "balance-sheet reconciliation", "balance sheet reconciliation", "fixed assets"],
    minimumPartialMatches: 3,
  } }),
  sap({ id: "FSCM", label: "SAP FSCM", aliases: ["sap fscm", "financial supply chain management"], contextAliases: ["fscm"], related: ["FI", "FICO"] }),
  sap({ id: "CREDIT_MANAGEMENT", label: "SAP Credit Management", aliases: ["sap credit management"], contextAliases: ["credit management"], parent: "FSCM", related: ["SD", "OTC"] }),
  sap({ id: "COLLECTIONS_MANAGEMENT", label: "SAP Collections Management", aliases: ["sap collections management"], contextAliases: ["collections management"], parent: "FSCM" }),
  sap({ id: "DISPUTE_MANAGEMENT", label: "SAP Dispute Management", aliases: ["sap dispute management"], contextAliases: ["dispute management"], parent: "FSCM" }),
  sap({ id: "TRM", label: "SAP Treasury / TRM", aliases: ["sap trm", "sap treasury", "treasury and risk management", "s/4hana treasury"], roleAliases: ["trm consultant", "sap treasury consultant", "treasury lead"], contextAliases: ["trm", "treasury"], weaklyRelated: ["FICO", "FI"], stronglyRelated: ["MBC", "BCM", "CASH_MANAGEMENT"], supporting: ["Treasury", "TRM", "Cash Management", "Payments", "Bank Integration", "S/4HANA Treasury"] }),
  sap({ id: "CASH_MANAGEMENT", label: "SAP Cash Management", aliases: ["sap cash management"], contextAliases: ["cash management"], parent: "TRM" }),
  sap({ id: "BCM", label: "SAP Bank Communication Management / BCM", aliases: ["sap bcm", "bank communication management"], roleAliases: ["bcm consultant", "bank communication management consultant"], contextAliases: ["bcm"], parent: "TRM", stronglyRelated: ["MBC", "CASH_MANAGEMENT"], supporting: ["BCM", "Bank Communication Management", "Payments", "Bank Integration"] }),
  sap({ id: "MBC", label: "SAP Multi-Bank Connectivity / MBC", aliases: ["sap mbc", "sap multi-bank connectivity", "multi bank connectivity", "multi-bank connectivity"], roleAliases: ["mbc consultant", "multi bank connectivity consultant"], contextAliases: ["mbc"], parent: "TRM", stronglyRelated: ["BCM", "CASH_MANAGEMENT"], weaklyRelated: ["FICO"], supporting: ["MBC", "Multi-Bank Connectivity", "SAP Multi-Bank Connectivity", "Treasury", "TRM", "BCM", "Bank Communication Management", "Cash Management", "Payments", "Bank Integration"], semanticEvidence: {
    strong: ["bank integration", "payment factory", "host-to-host connectivity", "host to host connectivity", "swift connectivity", "sap payment connectivity"],
    partial: ["bcm", "bank communication management", "cash management", "payments", "swift", "host-to-host", "host to host"],
    minimumPartialMatches: 3,
  } }),
  sap({ id: "GROUP_REPORTING", label: "SAP Group Reporting", aliases: ["sap group reporting", "s/4hana group reporting", "group reporting"], roleAliases: ["group reporting consultant"], related: ["FICO", "BPC"] }),
  sap({ id: "CFIN", label: "SAP Central Finance / CFIN", aliases: ["sap central finance", "central finance", "sap cfin"], roleAliases: ["central finance consultant", "cfin consultant"], contextAliases: ["cfin"], related: ["FICO", "FI"] }),

  sap({ id: "SD", label: "SAP SD", aliases: ["sap sd", "sales and distribution"], roleAliases: ["sd consultant", "sales distribution consultant"], contextAliases: ["sd"], supporting: ["SD", "Sales & Distribution", "OTC", "Sales Order", "Pricing", "Delivery", "Billing"] }),
  sap({ id: "OTC", label: "SAP OTC / O2C", aliases: ["sap otc", "sap o2c", "order to cash", "order-to-cash", "quote to cash", "quote-to-cash"], roleAliases: ["otc consultant", "o2c consultant", "order to cash consultant", "order-to-cash consultant"], contextAliases: ["otc", "o2c"], parent: "SD", supporting: ["OTC", "O2C", "Order to Cash", "Sales Order Management", "Pricing", "Delivery", "Billing", "Credit Management", "Returns", "ATP", "aATP"], semanticEvidence: {
    strong: ["order-to-cash", "order to cash", "quote-to-cash", "quote to cash", "end-to-end otc", "end to end otc"],
    partial: ["sales order management", "pricing", "delivery", "billing", "credit management", "returns", "atp", "aatp"],
    minimumPartialMatches: 4,
  } }),
  sap({ id: "SALES_ORDER", label: "SAP Sales Order Management", aliases: ["sap sales order management"], contextAliases: ["sales order", "order management"], parent: "OTC" }),
  sap({ id: "PRICING", label: "SAP SD Pricing", aliases: ["sap sd pricing"], contextAliases: ["pricing"], parent: "OTC" }),
  sap({ id: "DELIVERY", label: "SAP Delivery Processing", aliases: ["sap delivery processing"], contextAliases: ["delivery", "delivery processing"], parent: "OTC", related: ["LE"] }),
  sap({ id: "BILLING", label: "SAP Billing", aliases: ["sap billing"], contextAliases: ["billing"], parent: "OTC" }),
  sap({ id: "RETURNS", label: "SAP Returns", aliases: ["sap returns management"], contextAliases: ["returns"], parent: "OTC" }),
  sap({ id: "ATP", label: "SAP ATP / aATP", aliases: ["sap atp", "sap aatp", "advanced available to promise", "availability check"], contextAliases: ["atp", "aatp"], parent: "SD" }),

  sap({ id: "MM", label: "SAP MM", aliases: ["sap mm", "materials management"], roleAliases: ["mm consultant", "materials management consultant"], contextAliases: ["mm"], supporting: ["MM", "Materials Management", "P2P", "Purchasing", "Inventory Management", "Invoice Verification"] }),
  sap({ id: "P2P", label: "SAP P2P", aliases: ["sap p2p", "procure to pay", "procure-to-pay", "sap source to pay", "source to pay", "source-to-pay"], roleAliases: ["p2p consultant", "procure to pay consultant", "source to pay consultant"], contextAliases: ["p2p"], parent: "MM", supporting: ["P2P", "Procure to Pay", "Source to Pay", "Purchasing", "Procurement", "Purchase Requisition", "Purchase Order", "Invoice Verification", "Vendor Management", "Goods Receipt", "GR/IR", "LIV", "Procurement Cycle", "Purchasing Cycle"], semanticEvidence: {
    strong: ["source-to-pay", "source to pay", "procurement cycle", "purchasing cycle", "gr/ir", "goods receipt and invoice receipt"],
    partial: ["purchasing", "procurement", "purchase requisition", "purchase requisitions", "purchase order", "purchase orders", "invoice verification", "vendor management", "goods receipt", "liv"],
    minimumPartialMatches: 3,
  } }),
  sap({ id: "PURCHASING", label: "SAP Purchasing / Procurement", aliases: ["sap purchasing", "sap procurement"], contextAliases: ["purchasing", "procurement"], parent: "P2P" }),
  sap({ id: "PURCHASE_REQUISITION", label: "SAP Purchase Requisition", aliases: ["sap purchase requisition"], contextAliases: ["purchase requisition"], parent: "P2P" }),
  sap({ id: "PURCHASE_ORDER", label: "SAP Purchase Order", aliases: ["sap purchase order"], contextAliases: ["purchase order"], parent: "P2P" }),
  sap({ id: "INVENTORY_MANAGEMENT", label: "SAP Inventory Management", aliases: ["sap inventory management"], contextAliases: ["inventory management"], parent: "MM" }),
  sap({ id: "INVOICE_VERIFICATION", label: "SAP Invoice Verification", aliases: ["sap invoice verification", "logistics invoice verification"], contextAliases: ["invoice verification", "liv"], parent: "MM" }),
  sap({ id: "VENDOR_MANAGEMENT", label: "SAP Vendor Management", aliases: ["sap vendor management"], contextAliases: ["vendor management"], parent: "MM" }),

  sap({ id: "PP", label: "SAP PP", aliases: ["sap pp", "production planning"], roleAliases: ["pp consultant", "production planning consultant"], contextAliases: ["pp"], supporting: ["PP", "Production Planning", "MRP", "Production Orders", "BOM", "Routing", "Shop Floor Control"] }),
  sap({ id: "MRP", label: "SAP MRP", aliases: ["sap mrp", "material requirements planning"], contextAliases: ["mrp"], parent: "PP" }),
  sap({ id: "PRODUCTION_ORDERS", label: "SAP Production Orders", aliases: ["sap production orders"], contextAliases: ["production order", "production orders"], parent: "PP" }),
  sap({ id: "BOM", label: "SAP Bill of Materials / BOM", aliases: ["sap bom", "bill of materials"], contextAliases: ["bom"], parent: "PP" }),
  sap({ id: "ROUTING", label: "SAP Routing", aliases: ["sap routing"], contextAliases: ["routing"], parent: "PP" }),
  sap({ id: "SHOP_FLOOR", label: "SAP Shop Floor Control", aliases: ["sap shop floor control"], contextAliases: ["shop floor control"], parent: "PP" }),
  sap({ id: "PP_PI", label: "SAP PP-PI", aliases: ["sap pp-pi", "sap pp/pi", "production planning for process industries", "process industries"], contextAliases: ["pp-pi", "pp pi"], parent: "PP" }),
  sap({ id: "PPDS", label: "SAP PP/DS", aliases: ["sap pp/ds", "sap ppds", "production planning and detailed scheduling", "apo pp/ds", "apo ppds", "embedded pp/ds", "s/4hana pp/ds"], roleAliases: ["ppds consultant", "pp/ds consultant"], contextAliases: ["ppds", "pp/ds"], parent: "PP", stronglyRelated: ["APO"], supporting: ["PP/DS", "PPDS", "Production Planning and Detailed Scheduling", "APO PP/DS", "S/4HANA Embedded PP/DS"], semanticEvidence: {
    strong: ["production planning and detailed scheduling", "embedded pp/ds", "apo pp/ds", "apo ppds"],
    partial: ["detailed scheduling", "product planning table", "planning board", "heuristics", "optimizer"],
    minimumPartialMatches: 3,
  } }),
  sap({ id: "QM", label: "SAP QM", aliases: ["sap qm", "sap quality management"], roleAliases: ["qm consultant", "quality management consultant"], contextAliases: ["qm", "quality management"], supporting: ["QM", "Quality Management", "Inspection", "Quality Notification", "Quality Planning"] }),
  sap({ id: "QM_INSPECTION", label: "SAP Quality Inspection", aliases: ["sap quality inspection"], contextAliases: ["inspection", "inspection lot"], parent: "QM" }),
  sap({ id: "QUALITY_NOTIFICATION", label: "SAP Quality Notification", aliases: ["sap quality notification"], contextAliases: ["quality notification"], parent: "QM" }),
  sap({ id: "QUALITY_PLANNING", label: "SAP Quality Planning", aliases: ["sap quality planning"], contextAliases: ["quality planning"], parent: "QM" }),

  sap({ id: "PM", label: "SAP PM / EAM", aliases: ["sap pm", "sap eam", "plant maintenance", "enterprise asset management"], roleAliases: ["pm consultant", "eam consultant", "plant maintenance consultant"], contextAliases: ["pm", "eam"], supporting: ["PM", "EAM", "Plant Maintenance", "Maintenance Orders", "Preventive Maintenance", "Equipment", "Functional Location"] }),
  sap({ id: "MAINTENANCE_ORDER", label: "SAP Maintenance Orders", aliases: ["sap maintenance order"], contextAliases: ["maintenance order", "maintenance orders"], parent: "PM" }),
  sap({ id: "PREVENTIVE_MAINTENANCE", label: "SAP Preventive Maintenance", aliases: ["sap preventive maintenance"], contextAliases: ["preventive maintenance"], parent: "PM" }),
  sap({ id: "EQUIPMENT", label: "SAP Equipment", aliases: ["sap equipment master"], contextAliases: ["equipment"], parent: "PM" }),
  sap({ id: "FUNCTIONAL_LOCATION", label: "SAP Functional Location", aliases: ["sap functional location"], contextAliases: ["functional location"], parent: "PM" }),
  sap({ id: "WM", label: "SAP WM", aliases: ["sap wm", "classic warehouse management"], roleAliases: ["wm consultant", "warehouse management consultant"], contextAliases: ["wm", "warehouse management"], supporting: ["WM", "Warehouse Management", "Putaway", "Picking", "RF"] }),
  sap({ id: "EWM", label: "SAP EWM", aliases: ["sap ewm", "s/4hana ewm", "extended warehouse management", "embedded ewm", "decentralized ewm"], roleAliases: ["ewm consultant", "extended warehouse management consultant"], contextAliases: ["ewm"], weaklyRelated: ["WM", "MM"], supporting: ["EWM", "Extended Warehouse Management", "S/4HANA EWM", "Embedded EWM", "Decentralized EWM", "Inbound", "Outbound", "Putaway", "Picking", "RF", "Warehouse Processes"], semanticEvidence: {
    strong: ["extended warehouse management", "embedded ewm", "decentralized ewm", "s/4hana ewm"],
    partial: ["warehouse process type", "warehouse order", "warehouse task", "handling unit", "putaway", "picking", "radio frequency", "rf framework"],
    minimumPartialMatches: 4,
  } }),
  sap({ id: "WAREHOUSE_PROCESS", label: "SAP Warehouse Processes", aliases: ["sap warehouse processes"], contextAliases: ["inbound", "outbound", "putaway", "picking", "warehouse process", "rf"], related: ["WM", "EWM"] }),
  sap({ id: "TM", label: "SAP Transportation Management / TM", aliases: ["sap tm", "sap transportation management"], roleAliases: ["sap tm consultant", "transportation management consultant"], contextAliases: ["tm", "transportation management"], supporting: ["TM", "Transportation Management", "Freight Order", "Freight Unit", "Transportation Planning", "Freight Settlement"] }),
  sap({ id: "FREIGHT_ORDER", label: "SAP Freight Order", aliases: ["sap freight order"], contextAliases: ["freight order"], parent: "TM" }),
  sap({ id: "FREIGHT_UNIT", label: "SAP Freight Unit", aliases: ["sap freight unit"], contextAliases: ["freight unit"], parent: "TM" }),
  sap({ id: "TRANSPORT_PLANNING", label: "SAP Transportation Planning", aliases: ["sap transportation planning"], contextAliases: ["transportation planning"], parent: "TM" }),
  sap({ id: "FREIGHT_SETTLEMENT", label: "SAP Freight Settlement", aliases: ["sap freight settlement"], contextAliases: ["freight settlement"], parent: "TM" }),
  sap({ id: "LE", label: "SAP Logistics Execution / LE", aliases: ["sap le", "sap logistics execution", "logistics execution"], roleAliases: ["le consultant", "logistics execution consultant"], contextAliases: ["le"], related: ["SD", "WM", "TM"], supporting: ["LE", "Logistics Execution", "Shipping", "Transportation", "Delivery Processing"] }),

  sap({ id: "PS", label: "SAP PS", aliases: ["sap ps", "project system", "project systems"], roleAliases: ["ps consultant", "project system consultant"], contextAliases: ["ps"], supporting: ["PS", "Project System", "WBS", "Network", "Project Planning", "Project Costing"] }),
  sap({ id: "WBS", label: "SAP WBS", aliases: ["sap wbs", "work breakdown structure"], contextAliases: ["wbs"], parent: "PS" }),
  sap({ id: "PS_NETWORK", label: "SAP PS Network", aliases: ["sap project network"], contextAliases: ["network"], parent: "PS" }),
  sap({ id: "PROJECT_PLANNING", label: "SAP Project Planning", aliases: ["sap project planning"], contextAliases: ["project planning"], parent: "PS" }),
  sap({ id: "PROJECT_COSTING", label: "SAP Project Costing", aliases: ["sap project costing"], contextAliases: ["project costing"], parent: "PS" }),
  sap({ id: "CS", label: "SAP Customer Service / CS", aliases: ["sap cs", "sap customer service", "s/4hana service", "sap service management"], roleAliases: ["cs consultant", "sap service consultant"], contextAliases: ["cs", "customer service", "service management"], supporting: ["CS", "Customer Service", "S/4HANA Service", "Service Order"] }),
  sap({ id: "SERVICE_ORDER", label: "SAP Service Order", aliases: ["sap service order"], contextAliases: ["service order"], parent: "CS" }),
  sap({ id: "CRM", label: "SAP CRM / CX", aliases: ["sap crm", "sap customer experience", "sap cx"], roleAliases: ["sap crm consultant", "sap cx consultant"], contextAliases: ["crm", "cx"], supporting: ["CRM", "CX", "C4C", "Sales Cloud", "Service Cloud", "Marketing"] }),
  sap({ id: "C4C", label: "SAP Cloud for Customer / C4C", aliases: ["sap c4c", "cloud for customer"], contextAliases: ["c4c"], parent: "CRM" }),
  sap({ id: "SALES_CLOUD", label: "SAP Sales Cloud", aliases: ["sap sales cloud"], contextAliases: ["sales cloud"], parent: "CRM" }),
  sap({ id: "SERVICE_CLOUD", label: "SAP Service Cloud", aliases: ["sap service cloud"], contextAliases: ["service cloud"], parent: "CRM" }),
  sap({ id: "HCM", label: "SAP HCM", aliases: ["sap hcm", "sap hr", "human capital management"], roleAliases: ["hcm consultant", "sap hr consultant"], contextAliases: ["hcm", "hr"], related: ["SUCCESSFACTORS"] }),
  sap({ id: "SUCCESSFACTORS", label: "SAP SuccessFactors", aliases: ["sap successfactors", "successfactors"], roleAliases: ["successfactors consultant"], contextAliases: ["sf"], related: ["HCM"], supporting: ["SuccessFactors", "EC", "ECP", "RCM", "Onboarding", "Performance & Goals", "Compensation", "LMS"] }),
  sap({ id: "EC", label: "SuccessFactors Employee Central / EC", aliases: ["employee central", "successfactors employee central"], contextAliases: ["ec"], parent: "SUCCESSFACTORS" }),
  sap({ id: "ECP", label: "Employee Central Payroll / ECP", aliases: ["employee central payroll", "successfactors payroll"], contextAliases: ["ecp"], parent: "SUCCESSFACTORS" }),
  sap({ id: "RCM", label: "SuccessFactors Recruiting / RCM", aliases: ["successfactors recruiting", "sap recruiting management"], contextAliases: ["rcm", "recruiting"], parent: "SUCCESSFACTORS" }),
  sap({ id: "SF_ONBOARDING", label: "SuccessFactors Onboarding", aliases: ["successfactors onboarding"], contextAliases: ["onboarding"], parent: "SUCCESSFACTORS" }),
  sap({ id: "SF_PERFORMANCE", label: "SuccessFactors Performance & Goals", aliases: ["successfactors performance and goals"], contextAliases: ["performance and goals"], parent: "SUCCESSFACTORS" }),
  sap({ id: "SF_COMPENSATION", label: "SuccessFactors Compensation", aliases: ["successfactors compensation"], contextAliases: ["compensation"], parent: "SUCCESSFACTORS" }),
  sap({ id: "LMS", label: "SAP Learning / LMS", aliases: ["successfactors learning", "sap lms"], contextAliases: ["lms", "learning"], parent: "SUCCESSFACTORS" }),
  sap({ id: "TIME_MANAGEMENT", label: "SAP Time Management", aliases: ["sap time management"], contextAliases: ["time management"], parent: "HCM" }),
  sap({ id: "PAYROLL", label: "SAP Payroll", aliases: ["sap payroll"], contextAliases: ["payroll"], parent: "HCM", related: ["ECP"] }),
  sap({ id: "BW", label: "SAP BW / BI", aliases: ["sap bw", "sap bi", "bw/4hana", "bw4hana", "business warehouse", "sap business warehouse"], roleAliases: ["bw consultant", "bi consultant", "business warehouse consultant"], contextAliases: ["bw", "bi"], weaklyRelated: ["SAC", "DATASPHERE"], supporting: ["BW", "BW/4HANA", "BI", "Business Warehouse", "HANA Modeling", "BusinessObjects"] }),
  sap({ id: "SAC", label: "SAP Analytics Cloud / SAC", aliases: ["sap analytics cloud"], roleAliases: ["sac consultant", "sap analytics cloud consultant"], contextAliases: ["sac"], stronglyRelated: ["DATASPHERE"], weaklyRelated: ["BW", "HANA_MODELING"], supporting: ["SAC", "SAP Analytics Cloud", "Datasphere", "Data Warehouse Cloud"] }),
  sap({ id: "DATASPHERE", label: "SAP Datasphere", aliases: ["sap datasphere", "sap data warehouse cloud", "data warehouse cloud"], roleAliases: ["datasphere consultant", "data warehouse cloud consultant"], contextAliases: ["datasphere", "dwc"], stronglyRelated: ["SAC"], weaklyRelated: ["BW", "HANA_MODELING"], supporting: ["Datasphere", "SAP Datasphere", "DWC", "Data Warehouse Cloud", "SAP Data Warehouse Cloud"], semanticEvidence: {
    strong: ["sap datasphere", "data warehouse cloud", "sap dwc"],
    partial: ["datasphere space", "datasphere data builder", "datasphere business builder", "datasphere replication flow"],
    minimumPartialMatches: 2,
  } }),
  sap({ id: "BOBJ", label: "SAP BusinessObjects / BOBJ", aliases: ["sap businessobjects", "business objects", "businessobjects"], contextAliases: ["bobj"], related: ["BW"] }),
  sap({ id: "HANA_MODELING", label: "SAP HANA Modeling", aliases: ["sap hana modeling", "hana modelling", "hana modeling"], related: ["BW", "DATASPHERE"] }),
  sap({ id: "BPC", label: "SAP BPC", aliases: ["sap bpc", "business planning and consolidation"], roleAliases: ["bpc consultant"], contextAliases: ["bpc"], related: ["FICO", "GROUP_REPORTING"], supporting: ["BPC", "Planning", "Consolidation"] }),
  sap({ id: "BTP", label: "SAP BTP", aliases: ["sap btp", "business technology platform", "sap business technology platform"], roleAliases: ["btp consultant", "btp architect"], contextAliases: ["btp"], stronglyRelated: ["INTEGRATION_SUITE"], weaklyRelated: ["PI_PO"], supporting: ["BTP", "Business Technology Platform", "CAP", "RAP", "Integration Suite", "Cloud Integration", "Extension Suite", "Event Mesh"] }),
  sap({ id: "CAP", label: "SAP CAP", aliases: ["sap cap", "cloud application programming model"], contextAliases: ["cap"], parent: "BTP" }),
  sap({ id: "INTEGRATION_SUITE", label: "SAP Integration Suite", aliases: ["sap integration suite", "sap cloud integration", "cloud integration"], roleAliases: ["integration suite consultant", "cloud integration consultant"], parent: "BTP", stronglyRelated: ["CPI", "PI_PO"], supporting: ["Integration Suite", "CPI", "Cloud Integration", "Event Mesh", "API", "EDI"] }),
  sap({ id: "CPI", label: "SAP Cloud Integration / CPI", aliases: ["sap cpi", "sap cloud platform integration", "sap cloud integration", "cloud integration"], roleAliases: ["sap cpi consultant", "cpi integration consultant", "cloud integration consultant"], contextAliases: ["cpi"], parent: "INTEGRATION_SUITE", stronglyRelated: ["PI_PO"], supporting: ["CPI", "Cloud Integration", "SAP Cloud Platform Integration", "SAP Integration Suite", "iFlow", "iFlows"], semanticEvidence: {
    strong: ["sap integration suite", "cloud platform integration", "cloud integration", "integration flow", "integration flows", "iflow", "iflows"],
    partial: ["integration package", "message mapping", "integration adapter", "cloud connector", "api management"],
    minimumPartialMatches: 3,
  } }),
  sap({ id: "EVENT_MESH", label: "SAP Event Mesh", aliases: ["sap event mesh"], contextAliases: ["event mesh"], parent: "BTP" }),
  sap({ id: "PI_PO", label: "SAP PI/PO", aliases: ["sap pi/po", "sap pi", "sap po", "process integration process orchestration"], roleAliases: ["pi/po consultant", "sap integration consultant"], contextAliases: ["pi/po", "pi po"], stronglyRelated: ["CPI", "INTEGRATION_SUITE"], weaklyRelated: ["BTP"] }),
  sap({ id: "INTEGRATION_TECH", label: "SAP Integration Technologies", aliases: ["sap integration technologies"], contextAliases: ["idoc", "rfc", "bapi", "api", "edi"], related: ["PI_PO", "INTEGRATION_SUITE", "ABAP"] }),
  sap({ id: "ABAP", label: "SAP ABAP", aliases: ["sap abap", "abap"], roleAliases: ["abap consultant", "abap developer"], supporting: ["ABAP", "ABAP OO", "Web Dynpro", "CDS", "AMDP", "RAP", "OData", "Fiori", "UI5"] }),
  sap({ id: "ABAP_OO", label: "SAP ABAP OO", aliases: ["abap oo", "object oriented abap"], parent: "ABAP" }),
  sap({ id: "WEB_DYNPRO", label: "SAP Web Dynpro", aliases: ["web dynpro"], parent: "ABAP" }),
  sap({ id: "CDS", label: "SAP CDS", aliases: ["sap cds", "core data services"], contextAliases: ["cds"], parent: "ABAP" }),
  sap({ id: "AMDP", label: "SAP AMDP", aliases: ["sap amdp", "abap managed database procedures"], contextAliases: ["amdp"], parent: "ABAP" }),
  sap({ id: "RAP", label: "SAP RAP", aliases: ["sap rap", "restful abap programming model"], contextAliases: ["rap"], parent: "ABAP", related: ["BTP"] }),
  sap({ id: "ODATA", label: "SAP OData", aliases: ["sap odata", "odata"], parent: "ABAP" }),
  sap({ id: "FIORI", label: "SAP Fiori / UI5", aliases: ["sap fiori", "sap ui5", "fiori", "ui5"], roleAliases: ["fiori consultant", "ui5 developer"], related: ["ABAP", "BTP"] }),
  sap({ id: "BASIS", label: "SAP Basis", aliases: ["sap basis"], roleAliases: ["basis consultant", "basis administrator"], contextAliases: ["basis"], supporting: ["Basis", "NetWeaver", "System Administration", "Upgrade", "Migration", "HANA Administration"] }),
  sap({ id: "NETWEAVER", label: "SAP NetWeaver", aliases: ["sap netweaver", "netweaver"], parent: "BASIS" }),
  sap({ id: "HANA_ADMIN", label: "SAP HANA Administration", aliases: ["sap hana administration", "hana administration"], parent: "BASIS" }),
  sap({ id: "SECURITY", label: "SAP Security", aliases: ["sap security"], roleAliases: ["sap security consultant", "sap security analyst"], supporting: ["SAP Security", "GRC", "Roles & Authorization"] }),
  sap({ id: "GRC", label: "SAP GRC", aliases: ["sap grc", "governance risk and compliance"], contextAliases: ["grc"], parent: "SECURITY" }),
  sap({ id: "AUTHORIZATION", label: "SAP Roles & Authorization", aliases: ["sap authorization", "sap roles and authorization", "sap roles & authorization"], contextAliases: ["authorization", "authorizations"], parent: "SECURITY" }),
  sap({ id: "S4HANA", label: "SAP S/4HANA", aliases: ["sap s/4hana", "s/4hana", "s4hana", "sap s4"], contextAliases: ["s4"], related: ["ECC"] }),
  sap({ id: "ECC", label: "SAP ECC", aliases: ["sap ecc"], contextAliases: ["ecc"], related: ["S4HANA"] }),
  sap({ id: "IS_U", label: "SAP IS-U", aliases: ["sap is-u", "sap isu", "industry solution utilities"], contextAliases: ["is-u", "isu"], supporting: ["Utilities"] }),
  sap({ id: "IS_RETAIL", label: "SAP IS-Retail", aliases: ["sap is-retail", "sap retail"], contextAliases: ["is-retail"], supporting: ["Retail"] }),
  sap({ id: "IS_OIL", label: "SAP IS-Oil", aliases: ["sap is-oil", "sap oil and gas"], contextAliases: ["is-oil"], supporting: ["Oil & Gas"] }),
  sap({ id: "IS_AUTO", label: "SAP IS-Auto", aliases: ["sap is-auto", "sap automotive"], contextAliases: ["is-auto"], supporting: ["Automotive"] }),
  sap({ id: "BANKING", label: "SAP Banking", aliases: ["sap banking"], roleAliases: ["sap banking consultant"] }),
  sap({ id: "INSURANCE", label: "SAP Insurance", aliases: ["sap insurance"], roleAliases: ["sap insurance consultant"] }),
  sap({ id: "BRIM", label: "SAP BRIM", aliases: ["sap brim", "billing and revenue innovation management"], roleAliases: ["brim consultant"], contextAliases: ["brim"], supporting: ["Convergent Invoicing", "Subscription Billing"] }),
  sap({ id: "CONVERGENT_INVOICING", label: "SAP Convergent Invoicing", aliases: ["sap convergent invoicing", "convergent invoicing"], parent: "BRIM" }),
  sap({ id: "SUBSCRIPTION_BILLING", label: "SAP Subscription Billing", aliases: ["sap subscription billing"], contextAliases: ["subscription billing"], parent: "BRIM" }),
  sap({ id: "REFX", label: "SAP RE-FX", aliases: ["sap re-fx", "sap refx", "flexible real estate management"], roleAliases: ["re-fx consultant"], contextAliases: ["re-fx", "refx"] }),
  ...["ARIBA", "FIELDGLASS", "CONCUR", "IBP", "APO", "GTS", "MDG"].map((id) => sap({ id, label: `SAP ${id}`, aliases: [`sap ${id.toLowerCase()}`, id.toLowerCase()], roleAliases: [`${id.toLowerCase()} consultant`] })),
];

export const SAP_SEARCH_CONCEPT_IDS = new Set(SAP_SEARCH_CONCEPTS.map((concept) => concept.id));
