import {buildRecruiterPackCompareView} from "./recruiterPackCompare";
import {buildRecruiterResultsUrl} from "./talentPackBuilder";
import type {SavedPackPreview,SavedSearchPackPreviewState,SavedSearchPreview} from "./savedSearchPackTypes";
import type {TalentPackSize} from "./talentPackTypes";
type Params=URLSearchParams|Record<string,unknown>;
const toParams=(input:Params)=>{if(input instanceof URLSearchParams)return new URLSearchParams(input);const query=new URLSearchParams();for(const[key,value]of Object.entries(input)){if(value===undefined||value===null||value==="")continue;if(Array.isArray(value))value.forEach(item=>query.append(key,String(item)));else query.set(key,String(value));}return query;};
const first=(query:URLSearchParams,...keys:string[])=>keys.map(key=>query.get(key)?.trim()).find(Boolean)||"";
const record=(query:URLSearchParams)=>Object.fromEntries([...new Set(query.keys())].map(key=>{const values=query.getAll(key);return[key,values.length>1?values:values[0]||""]}));
const stableId=(prefix:string,query:URLSearchParams)=>{const canonical=[...query.entries()].filter(([key])=>key!=="createdAt").sort(([a,av],[b,bv])=>a.localeCompare(b)||av.localeCompare(bv)).map(([key,value])=>`${key}=${value}`).join("&");let hash=2166136261;for(let index=0;index<canonical.length;index++){hash^=canonical.charCodeAt(index);hash=Math.imul(hash,16777619)}return `${prefix}-${(hash>>>0).toString(36)}`;};
const ids=(query:URLSearchParams)=>query.getAll("candidateIds").flatMap(value=>value.split(",")).concat(query.getAll("candidateId")).map(value=>value.trim()).filter(Boolean).filter((value,index,all)=>all.indexOf(value)===index);
const createdAt=(query:URLSearchParams)=>first(query,"createdAt")||new Date().toISOString();
export function normalizeSavedPackSize(input:unknown):TalentPackSize{const value=Number(input);return value===10?10:value===20?20:5;}
export function buildSavedSearchPreview(params:Params):SavedSearchPreview{const query=toParams(params),keyword=first(query,"q","keyword"),module=first(query,"module","background"),country=first(query,"country","countries"),location=first(query,"location","city"),roleTitle=first(query,"roleTitle")||keyword||module||"Untitled talent search",clientName=first(query,"clientName"),years=Number(first(query,"years","yearsMin","minYears")),resultCount=Number(first(query,"resultCount","totalResults"));return{id:stableId("saved-search-preview",query),name:first(query,"searchName","name")||`${roleTitle} search preview`,roleTitle,clientName:clientName||undefined,keyword,module,country,location,yearsMin:Number.isFinite(years)&&years>0?years:undefined,filters:record(query),searchParams:record(query),resultCount:Number.isFinite(resultCount)&&resultCount>=0?resultCount:0,createdAt:createdAt(query),createdByRole:"recruiter",status:"preview_only"};}
export function buildPackClientReportPreviewUrl(candidateIds:string[],params:Params){const query=toParams(params),unique=candidateIds.map(value=>value.trim()).filter(Boolean).filter((value,index,all)=>all.indexOf(value)===index);query.set("candidateIds",unique.join(","));query.set("preview","saved-pack");return `/recruiter/client-report?${query.toString()}`;}
export function buildSavedPackPreview(params:Params):SavedPackPreview{const query=toParams(params),packSize=normalizeSavedPackSize(query.get("packSize"));query.set("packSize",String(packSize));if(query.get("mode")!=="executive")query.set("mode",`top${packSize}`);const savedSearch=buildSavedSearchPreview(query),candidateIds=ids(query),view=buildRecruiterPackCompareView(query);return{id:stableId("saved-pack-preview",query),savedSearchId:savedSearch.id,name:first(query,"packName")||`${savedSearch.roleTitle} Top ${packSize} preview`,packSize,mode:view.selectedMode,candidateIds,candidateCount:candidateIds.length,searchContext:view.searchContext,packCompareUrl:view.packOptions.find(option=>option.mode===view.selectedMode)?.url||`/recruiter/pack-compare?${query.toString()}`,recruiterResultsUrl:view.recruiterResultsUrl,quickCompareUrl:view.quickCompareUrl,clientReportUrl:candidateIds.length?buildPackClientReportPreviewUrl(candidateIds,query):undefined,createdAt:createdAt(query),status:"preview_only"};}
export function buildSavedSearchPreviewUrl(params:Params){const query=toParams(params);return `/recruiter/saved-searches${query.size?`?${query.toString()}`:""}`;}
export function buildSavedPackPreviewUrl(params:Params){return buildSavedSearchPreviewUrl(params);}
export function buildSavedSearchPackPreviewState(params:Params):SavedSearchPackPreviewState{const query=toParams(params),savedSearch=buildSavedSearchPreview(query),savedPacks=[5,10,20].map(size=>{const next=new URLSearchParams(query);next.set("packSize",String(size));next.set("mode",`top${size}`);return buildSavedPackPreview(next)});return{savedSearches:[savedSearch],savedPacks,safety:{previewOnly:true,candidateDbWrites:0,workflowWrites:0,supabaseWrites:0,shortlistWrites:0,openAiCalls:0,databasePersistence:false}};}
export function buildLegacySearchPreviewUrl(params:Params){const query=toParams(params);return `/search${query.size?`?${query.toString()}`:""}`;}
export {buildRecruiterResultsUrl};
