import type {StagingAuthOperationBoundaryStatus,StagingAuthOperationRequestKey} from "./stagingAuthOperationTypes";
export type StagingAuthE2eScenarioKey="sign_in_default_blocked"|"sign_in_approved_simulation"|"password_reset_default_blocked"|"invitation_default_blocked"|"sign_out_default_blocked"|"get_session_default_blocked"|"get_user_default_blocked"|"get_profile_default_blocked"|"refresh_session_default_blocked"|"production_sign_in_blocked";
export type StagingAuthE2eLayerKey="ui_form"|"server_action"|"request_sanitizer"|"operation_boundary"|"execution_gate"|"adapter_factory"|"auth_adapter"|"audit_preview"|"rate_limit_preview"|"ui_result";
export type StagingAuthE2eLayerStatus="reached"|"blocked"|"preview_only"|"skipped_safely"|"provider_not_implemented"|"completed_preview";
export type StagingAuthE2eTraceStep={order:number;layer:StagingAuthE2eLayerKey;status:StagingAuthE2eLayerStatus;label:string;inputSafe:boolean;outputSafe:boolean;blockerKeys:string[];warningKeys:string[];sensitiveDataPresent:false;rawEnvironmentPresent:false;realActionExecuted:false;persisted:false};
export type StagingAuthE2eScenarioResult={scenarioKey:StagingAuthE2eScenarioKey;operation:StagingAuthOperationRequestKey;status:StagingAuthOperationBoundaryStatus;traceId:string;requestId:string;traceSteps:StagingAuthE2eTraceStep[];layersExpected:number;layersReached:number;bypassDetected:false;sensitiveDataReturned:false;completeEmailExposed:false;rawFormDataExposed:false;rawEnvironmentExposed:false;sessionCreated:false;cookieUsed:false;redirectExecuted:false;emailSent:false;databaseMutation:false;realActionExecuted:false;productionBlocked:true};
export type StagingAuthE2eCoverage={scenariosExpected:number;scenariosGenerated:number;layersExpected:number;operationsCovered:StagingAuthOperationRequestKey[];publicFormsCovered:number;diagnosticOperationsCovered:number;productionScenarioCovered:boolean;bypassChecksPassed:boolean};
export type StagingAuthE2eSafety={supabaseImports:0;supabaseCalls:0;authCalls:0;sessionsCreated:0;cookiesRead:0;cookiesSet:0;redirectsExecuted:0;databaseReads:0;databaseWrites:0;auditWrites:0;rateLimitStoreWrites:0;emailSends:0;sqlStatementsExecuted:0;migrationsExecuted:0;rlsPoliciesExecuted:0;middlewareEnforced:false;openAiCalls:0;productionBlocked:true};
export type StagingAuthE2ePreview={scenarios:StagingAuthE2eScenarioResult[];layerMatrix:Array<{scenarioKey:StagingAuthE2eScenarioKey;layers:StagingAuthE2eLayerKey[]}>;coverage:StagingAuthE2eCoverage;blockers:string[];safety:StagingAuthE2eSafety};
