import {createHash} from "node:crypto";
import {existsSync,readFileSync} from "node:fs";
import {resolve} from "node:path";
export const STAGING_AUTH_SQL_V1_PATHS={schema:"supabase/migrations/202607230001_staging_auth_schema.sql",helpers:"supabase/migrations/202607230002_staging_auth_helpers.sql",rls:"supabase/migrations/202607230003_staging_auth_rls.sql",rollback:"supabase/rollback/202607230001_staging_auth_rollback.sql"} as const;
export const STAGING_AUTH_SQL_V2_PATHS={preflight:"supabase/preflight/202607230004_staging_auth_preflight.sql",schema:"supabase/migrations/202607230005_staging_auth_schema_v2.sql",helpers:"supabase/migrations/202607230006_staging_auth_helpers_v2.sql",rls:"supabase/migrations/202607230007_staging_auth_rls_v2.sql",bootstrap:"supabase/bootstrap/202607230008_staging_first_admin_bootstrap_template.sql",rlsRollback:"supabase/rollback/202607230007_staging_auth_rls_rollback_v2.sql",helpersRollback:"supabase/rollback/202607230006_staging_auth_helpers_rollback_v2.sql",schemaRollback:"supabase/rollback/202607230005_staging_auth_schema_rollback_v2.sql"} as const;
export const STAGING_AUTH_SQL_V3_PATHS={preflight:"supabase/preflight/202607230009_staging_auth_preflight_v3.sql",schema:"supabase/migrations/202607230010_staging_auth_schema_v3.sql",helpers:"supabase/migrations/202607230011_staging_auth_helpers_v3.sql",bootstrap:"supabase/bootstrap/202607230012_staging_initial_owner_bootstrap_v3.sql",rls:"supabase/migrations/202607230013_staging_auth_rls_v3.sql",rlsRollback:"supabase/rollback/202607230013_staging_auth_rls_rollback_v3.sql",bootstrapRollback:"supabase/rollback/202607230012_staging_initial_owner_bootstrap_rollback_v3.sql",helpersRollback:"supabase/rollback/202607230011_staging_auth_helpers_rollback_v3.sql",schemaRollback:"supabase/rollback/202607230010_staging_auth_schema_rollback_v3.sql"} as const;
export const STAGING_AUTH_SQL_ARTIFACT_PATHS={preflight:"supabase/preflight/202607230014_staging_auth_preflight_v4.sql",schema:"supabase/migrations/202607230015_staging_auth_schema_v4.sql",helpers:"supabase/migrations/202607230016_staging_auth_helpers_v4.sql",bootstrap:"supabase/bootstrap/202607230017_staging_initial_owner_bootstrap_v4.sql",rls:"supabase/migrations/202607230018_staging_auth_rls_v4.sql",rlsRollback:"supabase/rollback/202607230018_staging_auth_rls_rollback_v4.sql",bootstrapRollback:"supabase/rollback/202607230017_staging_initial_owner_bootstrap_rollback_v4.sql",helpersRollback:"supabase/rollback/202607230016_staging_auth_helpers_rollback_v4.sql",schemaRollback:"supabase/rollback/202607230015_staging_auth_schema_rollback_v4.sql",rollback:"supabase/rollback/202607230015_staging_auth_schema_rollback_v4.sql"} as const;
export type StagingAuthSqlArtifactKey=Exclude<keyof typeof STAGING_AUTH_SQL_ARTIFACT_PATHS,"rollback">;
export type StagingAuthSqlReviewStatus="rejected"|"read_only_preflight_passed_rejected_for_mutation"|"pending_manual_review";
export type StagingAuthSqlArtifact={artifactKey:string;path:string;label:string;exists:boolean;fingerprint:string;artifactVersion:"v1"|"v2"|"v3"|"v4";phase:string;reviewStatus:StagingAuthSqlReviewStatus;executableStatus:"review_only_not_approved";executionStatus:"not_executed"|"read_only_preflight_executed";supersedes:string|null;stagingOnly:true;manuallyReviewed:false;executed:boolean;authoritative:boolean;expectedOrder:number};
type Definition=readonly[string,string,string,string,number,string|null];
const definitions=(version:"v1"|"v2"|"v3",paths:Record<string,string>)=>Object.entries(paths).map(([key,path],i)=>[`${version}_${key}`,path,`${version.toUpperCase()} ${key}`,key,i+1,null] as Definition);
const historicalDefinitions=[...definitions("v1",STAGING_AUTH_SQL_V1_PATHS),...definitions("v2",STAGING_AUTH_SQL_V2_PATHS),...definitions("v3",STAGING_AUTH_SQL_V3_PATHS)];
const v4Definitions:Definition[]=[
 ["preflight",STAGING_AUTH_SQL_ARTIFACT_PATHS.preflight,"V4 read-only compatibility preflight","preflight",1,STAGING_AUTH_SQL_V3_PATHS.preflight],
 ["schema",STAGING_AUTH_SQL_ARTIFACT_PATHS.schema,"V4 schema with immutable bootstrap provenance","schema",2,STAGING_AUTH_SQL_V3_PATHS.schema],
 ["helpers",STAGING_AUTH_SQL_ARTIFACT_PATHS.helpers,"V4 postgres-owned helpers","helpers",3,STAGING_AUTH_SQL_V3_PATHS.helpers],
 ["bootstrap",STAGING_AUTH_SQL_ARTIFACT_PATHS.bootstrap,"V4 provenance-backed initial-owner bootstrap","bootstrap",4,STAGING_AUTH_SQL_V3_PATHS.bootstrap],
 ["rls",STAGING_AUTH_SQL_ARTIFACT_PATHS.rls,"V4 seven-table deny-by-default RLS","rls",5,STAGING_AUTH_SQL_V3_PATHS.rls],
 ["rlsRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.rlsRollback,"V4 RLS rollback","rls_rollback",1,STAGING_AUTH_SQL_V3_PATHS.rlsRollback],
 ["bootstrapRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.bootstrapRollback,"V4 provenance bootstrap rollback","bootstrap_rollback",2,STAGING_AUTH_SQL_V3_PATHS.bootstrapRollback],
 ["helpersRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.helpersRollback,"V4 helpers rollback","helpers_rollback",3,STAGING_AUTH_SQL_V3_PATHS.helpersRollback],
 ["schemaRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.schemaRollback,"V4 schema rollback","schema_rollback",4,STAGING_AUTH_SQL_V3_PATHS.schemaRollback]
];
const allowedPaths=new Set<string>([...Object.values(STAGING_AUTH_SQL_V1_PATHS),...Object.values(STAGING_AUTH_SQL_V2_PATHS),...Object.values(STAGING_AUTH_SQL_V3_PATHS),...Object.values(STAGING_AUTH_SQL_ARTIFACT_PATHS)]);
export function readStagingAuthSqlArtifact(path:string,baseDir=process.cwd()){if(!allowedPaths.has(path))throw new Error("staging_auth_sql_artifact_path_not_allowed");return readFileSync(resolve(baseDir,path),"utf8")}
export function calculateStagingAuthSqlArtifactFingerprint(content:string){return createHash("sha256").update(content,"utf8").digest("hex")}
function artifact(baseDir:string,d:Definition,version:"v1"|"v2"|"v3"|"v4",reviewStatus:StagingAuthSqlReviewStatus,authoritative:boolean):StagingAuthSqlArtifact{const[k,path,label,phase,expectedOrder,supersedes]=d,found=existsSync(resolve(baseDir,path)),isV3Preflight=version==="v3"&&phase==="preflight";return{artifactKey:k,path,label,exists:found,fingerprint:found?calculateStagingAuthSqlArtifactFingerprint(readStagingAuthSqlArtifact(path,baseDir)):"",artifactVersion:version,phase,reviewStatus,executableStatus:"review_only_not_approved",executionStatus:isV3Preflight?"read_only_preflight_executed":"not_executed",supersedes,stagingOnly:true,manuallyReviewed:false,executed:isV3Preflight,authoritative,expectedOrder}}
export function listHistoricalStagingAuthSqlArtifacts(baseDir=process.cwd()){return historicalDefinitions.map(d=>{const version=d[0].slice(0,2) as "v1"|"v2"|"v3";return artifact(baseDir,d,version,version==="v3"?"read_only_preflight_passed_rejected_for_mutation":"rejected",false)})}
export function listStagingAuthSqlArtifacts(baseDir=process.cwd()){return v4Definitions.map(d=>artifact(baseDir,d,"v4","pending_manual_review",true))}
export function buildStagingAuthSqlArtifactReview(baseDir=process.cwd()){return{id:"staging-auth-sql-artifacts-v4",generatedAt:new Date().toISOString(),artifacts:listStagingAuthSqlArtifacts(baseDir),historicalArtifacts:listHistoricalStagingAuthSqlArtifacts(baseDir),authoritative:true,authoritativeVersion:"v4" as const,executionOrder:["preflight","schema","helpers","bootstrap","rls"],rollbackOrder:["rlsRollback","bootstrapRollback","helpersRollback","schemaRollback"],v3PreflightEvidence:{confirmed:true,result:"passed" as const,evidenceReference:"STG-PREFLIGHT-V3-20260723-01",executionRole:"postgres",executionDate:"2026-07-23",readOnly:true,rolledBack:true,databaseMutation:false,productionBlocked:true},migrationManuallyReviewed:false,helpersManuallyReviewed:false,rlsManuallyReviewed:false,bootstrapManuallyApproved:false,rollbackManuallyApproved:false,stagingImplementationApproved:false,productionCandidateDataCopied:false,safety:{readOnly:true,sqlExecuted:0,migrationsExecuted:0,rlsExecuted:0,bootstrapExecuted:0,rollbackExecuted:0,supabaseCalls:0,databaseReads:0,databaseWrites:0,environmentFilesModified:false,candidateDbWrites:0,productionBlocked:true}}}
export function validateStagingAuthSqlArtifacts(baseDir=process.cwd()){
 const review=buildStagingAuthSqlArtifactReview(baseDir),by=Object.fromEntries(review.artifacts.map(x=>[x.artifactKey,readStagingAuthSqlArtifact(x.path,baseDir)])) as Record<StagingAuthSqlArtifactKey,string>,all=Object.values(by).join("\n");
 const policies=[...by.rls.matchAll(/create policy[\s\S]*?;/gi)].map(x=>x[0]),inserts=policies.filter(x=>/ for insert /i.test(x)),updates=policies.filter(x=>/ for update /i.test(x)),preflightCode=by.preflight.split(/\r?\n/).filter(x=>!x.trim().startsWith("--")).join("\n");
 const checks={historyPreserved:review.historicalArtifacts.length===21&&review.historicalArtifacts.every(x=>x.exists&&!x.authoritative),v3Evidence:review.v3PreflightEvidence.result==="passed"&&review.historicalArtifacts.filter(x=>x.artifactVersion==="v3"&&x.phase!=="preflight").every(x=>!x.executed),v4Complete:review.artifacts.length===9&&review.artifacts.every(x=>x.exists&&x.artifactVersion==="v4"&&x.reviewStatus==="pending_manual_review"&&!x.executed),fingerprints:review.artifacts.every(x=>/^[a-f0-9]{64}$/.test(x.fingerprint)),preflightReadOnly:/begin;\s*set transaction read only/i.test(by.preflight)&&/\brollback;/i.test(by.preflight)&&!/^\s*(create|alter|drop|truncate|insert|update|delete|copy)\b/im.test(preflightCode),authUid:/to_regprocedure\('auth\.uid\(\)'\)/.test(by.preflight)&&/p\.pronargs = 0/.test(by.preflight)&&/t\.typname = 'uuid'/.test(by.preflight),scopedConflicts:/t\.tgrelid/.test(by.preflight)&&/p\.pronargs = 0/.test(by.preflight)&&/pol\.polrelid/.test(by.preflight),provenance:/create table public\.staging_auth_bootstrap_provenance/.test(by.schema)&&/bootstrap_type_key unique/.test(by.schema),exactPlaceholders:!/\blike\s+'__STAGING/i.test(by.bootstrap)&&!/\blike\s+'__STAGING/i.test(by.bootstrapRollback),emailMatch:/confirmed_auth_email <> admin_email/.test(by.bootstrap)&&/from auth\.users u/.test(by.bootstrap),threeRows:/provenance_insert_count_invalid/.test(by.bootstrap)&&/provenance_delete_count_invalid/.test(by.bootstrapRollback)&&/profile_delete_count_invalid/.test(by.bootstrapRollback)&&/organization_delete_count_invalid/.test(by.bootstrapRollback),policySyntax:inserts.length>0&&inserts.every(x=>/with check/i.test(x)&&!/\busing\s*\(/i.test(x))&&updates.every(x=>/\busing\s*\(/i.test(x)&&/with check/i.test(x)),provenancePolicy:policies.filter(x=>/bootstrap_provenance/i.test(x)).length===1&&!policies.some(x=>/bootstrap_provenance[\s\S]*for (insert|update|delete)/i.test(x)),candidateProtected:!/(alter|update|delete|drop)\s+(table\s+|from\s+)?public\.candidates\b/i.test(all)};
 const issues=Object.entries(checks).filter(([,ok])=>!ok).map(([key])=>key);return{valid:issues.length===0,checks,issues,artifacts:review.artifacts,historicalArtifacts:review.historicalArtifacts};
}
