import {STAGING_AUTH_ADAPTER_OPERATION_CONTRACT} from "./stagingAuthAdapterContract";import {buildStagingAuthAdapterForGate,getStagingAuthAdapterDecision} from "./stagingAuthAdapterFactory";import {buildStagingAuthExecutionGate} from "./stagingAuthExecutionGate";import type {StagingAuthAdapter,StagingAuthOperationKey,StagingAuthOperationResult} from "./stagingAuthAdapterTypes";
const full={appEnvironment:"staging" as const,authMode:"staging_approved" as const,stagingAuthEnabled:true,stagingAuthApproved:true,productionAuthEnabled:false,evidencePackAvailable:true,runbookAvailable:true,stagingBackupConfirmed:true,migrationReviewed:true,rlsReviewed:true,ownershipApproved:true,rollbackApproved:true};
const operation=(adapter:StagingAuthAdapter,key:StagingAuthOperationKey):StagingAuthOperationResult<unknown>=>{switch(key){case"get_session":return adapter.getSession();case"get_user":return adapter.getUser();case"get_profile":return adapter.getProfile();case"sign_in":return adapter.signIn({email:"discarded@example.invalid",password:"discarded-input"});case"sign_out":return adapter.signOut();case"request_password_reset":return adapter.requestPasswordReset({email:"discarded@example.invalid"});case"accept_invitation":return adapter.acceptInvitation({invitationToken:"discarded-input"});case"refresh_session":return adapter.refreshSession()}}
export function buildAdapterOperationMatrix(adapter=buildStagingAuthAdapterForGate(buildStagingAuthExecutionGate())){return STAGING_AUTH_ADAPTER_OPERATION_CONTRACT.map(contract=>({contract,result:operation(adapter,contract.operation)}))}
export function buildDisabledAdapterPreview(){const adapter=buildStagingAuthAdapterForGate(buildStagingAuthExecutionGate());return{decision:getStagingAuthAdapterDecision(adapter),operations:buildAdapterOperationMatrix(adapter),safety:adapter.safety}}
export function buildApprovedSimulationAdapterPreview(){const adapter=buildStagingAuthAdapterForGate(buildStagingAuthExecutionGate(full));return{decision:getStagingAuthAdapterDecision(adapter),operations:buildAdapterOperationMatrix(adapter),safety:adapter.safety}}
export function buildProductionAdapterPreview(){const adapter=buildStagingAuthAdapterForGate(buildStagingAuthExecutionGate({...full,appEnvironment:"production"}));return{decision:getStagingAuthAdapterDecision(adapter),operations:buildAdapterOperationMatrix(adapter),safety:adapter.safety}}
export function buildStagingAuthAdapterPreview(){return{id:"staging-auth-adapter-preview-v1",generatedAt:new Date().toISOString(),defaultAdapter:buildDisabledAdapterPreview(),approvedSimulation:buildApprovedSimulationAdapterPreview(),productionAdapter:buildProductionAdapterPreview(),operationMatrix:buildAdapterOperationMatrix(),realProviderImplemented:false,productionBlocked:true}}
export function validateStagingAuthAdapterPreview(preview:ReturnType<typeof buildStagingAuthAdapterPreview>){const results=[...preview.defaultAdapter.operations,...preview.approvedSimulation.operations,...preview.productionAdapter.operations].map(x=>x.result);const issues:string[]=[];if(preview.operationMatrix.length!==8)issues.push("operation_count_invalid");if(results.some(x=>x.realActionExecuted||x.sensitiveInputReturned||x.tokenReturned))issues.push("unsafe_operation_result");if(preview.defaultAdapter.decision.provider!=="disabled"||preview.productionAdapter.decision.provider!=="disabled")issues.push("disabled_provider_required");return{valid:issues.length===0,issues}}
