import type {StagingAuthOperationBoundaryResult} from "./stagingAuthOperationTypes";import type {StagingAuthE2eLayerKey,StagingAuthE2eLayerStatus,StagingAuthE2eTraceStep} from "./stagingAuthE2eTypes";
export const STAGING_AUTH_E2E_LAYERS:StagingAuthE2eLayerKey[]=["ui_form","server_action","request_sanitizer","operation_boundary","execution_gate","adapter_factory","auth_adapter","rate_limit_preview","audit_preview","ui_result"];
export function createStagingAuthE2eTraceId(seed="preview"){return `staging-auth-e2e-trace-${seed.replace(/[^a-z0-9_-]/gi,"-").toLowerCase()}`}
export function buildStagingAuthE2eTraceStep(order:number,layer:StagingAuthE2eLayerKey,status:StagingAuthE2eLayerStatus,blockerKeys:string[]=[],warningKeys:string[]=[]):StagingAuthE2eTraceStep{return{order,layer,status,label:layer.replaceAll("_"," "),inputSafe:true,outputSafe:true,blockerKeys:blockerKeys.filter(x=>/^[a-z0-9_]+$/.test(x)),warningKeys:warningKeys.filter(x=>/^[a-z0-9_]+$/.test(x)),sensitiveDataPresent:false,rawEnvironmentPresent:false,realActionExecuted:false,persisted:false}}
export function buildSafeE2eTraceFromOperationResult(result:StagingAuthOperationBoundaryResult,{diagnostic=false,approved=false,production=false}:{diagnostic?:boolean;approved?:boolean;production?:boolean}={}){return STAGING_AUTH_E2E_LAYERS.map((layer,index)=>{let status:StagingAuthE2eLayerStatus="reached";if(layer==="ui_form"&&diagnostic)status="skipped_safely";else if(layer==="auth_adapter"&&approved)status="provider_not_implemented";else if(production&&["execution_gate","adapter_factory","auth_adapter"].includes(layer))status="blocked";else if(layer==="ui_result")status=result.status==="provider_not_implemented"?"provider_not_implemented":result.status==="completed_preview"?"completed_preview":"preview_only";else if(["audit_preview","rate_limit_preview"].includes(layer))status="preview_only";return buildStagingAuthE2eTraceStep(index+1,layer,status,result.blockerKeys,result.warningKeys)})}
export function validateStagingAuthE2eTraceStep(step:StagingAuthE2eTraceStep){return step.order>0&&step.inputSafe&&step.outputSafe&&!step.sensitiveDataPresent&&!step.rawEnvironmentPresent&&!step.realActionExecuted&&!step.persisted}
export function validateNoSensitiveDataInTrace(trace:StagingAuthE2eTraceStep[]){const text=JSON.stringify(trace);return trace.every(validateStagingAuthE2eTraceStep)&&!/(password|invitationToken|FormData|process\.env|\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b|stack\s*trace)/i.test(text)}
export function validateNoLayerBypass(trace:StagingAuthE2eTraceStep[]){const orders=trace.map(x=>x.order);return trace.length===10&&new Set(orders).size===10&&trace.every((step,index)=>step.order===index+1&&step.layer===STAGING_AUTH_E2E_LAYERS[index])&&["operation_boundary","execution_gate","adapter_factory","auth_adapter"].every(layer=>trace.some(x=>x.layer===layer&&x.status!=="skipped_safely"))}


