import {buildStagingAuthAdapterForGate} from "./stagingAuthAdapterFactory";import {buildStagingAuthExecutionGate} from "./stagingAuthExecutionGate";import {executeStagingAuthOperationWithAdapter,STAGING_AUTH_OPERATION_BOUNDARY_SAFETY,validateStagingAuthOperationBoundaryResult} from "./stagingAuthOperationService";import type {StagingAuthOperationRequest,StagingAuthOperationRequestKey} from "./stagingAuthOperationTypes";
const operations:StagingAuthOperationRequestKey[]=["get_session","get_user","get_profile","sign_in","sign_out","request_password_reset","accept_invitation","refresh_session"],full={appEnvironment:"staging" as const,authMode:"staging_approved" as const,stagingAuthEnabled:true,stagingAuthApproved:true,productionAuthEnabled:false,evidencePackAvailable:true,runbookAvailable:true,stagingBackupConfirmed:true,migrationReviewed:true,rlsReviewed:true,ownershipApproved:true,rollbackApproved:true};
const request=(operation:StagingAuthOperationRequestKey,index:number):StagingAuthOperationRequest=>({requestId:`operation-preview-${index+1}`,operation,source:"test_preview",requestedAt:"1970-01-01T00:00:00.000Z",simulationOnly:true,productionAllowed:false,...(operation==="sign_in"?{email:"preview@example.invalid",password:"discard-immediately"}:{}),...(operation==="request_password_reset"?{email:"preview@example.invalid"}:{}),...(operation==="accept_invitation"?{invitationToken:"discard-immediately"}:{})} as StagingAuthOperationRequest);
export function buildOperationResultMatrix(adapter=buildStagingAuthAdapterForGate(buildStagingAuthExecutionGate())){return operations.map((operation,index)=>executeStagingAuthOperationWithAdapter(request(operation,index),adapter))}
export function buildDefaultBlockedOperationPreview(){return buildOperationResultMatrix()}
export function buildApprovedSimulationOperationPreview(){return buildOperationResultMatrix(buildStagingAuthAdapterForGate(buildStagingAuthExecutionGate(full)))}
export function buildProductionOperationPreview(){return buildOperationResultMatrix(buildStagingAuthAdapterForGate(buildStagingAuthExecutionGate({...full,appEnvironment:"production"})))}
export function buildStagingAuthOperationBoundaryPreview(){return{id:"staging-auth-operation-boundary-v1",generatedAt:new Date().toISOString(),defaultOperations:buildDefaultBlockedOperationPreview(),approvedSimulation:buildApprovedSimulationOperationPreview(),productionOperations:buildProductionOperationPreview(),operationMatrix:buildOperationResultMatrix(),realProviderImplemented:false,safety:STAGING_AUTH_OPERATION_BOUNDARY_SAFETY,productionBlocked:true}}
export function validateStagingAuthOperationBoundaryPreview(preview:ReturnType<typeof buildStagingAuthOperationBoundaryPreview>){const all=[...preview.defaultOperations,...preview.approvedSimulation,...preview.productionOperations];return{valid:preview.operationMatrix.length===8&&all.every(validateStagingAuthOperationBoundaryResult)&&preview.productionOperations.every(x=>x.status==="production_blocked"),issues:[] as string[]}}
