import {createHash} from "node:crypto";
import {existsSync,readFileSync} from "node:fs";
import {resolve} from "node:path";
export const STAGING_AUTH_SQL_V1_PATHS={schema:"supabase/migrations/202607230001_staging_auth_schema.sql",helpers:"supabase/migrations/202607230002_staging_auth_helpers.sql",rls:"supabase/migrations/202607230003_staging_auth_rls.sql",rollback:"supabase/rollback/202607230001_staging_auth_rollback.sql"} as const;
export const STAGING_AUTH_SQL_V2_PATHS={preflight:"supabase/preflight/202607230004_staging_auth_preflight.sql",schema:"supabase/migrations/202607230005_staging_auth_schema_v2.sql",helpers:"supabase/migrations/202607230006_staging_auth_helpers_v2.sql",rls:"supabase/migrations/202607230007_staging_auth_rls_v2.sql",bootstrap:"supabase/bootstrap/202607230008_staging_first_admin_bootstrap_template.sql",rlsRollback:"supabase/rollback/202607230007_staging_auth_rls_rollback_v2.sql",helpersRollback:"supabase/rollback/202607230006_staging_auth_helpers_rollback_v2.sql",schemaRollback:"supabase/rollback/202607230005_staging_auth_schema_rollback_v2.sql"} as const;
export const STAGING_AUTH_SQL_V3_PATHS={preflight:"supabase/preflight/202607230009_staging_auth_preflight_v3.sql",schema:"supabase/migrations/202607230010_staging_auth_schema_v3.sql",helpers:"supabase/migrations/202607230011_staging_auth_helpers_v3.sql",bootstrap:"supabase/bootstrap/202607230012_staging_initial_owner_bootstrap_v3.sql",rls:"supabase/migrations/202607230013_staging_auth_rls_v3.sql",rlsRollback:"supabase/rollback/202607230013_staging_auth_rls_rollback_v3.sql",bootstrapRollback:"supabase/rollback/202607230012_staging_initial_owner_bootstrap_rollback_v3.sql",helpersRollback:"supabase/rollback/202607230011_staging_auth_helpers_rollback_v3.sql",schemaRollback:"supabase/rollback/202607230010_staging_auth_schema_rollback_v3.sql"} as const;
export const STAGING_AUTH_SQL_V4_PATHS={preflight:"supabase/preflight/202607230014_staging_auth_preflight_v4.sql",schema:"supabase/migrations/202607230015_staging_auth_schema_v4.sql",helpers:"supabase/migrations/202607230016_staging_auth_helpers_v4.sql",bootstrap:"supabase/bootstrap/202607230017_staging_initial_owner_bootstrap_v4.sql",rls:"supabase/migrations/202607230018_staging_auth_rls_v4.sql",rlsRollback:"supabase/rollback/202607230018_staging_auth_rls_rollback_v4.sql",bootstrapRollback:"supabase/rollback/202607230017_staging_initial_owner_bootstrap_rollback_v4.sql",helpersRollback:"supabase/rollback/202607230016_staging_auth_helpers_rollback_v4.sql",schemaRollback:"supabase/rollback/202607230015_staging_auth_schema_rollback_v4.sql"} as const;
export const STAGING_AUTH_SQL_V5_PATHS={bootstrap:"supabase/bootstrap/202607230019_staging_initial_owner_bootstrap_v5.sql",bootstrapRollback:"supabase/rollback/202607230019_staging_initial_owner_bootstrap_rollback_v5.sql"} as const;
export const STAGING_AUTH_SQL_ARTIFACT_PATHS={preflight:STAGING_AUTH_SQL_V4_PATHS.preflight,schema:STAGING_AUTH_SQL_V4_PATHS.schema,helpers:STAGING_AUTH_SQL_V4_PATHS.helpers,privileges:"supabase/migrations/202607230020_staging_auth_function_privileges_v6.sql",bootstrap:"supabase/bootstrap/202607230021_staging_initial_owner_bootstrap_v7.sql",rls:STAGING_AUTH_SQL_V4_PATHS.rls,rlsRollback:STAGING_AUTH_SQL_V4_PATHS.rlsRollback,bootstrapRollback:"supabase/rollback/202607230021_staging_initial_owner_bootstrap_rollback_v7.sql",privilegesRollback:"supabase/rollback/202607230020_staging_auth_function_privileges_rollback_v6.sql",helpersRollback:STAGING_AUTH_SQL_V4_PATHS.helpersRollback,schemaRollback:STAGING_AUTH_SQL_V4_PATHS.schemaRollback,rollback:STAGING_AUTH_SQL_V4_PATHS.schemaRollback} as const;
export const STAGING_AUTH_SQL_V4_CORE_FINGERPRINTS={preflight:"181a500cb170606165048690059d09ef467db8687a46a439169ec2288da31e09",schema:"a30351a050111fadb7f6939700c543a1bf53ae179568cf200d69e79bd266a6fb",helpers:"1b1d8f9393900d57972d97efddfe71fca4447fd238444b92433e1d9c98980105",rls:"e61484fef2c633c7c146cb3b5c7a74584b700526156b191049288d98ea005a45",rlsRollback:"6f83411e7abe88c88968ead29d56d656e1814ffcd09fb67fb6b4858710e7e352",helpersRollback:"97b786ab8286fb69d083a2a4a342e8607f7a76f20ae39e7932a4dc7cd6692442",schemaRollback:"431b9453f7d731549d989d4de7df373dfbedf1355dcb487af7113d705555f903"} as const;
export type StagingAuthSqlArtifactKey=Exclude<keyof typeof STAGING_AUTH_SQL_ARTIFACT_PATHS,"rollback">;
export type StagingAuthSqlReviewStatus="rejected"|"read_only_preflight_passed_rejected_for_mutation"|"pending_manual_review";
export type StagingAuthSqlArtifact={artifactKey:string;path:string;label:string;exists:boolean;fingerprint:string;artifactVersion:"v1"|"v2"|"v3"|"v4"|"v5"|"v6"|"v7";phase:string;reviewStatus:StagingAuthSqlReviewStatus;executableStatus:"review_only_not_approved";executionStatus:"not_executed"|"read_only_preflight_executed";supersedes:string|null;stagingOnly:true;manuallyReviewed:false;executed:boolean;authoritative:boolean;expectedOrder:number};
type Definition=readonly[string,string,string,string,number,string|null];
const definitions=(version:"v1"|"v2"|"v3"|"v4",paths:Record<string,string>)=>Object.entries(paths).map(([key,path],i)=>[`${version}_${key}`,path,`${version.toUpperCase()} ${key}`,key,i+1,null] as Definition);
const v5HistoricalDefinitions:Definition[]=[
 ["v5_bootstrap",STAGING_AUTH_SQL_V5_PATHS.bootstrap,"V5 bootstrap rejected after two safe failed execution attempts","bootstrap",1,STAGING_AUTH_SQL_V4_PATHS.bootstrap],
 ["v5_bootstrapRollback",STAGING_AUTH_SQL_V5_PATHS.bootstrapRollback,"V5 bootstrap rollback rejected for substitution/sentinel collision","bootstrap_rollback",2,STAGING_AUTH_SQL_V4_PATHS.bootstrapRollback]
];
const historicalDefinitions=[...definitions("v1",STAGING_AUTH_SQL_V1_PATHS),...definitions("v2",STAGING_AUTH_SQL_V2_PATHS),...definitions("v3",STAGING_AUTH_SQL_V3_PATHS),...definitions("v4",STAGING_AUTH_SQL_V4_PATHS),...v5HistoricalDefinitions];
const v7Definitions:Definition[]=[
 ["preflight",STAGING_AUTH_SQL_ARTIFACT_PATHS.preflight,"V7 composite: completed V4 read-only compatibility preflight","preflight",1,STAGING_AUTH_SQL_V4_PATHS.preflight],
 ["schema",STAGING_AUTH_SQL_ARTIFACT_PATHS.schema,"V7 composite: completed V4 schema","schema",2,STAGING_AUTH_SQL_V4_PATHS.schema],
 ["helpers",STAGING_AUTH_SQL_ARTIFACT_PATHS.helpers,"V7 composite: completed V4 helpers","helpers",3,STAGING_AUTH_SQL_V4_PATHS.helpers],
 ["privileges",STAGING_AUTH_SQL_ARTIFACT_PATHS.privileges,"V7 composite: completed V6 least-privilege correction","function_privileges",4,null],
 ["bootstrap",STAGING_AUTH_SQL_ARTIFACT_PATHS.bootstrap,"V7 substitution-safe JSON bootstrap","bootstrap",5,STAGING_AUTH_SQL_V5_PATHS.bootstrap],
 ["rls",STAGING_AUTH_SQL_ARTIFACT_PATHS.rls,"V7 composite: V4 seven-table deny-by-default RLS","rls",6,STAGING_AUTH_SQL_V4_PATHS.rls],
 ["rlsRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.rlsRollback,"V7 composite: V4 RLS rollback","rls_rollback",1,STAGING_AUTH_SQL_V4_PATHS.rlsRollback],
 ["bootstrapRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.bootstrapRollback,"V7 substitution-safe JSON bootstrap rollback","bootstrap_rollback",2,STAGING_AUTH_SQL_V5_PATHS.bootstrapRollback],
 ["privilegesRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.privilegesRollback,"V7 composite: V6 safe privilege rollback","function_privileges_rollback",3,null],
 ["helpersRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.helpersRollback,"V7 composite: V4 helpers rollback","helpers_rollback",4,STAGING_AUTH_SQL_V4_PATHS.helpersRollback],
 ["schemaRollback",STAGING_AUTH_SQL_ARTIFACT_PATHS.schemaRollback,"V7 composite: V4 schema rollback","schema_rollback",5,STAGING_AUTH_SQL_V4_PATHS.schemaRollback]
];
const allowedPaths=new Set<string>([...Object.values(STAGING_AUTH_SQL_V1_PATHS),...Object.values(STAGING_AUTH_SQL_V2_PATHS),...Object.values(STAGING_AUTH_SQL_V3_PATHS),...Object.values(STAGING_AUTH_SQL_V4_PATHS),...Object.values(STAGING_AUTH_SQL_V5_PATHS),...Object.values(STAGING_AUTH_SQL_ARTIFACT_PATHS)]);
export function readStagingAuthSqlArtifact(path:string,baseDir=process.cwd()){if(!allowedPaths.has(path))throw new Error("staging_auth_sql_artifact_path_not_allowed");return readFileSync(resolve(baseDir,path),"utf8")}
export function calculateStagingAuthSqlArtifactFingerprint(content:string){return createHash("sha256").update(content,"utf8").digest("hex")}
function artifact(baseDir:string,d:Definition,version:"v1"|"v2"|"v3"|"v4"|"v5"|"v6"|"v7",reviewStatus:StagingAuthSqlReviewStatus,authoritative:boolean):StagingAuthSqlArtifact{const[k,path,label,phase,expectedOrder,supersedes]=d,found=existsSync(resolve(baseDir,path)),isV3Preflight=version==="v3"&&phase==="preflight";return{artifactKey:k,path,label,exists:found,fingerprint:found?calculateStagingAuthSqlArtifactFingerprint(readStagingAuthSqlArtifact(path,baseDir)):"",artifactVersion:version,phase,reviewStatus,executableStatus:"review_only_not_approved",executionStatus:isV3Preflight?"read_only_preflight_executed":"not_executed",supersedes,stagingOnly:true,manuallyReviewed:false,executed:isV3Preflight,authoritative,expectedOrder}}
export function listHistoricalStagingAuthSqlArtifacts(baseDir=process.cwd()){return historicalDefinitions.map(d=>{const version=d[0].slice(0,2) as "v1"|"v2"|"v3"|"v4"|"v5";return artifact(baseDir,d,version,version==="v3"?"read_only_preflight_passed_rejected_for_mutation":"rejected",false)})}
export function listStagingAuthSqlArtifacts(baseDir=process.cwd()){return v7Definitions.map(d=>artifact(baseDir,d,"v7","pending_manual_review",true))}
export function buildStagingAuthSqlArtifactReview(baseDir=process.cwd()){return{id:"staging-auth-bootstrap-v7",generatedAt:new Date().toISOString(),artifacts:listStagingAuthSqlArtifacts(baseDir),historicalArtifacts:listHistoricalStagingAuthSqlArtifacts(baseDir),authoritative:true,authoritativeVersion:"v7" as const,executionOrder:["preflight","schema","helpers","privileges","bootstrap","rls"],rollbackOrder:["rlsRollback","bootstrapRollback","privilegesRollback","helpersRollback","schemaRollback"],v3PreflightEvidence:{confirmed:true,result:"passed" as const,evidenceReference:"STG-PREFLIGHT-V3-20260723-01",executionRole:"postgres",executionDate:"2026-07-23",readOnly:true,rolledBack:true,databaseMutation:false,productionBlocked:true},stagingExecutionEvidence:{schema:{completed:true,verified:true},helpers:{completed:true,structuralVerification:"passed" as const,privilegeVerification:"passed_after_v6_repair" as const,functions:9,triggers:8,policies:0,rlsEnabled:0,tableRows:0,candidateDomainMutation:false,productionMutation:false},privileges:{version:"v6" as const,completed:true,verified:true},v5Bootstrap:{status:"rejected" as const,attempts:2,safeFailures:2,error:"staging_owner_v5_placeholder_not_replaced",rowsCreated:0,candidateDomainMutation:false,productionMutation:false}},migrationManuallyReviewed:false,helpersManuallyReviewed:false,rlsManuallyReviewed:false,bootstrapManuallyApproved:false,rollbackManuallyApproved:false,stagingImplementationApproved:false,productionCandidateDataCopied:false,safety:{readOnly:true,sqlExecuted:0,migrationsExecuted:0,rlsExecuted:0,bootstrapExecuted:0,rollbackExecuted:0,supabaseCalls:0,databaseReads:0,databaseWrites:0,environmentFilesModified:false,candidateDbWrites:0,productionBlocked:true}}}
export function validateStagingAuthSqlArtifacts(baseDir=process.cwd()){
 const review=buildStagingAuthSqlArtifactReview(baseDir),by=Object.fromEntries(review.artifacts.map(x=>[x.artifactKey,readStagingAuthSqlArtifact(x.path,baseDir)])) as Record<StagingAuthSqlArtifactKey,string>,all=Object.values(by).join("\n");
 const policies=[...by.rls.matchAll(/create policy[\s\S]*?;/gi)].map(x=>x[0]),inserts=policies.filter(x=>/ for insert /i.test(x)),updates=policies.filter(x=>/ for update /i.test(x)),preflightCode=by.preflight.split(/\r?\n/).filter(x=>!x.trim().startsWith("--")).join("\n");
 const privilegeCode=by.privileges.split(/\r?\n/).filter(x=>!x.trim().startsWith("--")).join("\n"),privilegeRollbackCode=by.privilegesRollback.split(/\r?\n/).filter(x=>!x.trim().startsWith("--")).join("\n");
 const configToken="__STAGING_BOOTSTRAP_CONFIG_JSON__",v5Bootstrap=readStagingAuthSqlArtifact(STAGING_AUTH_SQL_V5_PATHS.bootstrap,baseDir),v5Rollback=readStagingAuthSqlArtifact(STAGING_AUTH_SQL_V5_PATHS.bootstrapRollback,baseDir);
 const tokenCount=(sql:string)=>(sql.match(new RegExp(configToken,"g"))||[]).length;
 const substitutedBootstrap=by.bootstrap.replace(configToken,"{}");
 const substitutedRollback=by.bootstrapRollback.replace(configToken,"{}");
 const v7Code=by.bootstrap+"\n"+by.bootstrapRollback;
 const checks={
  historyPreserved:review.historicalArtifacts.length===32&&review.historicalArtifacts.every(x=>x.exists&&!x.authoritative),
  v3Evidence:review.v3PreflightEvidence.result==="passed"&&review.historicalArtifacts.filter(x=>x.artifactVersion==="v3"&&x.phase!=="preflight").every(x=>!x.executed),
  v4Rejected:review.historicalArtifacts.filter(x=>x.artifactVersion==="v4").length===9&&review.historicalArtifacts.filter(x=>x.artifactVersion==="v4").every(x=>x.reviewStatus==="rejected"&&!x.executed),
  v5Rejected:review.historicalArtifacts.filter(x=>x.artifactVersion==="v5").length===2&&review.historicalArtifacts.filter(x=>x.artifactVersion==="v5").every(x=>x.reviewStatus==="rejected"&&!x.executed)&&review.stagingExecutionEvidence.v5Bootstrap.safeFailures===2,
  v5Preserved:calculateStagingAuthSqlArtifactFingerprint(v5Bootstrap)==="8182a28057d5c3276e3a23443c03159c141511ea6df2b5c8a858527e08886b1d"&&calculateStagingAuthSqlArtifactFingerprint(v5Rollback)==="6caf8e9645ecf624043d1602e9daf5fb7eaaf1ca22ed97aa0b150c0b3d0a0468",
  v7Complete:review.artifacts.length===11&&review.artifacts.every(x=>x.exists&&x.artifactVersion==="v7"&&x.reviewStatus==="pending_manual_review"&&!x.executed),
  v4CoreUnchanged:(Object.keys(STAGING_AUTH_SQL_V4_CORE_FINGERPRINTS) as Array<keyof typeof STAGING_AUTH_SQL_V4_CORE_FINGERPRINTS>).every(key=>calculateStagingAuthSqlArtifactFingerprint(readStagingAuthSqlArtifact(STAGING_AUTH_SQL_V4_PATHS[key],baseDir))===STAGING_AUTH_SQL_V4_CORE_FINGERPRINTS[key]),
  fingerprints:review.artifacts.every(x=>/^[a-f0-9]{64}$/.test(x.fingerprint)),
  preflightReadOnly:/begin;\s*set transaction read only/i.test(by.preflight)&&/\brollback;/i.test(by.preflight)&&!/^\s*(create|alter|drop|truncate|insert|update|delete|copy)\b/im.test(preflightCode),
  authUid:/to_regprocedure\('auth\.uid\(\)'\)/.test(by.preflight)&&/p\.pronargs = 0/.test(by.preflight)&&/t\.typname = 'uuid'/.test(by.preflight),
  scopedConflicts:/t\.tgrelid/.test(by.preflight)&&/p\.pronargs = 0/.test(by.preflight)&&/pol\.polrelid/.test(by.preflight),
  provenance:/create table public\.staging_auth_bootstrap_provenance/.test(by.schema)&&/bootstrap_type_key unique/.test(by.schema),
  singleConfigToken:tokenCount(by.bootstrap)===1&&tokenCount(by.bootstrapRollback)===1,
  substitutionSafe:/concat\('__STAGING_BOOTSTRAP_',\s*'CONFIG_JSON__'\)/.test(by.bootstrap)&&/concat\('__STAGING_BOOTSTRAP_',\s*'CONFIG_JSON__'\)/.test(by.bootstrapRollback)&&!substitutedBootstrap.includes("if config_json_text = '{}'")&&!substitutedRollback.includes("if config_json_text = '{}'"),
  strictJson:/jsonb_object_keys\(v_config\)/.test(by.bootstrap)&&/cardinality\(v_required_keys\)/.test(by.bootstrap)&&/jsonb_typeof\(v_config\)/.test(by.bootstrap),
  jsonNotPersisted:!/insert into[\s\S]{0,300}\b(v_config|config_json_text)\b/i.test(v7Code),
  fixedErrors:![...v7Code.matchAll(/message\s*=\s*([^;]+)/gi)].some(x=>!/^'staging_owner_v7_[a-z_]+'$/.test(x[1].trim())),
  exactTransactions:/^\s*begin;/im.test(by.bootstrap)&&/commit;\s*(?:--[\s\S]*)?$/i.test(by.bootstrap)&&/^\s*begin;/im.test(by.bootstrapRollback)&&/commit;\s*(?:--[\s\S]*)?$/i.test(by.bootstrapRollback),
  advisoryLock:/pg_advisory_xact_lock\(731942607230017\)/.test(by.bootstrap)&&/pg_advisory_xact_lock\(731942607230017\)/.test(by.bootstrapRollback),
  emailMatch:/v_confirmed_auth_email <> v_admin_email/.test(by.bootstrap)&&/from auth\.users u/.test(by.bootstrap),
  threeInsertAssertions:(by.bootstrap.match(/insert_count_invalid/g)||[]).length===3,
  threeDeleteAssertions:(by.bootstrapRollback.match(/delete_count_invalid/g)||[]).length===3,
  rollbackOrder:by.bootstrapRollback.indexOf("delete from public.staging_auth_bootstrap_provenance")<by.bootstrapRollback.indexOf("delete from public.user_profiles")&&by.bootstrapRollback.indexOf("delete from public.user_profiles")<by.bootstrapRollback.indexOf("delete from public.organizations"),
  authUserUntouched:!/\b(delete|update|insert into)\s+(from\s+)?auth\.users\b/i.test(v7Code),
  candidateFoundationUntouched:!/\b(delete|update|insert into)\s+(from\s+)?public\.candidate_accounts\b/i.test(v7Code),
  privilegeRevokes:(privilegeCode.match(/^revoke execute on function public\.[a-z_]+\(\) from public;$/gim)||[]).length===9&&(privilegeCode.match(/^revoke execute on function public\.[a-z_]+\(\) from anon;$/gim)||[]).length===9&&(privilegeCode.match(/^revoke execute on function public\.[a-z_]+\(\) from authenticated;$/gim)||[]).length===9&&(privilegeCode.match(/^revoke execute on function public\.[a-z_]+\(\) from service_role;$/gim)||[]).length===9,
  privilegeGrants:(privilegeCode.match(/^grant execute on function public\.current_user_[a-z_]+\(\) to authenticated;$/gim)||[]).length===6&&!/^grant execute .* to (anon|service_role|public);$/im.test(privilegeCode)&&!/^grant execute on function public\.(set_staging_auth_updated_at|guard_user_profile_protected_columns|reject_access_audit_log_mutation)\(\) to authenticated;$/im.test(privilegeCode),
  privilegeOnly:!/^\s*(create|alter|drop)\s+(or replace\s+)?(function|trigger|table|policy)\b/im.test(privilegeCode)&&!/^\s*(insert|update|delete|copy|truncate)\b/im.test(privilegeCode)&&!/row level security/i.test(privilegeCode),
  safePrivilegeRollback:!/^grant execute/im.test(privilegeRollbackCode)&&(privilegeRollbackCode.match(/^revoke execute on function public\.[a-z_]+\(\) from authenticated;$/gim)||[]).length===9,
  phaseEvidence:review.stagingExecutionEvidence.schema.verified&&review.stagingExecutionEvidence.helpers.structuralVerification==="passed"&&review.stagingExecutionEvidence.privileges.verified,
  policySyntax:inserts.length>0&&inserts.every(x=>/with check/i.test(x)&&!/\busing\s*\(/i.test(x))&&updates.every(x=>/\busing\s*\(/i.test(x)&&/with check/i.test(x)),
  provenancePolicy:policies.filter(x=>/bootstrap_provenance/i.test(x)).length===1&&!policies.some(x=>/bootstrap_provenance[\s\S]*for (insert|update|delete)/i.test(x)),
  candidateProtected:!/(alter|update|delete|drop)\s+(table\s+|from\s+)?public\.candidates\b/i.test(all)
 };
 const issues=Object.entries(checks).filter(([,ok])=>!ok).map(([key])=>key);return{valid:issues.length===0,checks,issues,artifacts:review.artifacts,historicalArtifacts:review.historicalArtifacts};
}
