import type {StagingAuthNormalizedOperationRequest,StagingAuthOperationRequest,StagingAuthOperationRequestKey,StagingAuthOperationRequestSource} from "./stagingAuthOperationTypes";
let requestSequence=0;const operations:StagingAuthOperationRequestKey[]=["get_session","get_user","get_profile","sign_in","sign_out","request_password_reset","accept_invitation","refresh_session"],sources:StagingAuthOperationRequestSource[]=["server_preview","admin_preview","auth_ui_future","test_preview"];
export function createStagingAuthRequestId(){requestSequence+=1;return`staging-auth-request-${String(requestSequence).padStart(4,"0")}`}
export function maskOperationEmail(email:unknown){if(typeof email!=="string")return"hidden";const match=email.trim().toLowerCase().match(/^([^@]+)@([^@.]+)(\..+)$/);if(!match)return"hidden";return`${match[1][0]}***@${match[2][0]}***${match[3]}`}
export function redactSensitiveAuthValue(_value:unknown){return"[REDACTED]" as const}
export function sanitizeSignInInput(input:unknown){const value=input&&typeof input==="object"?input as Record<string,unknown>:{};return{emailMasked:maskOperationEmail(value.email),password:redactSensitiveAuthValue(value.password),validationCodes:typeof value.email==="string"&&typeof value.password==="string"?[]:["invalid_sign_in_input"]}}
export function sanitizePasswordResetInput(input:unknown){const value=input&&typeof input==="object"?input as Record<string,unknown>:{};return{emailMasked:maskOperationEmail(value.email),validationCodes:typeof value.email==="string"?[]:["invalid_password_reset_input"]}}
export function sanitizeInvitationInput(input:unknown){const value=input&&typeof input==="object"?input as Record<string,unknown>:{};return{invitationToken:redactSensitiveAuthValue(value.invitationToken),validationCodes:typeof value.invitationToken==="string"?[]:["invalid_invitation_input"]}}
export function normalizeStagingAuthOperationRequest(input:unknown):StagingAuthNormalizedOperationRequest{const value=input&&typeof input==="object"?input as Record<string,unknown>:{},operation=operations.includes(value.operation as StagingAuthOperationRequestKey)?value.operation as StagingAuthOperationRequestKey:"get_session",source=sources.includes(value.source as StagingAuthOperationRequestSource)?value.source as StagingAuthOperationRequestSource:"server_preview",base={requestId:typeof value.requestId==="string"&&/^[a-z0-9-]{1,80}$/.test(value.requestId)?value.requestId:createStagingAuthRequestId(),operation,source,requestedAt:typeof value.requestedAt==="string"&&/^\d{4}-\d{2}-\d{2}T/.test(value.requestedAt)?value.requestedAt:"1970-01-01T00:00:00.000Z",simulationOnly:value.simulationOnly!==false,productionAllowed:false as const};if(operation==="sign_in"){const safe=sanitizeSignInInput(value);return{...base,emailMasked:typeof value.emailMasked==="string"?value.emailMasked:safe.emailMasked,validationCodes:safe.validationCodes}}if(operation==="request_password_reset"){const safe=sanitizePasswordResetInput(value);return{...base,emailMasked:typeof value.emailMasked==="string"?value.emailMasked:safe.emailMasked,validationCodes:safe.validationCodes}}if(operation==="accept_invitation"){const safe=sanitizeInvitationInput(value);return{...base,validationCodes:safe.validationCodes}}return{...base,validationCodes:[]}}
export function serializeSafeAuthOperationRequest(request:StagingAuthOperationRequest|StagingAuthNormalizedOperationRequest){return JSON.stringify(normalizeStagingAuthOperationRequest(request))}
export function validateSensitiveDataNotPresent(value:unknown){const text=typeof value==="string"?value:JSON.stringify(value);return!/("password"|invitationToken|Bearer\s+|eyJ[a-zA-Z0-9_-]{8,}|\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b)/i.test(text)}


