import type {StagingAuthOperationBoundaryResult} from "./stagingAuthOperationTypes";import type {StagingAuthUiActionState,StagingAuthUiFieldError,StagingAuthUiOperationKey} from "./stagingAuthUiBindingTypes";
const operations:StagingAuthUiOperationKey[]=["sign_in","sign_out","request_password_reset","accept_invitation","get_session","get_user","get_profile","refresh_session"],statuses=new Set(["blocked","disabled","preview_only","provider_not_implemented","failed_safe","completed_preview","production_blocked"]);
export function buildInitialStagingAuthUiActionState(operation:StagingAuthUiOperationKey):StagingAuthUiActionState{return{operation,status:"idle",submitted:false,ok:false,safeMessage:"Preview only. No real authentication has occurred. No session or cookie was created. Production remains blocked.",blockerKeys:[],warningKeys:[],fieldErrors:[],sensitiveInputReturned:false,passwordReturned:false,invitationTokenReturned:false,stackTraceReturned:false,realActionExecuted:false,productionBlocked:true}}
export function buildSafeAuthUiMessage(result:Pick<StagingAuthOperationBoundaryResult,"status">){const lead=result.status==="production_blocked"?"Production authentication is blocked.":result.status==="provider_not_implemented"?"The staging provider is not implemented.":result.status==="failed_safe"?"The preview could not be completed safely.":"The operation remains blocked or preview-only.";return`${lead} Preview only; no real authentication occurred, no session or cookie was created, and production remains blocked.`}
export function buildStagingAuthUiFieldErrors(operation:StagingAuthUiOperationKey,errorCode?:string):StagingAuthUiFieldError[]{if(!errorCode)return[];const field=errorCode.includes("email")?"email":errorCode.includes("password")?"password":errorCode.includes("invitation")?"invitationToken":"form";return[{field,code:/^[a-z0-9_]{1,64}$/.test(errorCode)?errorCode:"preview_failed_safe",safeMessage:"Review the preview input. Sensitive values were discarded and were not returned."}]}
export function buildStagingAuthUiActionState(result:StagingAuthOperationBoundaryResult):StagingAuthUiActionState{const operation=operations.includes(result.operation)?result.operation:"get_session",status=statuses.has(result.status)?result.status as StagingAuthUiActionState["status"]:"failed_safe",emailMasked=result.auditPreview.emailMasked;return sanitizeStagingAuthUiActionState({operation,status,submitted:true,ok:false,safeMessage:buildSafeAuthUiMessage(result),blockerKeys:[...result.blockerKeys],warningKeys:[...result.warningKeys],fieldErrors:buildStagingAuthUiFieldErrors(operation,result.errorCode),...(emailMasked?{emailMasked}:{}),sensitiveInputReturned:false,passwordReturned:false,invitationTokenReturned:false,stackTraceReturned:false,realActionExecuted:false,productionBlocked:true})}
export function sanitizeStagingAuthUiActionState(state:StagingAuthUiActionState):StagingAuthUiActionState{const masked=state.emailMasked&&/^[^@]*\*+@[^@]*\*+\.[a-z]{2,}$/i.test(state.emailMasked)?state.emailMasked:undefined;return{...buildInitialStagingAuthUiActionState(operations.includes(state.operation)?state.operation:"get_session"),...state,status:statuses.has(state.status)||state.status==="idle"||state.status==="submitting_preview"?state.status:"failed_safe",safeMessage:typeof state.safeMessage==="string"&&!/@|password\s*[:=]|token\s*[:=]/i.test(state.safeMessage)?state.safeMessage:"The preview returned a safe result. No real authentication occurred, and production remains blocked.",blockerKeys:state.blockerKeys.filter(x=>/^[a-z0-9_]+$/.test(x)),warningKeys:state.warningKeys.filter(x=>/^[a-z0-9_]+$/.test(x)),fieldErrors:state.fieldErrors.map(x=>({...x,safeMessage:"Review the preview input. Sensitive values were discarded and were not returned."})),...(masked?{emailMasked:masked}:{emailMasked:undefined}),sensitiveInputReturned:false,passwordReturned:false,invitationTokenReturned:false,stackTraceReturned:false,realActionExecuted:false,productionBlocked:true}}
export function validateStagingAuthUiActionState(state:StagingAuthUiActionState){const text=JSON.stringify(state);return state.productionBlocked&&!state.realActionExecuted&&!state.passwordReturned&&!state.invitationTokenReturned&&!state.stackTraceReturned&&!/("password"\s*:\s*"(?!false)|invitationToken"\s*:|\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b)/i.test(text)}
export function buildStagingAuthUiBindingPreview(){const operationStates=operations.map(buildInitialStagingAuthUiActionState);return{forms:operations.slice(0,4),operationStates,resultPanels:operationStates,safety:{clientReceivesPassword:false,clientReceivesInvitationToken:false,completeEmailExposed:false,stackTraceExposed:false,supabaseImports:0,supabaseCalls:0,authCalls:0,sessionsCreated:0,cookiesRead:0,cookiesSet:0,redirectsExecuted:0,databaseReads:0,databaseWrites:0,auditWrites:0,rateLimitStoreWrites:0,emailSends:0,sqlStatementsExecuted:0,migrationsExecuted:0,rlsPoliciesExecuted:0,middlewareEnforced:false,openAiCalls:0,productionBlocked:true}} as const}
export function validateStagingAuthUiBindingPreview(preview:ReturnType<typeof buildStagingAuthUiBindingPreview>){return preview.forms.length===4&&preview.operationStates.length===8&&preview.operationStates.every(validateStagingAuthUiActionState)&&preview.safety.productionBlocked}

