import fs from "node:fs";import path from "node:path";import {buildStagingAuthSqlArtifactReview} from "./stagingAuthSqlArtifacts";import type {StagingAuthImplementationRequirement,StagingEnvironmentReadiness,StagingEnvironmentVariableRequirement,StagingGoNoGoGate,StagingImplementationReadinessReport,StagingReadinessBlocker,StagingReadinessNextAction,StagingReadinessStatus,StagingRoleOwnershipRequirement,StagingRollbackRequirement,StagingSmokeTestCase,StagingSqlArtifactPreview} from "./stagingImplementationReadinessTypes";
const exists=(base:string,file:string)=>fs.existsSync(path.join(base,file));const source=(base:string,file:string)=>{try{return fs.readFileSync(path.join(base,file),"utf8")}catch{return""}};
const variableDefinitions=[
 ["NEXT_PUBLIC_SUPABASE_URL","public_client",true,"staging deployment environment"],["NEXT_PUBLIC_SUPABASE_ANON_KEY","public_client",true,"staging deployment environment"],["SUPABASE_SERVICE_ROLE_KEY","server_only",true,"server-only staging secret storage"],["NEXT_PUBLIC_APP_URL","operational",true,"staging deployment environment"],["AUTH_REDIRECT_URL","optional",false,"server-side staging configuration"],["AUTH_INVITE_SECRET","optional",false,"server-only staging secret storage"]
] as const;
export function buildEnvironmentVariableRequirements(baseDir=process.cwd()):StagingEnvironmentVariableRequirement[]{const documented=source(baseDir,"lib/authSetupPreview.ts");return variableDefinitions.map(([key,category,requiredForStaging,expectedLocation])=>({key,category,requiredForStaging,expectedLocation,valueInspected:false,presenceStatus:documented.includes(`\"${key}\"`)?"present":"missing",safetyNotes:[category==="server_only"?"Server-only; never expose to client code.":"Name/documentation checked only.","Value intentionally not inspected or displayed."]}));}
export function buildStagingEnvironmentReadiness(baseDir=process.cwd()):StagingEnvironmentReadiness{const vars=buildEnvironmentVariableRequirements(baseDir),missingVariableNames=vars.filter(v=>v.requiredForStaging&&v.presenceStatus==="missing").map(v=>v.key);return{dedicatedStagingEnvironmentConfirmed:false,productionEnvironmentSeparated:false,environmentConventionDetected:vars.some(v=>v.presenceStatus==="present"),requiredVariableNames:vars.filter(v=>v.requiredForStaging).map(v=>v.key),missingVariableNames,secretValuesInspected:false,environmentFilesModified:false,status:missingVariableNames.length?"blocked":"conditionally_ready",issues:missingVariableNames.map(x=>`${x} is not documented.`),manualEvidenceRequired:["Dedicated staging Supabase project confirmation","Staging/production project separation confirmation","Secret storage and client-bundle review"]};}
export function buildStagingSqlArtifactPreview(baseDir=process.cwd()):StagingSqlArtifactPreview[]{
 const review=buildStagingAuthSqlArtifactReview(baseDir),by=Object.fromEntries(review.artifacts.map(x=>[x.artifactKey,x]));
 const artifact=(artifactKey:string,label:string,category:StagingSqlArtifactPreview["category"],route:string,sourceKey:"schema"|"helpers"|"rls"|"rollback"):StagingSqlArtifactPreview=>{const sourceArtifact=by[sourceKey];return{artifactKey,label,category,route,sourceFile:sourceArtifact.path,previewAvailable:sourceArtifact.exists,manuallyReviewed:false,executionStatus:"not_executed",fingerprint:sourceArtifact.fingerprint,issues:sourceArtifact.exists?["Authoritative SQL artifact available; manual review evidence is required."]:["Authoritative SQL artifact is missing."]}};
 return[
  artifact("schema_migration","User/profile schema migration","schema_migration","/auth/migrations","schema"),artifact("organization_schema","Organization/client relationship schema","ownership","/auth/migrations","schema"),artifact("role_assignment","Role assignment model","role_profile","/auth/migrations","schema"),artifact("auth_helpers","Active-profile helper functions","role_profile","/auth/rls","helpers"),artifact("candidate_ownership","Candidate ownership","ownership","/auth/rls","rls"),artifact("client_ownership","Client ownership","ownership","/auth/rls","rls"),artifact("recruiter_scope","Recruiter organization scope","ownership","/auth/rls","rls"),artifact("rls_policies","RLS policy artifact","rls","/auth/rls","rls"),artifact("rollback","Migration/RLS rollback artifact","rollback","/auth/staging","rollback")
 ];
}
export function buildStagingRoleOwnershipRequirements():StagingRoleOwnershipRequirement[]{const row=(role:StagingRoleOwnershipRequirement["role"],expectedPortal:string,expectedOrganizationScope:string,candidateOwnershipRequired:boolean,clientOwnershipRequired:boolean,recruiterOrganizationRequired:boolean,tests:string[]):StagingRoleOwnershipRequirement=>({role,expectedPortal,expectedOrganizationScope,candidateOwnershipRequired,clientOwnershipRequired,recruiterOrganizationRequired,adminOverridePreview:role==="admin",implementationStatus:"requires_manual_confirmation",testCases:tests});return[
 row("admin","/admin/portal","Platform-wide preview; production override not approved",false,false,false,["Access readiness/auth planning routes","Verify future admin activity logging"]),row("recruiter_manager","/recruiter/dashboard","Recruiter organization/team scope",false,false,true,["Team jobs only","Deny unrelated organization"]),row("recruiter","/recruiter/dashboard","Organization-assigned jobs and candidates",false,false,true,["Assigned records only","Deny unrelated client/candidate"]),row("client","/client/portal","Owning client organization",false,true,false,["Own jobs, packs and reports","Deny another client"]),row("candidate","/candidate/portal","Own candidate profile and confirmations",true,false,false,["Own profile only","Deny another candidate"]),row("guest","/portal","Public portal/login preview only",false,false,false,["No protected data","Future protected-route redirect"] )];}
export function buildStagingAuthImplementationRequirements(baseDir=process.cwd()):StagingAuthImplementationRequirement[]{const defs=[
 ["auth_client","Auth client","auth_client","lib/authHelperPreview.ts"],["auth_server","Auth server","auth_server","lib/authHelperPreview.ts"],["profile_lookup","User profile lookup","profile_lookup","lib/authHelperPreview.ts"],["role_resolution","Role resolution","role_resolution","lib/roleAccessPreview.ts"],["middleware","Staging middleware","middleware","lib/middlewareGuardPreview.ts"],["invitation","Invitation flow","invitation","lib/authSetupPreview.ts"],["password_reset","Password reset","password_reset","app/auth/forgot-password/page.tsx"],["logout","Logout","logout","app/auth/logout/page.tsx"],["ownership","Ownership enforcement","ownership","lib/rlsPolicyPreview.ts"]
 ] as const;return defs.map(([requirementKey,label,area,file])=>({requirementKey,label,area,currentStatus:exists(baseDir,file)?"requires_manual_confirmation":"missing",requiredEvidence:[`${file} preview reviewed`,`Staging-only implementation and test evidence`],blockerReason:"Real staging implementation and verification have not started.",productionRequired:true}));}
export function buildStagingSmokeTests():StagingSmokeTestCase[]{const row=(role:StagingSmokeTestCase["role"],start:string,landing:string,allowed:string[],denied:string[]):StagingSmokeTestCase=>({testKey:`${role}_access`,label:`${role} staging access and ownership`,role,startingRoute:start,expectedRoute:landing,expectedAccess:allowed,expectedDeniedRoutes:denied,databaseMutationExpected:false,manualExecutionRequired:true,currentStatus:"not_started"});return[
 row("admin","/auth/login","/admin/portal",["/admin/platform-readiness","/admin/staging-readiness","/auth/setup"],["production project"]),row("recruiter_manager","/auth/login","/recruiter/dashboard",["/recruiter/jobs","/recruiter/talent-search"],["/client/portal","/candidate/portal","unrelated organization data"]),row("recruiter","/auth/login","/recruiter/dashboard",["/recruiter/jobs","/recruiter/talent-search"],["/admin/portal","unrelated organization data"]),row("client","/auth/login","/client/portal",["own submitted packs","own reports"],["/recruiter/dashboard","/admin/portal","/candidate/portal","another client record"]),row("candidate","/auth/login","/candidate/portal",["own profile","own confirmations"],["/recruiter/dashboard","/admin/portal","/client/portal","another candidate profile"]),row("guest","/portal","/portal",["/portal","/auth/login"],["all protected data routes"] )];}
export function buildStagingRollbackRequirements(baseDir=process.cwd()):StagingRollbackRequirement[]{const plan=source(baseDir,"lib/stagingAuthEnablementPlan.ts"),defs=[
 ["backup","Staging database backup confirmed","Create and verify a staging backup",false],["migration","Migration rollback reviewed","Use manually reviewed rollback SQL",true],["rls","RLS rollback reviewed","Restore prior policies from reviewed plan",true],["middleware","Middleware disable switch documented","Disable staging guard deployment",false],["helpers","Auth helper fallback documented","Restore preview-only helper path",false],["sessions","Session invalidation plan documented","Invalidate staging sessions manually",false],["users","Staging user cleanup plan documented","Remove test identities with explicit approval",true],["email","Email remains disabled","Keep delivery disabled",false],["production","Production remains untouched","Do not target production",false]
 ] as const;return defs.map(([rollbackKey,label,rollbackAction,destructive])=>({rollbackKey,label,required:true,evidenceStatus:rollbackKey==="production"||rollbackKey==="email"?"present":plan.includes("rollback")?"requires_manual_confirmation":"missing",rollbackAction,destructive,manualApprovalRequired:true}));}
export function buildStagingGoNoGoGates(baseDir=process.cwd()):StagingGoNoGoGate[]{const env=buildStagingEnvironmentReadiness(baseDir),sql=buildStagingSqlArtifactPreview(baseDir);return[
 {gateKey:"environment_separation",label:"Environment separation",required:true,status:"requires_manual_confirmation",evidence:env.requiredVariableNames,blockerReason:"Dedicated staging project and production separation are not confirmed.",approvalOwner:"Platform owner",manualApprovalRequired:true},{gateKey:"secrets",label:"Secrets",required:true,status:"requires_manual_confirmation",evidence:["Variable names documented","Values intentionally not inspected"],blockerReason:"Secret storage and client-bundle safety require confirmation.",approvalOwner:"Security owner",manualApprovalRequired:true},{gateKey:"sql_review",label:"SQL review",required:true,status:"requires_manual_confirmation",evidence:sql.map(x=>`${x.label}: preview ${x.previewAvailable?"available":"missing"}`),blockerReason:"Migration, RLS, and rollback are not manually reviewed.",approvalOwner:"Database owner",manualApprovalRequired:true},{gateKey:"ownership",label:"Ownership model",required:true,status:"requires_manual_confirmation",evidence:["Six role requirements generated"],blockerReason:"Ownership matrix approval is missing.",approvalOwner:"Product and security owners",manualApprovalRequired:true},{gateKey:"backup",label:"Staging backup",required:true,status:"requires_manual_confirmation",evidence:["Rollback requirements generated"],blockerReason:"Backup and rollback evidence is unconfirmed.",approvalOwner:"Database owner",manualApprovalRequired:true},{gateKey:"implementation_approval",label:"Implementation approval",required:true,status:"blocked",evidence:[],blockerReason:"Explicit human approval has not been recorded.",approvalOwner:"Release owner",manualApprovalRequired:true},{gateKey:"production_protection",label:"Production protection",required:true,status:"present",evidence:["Production remains blocked","No production operation is performed"],approvalOwner:"Release owner",manualApprovalRequired:false}];}
type Parts={environmentReadiness:StagingEnvironmentReadiness;sqlArtifacts:StagingSqlArtifactPreview[];roleOwnershipRequirements:StagingRoleOwnershipRequirement[];authImplementationRequirements:StagingAuthImplementationRequirement[];smokeTests:StagingSmokeTestCase[];rollbackRequirements:StagingRollbackRequirement[];goNoGoGates:StagingGoNoGoGate[]};
export function buildStagingReadinessBlockers(parts:Parts):StagingReadinessBlocker[]{return[
 ["staging_environment","environment","critical","Dedicated staging environment not confirmed","Confirm a dedicated staging Supabase project and production separation."],["manual_sql","sql","critical","Migration and RLS review missing","Review fingerprints and preview SQL manually."],["ownership","ownership","high","Ownership matrix not approved","Approve organization, client, and candidate isolation rules."],["backup","rollback","high","Backup and rollback evidence missing","Confirm backup restoration and rollback evidence."],["approval","approval","critical","Implementation approval missing","Record explicit human go/no-go approval."]
 ].map(([blockerKey,area,severity,title,remediation])=>({blockerKey,area,severity:severity as StagingReadinessBlocker["severity"],title,description:`${title}; repository planning evidence alone is insufficient.`,remediation,blocksImplementation:true,blocksProduction:true}));}
export function buildStagingReadinessNextActions(_parts:Parts):StagingReadinessNextAction[]{return[
 ["confirm_staging","P0","Confirm a dedicated staging Supabase project","Environment evidence required","/auth/setup"],["confirm_separation","P0","Confirm staging and production separation","Protect production","/auth/staging"],["review_sql","P0","Review migration and RLS previews manually","SQL approval required","/auth/migrations"],["confirm_rollback","P0","Confirm backup and rollback evidence","Recovery evidence required","/auth/staging"],["approve_ownership","P0","Approve ownership matrix","Isolation rules require approval","/admin/staging-readiness"],["helpers","P1","Implement auth helpers on staging only","After approval","/auth/helpers"],["migration","P1","Apply reviewed migration to staging only","After approval","/auth/migrations"],["rls","P1","Apply reviewed RLS to staging only","After approval","/auth/rls"],["middleware","P1","Enable middleware on staging only","After access tests","/auth/middleware"],["smoke","P1","Run role and ownership smoke tests","Verify isolation"],["invite_reset","P2","Implement invitation and password reset","Complete account lifecycle"],["audit_logs","P2","Add audit logging","Record security activity"],["production_package","P2","Prepare production go/no-go package","Production remains blocked"]
 ].map(([actionKey,priority,label,reason,route])=>({actionKey,priority:priority as StagingReadinessNextAction["priority"],label,reason,route,status:"preview_only"}));}
export function calculateStagingReadinessStatus(parts:Parts):StagingReadinessStatus{return parts.environmentReadiness.missingVariableNames.length||parts.sqlArtifacts.some(x=>!x.previewAvailable)?"blocked":"conditionally_ready";}
export function buildStagingImplementationReadinessReport(baseDir=process.cwd()):StagingImplementationReadinessReport{const parts={environmentReadiness:buildStagingEnvironmentReadiness(baseDir),sqlArtifacts:buildStagingSqlArtifactPreview(baseDir),roleOwnershipRequirements:buildStagingRoleOwnershipRequirements(),authImplementationRequirements:buildStagingAuthImplementationRequirements(baseDir),smokeTests:buildStagingSmokeTests(),rollbackRequirements:buildStagingRollbackRequirements(baseDir),goNoGoGates:buildStagingGoNoGoGates(baseDir)};return{id:"staging-implementation-readiness-v1",generatedAt:new Date().toISOString(),status:calculateStagingReadinessStatus(parts),executiveSummary:"Repository planning evidence is available. Manual environment, SQL, ownership, backup, and approval evidence is still required; production remains blocked.",environmentVariables:buildEnvironmentVariableRequirements(baseDir),...parts,blockers:buildStagingReadinessBlockers(parts),nextActions:buildStagingReadinessNextActions(parts),safety:{readOnly:true,secretValuesInspected:false,environmentFilesModified:false,supabaseCalls:0,authCalls:0,sessionsCreated:0,cookiesRead:0,cookiesSet:0,migrationsExecuted:0,sqlStatementsExecuted:0,rlsPoliciesExecuted:0,middlewareCreated:false,middlewareEnforced:false,candidateDbWrites:0,jobDbWrites:0,clientDbWrites:0,userDbWrites:0,workflowWrites:0,emailSends:0,openAiCalls:0,productionBlocked:true}};}
export function validateStagingImplementationReadinessReport(report:StagingImplementationReadinessReport){const safe=report.safety.secretValuesInspected===false&&report.safety.sqlStatementsExecuted===0&&report.safety.productionBlocked&&report.goNoGoGates.find(g=>g.gateKey==="production_protection")?.status==="present";return{valid:Boolean(safe&&report.environmentVariables.every(v=>v.valueInspected===false)&&report.sqlArtifacts.every(a=>a.executionStatus==="not_executed")),issues:[] as string[]};}
