import {buildStagingAuthAdapterForGate} from "./stagingAuthAdapterFactory";import {buildStagingAuthExecutionGate} from "./stagingAuthExecutionGate";import {buildSafeE2eTraceFromOperationResult,createStagingAuthE2eTraceId,STAGING_AUTH_E2E_LAYERS,validateNoLayerBypass,validateNoSensitiveDataInTrace} from "./stagingAuthE2eTrace";import {executeStagingAuthOperationWithAdapter} from "./stagingAuthOperationService";import type {StagingAuthOperationRequest,StagingAuthOperationRequestKey} from "./stagingAuthOperationTypes";import type {StagingAuthE2eCoverage,StagingAuthE2ePreview,StagingAuthE2eScenarioKey,StagingAuthE2eScenarioResult} from "./stagingAuthE2eTypes";
const full={appEnvironment:"staging" as const,authMode:"staging_approved" as const,stagingAuthEnabled:true,stagingAuthApproved:true,productionAuthEnabled:false,evidencePackAvailable:true,runbookAvailable:true,stagingBackupConfirmed:true,migrationReviewed:true,rlsReviewed:true,ownershipApproved:true,rollbackApproved:true};
const request=(scenarioKey:StagingAuthE2eScenarioKey,operation:StagingAuthOperationRequestKey):StagingAuthOperationRequest=>({requestId:`e2e-request-${scenarioKey}`,operation,source:"test_preview",requestedAt:"1970-01-01T00:00:00.000Z",simulationOnly:true,productionAllowed:false,...(operation==="sign_in"?{email:"remove@example.invalid",password:"remove-sensitive-value"}:{}),...(operation==="request_password_reset"?{email:"remove@example.invalid"}:{}),...(operation==="accept_invitation"?{invitationToken:"remove-sensitive-value"}:{})} as StagingAuthOperationRequest);
function scenario(scenarioKey:StagingAuthE2eScenarioKey,operation:StagingAuthOperationRequestKey,mode:"default"|"approved"|"production"="default"):StagingAuthE2eScenarioResult{const gate=buildStagingAuthExecutionGate(mode==="approved"?full:mode==="production"?{...full,appEnvironment:"production"}:{}),adapter=buildStagingAuthAdapterForGate(gate),result=executeStagingAuthOperationWithAdapter(request(scenarioKey,operation),adapter),diagnostic=["get_session","get_user","get_profile","refresh_session"].includes(operation),traceSteps=buildSafeE2eTraceFromOperationResult(result,{diagnostic,approved:mode==="approved",production:mode==="production"});return{scenarioKey,operation,status:result.status,traceId:createStagingAuthE2eTraceId(scenarioKey),requestId:result.requestId,traceSteps,layersExpected:10,layersReached:traceSteps.filter(x=>x.status!=="skipped_safely").length,bypassDetected:false,sensitiveDataReturned:false,completeEmailExposed:false,rawFormDataExposed:false,rawEnvironmentExposed:false,sessionCreated:false,cookieUsed:false,redirectExecuted:false,emailSent:false,databaseMutation:false,realActionExecuted:false,productionBlocked:true}}
export const buildSignInDefaultBlockedScenario=()=>scenario("sign_in_default_blocked","sign_in");export const buildSignInApprovedSimulationScenario=()=>scenario("sign_in_approved_simulation","sign_in","approved");export const buildPasswordResetBlockedScenario=()=>scenario("password_reset_default_blocked","request_password_reset");export const buildInvitationBlockedScenario=()=>scenario("invitation_default_blocked","accept_invitation");export const buildSignOutBlockedScenario=()=>scenario("sign_out_default_blocked","sign_out");export const buildSessionBlockedScenario=()=>scenario("get_session_default_blocked","get_session");export const buildUserBlockedScenario=()=>scenario("get_user_default_blocked","get_user");export const buildProfileBlockedScenario=()=>scenario("get_profile_default_blocked","get_profile");export const buildRefreshBlockedScenario=()=>scenario("refresh_session_default_blocked","refresh_session");export const buildProductionSignInBlockedScenario=()=>scenario("production_sign_in_blocked","sign_in","production");
const builders=[buildSignInDefaultBlockedScenario,buildSignInApprovedSimulationScenario,buildPasswordResetBlockedScenario,buildInvitationBlockedScenario,buildSignOutBlockedScenario,buildSessionBlockedScenario,buildUserBlockedScenario,buildProfileBlockedScenario,buildRefreshBlockedScenario,buildProductionSignInBlockedScenario];
export function buildStagingAuthE2eLayerMatrix(scenarios:StagingAuthE2eScenarioResult[]){return scenarios.map(x=>({scenarioKey:x.scenarioKey,layers:x.traceSteps.map(step=>step.layer)}))}
export function buildStagingAuthE2eCoverage(scenarios:StagingAuthE2eScenarioResult[]):StagingAuthE2eCoverage{return{scenariosExpected:10,scenariosGenerated:scenarios.length,layersExpected:10,operationsCovered:[...new Set(scenarios.map(x=>x.operation))],publicFormsCovered:4,diagnosticOperationsCovered:4,productionScenarioCovered:scenarios.some(x=>x.scenarioKey==="production_sign_in_blocked"),bypassChecksPassed:scenarios.every(x=>validateNoLayerBypass(x.traceSteps))}}
export function buildStagingAuthE2ePreview():StagingAuthE2ePreview{const scenarios=builders.map(build=>build()),coverage=buildStagingAuthE2eCoverage(scenarios);return{scenarios,layerMatrix:buildStagingAuthE2eLayerMatrix(scenarios),coverage,blockers:[...new Set(scenarios.flatMap(x=>x.traceSteps.flatMap(step=>step.blockerKeys)))],safety:{supabaseImports:0,supabaseCalls:0,authCalls:0,sessionsCreated:0,cookiesRead:0,cookiesSet:0,redirectsExecuted:0,databaseReads:0,databaseWrites:0,auditWrites:0,rateLimitStoreWrites:0,emailSends:0,sqlStatementsExecuted:0,migrationsExecuted:0,rlsPoliciesExecuted:0,middlewareEnforced:false,openAiCalls:0,productionBlocked:true}}}
export function validateStagingAuthE2ePreview(preview:StagingAuthE2ePreview){return preview.scenarios.length===10&&preview.coverage.scenariosGenerated===10&&preview.coverage.bypassChecksPassed&&preview.scenarios.every(x=>validateNoSensitiveDataInTrace(x.traceSteps)&&!x.realActionExecuted&&x.productionBlocked)&&preview.safety.productionBlocked}

