import {buildStagingAuthExecutionGate} from "./stagingAuthExecutionGate";
import {buildCurrentStagingAuthExecutionGate} from "./stagingAuthExecutionGateRuntime";
import type {StagingAuthExecutionGate,StagingAuthGateInput} from "./stagingAuthExecutionGateTypes";
import type {StagingAuthPreflightCapabilitySummary,StagingAuthPreflightMode,StagingAuthPreflightReport,StagingAuthPreflightStatus} from "./stagingAuthPreflightTypes";
const approved:StagingAuthGateInput={appEnvironment:"staging",authMode:"staging_approved",stagingAuthEnabled:true,stagingAuthApproved:true,productionAuthEnabled:false,evidencePackAvailable:true,runbookAvailable:true,stagingBackupConfirmed:true,migrationReviewed:true,rlsReviewed:true,ownershipApproved:true,rollbackApproved:true};
export function buildCapabilitySummary(gate:StagingAuthExecutionGate):StagingAuthPreflightCapabilitySummary{const allowedCapabilities=gate.capabilityDecisions.filter(x=>x.allowed).map(x=>x.capability),blockedCapabilities=gate.capabilityDecisions.filter(x=>!x.allowed).map(x=>x.capability);return{total:gate.capabilityDecisions.length,allowed:allowedCapabilities.length,blocked:blockedCapabilities.length,allowedCapabilities,blockedCapabilities}}
const reportStatus=(gate:StagingAuthExecutionGate):StagingAuthPreflightStatus=>gate.status==="ready_for_staging_implementation"?"ready_for_staging_implementation":gate.status==="production_blocked"?"production_blocked":gate.status==="invalid_configuration"?"invalid_configuration":"blocked";
export function buildStagingAuthPreflightReport(gate:StagingAuthExecutionGate,mode:StagingAuthPreflightMode):StagingAuthPreflightReport{return{id:"staging-auth-preflight-v1",generatedAt:new Date().toISOString(),mode,status:reportStatus(gate),environment:gate.environment,authMode:gate.mode,globallyAllowed:gate.globallyAllowed,capabilitySummary:buildCapabilitySummary(gate),blockers:[...gate.blockers],warnings:[...gate.warnings],nextActions:[...gate.nextActions],productionBlocked:true,simulationOnly:mode!=="current_safe_flags",safety:{rawEnvironmentValuesExposed:false,secretValuesInspected:false,environmentFilesModified:false,commandsExecuted:0,supabaseCalls:0,authCalls:0,sqlStatementsExecuted:0,migrationsExecuted:0,rlsPoliciesExecuted:0,middlewareCreated:false,middlewareEnforced:false,sessionsCreated:0,cookiesRead:0,cookiesSet:0,databaseWrites:0,approvalDbWrites:0,emailSends:0,openAiCalls:0,productionBlocked:true}}}
export const buildCurrentSafePreflightReport=()=>buildStagingAuthPreflightReport(buildCurrentStagingAuthExecutionGate(),"current_safe_flags");
export const buildEmptyConfigurationPreflight=()=>buildStagingAuthPreflightReport(buildStagingAuthExecutionGate({}),"empty_configuration");
export const buildLocalPreflightSimulation=()=>buildStagingAuthPreflightReport(buildStagingAuthExecutionGate({...approved,appEnvironment:"local"}),"local_simulation");
export const buildTestPreflightSimulation=()=>buildStagingAuthPreflightReport(buildStagingAuthExecutionGate({...approved,appEnvironment:"test"}),"test_simulation");
export const buildProductionPreflightSimulation=(productionAuthEnabled=false)=>buildStagingAuthPreflightReport(buildStagingAuthExecutionGate({...approved,appEnvironment:"production",productionAuthEnabled}),"production_simulation");
export const buildStagingRequestedPreflightSimulation=()=>buildStagingAuthPreflightReport(buildStagingAuthExecutionGate({...approved,authMode:"staging_requested",stagingAuthApproved:false}),"staging_requested_simulation");
export const buildIncompleteStagingPreflightSimulation=()=>buildStagingAuthPreflightReport(buildStagingAuthExecutionGate({...approved,evidencePackAvailable:false,stagingBackupConfirmed:false,migrationReviewed:false,rlsReviewed:false,ownershipApproved:false,rollbackApproved:false}),"incomplete_staging_simulation");
export const buildFullyApprovedStagingPreflightSimulation=()=>buildStagingAuthPreflightReport(buildStagingAuthExecutionGate(approved),"fully_approved_staging_simulation");
export function validateStagingAuthPreflightReport(report:StagingAuthPreflightReport){const issues:string[]=[];if(report.capabilitySummary.total!==10)issues.push("capability_count_invalid");if(!report.productionBlocked||!report.safety.productionBlocked)issues.push("production_not_blocked");if(report.safety.environmentFilesModified||report.safety.approvalDbWrites!==0)issues.push("preflight_safety_invalid");if(report.safety.rawEnvironmentValuesExposed||report.safety.secretValuesInspected)issues.push("unsafe_value_exposure");return{valid:issues.length===0,issues}}


