import Link from "next/link";import {buildStagingAuthExecutionGate} from "../../../lib/stagingAuthExecutionGate";import {STAGING_AUTH_ENVIRONMENT_CONTRACT} from "../../../lib/stagingAuthEnvironmentContract";
const card="rounded-2xl border border-slate-800 bg-[#0B0F16] p-5",badge="rounded-full border border-slate-700 px-3 py-1 text-xs",label=(x:string)=>x.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const full={appEnvironment:"staging" as const,authMode:"staging_approved" as const,stagingAuthEnabled:true,stagingAuthApproved:true,productionAuthEnabled:false,evidencePackAvailable:true,runbookAvailable:true,stagingBackupConfirmed:true,migrationReviewed:true,rlsReviewed:true,ownershipApproved:true,rollbackApproved:true};
export default function StagingExecutionGatePage(){const gate=buildStagingAuthExecutionGate(),examples=[buildStagingAuthExecutionGate(),buildStagingAuthExecutionGate({appEnvironment:"local",authMode:"preview"}),buildStagingAuthExecutionGate({...full,appEnvironment:"production"}),buildStagingAuthExecutionGate({appEnvironment:"staging",authMode:"staging_requested",stagingAuthEnabled:true}),buildStagingAuthExecutionGate(full)];return <main className="min-h-screen bg-[#05070A] text-slate-100"><header className="border-b border-slate-800 px-6 py-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap gap-2">{["Locked by default","Server-side gate","No secret values","No Supabase calls","Production blocked"].map(x=><span className={badge} key={x}>{x}</span>)}</div><h1 className="mt-5 text-4xl font-semibold">Staging Auth Execution Gate</h1><p className="mt-2 text-slate-300">Review the server-side conditions that must pass before any staging authentication capability can be implemented or executed.</p></div></header><div className="mx-auto max-w-7xl space-y-8 px-6 py-8">
<section className={card}><h2 className="text-xl font-semibold">Overall gate state</h2><p className="mt-3">Status: {gate.status} · Globally allowed: no · Environment: {gate.environment} · Auth mode: {gate.mode} · Staging enabled: no · Staging approved: no · Production blocked: yes</p></section>
<section><h2 className="text-xl font-semibold">Required safe flags</h2><p className="mt-2 text-amber-200">Only normalized non-secret states are shown. Raw values are never displayed.</p><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Variable","Category","Expected value","Current preview","Missing behavior"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{STAGING_AUTH_ENVIRONMENT_CONTRACT.map(x=><tr className="border-t border-slate-800" key={x.name}><td className="p-3 font-mono">{x.name}</td><td>{x.category}</td><td>{x.expectedValues.join(" | ")}</td><td>missing / false</td><td>{x.missingBehavior}</td></tr>)}</tbody></table></div></section>
<section><h2 className="text-xl font-semibold">Capability matrix</h2><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Capability","Allowed","Status","Blockers","Required evidence","Staging only","Production protected"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{gate.capabilityDecisions.map(x=><tr className="border-t border-slate-800" key={x.capability}><td className="p-3">{label(x.capability)}</td><td>No</td><td>{x.status}</td><td>{x.blockers.join(", ")}</td><td>{x.requiredEvidence.join(", ")}</td><td>Yes</td><td>Yes</td></tr>)}</tbody></table></div></section>
<section><h2 className="text-xl font-semibold">Blockers</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{gate.blockers.map(x=><article className={card} key={x}><h3>{label(x)}</h3><p className="text-sm text-slate-400">Resolve through manual staging evidence and approval. Production remains blocked.</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Safe evaluation examples</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{[["Default/missing configuration",examples[0]],["Local preview",examples[1]],["Production",examples[2]],["Staging requested without approval",examples[3]],["Fully approved staging simulation",examples[4]]].map(([name,value])=>{const x=value as ReturnType<typeof buildStagingAuthExecutionGate>;return <article className={card} key={String(name)}><h3>{String(name)}</h3><p className="mt-2 text-sm">{x.status} · Allowed capabilities: {x.capabilityDecisions.filter(d=>d.allowed).length}</p><p className="mt-2 text-xs text-slate-400">Pure simulation only. No real action executed.</p></article>})}</div></section>
<section className={card}><h2 className="text-xl font-semibold">Preflight CLI</h2><p className="mt-2 text-sm text-slate-400">Preflight available: yes � Default current configuration expected to remain blocked � Production blocked</p><div className="mt-4 grid gap-2">{["npm run staging-auth:preflight","npm run staging-auth:preflight -- --json","npm run staging-auth:preflight -- --strict","npm run staging-auth:preflight -- --simulate-approved"].map(command=><code className="rounded-lg bg-slate-950 p-3 text-cyan-200" key={command}>{command}</code>)}</div><p className="mt-3 text-xs text-amber-200">Display only � No real actions � Simulations do not enable auth � Strict mode only changes the exit code</p></section><section className={card}><h2 className="text-xl font-semibold">Links</h2><div className="mt-4 flex flex-wrap gap-4">{[["Staging Readiness","/admin/staging-readiness"],["Staging Evidence","/admin/staging-evidence"],["Staging Runbook","/admin/staging-runbook"],["Platform Readiness","/admin/platform-readiness"]].map(([a,b])=><Link className="text-cyan-300" href={b} key={b}>{a}</Link>)}</div></section>
<section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-semibold">Safety panel</h2><p className="mt-2 text-sm">Raw environment values exposed: no · Secret values inspected: no · Environment files modified: no · Supabase calls: 0 · Commands executed: 0 · SQL/migrations/RLS executed: 0 · Middleware created: no · Sessions/cookies: 0 · DB writes: 0 · Emails: 0 · OpenAI calls: 0 · Production blocked: yes</p></section></div></main>}

