import Link from "next/link";import {buildStagingImplementationReadinessReport} from "../../../lib/stagingImplementationReadiness";
const card="rounded-2xl border border-slate-800 bg-[#0B0F16] p-5",badge="rounded-full border border-slate-700 px-3 py-1 text-xs";
export default function StagingReadinessPage(){const r=buildStagingImplementationReadinessReport();return <main className="min-h-screen bg-[#05070A] text-slate-100"><header className="border-b border-slate-800 px-6 py-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap gap-2">{["Read-only","No secret values","No Supabase calls","No SQL execution","Production blocked"].map(x=><span className={badge} key={x}>{x}</span>)}</div><h1 className="mt-5 text-4xl font-semibold">Staging Implementation Readiness</h1><p className="mt-2 text-slate-300">Verify environment separation, SQL review, ownership rules, smoke tests, rollback evidence, and approval gates before real auth implementation.</p></div></header><div className="mx-auto max-w-7xl space-y-8 px-6 py-8">
<section className={card}><h2 className="text-xl font-semibold">Staging Auth Adapter available</h2><p className="mt-3">Default provider disabled � Real provider not implemented � Production blocked</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-auth-adapter">Open Auth Adapter</Link></section><section className={card}><h2 className="text-xl font-semibold">Staging Auth Preflight CLI available</h2><p className="mt-3">Execution gate remains authoritative � Implementation not started � Production blocked</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-execution-gate">Open preflight guidance</Link></section><section className={card}><h2 className="text-xl font-semibold">Execution gate available</h2><p className="mt-3">Locked by default � Manual evidence and approval required.</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-execution-gate">Open Execution Gate</Link></section><section className={card}><h2 className="text-xl font-semibold">Staging runbook available</h2><p className="mt-3">Manual evidence and approval still required.</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-runbook">Open Staging Runbook</Link></section><section className={card}><h2 className="text-xl font-semibold">Evidence & Approval Pack available</h2><p className="mt-3">Manual approvals pending � Staging implementation approved: no</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-evidence">Open Staging Evidence</Link></section><section className={card}><h2 className="text-xl font-semibold">Executive summary</h2><p className="mt-3">Status: {r.status} · Dedicated staging: not confirmed · SQL review: required · Ownership approval: required · Rollback: requires confirmation · Implementation approval: blocked · Production blocked</p></section>
<section><h2 className="text-xl font-semibold">Environment readiness</h2><p className="mt-2 text-amber-200">Secret values are intentionally not inspected or displayed.</p><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Variable","Category","Required","Expected location","Status","Safety note"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{r.environmentVariables.map(v=><tr className="border-t border-slate-800" key={v.key}><td className="p-3 font-mono">{v.key}</td><td>{v.category}</td><td>{v.requiredForStaging?"Yes":"No"}</td><td>{v.expectedLocation}</td><td>{v.presenceStatus}</td><td>{v.safetyNotes.join(" ")}</td></tr>)}</tbody></table></div></section>
<section><h2 className="text-xl font-semibold">SQL artifact inventory</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.sqlArtifacts.map(a=><article className={card} key={a.artifactKey}><h3 className="font-semibold">{a.label}</h3><p className="mt-2 text-sm">{a.category} · preview {a.previewAvailable?"available":"missing"} · manually reviewed: no · execution: Not executed</p><p className="mt-2 break-all text-xs text-slate-500">SHA-256: {a.fingerprint||"unavailable"}</p><Link className="mt-3 inline-block text-cyan-300" href={a.route}>Open preview</Link></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Role and ownership matrix</h2><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Role</th><th>Default portal</th><th>Scope</th><th>Ownership</th><th>Status</th><th>Planned tests</th></tr></thead><tbody>{r.roleOwnershipRequirements.map(x=><tr className="border-t border-slate-800" key={x.role}><td className="p-3">{x.role}</td><td>{x.expectedPortal}</td><td>{x.expectedOrganizationScope}</td><td>candidate {x.candidateOwnershipRequired?"yes":"no"}; client {x.clientOwnershipRequired?"yes":"no"}; recruiter org {x.recruiterOrganizationRequired?"yes":"no"}</td><td>{x.implementationStatus}</td><td>{x.testCases.join("; ")}</td></tr>)}</tbody></table></div></section>
<section><h2 className="text-xl font-semibold">Auth implementation requirements</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{r.authImplementationRequirements.map(x=><article className={card} key={x.requirementKey}><h3>{x.label}</h3><p className="mt-2 text-sm text-amber-200">{x.currentStatus}</p><p className="text-xs text-slate-400">{x.requiredEvidence.join("; ")}</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Smoke-test matrix</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.smokeTests.map(x=><article className={card} key={x.testKey}><h3 className="font-semibold">{x.role}</h3><p className="mt-2 text-sm">{x.startingRoute} → {x.expectedRoute}</p><p className="text-xs text-slate-400">Allowed: {x.expectedAccess.join(", ")} · Denied: {x.expectedDeniedRoutes.join(", ")} · Manual: not started · DB mutation: no</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Rollback readiness</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.rollbackRequirements.map(x=><article className={card} key={x.rollbackKey}><h3>{x.label}</h3><p className="text-sm text-slate-400">{x.evidenceStatus} · {x.rollbackAction} · Manual approval required</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Go/No-Go checklist</h2><div className="mt-4 space-y-3">{r.goNoGoGates.map(g=><article className={card} key={g.gateKey}><b>{g.label}</b> · {g.status} · Owner: {g.approvalOwner}<p className="text-sm text-slate-400">{g.evidence.join("; ")||g.blockerReason}</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Blocking issues</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.blockers.map(b=><article className={card} key={b.blockerKey}><span className={badge}>{b.severity}</span><h3 className="mt-3 font-semibold">{b.title}</h3><p className="text-sm text-slate-400">Blocks staging implementation and production. {b.remediation}</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Next actions</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.nextActions.map(a=><article className={card} key={a.actionKey}><span className={badge}>{a.priority}</span><h3 className="mt-3">{a.label}</h3><p className="text-sm text-slate-400">{a.reason}</p>{a.route&&<Link className="text-cyan-300" href={a.route}>Open preview</Link>}</article>)}</div></section>
<section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-semibold">Safety panel</h2><p className="mt-2 text-sm">No secret values inspected · No environment files modified · No Supabase calls · No SQL/migration/RLS executed · No middleware created · No sessions/cookies · No DB writes · No email sends · No OpenAI calls · Production blocked</p></section></div></main>}


