import { createClient } from "@supabase/supabase-js";
import { executeQuickFixSubsetApply } from "../lib/quickFixApplySubsetExecutor";
import { quickFixSubsetApplyModeFromFlags } from "../lib/quickFixApplySubsetValidator";
import { loadCliEnv, printSupabaseEnvDiagnostics } from "../lib/cliEnv";
function argValue(name:string,fallback=""){const p=`--${name}=`;return process.argv.find((a)=>a.startsWith(p))?.slice(p.length)||fallback;}
function hasFlag(name:string){return process.argv.includes(`--${name}`)}
function supabaseClient(){const env=loadCliEnv();printSupabaseEnvDiagnostics(env.diagnostics);if(!env.supabaseUrl)throw new Error("Quick fix subset apply failed: missing Supabase URL.");if(!env.supabaseServiceRoleKey){if(env.supabaseAnonKey)throw new Error("Real apply requires SUPABASE_SERVICE_ROLE_KEY. Anon key is not allowed for candidate DB writes.");throw new Error("Quick fix subset apply failed: missing SUPABASE_SERVICE_ROLE_KEY.");}return createClient(env.supabaseUrl,env.supabaseServiceRoleKey);}
async function main(){const write=hasFlag("writeCandidateUpdates");const confirm=hasFlag("confirmApplySubset");const mode=quickFixSubsetApplyModeFromFlags(write,confirm);const subsetPath=argValue("subsetPath","reports/quick-fix-apply-subset.json");if(mode==="dry_run"){const {plan}=await executeQuickFixSubsetApply({subsetPath});console.log("Mode: subset apply preview only; no candidate DB writes");console.log(`Subset items loaded: ${plan.stagedItemsLoaded}`);console.log(`Eligible field updates: ${plan.fieldsEligibleForApply}`);console.log(`Blocked field updates: ${plan.fieldsBlocked}`);console.log(`Conflicts: ${plan.conflictsDetected}`);console.log(`Backup required: ${plan.backupRequired}`);console.log(`Rollback ready: ${plan.rollbackReady}`);console.log(`Would update count: ${plan.wouldUpdateCount}`);console.log(`Would preserve count: ${plan.wouldPreserveCount}`);console.log("Output path: reports/quick-fix-subset-apply-preview.json");return;}console.log("CONFIRMED QUICK FIX SUBSET APPLY. Candidate DB field updates enabled.");const supabase=supabaseClient();const {result,backupPath,rollbackPath,postAuditPath}=await executeQuickFixSubsetApply({subsetPath,writeCandidateUpdates:true,confirmApplySubset:true,updateCandidate:async(id,update)=>{const {error}=await supabase.from("candidates").update(update).eq("id",id);if(error)throw new Error(`Failed to update candidate ${id}: ${error.message}`);}});console.log(`Backup written: ${backupPath}`);console.log(`Rollback written: ${rollbackPath}`);console.log(`Applied field updates: ${result.appliedCount}`);console.log(`Post-audit path: ${postAuditPath}`);}
if (process.argv[1]?.replace(/\\/g,"/").endsWith("scripts/applyQuickFixApplySubset.ts")) main().catch((e)=>{console.error(e instanceof Error?e.message:e);process.exitCode=1});
