import fs from "node:fs";
import path from "node:path";
export const UI_POLISH_CATEGORIES=["navigation consistency","layout spacing","empty states","badge consistency","table/card readability","mobile responsiveness","loading/error states","action clarity","safety labels","recruiter workflow clarity"] as const;
const PAGE_ROUTES=["/recruiter/dashboard","/recruiter/workflow","/recruiter/smart-shortlist","/recruiter/candidate360/[candidateId]","/candidate/self-confirm/[candidateId]","/recruiter/candidate-compare","/recruiter/submission-generator","/recruiter/client-report","/recruiter/import-staging","/recruiter/import-merge"];
const suggestions=[
["navigation consistency","medium","Standardize page titles, back links, and active navigation treatment across recruiter tools."],["navigation consistency","low","Keep candidate-context links visible after moving between compare, submission, and report previews."],["layout spacing","medium","Adopt shared section, card, and form spacing tokens for dense recruiter screens."],["layout spacing","low","Align maximum content widths and header padding across major pages."],["empty states","high","Give every candidate-data section a clear missing, unavailable, or to-be-confirmed state."],["empty states","medium","Add actionable zero-result guidance to shortlist filters and selection tools."],["badge consistency","medium","Unify verification, trust, workflow, risk, and preview badge color semantics."],["badge consistency","low","Standardize badge size, capitalization, and wrapping behavior."],["table/card readability","high","Improve comparison and import tables with responsive overflow, sticky context, and clearer row hierarchy."],["table/card readability","medium","Normalize candidate card field order for faster shortlist scanning."],["mobile responsiveness","high","Verify selection panels, dense forms, matrices, and evidence lists at narrow widths."],["mobile responsiveness","medium","Prevent long IDs, URLs, evidence, and command text from forcing horizontal page overflow."],["loading/error states","medium","Standardize loading, missing-report, candidate-not-found, and API-error panels."],["loading/error states","low","Preserve navigation and retry guidance when read-only data loading fails."],["action clarity","high","Separate primary preview actions from disabled future write/apply actions."],["action clarity","medium","Explain 2�5 candidate requirements next to disabled compare/report actions."],["safety labels","critical","Keep preview-only, no-write, no-email, and no-OpenAI labels visible beside consequential actions."],["safety labels","medium","Use consistent language for import staging and merge-approval boundaries."],["recruiter workflow clarity","high","Reinforce the Dashboard ? Shortlist ? Compare ? Submission ? Client Report sequence."],["recruiter workflow clarity","medium","Clarify when profile quality should be improved through self-confirm or import staging."],
] as const;
export function buildUiPolishBacklog(){const items=suggestions.map(([category,priority,recommendation],index)=>({id:`ui-polish-${String(index+1).padStart(2,"0")}`,category,priority,recommendation,status:"proposed",readOnly:true}));return{generatedAt:new Date().toISOString(),mode:"read-only UI polish backlog audit; no candidate DB writes; no OpenAI calls",pagesReviewed:PAGE_ROUTES.length,pages:PAGE_ROUTES,categories:[...UI_POLISH_CATEGORIES],items,suggestedPolishItems:items.length,criticalPolishItems:items.filter(item=>item.priority==="critical").length,recommendedNextUiMilestone:"visual-polish-v1",candidateDbWrites:0,workflowWrites:0,openAiCalls:0};}
async function main(){const report=buildUiPolishBacklog();fs.writeFileSync(path.join(process.cwd(),"reports","ui-polish-backlog.json"),`${JSON.stringify(report,null,2)}\n`);console.log(`Mode: ${report.mode}`);console.log(`Pages reviewed: ${report.pagesReviewed}`);console.log(`Suggested polish items: ${report.suggestedPolishItems}`);console.log(`Critical polish items: ${report.criticalPolishItems}`);console.log(`Recommended next UI milestone: ${report.recommendedNextUiMilestone}`);}
if(process.argv[1]?.replace(/\\/g,"/").endsWith("scripts/auditUiPolishBacklog.ts"))main().catch(error=>{console.error(error);process.exitCode=1});



