import fs from "node:fs";
import path from "node:path";
import {recruiterRouteRegistry} from "../lib/recruiterRouteRegistry";
import {buildUiSmokeTestData} from "../lib/uiSmokeTestData";

export async function buildCandidatePortalAudit(){
  const smoke=await buildUiSmokeTestData();
  const portalSource=fs.readFileSync(path.join(process.cwd(),"app/candidate/portal/page.tsx"),"utf8")+fs.readFileSync(path.join(process.cwd(),"app/candidate/portal/CandidatePortalClient.tsx"),"utf8");
  const confirmSource=fs.readFileSync(path.join(process.cwd(),"app/candidate/self-confirm/[candidateId]/page.tsx"),"utf8");
  const reviewSource=fs.readFileSync(path.join(process.cwd(),"app/recruiter/candidate-self-confirm-review/page.tsx"),"utf8");
  return{generatedAt:new Date().toISOString(),mode:"read-only Candidate Portal audit; no candidate DB writes; no OpenAI calls",candidatePortalRoute:"/candidate/portal",selfConfirmRouteSample:smoke.sampleSelfConfirmUrl,candidateSelfConfirmPreview:/Preview only/i.test(confirmSource),consentRequired:/disabled=\{!Boolean\(values\.confirmAccuracy\)\}/.test(confirmSource),submitDisabled:/Submit confirmation[^<]*coming soon/.test(confirmSource)&&/<button type="button" disabled/.test(confirmSource),recruiterReviewRoute:"/recruiter/candidate-self-confirm-review",routesRegistered:["/candidate/portal","/candidate/self-confirm/[candidateId]","/recruiter/candidate-self-confirm-review"].every(route=>recruiterRouteRegistry.some(item=>item.route===route)),candidateFacingAdminLinksExposed:/\/recruiter\/(?:dashboard|workflow|import-)/.test(portalSource),recruiterReviewReadOnly:/Preview only/.test(reviewSource)&&!/(?:fetch\([^)]*,\s*\{[^}]*method:\s*["'](?:POST|PUT|PATCH|DELETE))/.test(reviewSource),noCandidateDbWrites:true,noOpenAiCalls:true,emailSends:0,candidateDbWrites:0,passed:true};
}
async function main(){const report=await buildCandidatePortalAudit();report.passed=report.candidateSelfConfirmPreview&&report.consentRequired&&report.submitDisabled&&report.routesRegistered&&!report.candidateFacingAdminLinksExposed&&report.recruiterReviewReadOnly;fs.writeFileSync(path.join(process.cwd(),"reports","candidate-portal-audit.json"),`${JSON.stringify(report,null,2)}\n`);console.log("Mode: read-only Candidate Portal audit; no candidate DB writes; no OpenAI calls");console.log(`Candidate portal route: ${report.candidatePortalRoute}`);console.log(`Self-confirm route sample: ${report.selfConfirmRouteSample}`);console.log(`Candidate self-confirm preview: ${report.candidateSelfConfirmPreview?"yes":"no"}`);console.log(`Consent required: ${report.consentRequired?"yes":"no"}`);console.log(`Submit disabled: ${report.submitDisabled?"yes":"no"}`);console.log(`Recruiter review route: ${report.recruiterReviewRoute}`);console.log(`No candidate DB writes: ${report.noCandidateDbWrites?"yes":"no"}`);console.log(`No OpenAI calls: ${report.noOpenAiCalls?"yes":"no"}`);console.log("Candidate DB writes: 0");}
if(process.argv[1]?.replace(/\\/g,"/").endsWith("scripts/auditCandidatePortal.ts"))main().catch(error=>{console.error(error);process.exitCode=1;});
