import fs from "node:fs";
import path from "node:path";
import { recruiterRouteRegistry } from "../lib/recruiterRouteRegistry";

const PRIMARY=["Dashboard","Shortlist","Compare","Submissions","Reports"];
const ADMIN=["Data Import","Merge Review","Data Workflow","Product Health"];
const CORE_ROUTES=["/recruiter/dashboard","/recruiter/workflow","/recruiter/smart-shortlist","/recruiter/candidate360/[candidateId]","/candidate/self-confirm/[candidateId]","/recruiter/candidate-compare","/recruiter/submission-generator","/recruiter/client-report","/recruiter/import-staging","/recruiter/import-merge"];
const read=(base:string,file:string)=>fs.readFileSync(path.join(base,file),"utf8");
const all=(source:string,values:string[])=>values.every(value=>source.includes(value));

export function buildRoleBasedUxAudit(baseDir=process.cwd()){
  const nav=read(baseDir,"app/recruiter/layout.tsx"),shortlist=read(baseDir,"app/recruiter/smart-shortlist/page.tsx"),compare=read(baseDir,"app/recruiter/candidate-compare/page.tsx"),submissions=read(baseDir,"app/recruiter/submission-generator/page.tsx"),reports=read(baseDir,"app/recruiter/client-report/page.tsx"),dataImport=read(baseDir,"app/recruiter/import-staging/page.tsx"),merge=read(baseDir,"app/recruiter/import-merge/page.tsx"),workflow=read(baseDir,"app/recruiter/workflow/page.tsx");
  const primaryRecruiterNavItems=PRIMARY.filter(label=>nav.includes(`"${label}"`)).length,adminDataNavItems=ADMIN.filter(label=>nav.includes(`"${label}"`)).length;
  const checks={oldTechnicalLabelsHiddenFromPrimaryNav:!["Smart Shortlist","Candidate Compare","Submission Generator","Client Report","Import Staging","Import Merge","Recruiter Workflow"].some(label=>nav.includes(`"${label}"`)),shortlistLoadMoreAvailable:shortlist.includes("Load more candidates")&&shortlist.includes("visibleCount"),selectedCandidateActionsPresent:shortlist.includes("Compare selected")&&shortlist.includes("Create report"),formPagesHelperTextPresent:[compare,submissions,reports].every(source=>source.includes("Best flow: choose")&&source.includes("Open Shortlist")),adminDataPagesLabeled:all(dataImport,["Data Import","Admin / Data"])&&all(merge,["Merge Review","Admin / Data"])&&all(workflow,["Data Workflow","Admin / Data"]),routesBackwardCompatible:CORE_ROUTES.every(route=>recruiterRouteRegistry.some(item=>item.route===route))};
  const shortlistInitialRenderLimit=Number(shortlist.match(/SHORTLIST_INITIAL_RENDER_LIMIT\s*=\s*(\d+)/)?.[1]||0);
  return{generatedAt:new Date().toISOString(),mode:"read-only Role-Based UX audit; no candidate DB writes; no OpenAI calls",primaryRecruiterNavItems,adminDataNavItems,...checks,shortlistInitialRenderLimit,noOpenAiCalls:true,candidateDbWrites:0,workflowWrites:0,passed:primaryRecruiterNavItems===5&&adminDataNavItems===4&&shortlistInitialRenderLimit===30&&Object.values(checks).every(Boolean)};
}

async function main(){const report=buildRoleBasedUxAudit();fs.writeFileSync(path.join(process.cwd(),"reports","role-based-ux-audit.json"),`${JSON.stringify(report,null,2)}\n`);console.log(`Mode: ${report.mode}`);console.log(`Primary recruiter nav items: ${report.primaryRecruiterNavItems}`);console.log(`Admin/data nav items: ${report.adminDataNavItems}`);console.log(`Old technical labels hidden from primary nav: ${report.oldTechnicalLabelsHiddenFromPrimaryNav?"yes":"no"}`);console.log(`Shortlist initial render limit: ${report.shortlistInitialRenderLimit}`);console.log(`Shortlist load more available: ${report.shortlistLoadMoreAvailable?"yes":"no"}`);console.log(`Selected candidate actions present: ${report.selectedCandidateActionsPresent?"yes":"no"}`);console.log(`Form pages helper text present: ${report.formPagesHelperTextPresent?"yes":"no"}`);console.log(`Admin/data pages labeled: ${report.adminDataPagesLabeled?"yes":"no"}`);console.log(`Routes backward-compatible: ${report.routesBackwardCompatible?"yes":"no"}`);console.log("No OpenAI calls: yes");console.log("Candidate DB writes: 0");if(!report.passed)process.exitCode=1;}
if(process.argv[1]?.replace(/\\/g,"/").endsWith("scripts/auditRoleBasedUx.ts"))main().catch(error=>{console.error(error);process.exitCode=1});
