import assert from "node:assert/strict";import fs from "node:fs";import { buildCandidate360Profile } from "../lib/candidate360Profile";import { buildCandidateCompareResult } from "../lib/candidateCompare";import { normalizeCandidateCompareRequest } from "../lib/candidateCompareRequest";
const candidate=(id:string,data:any,metadata:any={})=>buildCandidate360Profile({id,name:id,...data,candidate360_fields:metadata},{currentStatus:"ready_for_shortlist"});
const strong=candidate("strong",{current_title:"Senior SAP Consultant",current_company:"Acme",location:"Singapore",years_of_experience:8,sap_modules:["FI","CO"],tech_skills:["SAP","TypeScript"],work_experience:[{title:"SAP Consultant",company:"Acme"}]},{currentTitle:{value:"Senior SAP Consultant",source:"recruiter_approved"},currentCompany:{value:"Acme",source:"candidate_confirmed"}});
const weak=candidate("weak",{current_title:"Analyst",tech_skills:["Excel"]});
const base={candidateIds:["strong","weak"],mustHaveSkills:["SAP"],requiredModules:["FI"],minYearsExperience:5,roleSeniority:"Senior",roleLocation:"Singapore"};
const result=buildCandidateCompareResult(normalizeCandidateCompareRequest(base),[weak,strong]);assert.equal(result.candidates[0].candidateId,"strong");assert.ok(result.candidates[0].overallScore>result.candidates[1].overallScore);assert.ok(result.candidates[1].gaps.some(item=>item.includes("0/1 required skills")));assert.ok(result.candidates[1].risks.some(item=>item.code==="missing_currentCompany"));
const noNice=buildCandidateCompareResult(normalizeCandidateCompareRequest({...base,niceToHaveSkills:[]}),[strong,weak]).candidates.find(item=>item.candidateId==="strong")!;const nice=buildCandidateCompareResult(normalizeCandidateCompareRequest({...base,niceToHaveSkills:["typescript"]}),[strong,weak]).candidates.find(item=>item.candidateId==="strong")!;assert.ok(nice.dimensionScores.find(item=>item.dimension==="skills_match")!.score>=noNice.dimensionScores.find(item=>item.dimension==="skills_match")!.score);
const neutral=buildCandidateCompareResult(normalizeCandidateCompareRequest({candidateIds:["strong","weak"]}),[strong,weak]);assert.equal(neutral.candidates[0].dimensionScores.find(item=>item.dimension==="module_match")?.neutral,true);
assert.ok(result.candidates[0].dimensionScores.find(item=>item.dimension==="verification_trust")!.score>result.candidates[1].dimensionScores.find(item=>item.dimension==="verification_trust")!.score);
assert.ok(result.candidates[0].evidence.every(item=>["techSkills","sapModules","yearsOfExperience","currentTitle","location"].includes(item.fieldName)));assert.ok(result.candidates[0].evidence.find(item=>item.fieldName==="techSkills")?.value.toLowerCase().split(", ").every(skill=>["sap","typescript"].includes(skill)));assert.ok(!result.candidates[1].evidence.some(item=>item.value.toLowerCase().includes("sap")),"does not hallucinate missing SAP evidence");
for(const file of ["lib/candidateCompare.ts","lib/candidateCompareData.ts","app/api/recruiter/candidate-compare/route.ts"]){const source=fs.readFileSync(file,"utf8");assert.doesNotMatch(source,/\.insert\(|\.update\(|\.upsert\(|\.delete\(|openai\./i);}
const shortlist=fs.readFileSync("app/recruiter/smart-shortlist/page.tsx","utf8");assert.match(shortlist,/candidate-compare\?candidateIds=/);assert.match(shortlist,/selected\.length\s*>=\s*2|selected\.length<2/);
console.log("candidateCompare.test.ts passed");
