import assert from "node:assert/strict";
import fs from "node:fs";import os from "node:os";import path from "node:path";
import { loadCliEnv, printSupabaseEnvDiagnostics } from "../lib/cliEnv";
import { quickFixSubsetApplyModeFromFlags } from "../lib/quickFixApplySubsetValidator";
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"cli-env-"));
fs.writeFileSync(path.join(tmp,".env.local"),"NEXT_PUBLIC_SUPABASE_URL=https://example.supabase.co\nNEXT_PUBLIC_SUPABASE_ANON_KEY=anon-secret\nSUPABASE_SERVICE_ROLE_KEY=service-secret\n");
const old={...process.env};
delete process.env.NEXT_PUBLIC_SUPABASE_URL;delete process.env.SUPABASE_URL;delete process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;delete process.env.SUPABASE_ANON_KEY;delete process.env.SUPABASE_SERVICE_ROLE_KEY;
let env=loadCliEnv({cwd:tmp,mutateProcessEnv:false});
assert.equal(env.diagnostics.hasSupabaseUrl,true,"loads .env.local sample");
assert.equal(env.diagnostics.sources.NEXT_PUBLIC_SUPABASE_URL,".env.local","source is env local");
process.env.NEXT_PUBLIC_SUPABASE_URL="https://process.supabase.co";
env=loadCliEnv({cwd:tmp,mutateProcessEnv:false});
assert.equal(env.supabaseUrl,"https://process.supabase.co","process.env takes precedence");
let printed="";const oldLog=console.log;console.log=(value:any)=>{printed+=String(value)+"\n"};printSupabaseEnvDiagnostics(env.diagnostics);console.log=oldLog;
assert.equal(printed.includes("service-secret"),false,"no env values printed");
assert.equal(printed.includes("anon-secret"),false,"no anon values printed");
assert.equal(quickFixSubsetApplyModeFromFlags(false,false),"dry_run","dry-run not requiring service role");
assert.throws(()=>quickFixSubsetApplyModeFromFlags(true,false),/confirmApplySubset/,"real apply still requires confirmation flags");
process.env={...old};
console.log("CLI env tests passed");
