import assert from 'node:assert/strict';
import { normalizeActualCandidateSchema } from '../lib/candidate360SchemaNormalize';
const jobs = (raw_text: string) => normalizeActualCandidateSchema({raw_text}).enterpriseProfile.employmentTimeline;
const ledger = 'EMPLOYMENT HISTORY 02 Feb 2025 to 26 Sep 2025 Example Advisory – Senior FI Consultant (Contract) Sept 2022 to date 30 Apr 2023 Example Systems – Senior FICO Consultant (Contract) Page 2 of 2 EMPLOYMENT HISTORY Apr 1994 – July 1998 Example Telecom - Payphone Division (subsidiary of Example Holdings) - Assistant Manager - Financial System (Permanent)';
const rows = jobs(ledger);
assert.equal(rows.length, 3);
assert.equal(rows[0].company, 'Example Advisory');
assert.equal(rows[0].start, '02 Feb 2025');
assert.equal(rows[1].end, '30 Apr 2023');
assert.equal(rows[1].current, false);
assert.equal(rows[2].company, 'Example Telecom - Payphone Division (subsidiary of Example Holdings)');
assert.equal(rows[2].title, 'Assistant Manager - Financial System');
assert.ok(rows.every(j => j.provenance?.length));
const pipes = jobs('EMPLOYMENT HISTORY  Jun 10 – present | Example Systems | Senior Consultant  Aug 08 – Jan 10 | Example Services | Application Specialist QUALIFICATIONS Degree WORK EXPERIENCE Company: Example Systems Project: Example Client Duration: Jan 2000 - Jan 2001');
assert.equal(pipes.length, 2);
assert.equal(pipes[0].start, 'Jun 2010');
assert.equal(pipes[1].end, 'Jan 2010');
const mixed = jobs('Employment History Date Company Name Role Jan 2014 – Present Example Data ABAP Technical Consultant Dec 2010 –2013 Example Systems ABAP Technical Consultant Sep 2008 – 2010 Example Computing Application Developer Qualifications');
assert.equal(mixed.length, 3);
assert.equal(mixed[0].company, 'Example Data');
assert.equal(mixed[0].title, 'ABAP Technical Consultant');
assert.equal(mixed[1].end, '2013');
assert.equal(mixed[2].title, 'Application Developer');
assert.equal(jobs(ledger.replaceAll('EMPLOYMENT HISTORY', 'PROJECT HISTORY')).length, 0);
assert.equal(jobs('EMPLOYMENT HISTORY Jan 2020 – Jan 2021 Client Example Systems – Senior Consultant (Contract)').length, 0);
assert.equal(jobs('EMPLOYMENT HISTORY Jan 2023 – Jan 2020 Example Systems – Senior Consultant (Contract)').length, 0);
assert.equal(jobs('EMPLOYMENT HISTORY Jan 2020 – Jan 2021 Example Systems – Senior Consultant (Contract) Responsibilities: Implement SAP for Example Customer').length, 0);
const columnMajor = jobs('Employment History Date Company Name Role 2020 – 2021 2018 – 2019 Example Systems Example Services SAP Consultant SAP Analyst Education');
assert.equal(columnMajor.length, 0);
console.log('Dated employment ledgers, mixed date precision and employer-role boundaries: passed');
