import assert from 'node:assert/strict';
import fs from 'node:fs';
import { normalizeActualCandidateSchema } from '../lib/candidate360SchemaNormalize';
const fixture = JSON.parse(fs.readFileSync(new URL('./fixtures/employment-date-company-role.json', import.meta.url), 'utf8'));
const profile = normalizeActualCandidateSchema(fixture).enterpriseProfile;
assert.equal(profile.employmentTimeline.length, 6);
assert.equal(profile.employmentTimeline[0].company, 'Example Consulting');
assert.equal(profile.employmentTimeline[0].start, 'Apr 2023');
assert.equal(profile.employmentTimeline[0].title, '');
assert.equal(profile.employmentTimeline.filter(x => x.company === 'Example Consulting').length, 2);
assert.equal(profile.employmentTimeline.find(x => x.start === 'Oct 2012')?.company, 'Example Systems');
assert.equal(profile.employmentTimeline.find(x => x.start === 'Dec 2015')?.company, 'Example Delivery');
assert.ok(profile.employmentTimeline.every(x => !/Example Client/.test(x.company)));
assert.equal(profile.education[0].institution, 'University of Example City');
assert.equal(profile.education[0].fieldOfStudy, 'Computerized Accounting');
assert.equal(profile.education[0].startYear, '2001');
assert.equal(profile.education[0].endYear, '2005');
const projectsOnly = normalizeActualCandidateSchema({raw_text: fixture.raw_text.replace('EXPERINCE Date', 'RELEVANT PROJECT EXPERINCE Date')}).enterpriseProfile;
// A project table must never qualify as an employment table.
assert.equal(projectsOnly.employmentTimeline.length, 0);
console.log('Employment table recovery: passed');
const mixed = normalizeActualCandidateSchema({raw_text: 'Employment History Date Company Name Role Nov 20 - present Example Services Senior Consultant Sept 17 – Oct 20 (3 years 1 month) Example Bank Senior Executive (Application Programmer) May 16 – Aug 17 Example School Lecturer Qualifications Selected Project Experience Nov 10 - Present Example Client SAP Consultant'}).enterpriseProfile;
assert.equal(mixed.employmentTimeline.length, 3);
assert.equal(mixed.employmentTimeline[0].company, 'Example Services');
assert.equal(mixed.employmentTimeline[1].company, 'Example Bank');
assert.equal(mixed.employmentTimeline[2].title, 'Lecturer');
const reversed = normalizeActualCandidateSchema({raw_text: 'Employment History Organization Designation Duration Example Systems SAP EWM Consultant May 2021 to Sep 2023 Example Logistics Warehouse executive Aug 2018 to April 2021. Example Client SAP Consultant April 2021 – September 2023 Project # 1 Support Project'}).enterpriseProfile;
assert.equal(reversed.employmentTimeline.length, 2);
assert.ok(reversed.employmentTimeline.every(x=>x.company !== 'Example Client'));
const degrees = normalizeActualCandidateSchema({raw_text: 'Education Master of Business Administration – Example City University, Example Country Bachelor of Science in Accounting – University of Example Town, Example Country'}).enterpriseProfile.education;
assert.equal(degrees.length, 2);
assert.equal(degrees[1].qualification, 'Bachelor of Science in Accounting');
const labels = normalizeActualCandidateSchema({raw_text: "Education Degree: Bachelor's Degree, Information Systems College/University: Example City University Year: 2011 Citizenship Example"}).enterpriseProfile.education;
assert.equal(labels.length, 1);
assert.equal(labels[0].endYear, '2011');
console.log('Mixed employment columns and education boundaries: passed');
const prose = normalizeActualCandidateSchema({raw_text: 'PROFESSIONAL EXPERIENCE Example Systems, Inc. – Package Consultant March 2022 – Present Delivered training and daily support. Example Services Inc. – Senior Consultant February 2017 – February 2020 EDUCATION'}).enterpriseProfile;
assert.equal(prose.employmentTimeline.length, 2);
assert.equal(prose.employmentTimeline[1].company, 'Example Services Inc.');
assert.equal(normalizeActualCandidateSchema({raw_text: 'PROJECT EXPERIENCE Example Client – Senior Consultant February 2017 – February 2020'}).enterpriseProfile.employmentTimeline.length, 0);
console.log('Prose employment headings: passed');
const schoolFirst = normalizeActualCandidateSchema({raw_text: 'Education Example City University，2015 - 2017 - Master of Business Administration - MBA, GPA 4.0 - Student club Example Town University，2011 - 2015 - Bachelor of Business Administration - BBA'}).enterpriseProfile.education;
assert.equal(schoolFirst.length, 1);
assert.equal(schoolFirst[0].institution, 'Example City University');
assert.equal(schoolFirst[0].startYear, '2015');
console.log('School-first boundary: passed');
const titleBoundaries = normalizeActualCandidateSchema({raw_text: 'Employment History Date Company Name Role Nov 08 – Jul 09 Example Energy SAP FICO Functional Consultant for Global Implementation in multiple countries. Sep 99 – Oct 05 Example Paper SAP COPC Functional Consultant and Team Lead for SAP Implementation project in multiple mills. EDUCATION'}).enterpriseProfile.employmentTimeline;
assert.equal(titleBoundaries[0].title, 'SAP FICO Functional Consultant');
assert.equal(titleBoundaries[1].title, 'SAP COPC Functional Consultant and Team Lead');
console.log('Employment title/responsibility separation: passed');
const assignments = normalizeActualCandidateSchema({raw_text: 'RELEVANT PROJECT EXPERIENCE Company client: Example Customer Company: Example Consultancy Duration: Feb 2021 – Mar 2022 Position: Finance Team Responsibilities (Electronic bank statement implementation) Configure the system and conduct testing. ' + 'Gather business requirements and document configuration. '.repeat(30) + 'EDUCATION'}).enterpriseProfile;
assert.equal(assignments.projects.length, 1);
assert.equal(assignments.projects[0].client, 'Example Customer');
assert.equal(assignments.employmentTimeline.length, 0);
console.log('Intact labelled assignment boundary: passed');
const labelled = (body: string) => normalizeActualCandidateSchema({raw_text: `RELEVANT PROJECT EXPERIENCE Company client: Example Customer Company: Example Consultancy Duration: Jan 2013 – Sep 2014 Position: SAP FSCM Consultant Responsibilities: ${body} EDUCATION`}).enterpriseProfile;
const sparseAssignment = labelled('Interface integration with external credit rating agency.');
assert.equal(sparseAssignment.projects.length, 1);
assert.equal(sparseAssignment.projects[0].projectType, '');
assert.equal(sparseAssignment.employmentTimeline.length, 0);
const implementationAssignment = labelled('Implement electronic bank statements. Configure and test interfaces. Provide support after go-live.');
assert.equal(implementationAssignment.projects[0].projectType, 'Implementation');
const supportAssignment = labelled('Monitor SLA and incident tickets. Maintain interface integration.');
assert.equal(supportAssignment.projects[0].projectType, 'Support / Enhancement');
const paginationAssignment = labelled('Page 6 of 8 Configure and test credit management.');
assert.ok(paginationAssignment.projects.every(p => p.responsibilities.every(r => !/Page 6 of 8/.test(r))));
console.log('Assignment existence, lifecycle and pagination boundaries: passed');

const repeatedClient = normalizeActualCandidateSchema({raw_text: 'RELEVANT PROJECT EXPERIENCE Company client: Example Customer Company: Example Consultancy Duration: Jan 2013 – Sep 2014 Position: FSCM Consultant Responsibilities: Interface integration with credit agency. Company client: Example Customer Company: Example Consultancy Duration: Aug 2009 – Dec 2012 Position: FI Consultant Responsibilities: Project implementation and configuration. EDUCATION'}).enterpriseProfile;
assert.equal(repeatedClient.projects.length, 2);
assert.equal(new Set(repeatedClient.projects.map(p => p.id)).size, 2);
assert.equal(labelled('Support and implement change request for SAP Finance. Monitor SLA and incident tickets.').projects[0].projectType, 'Support / Enhancement');
console.log('Repeated client assignment isolation: passed');
const compactSource = (body: string) => normalizeActualCandidateSchema({raw_text: `PROFESSIONAL EXPERIENCE ${body} EDUCATION`}).enterpriseProfile.employmentTimeline;
assert.equal(compactSource('Example Services Sdn. Bhd. Business Consultant April 2023 – Present Responsibilities include support.')[0].company, 'Example Services Sdn. Bhd.');
assert.equal(compactSource('SAP FICO Consultant Example Services, Inc. April 2023 to Present')[0].title, 'SAP FICO Consultant');
assert.equal(compactSource('Example Lawfirm (Feb 2025 – Now) Director Oversee strategy.')[0].current, true);
assert.equal(compactSource('June 2020 – Present SAP S&A Consultant Example Consulting City')[0].company, 'Example Consulting');
assert.equal(compactSource('with expertise in SAP implementation and support.').length, 0);
assert.equal(compactSource('Client Example Services Sdn. Bhd. Business Consultant April 2023 – Present').length, 0);
const standaloneTable = normalizeActualCandidateSchema({raw_text: 'Organization Designation Duration Example Services SAP MM Consultant June 2014 - Now Example Delivery SAP SD Consultant Dec 2012 - May 2014 EDUCATION'}).enterpriseProfile.employmentTimeline;
assert.equal(standaloneTable.length, 2);
assert.equal(standaloneTable[0].company, 'Example Services');
assert.equal(standaloneTable[0].title, 'SAP MM Consultant');
assert.equal(standaloneTable[0].current, true);
console.log('Compact heading orders and standalone employment table: passed');
