import assert from 'node:assert/strict';
import { normalizeActualCandidateSchema } from '../lib/candidate360SchemaNormalize';
const jobs = (raw_text: string) => normalizeActualCandidateSchema({raw_text}).enterpriseProfile.employmentTimeline;
const text = 'Career Summary From August 2018 – Now: SAP FICO senior consultant at Example Joint Venture Corporation company. From June 2014 to August 2018: SAP-ERP Business analyst at Example Bank (EB) in FICO role. From August 2011 to March 2014: SAP-ERP consultant at Example (ERP) as FICO consultant Repeated CV header Professional Experience Project Experience Customer: Another Company';
const rows = jobs(text);
assert.equal(rows.length, 3);
assert.equal(rows[0].company, 'Example Joint Venture Corporation');
assert.equal(rows[1].company, 'Example Bank (EB)');
assert.equal(rows[2].company, 'Example (ERP)');
assert.equal(rows[2].end, 'March 2014');
assert.equal(jobs(text.replace('Career Summary','Project Summary')).length, 0);
assert.equal(jobs('Career Summary From August 2022 to August 2020: SAP Consultant at Example Company.').length, 0);
const table = jobs('Professional Experience: Organization Period Example Japan K.K. Aug 2022 to Present Example Technology India Ltd. Jul 2018 – Aug 2022 Project Experience: SAP FI Lead Consultant | Nov 2025 – Present');
assert.equal(table.length, 2);
assert.equal(table[0].company, 'Example Japan K.K.');
assert.ok(table.every(j => !j.title));
assert.equal(table[1].end, 'Aug 2022');
assert.equal(jobs('Project Experience Organization Period Example Japan K.K. Aug 2022 to Present').length, 0);
console.log('Dated career statements and employer-only period tables: passed');
const numbered = jobs('Work Experience-2 Example Technologies Inc, Data Migration Consultant from March 2025 till 15th Feb 2026. Project Name: Customer Program ORGANISATION Client Systems ROLE Lead Consultant Work Experience-1 Example Services Pvt Ltd Bangalore, India. EIM Package Specialist from Nov-2021 to Aug-2024. Project Name: Another Project');
assert.equal(numbered.length, 2);
assert.equal(numbered[0].company, 'Example Technologies Inc');
assert.equal(numbered[0].end, '15 Feb 2026');
assert.equal(numbered[1].company, 'Example Services Pvt Ltd');
assert.equal(numbered[1].start, 'Nov 2021');
assert.equal(jobs('Project Experience-2 Example Technologies Inc, Data Migration Consultant from March 2025 till Feb 2026.').length, 0);
assert.equal(jobs('Work Experience-2 Client Example Inc, Data Migration Consultant from March 2025 till Feb 2026.').length, 0);
console.log('Numbered work experience and project organization isolation: passed');
