import assert from 'node:assert/strict';
import { normalizeActualCandidateSchema } from '../lib/candidate360SchemaNormalize';
const jobs = (raw_text: string) => normalizeActualCandidateSchema({raw_text}).enterpriseProfile.employmentTimeline;
const quoted = jobs('Currently working as SAP FI/CO Consultant with “Example Technologies”, Malaysia from June-2021 till date. Worked as SAP FI/CO Consultant with “Example Consulting”, Hyderabad from Oct-2017 – May 31-2021. Worked as an Accountant in “Example Services”, Hyderabad from Aug-2016 to Sep-2017.');
assert.equal(quoted.length, 3);
assert.equal(quoted[0].company, 'Example Technologies');
assert.equal(quoted[0].current, true);
assert.equal(quoted[1].end, 'May 2021');
assert.equal(quoted[2].title, 'Accountant');
const label = jobs('Work Experience: Employer Example Consulting Date of Employment August 2019 - Now Position SAP consultant PM Module (Plant Maintenance) Presale Example Project Role: Lead Consultant');
assert.equal(label.length, 1);
assert.equal(label[0].company, 'Example Consulting');
assert.equal(label[0].title, 'SAP Consultant PM Module (Plant Maintenance)');
const employerOnly = jobs('Selected Project Experience Employer Example Consulting Duration Jan 2010 - Present Client Example Client Project Duration Aug 2012 - Present Role MM Consultant');
assert.equal(employerOnly.length, 1);
assert.equal(employerOnly[0].company, 'Example Consulting');
assert.equal(employerOnly[0].title, '');
assert.equal(employerOnly[0].start, 'Jan 2010');
const borrowed = jobs('Selected Project Experience Employer Example Consulting Duration unknown Client Example Client Project Duration Aug 2012 - Present Role MM Consultant');
assert.equal(borrowed.length, 0);
assert.equal(jobs('Employer Example Consulting Client Example Client Duration August 2019 - Now Position SAP Consultant').length, 0);
assert.equal(jobs('Worked as SAP Consultant with “Example Consulting” from June-2023 to May-2020.').length, 0);
console.log('Explicit employer statements and project-date isolation: passed');
