import assert from 'node:assert/strict';
import { normalizeActualCandidateSchema } from '../lib/candidate360SchemaNormalize';
const jobs = (raw_text: string) => normalizeActualCandidateSchema({raw_text}).enterpriseProfile.employmentTimeline;
const source = 'Employment History 1. Example Telecom July 2012 – Present Position Title (Level) : SAP BW Managing Consultant (Freelance) (Manager) Role : Functional Consultant Industry : Telecom Responsibility narrative. 2. Example Systems March 2012 - July 2012 Position Title (Level) : SAP BW Consultant (Manager) Role : Functional Consultant Industry : Software Education Degree';
const rows = jobs(source);
assert.equal(rows.length, 2);
assert.equal(rows[0].company, 'Example Telecom');
assert.equal(rows[0].current, true);
assert.equal(rows[1].start, 'March 2012');
assert.equal(rows[1].end, 'July 2012');
const inverted = jobs('Employment History 2022 December – Present 1. Example Consulting Sdn Bhd Position Title (Level) : SAP Consultant (Senior Executive) Specialization : Software Work Description : Supported projects. 2018 October – 2022 November 2. Example Solutions Sdn Bhd Position Title (Level) : ERP Consultant (Senior Executive) Specialization : Software Education Degree');
assert.equal(inverted.length, 2);
assert.equal(inverted[0].start, 'December 2022');
assert.equal(inverted[1].end, 'November 2022');
assert.equal(jobs(source.replace('Employment History', 'Project History')).length, 0);
assert.equal(jobs('Employment History 1. Client Example Systems July 2012 – Present Position Title (Level) : SAP Consultant Role : Consultant').length, 0);
assert.equal(jobs('Employment History 1. Example Systems July 2022 – July 2012 Position Title (Level) : SAP Consultant Role : Consultant').length, 0);
assert.equal(jobs('Employment History 1. Example Systems Position Title (Level) : SAP Consultant Role : Consultant Project Duration: July 2012 – Present').length, 0);
console.log('Numbered employment title labels and year-first dates: passed');
