import fs from "node:fs";
import path from "node:path";
import { recruiterRouteRegistry } from "../lib/recruiterRouteRegistry";
import { buildUiSmokeTestData } from "../lib/uiSmokeTestData";

type SmokeData=Awaited<ReturnType<typeof buildUiSmokeTestData>>;
const route=(feature:string,fallback:string)=>recruiterRouteRegistry.find(item=>item.type==="page"&&item.feature===feature)?.route||fallback;
export function buildUiCheckRoutes(smoke:Partial<SmokeData>|null=null){const ids=smoke?.candidateIds?.filter(Boolean).slice(0,5)||[];const candidateId=smoke?.sampleCandidateId||ids[0]||null;const selection=ids.length>=2?ids.map(encodeURIComponent).join(","):null;return{generatedAt:new Date().toISOString(),mode:"read-only UI check route printer; no candidate DB writes; no OpenAI calls",sampleAvailable:Boolean(candidateId&&selection),warning:candidateId&&selection?null:"Ready-for-shortlist sample candidates are unavailable; placeholder routes were generated.",dashboard:route("Recruiter Dashboard","/recruiter/dashboard"),workflow:route("Recruiter Workflow","/recruiter/workflow"),smartShortlist:route("Smart Shortlist","/recruiter/smart-shortlist"),candidate360:candidateId?`/recruiter/candidate360/${encodeURIComponent(candidateId)}`:"/recruiter/candidate360/<sampleCandidateId>",selfConfirm:candidateId?`/candidate/self-confirm/${encodeURIComponent(candidateId)}`:"/candidate/self-confirm/<sampleCandidateId>",candidateCompare:selection?`/recruiter/candidate-compare?candidateIds=${selection}`:"/recruiter/candidate-compare",submissionGenerator:candidateId?`/recruiter/submission-generator?candidateId=${encodeURIComponent(candidateId)}`:"/recruiter/submission-generator",clientReport:selection?`/recruiter/client-report?candidateIds=${selection}`:"/recruiter/client-report",importStaging:route("Import Staging","/recruiter/import-staging"),importMerge:route("Import Merge Approval","/recruiter/import-merge"),candidateIds:ids,candidateDbWrites:0,openAiCalls:0};}
export async function loadUiCheckRoutes(loader:()=>Promise<SmokeData>=buildUiSmokeTestData){try{return buildUiCheckRoutes(await loader());}catch{return buildUiCheckRoutes(null);}}
async function main(){const report=await loadUiCheckRoutes();fs.writeFileSync(path.join(process.cwd(),"reports","ui-check-routes.json"),`${JSON.stringify(report,null,2)}\n`);console.log(`Mode: ${report.mode}`);console.log(`Dashboard: ${report.dashboard}`);console.log(`Workflow: ${report.workflow}`);console.log(`Smart Shortlist: ${report.smartShortlist}`);console.log(`Candidate360 sample: ${report.candidate360}`);console.log(`Self-confirm sample: ${report.selfConfirm}`);console.log(`Candidate Compare sample: ${report.candidateCompare}`);console.log(`Submission Generator sample: ${report.submissionGenerator}`);console.log(`Client Report sample: ${report.clientReport}`);console.log(`Import Staging: ${report.importStaging}`);console.log(`Import Merge: ${report.importMerge}`);if(report.warning)console.log(`Warning: ${report.warning}`);}
if(process.argv[1]?.replace(/\\/g,"/").endsWith("scripts/printUiCheckRoutes.ts"))main().catch(error=>{console.error(error);process.exitCode=1});


