import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildQuickFixReviewPromotion } from "../lib/quickFixReviewPromotion";
import { buildQuickFixApprovalWriteResult } from "../lib/quickFixApprovalWrite";
import { buildReviewWorkspace } from "../lib/aiExtractionReviewUi";
import { buildAiExtractionStagingPreview } from "../lib/aiExtractionStagingPreview";

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "quick-fix-promotion-"));
const suggestionsPath = path.join(tmp, "suggestions.json");
const reviewPath = path.join(tmp, "review.json");
const approvalsPath = path.join(tmp, "approvals.json");
const suggestion: any = { suggestionId: "c1:currentCompany", candidateId: "c1", candidateName: "Candidate", fieldName: "currentCompany", currentValue: "", suggestedValue: "Acme Consulting", confidence: 92, confidenceBand: "high", evidenceSource: "structured", evidenceSnippet: "Acme Consulting | SAP Consultant", repairCategory: "quick_fix_missing_company", priority: "P1", validationStatus: "safe_suggestion", approvalReadiness: "ready_for_manual_approval", validationReasons: [], safetyNote: "review" };
fs.writeFileSync(suggestionsPath, JSON.stringify({ generatedAt: "", mode: "test", candidatesProcessed: 1, suggestions: [suggestion], summary: {} }));
fs.writeFileSync(reviewPath, JSON.stringify({ exportedAt: "", summary: {}, queueItems: [], fieldComparisons: [] }));
const preview = buildQuickFixReviewPromotion({ suggestionsPath, reviewPath });
assert.equal(preview.reviewItemsReady, 1, "promotion preview prepares review item");
assert.equal(JSON.parse(fs.readFileSync(reviewPath, "utf8")).fieldComparisons.length, 0, "preview does not write review file");
const blockedApproval = buildQuickFixApprovalWriteResult({ suggestionsPath, approvalsPath, reviewPath });
assert.equal(blockedApproval.summary.approvalDecisionsReady, 0, "approval write blocks if matching review item missing");
assert.equal(blockedApproval.blocked[0].blockReasons.includes("missing matching review item; promote quick-fix suggestion to review first"), true, "missing review reason reported");
const promoted = buildQuickFixReviewPromotion({ suggestionsPath, reviewPath, writeReviewFile: true });
assert.equal(promoted.reviewItemsWritten, 1, "review promotion writes only review file when explicit");
const approval = buildQuickFixApprovalWriteResult({ suggestionsPath, approvalsPath, reviewPath, writeApprovalsFile: true });
assert.equal(approval.summary.approvalDecisionsReady, 1, "approval write succeeds after review promotion");
const workspace = buildReviewWorkspace(promoted.mergedReviewReport, null, null, { reviewReportFound: true });
const staging = buildAiExtractionStagingPreview(workspace, approval.approvals as any);
assert.equal(staging.validStagingItems, 1, "staging dry-run sees quick-fix approvals as valid after promotion");
const source = fs.readFileSync(new URL("../lib/quickFixReviewPromotion.ts", import.meta.url), "utf8") + fs.readFileSync(new URL("../lib/quickFixReviewMerge.ts", import.meta.url), "utf8");
assert.equal(/\.delete\(|\.update\(|\.insert\(|upsert\(/i.test(source), false, "no candidate DB writes and no delete");
assert.equal(/from ["']openai["']|new\s+OpenAI\b/i.test(source), false, "no OpenAI calls");
console.log("Quick fix review promotion tests passed");
