import assert from "node:assert/strict";
import {existsSync,readFileSync} from "node:fs";
import {buildCurrentSafePreflightReport,buildEmptyConfigurationPreflight,buildFullyApprovedStagingPreflightSimulation,buildIncompleteStagingPreflightSimulation,buildLocalPreflightSimulation,buildProductionPreflightSimulation,buildStagingRequestedPreflightSimulation,buildTestPreflightSimulation,validateStagingAuthPreflightReport} from "../lib/stagingAuthPreflight";
import {runStagingAuthPreflightCli} from "./stagingAuthPreflight";
const current=buildCurrentSafePreflightReport(),empty=buildEmptyConfigurationPreflight(),local=buildLocalPreflightSimulation(),test=buildTestPreflightSimulation(),prod=buildProductionPreflightSimulation(false),prodEnabled=buildProductionPreflightSimulation(true),requested=buildStagingRequestedPreflightSimulation(),incomplete=buildIncompleteStagingPreflightSimulation(),approved=buildFullyApprovedStagingPreflightSimulation();
const reports=[current,empty,local,test,prod,prodEnabled,requested,incomplete,approved];
assert(existsSync("scripts/stagingAuthPreflight.ts"));assert(existsSync("docs/staging-auth-preflight.md"));
assert(reports.every(x=>validateStagingAuthPreflightReport(x).valid&&x.productionBlocked&&x.safety.productionBlocked));
assert(reports.every(x=>x.safety.approvalDbWrites===0&&x.safety.environmentFilesModified===false));
assert(!empty.globallyAllowed&&!local.globallyAllowed&&!test.globallyAllowed);assert.equal(prod.status,"production_blocked");assert.equal(prodEnabled.status,"production_blocked");assert(!requested.globallyAllowed);
assert.equal(incomplete.mode,"incomplete_staging_simulation");assert.equal(incomplete.status,"blocked");assert.equal(incomplete.globallyAllowed,false);assert.equal(incomplete.productionBlocked,true);assert(incomplete.blockers.length>0);
assert.equal(approved.status,"ready_for_staging_implementation");assert(approved.globallyAllowed);assert.equal(approved.environment,"staging");assert.equal(approved.authMode,"staging_approved");assert.equal(approved.capabilitySummary.total,10);assert.equal(approved.capabilitySummary.allowed,10);assert.equal(approved.capabilitySummary.blocked,0);assert.deepEqual(approved.blockers,[]);assert.equal(approved.productionBlocked,true);assert.equal(approved.simulationOnly,true);assert.equal(current.capabilitySummary.total,10);assert.equal(current.capabilitySummary.allowed,0);
assert.equal(runStagingAuthPreflightCli([]).exitCode,0);assert.equal(runStagingAuthPreflightCli(["--strict"]).exitCode,1);assert.equal(runStagingAuthPreflightCli(["--strict","--simulate-approved"]).exitCode,0);assert.equal(runStagingAuthPreflightCli(["--strict","--simulate-incomplete"]).exitCode,1);assert.equal(runStagingAuthPreflightCli(["--simulate-approved","--write-report"],()=>{throw new Error("sensitive detail")}).exitCode,3);assert.equal(runStagingAuthPreflightCli(["--simulate-local","--simulate-test"]).exitCode,2);
const approvedHuman=runStagingAuthPreflightCli(["--simulate-approved"]).output;assert.match(approvedHuman,/^Status: ready_for_staging_implementation$/m);const approvedJson=runStagingAuthPreflightCli(["--simulate-approved","--json"]).output;assert.equal(JSON.parse(approvedJson).status,"ready_for_staging_implementation");assert.deepEqual(new Set(reports.map(x=>x.status)),new Set(["invalid_configuration","blocked","production_blocked","ready_for_staging_implementation"]));const human=runStagingAuthPreflightCli([]).output;assert.match(human,/^Status: /m);assert.match(human,/^Environment files modified: no$/m);assert.match(human,/^Approval DB writes: 0$/m);
const json=runStagingAuthPreflightCli(["--json"]).output;assert.equal(JSON.parse(json).safety.approvalDbWrites,0);assert.doesNotMatch(json,/SUPABASE_URL|SUPABASE_KEY|SERVICE_ROLE_KEY|connection_string/i);
const incompleteCli=runStagingAuthPreflightCli(["--simulate-incomplete"]);assert.equal(incompleteCli.report?.mode,"incomplete_staging_simulation");assert.equal(incompleteCli.report?.globallyAllowed,false);
let written="";const write=runStagingAuthPreflightCli(["--simulate-approved","--write-report"],r=>{written=JSON.stringify(r)});assert(write.writeRequested&&written.includes("fully_approved_staging_simulation"));assert.equal(JSON.parse(written).safety.approvalDbWrites,0);assert.doesNotMatch(written,/SUPABASE_URL|SUPABASE_KEY|SERVICE_ROLE_KEY|connection_string/i);
assert(reports.every(x=>Object.values(x.safety).every(v=>v===false||v===0||v===true)&&x.safety.supabaseCalls===0&&x.safety.databaseWrites===0&&x.safety.approvalDbWrites===0));
assert(reports.every(x=>x.safety.commandsExecuted===0&&x.safety.sqlStatementsExecuted===0&&x.safety.migrationsExecuted===0&&x.safety.rlsPoliciesExecuted===0&&x.safety.authCalls===0&&x.safety.emailSends===0&&x.safety.openAiCalls===0));const source=readFileSync("lib/stagingAuthPreflight.ts","utf8")+readFileSync("scripts/stagingAuthPreflight.ts","utf8")+readFileSync("lib/stagingAuthExecutionGateRuntime.ts","utf8");assert(!source.includes(".env.local"));assert(!source.includes("createClient("));
console.log("stagingAuthPreflight.test.ts passed");


