import assert from "node:assert/strict";
import {existsSync,readFileSync} from "node:fs";
import {buildStagingAuthSqlArtifactReview,calculateStagingAuthSqlArtifactFingerprint,readStagingAuthSqlArtifact,STAGING_AUTH_SQL_ARTIFACT_PATHS,STAGING_AUTH_SQL_V1_PATHS,STAGING_AUTH_SQL_V2_PATHS,STAGING_AUTH_SQL_V3_PATHS,STAGING_AUTH_SQL_V4_CORE_FINGERPRINTS,STAGING_AUTH_SQL_V4_PATHS,validateStagingAuthSqlArtifacts} from "../lib/stagingAuthSqlArtifacts";
const review=buildStagingAuthSqlArtifactReview(),read=(k:keyof typeof STAGING_AUTH_SQL_ARTIFACT_PATHS)=>readStagingAuthSqlArtifact(STAGING_AUTH_SQL_ARTIFACT_PATHS[k]);
for(const p of [...Object.values(STAGING_AUTH_SQL_V1_PATHS),...Object.values(STAGING_AUTH_SQL_V2_PATHS),...Object.values(STAGING_AUTH_SQL_V3_PATHS),...Object.values(STAGING_AUTH_SQL_V4_PATHS)])assert(existsSync(p));
assert(review.historicalArtifacts.filter(x=>x.artifactVersion==="v1").every(x=>x.reviewStatus==="rejected"));
assert(review.historicalArtifacts.filter(x=>x.artifactVersion==="v2").every(x=>x.reviewStatus==="rejected"));
assert(review.historicalArtifacts.filter(x=>x.artifactVersion==="v3").every(x=>x.reviewStatus==="read_only_preflight_passed_rejected_for_mutation"));
assert(review.historicalArtifacts.filter(x=>x.artifactVersion==="v4").every(x=>x.reviewStatus==="rejected"&&!x.executed&&!x.authoritative));
assert.equal(review.historicalArtifacts.filter(x=>x.artifactVersion==="v3"&&x.executed).length,1);
assert.equal(review.v3PreflightEvidence.result,"passed");assert.equal(review.v3PreflightEvidence.databaseMutation,false);
assert.equal(review.authoritativeVersion,"v5");assert.deepEqual(review.executionOrder,["preflight","schema","helpers","bootstrap","rls"]);assert.deepEqual(review.rollbackOrder,["rlsRollback","bootstrapRollback","helpersRollback","schemaRollback"]);
assert.equal(review.artifacts.length,9);assert(review.artifacts.every(x=>x.artifactVersion==="v5"&&x.reviewStatus==="pending_manual_review"&&x.authoritative&&!x.executed&&!x.manuallyReviewed));
for(const a of review.artifacts)assert.equal(a.fingerprint,calculateStagingAuthSqlArtifactFingerprint(readStagingAuthSqlArtifact(a.path)));
for(const key of Object.keys(STAGING_AUTH_SQL_V4_CORE_FINGERPRINTS) as Array<keyof typeof STAGING_AUTH_SQL_V4_CORE_FINGERPRINTS>)assert.equal(calculateStagingAuthSqlArtifactFingerprint(readStagingAuthSqlArtifact(STAGING_AUTH_SQL_V4_PATHS[key])),STAGING_AUTH_SQL_V4_CORE_FINGERPRINTS[key]);
assert.equal(calculateStagingAuthSqlArtifactFingerprint(readStagingAuthSqlArtifact(STAGING_AUTH_SQL_V4_PATHS.bootstrap)),"a5e3408dca2de6093fb487c90e9f8562ed5e7b0d57b46cefff137575af3cf103");
assert.equal(calculateStagingAuthSqlArtifactFingerprint(readStagingAuthSqlArtifact(STAGING_AUTH_SQL_V4_PATHS.bootstrapRollback)),"f0656f45715d487f2c5be586362af14990af4a2f1bcc27b170cb37f977cf522a");
const preflight=read("preflight"),schema=read("schema"),helpers=read("helpers"),bootstrap=read("bootstrap"),rls=read("rls"),rr=read("rlsRollback"),rollback=read("bootstrapRollback"),hr=read("helpersRollback"),sr=read("schemaRollback"),all=[preflight,schema,helpers,bootstrap,rls,rr,rollback,hr,sr].join("\n");
assert.match(preflight,/begin;\s*set transaction read only/i);assert.match(preflight,/\brollback;/i);assert.match(preflight,/to_regprocedure\('auth\.uid\(\)'\)/);
assert.match(schema,/create table public\.staging_auth_bootstrap_provenance/);assert.match(helpers,/security definer/);assert.match(rls,/staging_auth_v4_admin_bootstrap_provenance_select/);
for(const sql of [bootstrap,rollback]){
 assert.match(sql,/v_bootstrap_reference constant text/);
 assert.doesNotMatch(sql,/\bbootstrap_reference\s+constant\s+text/i);
 assert.doesNotMatch(sql,/btrim\s*\(\s*bootstrap_reference\s*\)/i);
 assert.match(sql,/p\.bootstrap_reference\s*=\s*v_bootstrap_reference/);
 assert.match(sql,/pg_advisory_xact_lock\(731942607230017\)/);
 assert.doesNotMatch(sql,/\blike\s+'__STAGING/i);
}
for(const placeholder of ["__STAGING_BOOTSTRAP_PROVENANCE_ID__","__STAGING_ORGANIZATION_ID__","__STAGING_ORGANIZATION_NAME__","__STAGING_AUTH_USER_ID__","__STAGING_ADMIN_PROFILE_ID__","__STAGING_ADMIN_EMAIL__","__STAGING_BOOTSTRAP_REFERENCE__"])assert(bootstrap.includes(placeholder)&&rollback.includes(placeholder));
assert.match(bootstrap,/from auth\.users u where u\.id = v_auth_user_id for share/);assert.match(bootstrap,/confirmed_auth_email <> admin_email/);assert.equal((bootstrap.match(/insert_count_invalid/g)||[]).length,3);
assert.match(rollback,/delete from public\.staging_auth_bootstrap_provenance p[\s\S]*p\.bootstrap_reference=v_bootstrap_reference/);assert(rollback.indexOf("delete from public.staging_auth_bootstrap_provenance")<rollback.indexOf("delete from public.user_profiles"));assert(rollback.indexOf("delete from public.user_profiles")<rollback.indexOf("delete from public.organizations"));assert.equal((rollback.match(/delete_count_invalid/g)||[]).length,3);
assert.doesNotMatch(all,/(alter|update|delete|drop|insert into|copy)\s+(table\s+|from\s+)?public\.candidates\b/i);assert.doesNotMatch(all,/\b(delete|update|insert into)\s+(from\s+)?auth\.users\b/i);assert.doesNotMatch(all,/https?:\/\/|service_role|password\s*=/i);
for(const rollbackArtifact of [rr,rollback,hr,sr])assert.match(rollbackArtifact,/NOT EXECUTED/);
const docs=readFileSync("docs/staging-auth-sql-review.md","utf8"),plan=readFileSync("docs/staging-auth-v3-validation-plan.md","utf8");for(const phrase of ["V3 READ-ONLY PREFLIGHT PASSED","V4 CHAIN REJECTED","V5 PENDING MANUAL REVIEW","V5 composite","FORCE RLS"])assert(docs.toLowerCase().includes(phrase.toLowerCase()));assert.match(plan,/V5 PENDING MANUAL REVIEW/);
const validation=validateStagingAuthSqlArtifacts();assert(validation.valid,validation.issues.join(","));assert.equal(review.safety.sqlExecuted,0);assert.equal(review.safety.productionBlocked,true);console.log("stagingAuthSqlArtifacts.test.ts passed");