import {mkdirSync,writeFileSync} from "node:fs";
import {dirname,resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {buildCurrentSafePreflightReport,buildEmptyConfigurationPreflight,buildFullyApprovedStagingPreflightSimulation,buildIncompleteStagingPreflightSimulation,buildLocalPreflightSimulation,buildProductionPreflightSimulation,buildStagingRequestedPreflightSimulation,buildTestPreflightSimulation} from "../lib/stagingAuthPreflight";
import type {StagingAuthPreflightReport} from "../lib/stagingAuthPreflightTypes";
const simulationFlags=["--simulate-empty","--simulate-local","--simulate-test","--simulate-production","--simulate-production-enabled","--simulate-staging-requested","--simulate-incomplete","--simulate-approved"] as const;
export type PreflightCliResult={exitCode:number;output:string;report?:StagingAuthPreflightReport;writeRequested:boolean};
export function formatStagingAuthPreflight(report:StagingAuthPreflightReport){const yes=(x:boolean)=>x?"yes":"no";return ["Mode: Staging Auth Preflight",`Preflight mode: ${report.mode}`,`Status: ${report.status}`,`Environment: ${report.environment}`,`Auth mode: ${report.authMode}`,`Global gate allowed: ${yes(report.globallyAllowed)}`,`Capabilities total: ${report.capabilitySummary.total}`,`Capabilities allowed: ${report.capabilitySummary.allowed}`,`Capabilities blocked: ${report.capabilitySummary.blocked}`,`Production blocked: ${yes(report.productionBlocked)}`,`Blocker keys: ${report.blockers.join(", ")||"none"}`,"Raw environment values exposed: no","Secret values inspected: no","Environment files modified: no","Supabase calls: 0","Auth calls: 0","Commands executed: 0","SQL executed: no","Migrations executed: no","RLS executed: no","Middleware created: no","Middleware enforced: no","Sessions created: 0","Cookies read: 0","Cookies set: 0","Database writes: 0","Approval DB writes: 0","Email sends: 0","No OpenAI calls: yes"].join("\n")}
function selectReport(flag:string|undefined){switch(flag){case"--simulate-empty":return buildEmptyConfigurationPreflight();case"--simulate-local":return buildLocalPreflightSimulation();case"--simulate-test":return buildTestPreflightSimulation();case"--simulate-production":return buildProductionPreflightSimulation(false);case"--simulate-production-enabled":return buildProductionPreflightSimulation(true);case"--simulate-staging-requested":return buildStagingRequestedPreflightSimulation();case"--simulate-incomplete":return buildIncompleteStagingPreflightSimulation();case"--simulate-approved":return buildFullyApprovedStagingPreflightSimulation();default:return buildCurrentSafePreflightReport()}}
export function runStagingAuthPreflightCli(args:string[],writeReport?:(report:StagingAuthPreflightReport)=>void):PreflightCliResult{const selected=simulationFlags.filter(x=>args.includes(x));if(selected.length>1)return{exitCode:2,output:"Usage error: choose exactly one simulation option.",writeRequested:false};const known=new Set<string>([...simulationFlags,"--json","--strict","--write-report"]),unknown=args.filter(x=>!known.has(x));if(unknown.length)return{exitCode:2,output:"Usage error: unsupported option.",writeRequested:false};try{const report=selectReport(selected[0]),writeRequested=args.includes("--write-report");if(writeRequested&&writeReport)writeReport(report);const ready=report.status==="ready_for_staging_implementation";return{exitCode:args.includes("--strict")&&!ready?1:0,output:args.includes("--json")?JSON.stringify(report,null,2):formatStagingAuthPreflight(report),report,writeRequested}}catch{return{exitCode:3,output:"Internal error: preflight_failed",writeRequested:args.includes("--write-report")}}}
export function writeSafePreflightReport(report:StagingAuthPreflightReport,path=resolve(process.cwd(),"reports/staging-auth-preflight.json")){mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(report,null,2)+"\n","utf8")}
if(fileURLToPath(import.meta.url)===resolve(process.argv[1]||"")){const result=runStagingAuthPreflightCli(process.argv.slice(2),writeSafePreflightReport);console.log(result.output);process.exitCode=result.exitCode}


