"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { filterAndSortSmartShortlist, type SmartShortlistCard, type SmartShortlistFilters } from "@/lib/smartShortlist";

type Board = { generatedAt: string; workflowGeneratedAt: string; source: string; summary: Record<string, number>; candidates: SmartShortlistCard[] };
const inputClass = "rounded-md border border-slate-700 bg-[#05070A] px-3 py-2 text-sm text-slate-100 outline-none focus:border-cyan-400";
const stats: Array<[string,string]> = [["Ready for shortlist","readyForShortlist"],["High completeness","highCompleteness"],["Low completeness","lowCompleteness"],["Missing company","missingCurrentCompany"],["Missing title","missingTitle"],["Missing location","missingLocation"],["Needs confirmation","needsCandidateConfirmation"]];

export default function SmartShortlistPage() {
  const [board,setBoard]=useState<Board|null>(null), [error,setError]=useState("");
  const [filters,setFilters]=useState<SmartShortlistFilters>({ completeness:"all", verification:"all", sort:"completeness_desc", includeNeedsRepair:false });
  useEffect(()=>{const controller=new AbortController(); fetch("/api/recruiter/smart-shortlist",{signal:controller.signal}).then(async response=>{const json=await response.json();if(!response.ok)throw new Error(json.error||"Unable to load board");setBoard(json)}).catch(reason=>{if(reason?.name!=="AbortError")setError(reason.message)});return()=>controller.abort()},[]);
  const cards=useMemo(()=>filterAndSortSmartShortlist(board?.candidates||[],filters),[board,filters]);
  const set=(key:keyof SmartShortlistFilters,value:unknown)=>setFilters(current=>({...current,[key]:value}));
  return <main className="min-h-screen bg-[#05070A] text-slate-100"><header className="border-b border-slate-800 bg-[#070A0F] px-6 py-5"><div className="mx-auto flex max-w-[1500px] flex-wrap items-end justify-between gap-4"><div><Link href="/recruiter/workflow" className="text-sm text-cyan-200">Back to workflow</Link><h1 className="mt-2 text-3xl font-semibold text-white">Smart Shortlist Board</h1><p className="mt-1 text-sm text-slate-400">Browse workflow-approved profiles. Read-only; no candidate or workflow updates.</p></div>{board?<div className="text-right text-xs text-slate-500"><div>{board.source}</div><div>Workflow generated {board.workflowGeneratedAt}</div></div>:null}</div></header>
  <section className="mx-auto max-w-[1500px] space-y-5 px-6 py-6">{error?<div className="border border-red-500/30 bg-red-500/10 p-4 text-red-100">{error}</div>:null}{!board&&!error?<div className="border border-slate-800 bg-[#0B0F16] p-6">Loading Smart Shortlist...</div>:null}{board?<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{stats.map(([label,key])=><div key={key} className="border border-slate-800 bg-[#0B0F16] p-4"><div className="text-xs uppercase text-slate-500">{label}</div><div className="mt-2 text-3xl font-semibold">{board.summary[key]??0}</div></div>)}</div>
  <div className="grid gap-3 border border-slate-800 bg-[#0B0F16] p-4 md:grid-cols-2 xl:grid-cols-6"><input className={`${inputClass} xl:col-span-2`} placeholder="Search name, company, or title" value={filters.search||""} onChange={event=>set("search",event.target.value)}/><select aria-label="Completeness" className={inputClass} value={filters.completeness} onChange={event=>set("completeness",event.target.value)}><option value="all">All completeness</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><select aria-label="Verification" className={inputClass} value={filters.verification} onChange={event=>set("verification",event.target.value)}><option value="all">All verification</option><option value="recruiter_approved">Recruiter approved</option><option value="needs_candidate_confirmation">Needs confirmation</option><option value="missing_company">Missing company</option><option value="missing_title">Missing title</option><option value="missing_location">Missing location</option></select><input className={inputClass} placeholder="Module or skill" value={filters.skill||""} onChange={event=>set("skill",event.target.value)}/><input className={inputClass} placeholder="Location" value={filters.location||""} onChange={event=>set("location",event.target.value)}/><select aria-label="Sort candidates" className={inputClass} value={filters.sort} onChange={event=>set("sort",event.target.value)}><option value="completeness_desc">Completeness</option><option value="recently_updated">Recently updated</option><option value="name">Name</option><option value="company">Company</option><option value="needs_confirmation_first">Needs confirmation first</option></select><label className="flex items-center gap-2 text-sm text-amber-100"><input type="checkbox" checked={false} disabled/> Include needs repair (off)</label></div>
  <div className="flex justify-between text-sm text-slate-400"><span>{cards.length} profiles shown</span><span>Default status: ready for shortlist only</span></div><div className="grid gap-4 lg:grid-cols-2">{cards.map(card=><article key={card.candidateId} className="border border-slate-800 bg-[#0B0F16] p-5"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-semibold text-white">{card.name}</h2><p className="text-sm text-cyan-100">{card.title||"Title not provided"} � {card.currentCompany||"Company not provided"}</p><p className="mt-1 text-sm text-slate-400">{card.location||"Location not provided"}</p></div><div className="text-right"><div className="text-3xl font-semibold">{card.completenessScore}%</div><div className="text-xs uppercase text-slate-500">{card.completenessBucket}</div></div></div><div className="mt-3 flex flex-wrap gap-2"><span className="rounded border border-emerald-500/30 bg-emerald-500/10 px-2 py-1 text-xs text-emerald-100">ready for shortlist</span>{card.trust.recruiterApproved?<span className="rounded border border-cyan-500/30 px-2 py-1 text-xs text-cyan-100">Recruiter approved {card.trust.recruiterApproved}</span>:null}{card.needsCandidateConfirmation?<span className="rounded border border-amber-500/30 px-2 py-1 text-xs text-amber-100">Needs confirmation</span>:null}</div><p className="mt-3 text-sm text-slate-400">{card.headline||"No headline available"}</p><div className="mt-3 text-xs text-amber-100">{card.missingFields.length?`Missing: ${card.missingFields.join(", ")}`:"No foundation field warnings"}</div><div className="mt-4 flex flex-wrap gap-2"><Link href={card.candidate360Href} className="rounded bg-cyan-400 px-3 py-2 text-sm font-semibold text-slate-950">View Candidate360</Link><Link href={card.selfConfirmHref} className="rounded border border-slate-600 px-3 py-2 text-sm">Self-confirm preview</Link><button disabled className="rounded border border-slate-800 px-3 py-2 text-sm text-slate-600">Import merge</button><button disabled className="rounded border border-slate-800 px-3 py-2 text-sm text-slate-600">Compare</button></div></article>)}{!cards.length?<div className="border border-slate-800 bg-[#0B0F16] p-8 text-slate-400">No ready-for-shortlist profiles match these filters.</div>:null}</div></>:null}</section></main>;
}
