"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { Candidate360Field, Candidate360Profile } from "@/lib/candidate360Types";

function badge(value: string) {
  if (/confirmed|verified/.test(value)) return "border-emerald-500/30 bg-emerald-500/10 text-emerald-100";
  if (/conflict|review/.test(value)) return "border-amber-500/30 bg-amber-500/10 text-amber-100";
  return "border-slate-700 bg-slate-900 text-slate-300";
}
function FieldCard({ label, field }: { label: string; field: Candidate360Field }) {
  return <div className="border border-slate-800 bg-[#05070A] p-4"><div className="text-xs font-semibold uppercase text-slate-500">{label}</div><div className="mt-2 text-base text-white">{String(field.value ?? "") || "Missing"}</div><div className="mt-3 flex flex-wrap gap-2"><span className={`rounded border px-2 py-1 text-xs ${badge(field.verificationStatus)}`}>{field.verificationStatus.replace(/_/g, " ")}</span><span className="rounded border border-slate-700 px-2 py-1 text-xs text-slate-400">{field.source.replace(/_/g, " ")}</span></div>{field.conflictReason ? <p className="mt-2 text-xs text-amber-100">{field.conflictReason}</p> : null}</div>;
}

export default function RecruiterCandidate360Page({ params }: { params: Promise<{ candidateId: string }> }) {
  const [profile, setProfile] = useState<Candidate360Profile | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    const controller = new AbortController();
    params.then(({ candidateId }) => fetch(`/api/candidate360/${encodeURIComponent(candidateId)}`, { signal: controller.signal }))
      .then(async (response) => { const json = await response.json(); if (!response.ok) throw new Error(json.error || "Unable to load profile"); setProfile(json); })
      .catch((reason) => { if (reason?.name !== "AbortError") setError(reason instanceof Error ? reason.message : "Unable to load profile"); });
    return () => controller.abort();
  }, [params]);
  return <main className="min-h-screen bg-[#05070A] text-slate-100">
    <header className="border-b border-slate-800 bg-[#070A0F] px-6 py-5"><div className="mx-auto max-w-[1300px]"><Link href="/recruiter/workflow" className="text-sm text-cyan-100">Back to workflow</Link><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold text-white">Candidate360 Profile</h1><p className="mt-1 text-sm text-slate-400">Trusted-field profile foundation. Read-only; candidate records are not updated.</p></div>{profile ? <Link href={`/candidate/self-confirm/${profile.candidateId}`} className="rounded-md bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">Open self-confirm preview</Link> : null}</div></div></header>
    <section className="mx-auto max-w-[1300px] space-y-5 px-6 py-6">
      {error ? <div className="border border-red-500/30 bg-red-500/10 p-4 text-red-100">{error}</div> : null}
      {!profile && !error ? <div className="border border-slate-800 bg-[#0B0F16] p-6">Loading Candidate360 profile...</div> : null}
      {profile ? <>
        <div className="border border-slate-800 bg-[#0B0F16] p-5"><div className="flex flex-wrap justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-wider text-cyan-200">Executive Summary</div><h2 className="mt-2 text-3xl font-semibold text-white">{String(profile.displayName.value) || "Candidate requires identity confirmation"}</h2><p className="mt-1 text-slate-300">{String(profile.headline.value) || "Headline not provided"} � {String(profile.currentCompany.value) || "Company not provided"}</p><p className="mt-3 text-sm text-slate-400">{profile.workExperienceSummary}. {profile.educationSummary}.</p></div><div className="min-w-52 border border-slate-700 bg-[#05070A] p-4"><div className="text-xs uppercase text-slate-500">Completeness</div><div className="mt-1 text-4xl font-semibold text-white">{profile.completeness.score}%</div><div className="mt-2 text-xs text-slate-400">{profile.completeness.completedFields}/{profile.completeness.totalFields} foundation fields</div></div></div></div>
        <div className="border border-slate-800 bg-[#0B0F16] p-5"><h3 className="font-semibold text-white">Trust / verification summary</h3><div className="mt-3 flex flex-wrap gap-2">{Object.entries(profile.verificationSummary).map(([key, count]) => <span key={key} className={`rounded border px-3 py-2 text-xs ${badge(key)}`}>{key.replace(/_/g, " ")}: {count}</span>)}</div></div>
        <div><h3 className="mb-3 font-semibold text-white">Core fields</h3><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><FieldCard label="Current title" field={profile.currentTitle}/><FieldCard label="Current company" field={profile.currentCompany}/><FieldCard label="Location" field={profile.location}/><FieldCard label="Email" field={profile.contactInfo.email}/><FieldCard label="Phone" field={profile.contactInfo.phone}/><FieldCard label="Years experience" field={profile.yearsOfExperience}/></div></div>
        <div className="grid gap-5 lg:grid-cols-2"><div className="border border-slate-800 bg-[#0B0F16] p-5"><h3 className="font-semibold">Missing fields</h3><div className="mt-3 flex flex-wrap gap-2">{profile.missingFields.map((item) => <span key={item} className="rounded border border-amber-500/30 bg-amber-500/10 px-2 py-1 text-sm text-amber-100">{item}</span>)}{!profile.missingFields.length ? <span className="text-sm text-emerald-100">No foundation fields missing</span> : null}</div></div><div className="border border-slate-800 bg-[#0B0F16] p-5"><h3 className="font-semibold">Candidate self-confirm status</h3><p className="mt-2 text-cyan-100">{profile.selfConfirmStatus.replace(/_/g, " ")}</p><p className="mt-2 text-sm text-slate-400">Needs candidate confirmation: {profile.readiness.needsCandidateConfirmation ? "yes" : "no"} � Recruiter review: {profile.readiness.needsRecruiterReview ? "yes" : "no"}</p></div></div>
        <div className="grid gap-5 lg:grid-cols-2"><div className="border border-slate-800 bg-[#0B0F16] p-5"><h3 className="font-semibold">Work experience</h3><div className="mt-3 space-y-3">{profile.workExperience.map((item) => <div key={item.id} className="border border-slate-800 bg-[#05070A] p-3"><div className="font-semibold">{String(item.title.value) || "Role to confirm"}</div><div className="text-sm text-cyan-100">{String(item.company.value) || "Company to confirm"}</div><div className="text-xs text-slate-500">{String(item.startDate.value)} � {String(item.endDate.value) || "Present"}</div></div>)}{!profile.workExperience.length ? <p className="text-sm text-slate-400">No structured experience. Candidate should complete this section.</p> : null}</div></div><div className="border border-slate-800 bg-[#0B0F16] p-5"><h3 className="font-semibold">Skills / modules</h3><div className="mt-3 flex flex-wrap gap-2">{[...profile.sapModules, ...profile.techSkills].map((item, index) => <span key={`${item.name.value}-${index}`} className="rounded border border-cyan-500/30 bg-cyan-500/10 px-2 py-1 text-sm text-cyan-100">{String(item.name.value)}</span>)}{!profile.sapModules.length && !profile.techSkills.length ? <p className="text-sm text-slate-400">Skills need confirmation.</p> : null}</div></div></div>
        <div className="grid gap-5 lg:grid-cols-2"><div className="border border-slate-800 bg-[#0B0F16] p-5"><h3 className="font-semibold">Recruiter next actions</h3><ul className="mt-3 space-y-2 text-sm text-slate-300">{profile.recommendedRecruiterActions.map((item) => <li key={item}>� {item}</li>)}{!profile.recommendedRecruiterActions.length ? <li>No immediate recruiter action.</li> : null}</ul></div><div className="border border-slate-800 bg-[#0B0F16] p-5"><h3 className="font-semibold">Workflow status</h3><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><span className="text-slate-500">Status</span><div>{profile.workflowStatus.replace(/_/g, " ")}</div></div><div><span className="text-slate-500">Repair queue</span><div>{profile.repairQueueStatus.replace(/_/g, " ")}</div></div><div><span className="text-slate-500">Searchable</span><div>{profile.readiness.searchable ? "yes" : "no"}</div></div><div><span className="text-slate-500">Ready for shortlist</span><div>{profile.readiness.readyForShortlist ? "yes" : "no"}</div></div></div></div></div>
      </> : null}
    </section>
  </main>;
}
