import Link from "next/link";
import {buildStagingAuthE2ePreview} from "../../../lib/stagingAuthE2ePreview";
const card="rounded-2xl border border-slate-800 bg-[#0B0F16] p-5",badge="rounded-full border border-slate-700 px-3 py-1 text-xs",pretty=(x:string)=>x.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function StagingAuthE2ePage(){const p=buildStagingAuthE2ePreview(),approved=p.scenarios.find(x=>x.scenarioKey==="sign_in_approved_simulation")!,production=p.scenarios.find(x=>x.scenarioKey==="production_sign_in_blocked")!;return <main className="min-h-screen bg-[#05070A] text-slate-100"><header className="border-b border-slate-800 px-6 py-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap gap-2">{["End-to-end preview","No layer bypass","Sensitive data removed","No real auth actions","Production blocked"].map(x=><span className={badge} key={x}>{x}</span>)}</div><h1 className="mt-5 text-4xl font-semibold">Staging Auth End-to-End Preview</h1><p className="mt-2 text-slate-300">Trace the complete preview-only authentication path from UI form to safe result without executing real authentication.</p></div></header><div className="mx-auto max-w-7xl space-y-8 px-6 py-8">
<section className={card}><h2 className="font-semibold">Staging Auth Security</h2><p className="mt-3 text-sm text-slate-400">Security review available � Real staging validation pending � Open findings remain � Production blocked</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-auth-security">Open Security Review</Link></section><section className={card}><h2 className="text-xl font-semibold">E2E status</h2><p className="mt-3">Scenarios expected/generated: {p.coverage.scenariosExpected}/{p.coverage.scenariosGenerated} � Layers expected: {p.coverage.layersExpected} � Operations covered: {p.coverage.operationsCovered.length} � Bypass detected: no � Real actions executed: 0 � Production blocked: yes</p></section>
<section className={card}><h2 className="text-xl font-semibold">Architecture flow</h2><p className="mt-3 text-cyan-200">Auth UI ? Preview Server Action ? Sanitizer ? Operation Boundary ? Execution Gate ? Adapter Factory ? Disabled/Preview Adapter ? Audit/Rate-limit Preview ? Safe UI Result</p></section>
<section><h2 className="text-xl font-semibold">Scenario matrix</h2><div className="mt-4 overflow-auto"><table className="min-w-[1100px] w-full text-left text-sm"><thead><tr>{["Scenario","Status","Layers reached","Blockers","Sensitive data","Session/cookie","Redirect","Email","DB mutation","Real action"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{p.scenarios.map(x=><tr className="border-t border-slate-800" key={x.scenarioKey}><td className="p-3">{pretty(x.scenarioKey)}</td><td>{x.status}</td><td>{x.layersReached}/{x.layersExpected}</td><td>{x.traceSteps.flatMap(s=>s.blockerKeys).join(", ")||"None"}</td><td>No</td><td>No</td><td>No</td><td>No</td><td>No</td><td>No</td></tr>)}</tbody></table></div></section>
<section><h2 className="text-xl font-semibold">Layer trace</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{p.scenarios.map(x=><article className={card} key={x.scenarioKey}><h3 className="font-semibold">{pretty(x.scenarioKey)}</h3><div className="mt-3 space-y-2 text-sm">{x.traceSteps.map(s=><p key={s.order}>{s.order}. {pretty(s.layer)} � {s.status} � input/output safe: yes � persisted: no � real action: no</p>)}</div></article>)}</div></section>
<section className="grid gap-4 lg:grid-cols-3"><article className={card}><h2 className="font-semibold">Sensitive-data proof</h2><p className="mt-3 text-sm">Password in trace: no � Invitation token in trace: no � Complete email: no � Raw FormData: no � Raw environment value: no � Stack trace: no</p></article><article className={card}><h2 className="font-semibold">Approved staging simulation</h2><p className="mt-3 text-sm">Status: {approved.status}. The gate may allow the simulated path, but the adapter remains provider-not-implemented. No credential validation, session, redirect, or real action occurs.</p></article><article className={card}><h2 className="font-semibold">Production scenario</h2><p className="mt-3 text-sm">Status: {production.status}. Blocked at the execution gate; adapter disabled; no operation executed; production blocked.</p></article></section>
<section className={card}><h2 className="font-semibold">Links</h2><div className="mt-4 flex flex-wrap gap-4">{[["Auth Login Preview","/auth/login"],["Auth Operations","/admin/staging-auth-operations"],["Auth Adapter","/admin/staging-auth-adapter"],["Execution Gate","/admin/staging-execution-gate"],["Preflight CLI","/admin/staging-execution-gate"],["Platform Readiness","/admin/platform-readiness"]].map(([a,b])=><Link className="text-cyan-300" href={b} key={a}>{a}</Link>)}</div></section>
<section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-semibold">Safety panel</h2><p className="mt-2 text-sm">Supabase calls: 0 � Auth calls: 0 � Sessions/cookies: 0 � Redirects: 0 � DB reads/writes: 0 � Audit/rate-limit writes: 0 � Emails: 0 � SQL/migrations/RLS: 0 � Middleware: no � OpenAI: 0 � Production blocked: yes</p></section></div></main>}
