import Link from "next/link";import {STAGING_AUTH_ADAPTER_OPERATION_CONTRACT} from "../../../lib/stagingAuthAdapterContract";import {buildStagingAuthAdapterPreview} from "../../../lib/stagingAuthAdapterPreview";
const card="rounded-2xl border border-slate-800 bg-[#0B0F16] p-5",badge="rounded-full border border-slate-700 px-3 py-1 text-xs",label=(x:string)=>x.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function StagingAuthAdapterPage(){const preview=buildStagingAuthAdapterPreview(),disabled=preview.defaultAdapter,approved=preview.approvedSimulation,production=preview.productionAdapter;return <main className="min-h-screen bg-[#05070A] text-slate-100"><header className="border-b border-slate-800 px-6 py-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap gap-2">{["Disabled by default","Gate controlled","No Supabase client","No sessions or cookies","Production blocked"].map(x=><span className={badge} key={x}>{x}</span>)}</div><h1 className="mt-5 text-4xl font-semibold">Staging Auth Adapter</h1><p className="mt-2 text-slate-300">Review the disabled-by-default authentication contract that future staging Supabase integration must use.</p></div></header><div className="mx-auto max-w-7xl space-y-8 px-6 py-8">
<section className={card}><h2 className="text-xl font-semibold">Staging Auth Operations available</h2><p className="mt-3">Every future operation must pass through the adapter · Sensitive inputs redacted · No persistence · Production blocked</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-auth-operations">Open Auth Operations</Link></section><section className={card}><h2 className="text-xl font-semibold">Adapter status</h2><p className="mt-3">Provider: {disabled.decision.provider} · Status: {disabled.decision.status} · Execution gate: invalid configuration · Auth helpers allowed: no · Real provider implemented: no · Production blocked: yes</p></section>
<section><h2 className="text-xl font-semibold">Operation contract</h2><div className="mt-4 overflow-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr>{["Operation","Required gate capability","Sensitive input","Current behavior","Server/client eligibility","Real action executed"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{STAGING_AUTH_ADAPTER_OPERATION_CONTRACT.map(x=><tr className="border-t border-slate-800" key={x.operation}><td className="p-3">{x.label}</td><td>{x.requiredCapability}</td><td>{x.sensitiveInput}</td><td>{x.disabledBehavior}</td><td>{x.eligibility}</td><td>No</td></tr>)}</tbody></table></div></section>
<section className="grid gap-4 lg:grid-cols-3"><article className={card}><h2 className="font-semibold">Default disabled adapter</h2><p className="mt-3 text-sm">All eight operations are blocked or disabled. No session, user, profile, or auth call is created.</p><p className="mt-3 text-xs text-slate-400">Provider: {disabled.decision.provider} · Real actions: 0</p></article><article className={card}><h2 className="font-semibold">Approved staging simulation</h2><p className="mt-3 text-sm">The simulated gate may allow auth helpers, but the adapter remains {approved.decision.provider} / {approved.decision.status}. A real provider is not implemented.</p><p className="mt-3 text-xs text-slate-400">Real actions: 0 · Simulation only</p></article><article className={card}><h2 className="font-semibold">Production behavior</h2><p className="mt-3 text-sm">Provider: {production.decision.provider} · Status: {production.decision.status}. Production has no override.</p><p className="mt-3 text-xs text-rose-200">Production blocked</p></article></section>
<section className={card}><h2 className="font-semibold">Sensitive data protection</h2><p className="mt-3 text-sm">Passwords logged: no · Invitation tokens returned: no · Auth tokens returned: no · Raw environment values exposed: no · Stack traces exposed: no</p></section>
<section className={card}><h2 className="font-semibold">Links</h2><div className="mt-4 flex flex-wrap gap-4">{[["Execution Gate","/admin/staging-execution-gate"],["Preflight CLI","/admin/staging-execution-gate"],["Staging Runbook","/admin/staging-runbook"],["Staging Evidence","/admin/staging-evidence"],["Platform Readiness","/admin/platform-readiness"]].map(([a,b])=><Link className="text-cyan-300" href={b} key={a}>{a}</Link>)}</div></section>
<section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-semibold">Safety panel</h2><p className="mt-2 text-sm">Supabase imports: 0 · Supabase calls: 0 · Auth calls: 0 · Sessions created: 0 · Cookies read/set: 0 · DB reads/writes: 0 · Email sends: 0 · SQL/migrations/RLS: 0 · OpenAI calls: 0 · Production blocked: yes</p></section></div></main>}

