import Link from "next/link";
import {buildRecruiterPackCompareView} from "../../../lib/recruiterPackCompare";
const badge="rounded-full border border-slate-700 px-3 py-1 text-xs";
const button="inline-flex rounded-lg border border-slate-700 px-4 py-2 text-sm transition hover:border-cyan-400";
export default async function RecruiterPackComparePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const view=buildRecruiterPackCompareView(await searchParams),context=Object.entries(view.searchContext).filter((entry):entry is [string,string]=>Boolean(entry[1]));return <main className="min-h-screen bg-[#05070A] text-slate-100"><header className="border-b border-slate-800 bg-[#070A0F] px-6 py-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap gap-2"><span className={badge}>Read-only</span><span className={badge}>No DB writes</span><span className={badge}>Deterministic v1</span><span className={badge}>Legacy compare compatible</span></div><h1 className="mt-4 text-4xl font-semibold">Pack Compare</h1><p className="mt-2 text-cyan-100">Compare Top 5, Top 10, or Top 20 candidates from Talent Search.</p></div></header><div className="mx-auto max-w-7xl space-y-6 px-6 py-8">
<section className="rounded-2xl border border-slate-800 bg-[#0B0F16] p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><h2 className="text-lg font-semibold">Search context</h2>{context.length?<dl className="mt-3 flex flex-wrap gap-2">{context.map(([key,value])=><div key={key} className="rounded-lg border border-slate-700 px-3 py-2 text-sm"><dt className="inline capitalize text-slate-500">{key}: </dt><dd className="inline">{value}</dd></div>)}</dl>:<p className="mt-2 text-sm text-slate-400">No search filters were provided.</p>}</div><div className="flex flex-wrap gap-3"><Link href={view.recruiterResultsUrl} className="text-cyan-300">Back to results</Link><Link href="/recruiter/talent-search">Back to Talent Search</Link></div></div></section>
<section><h2 className="mb-3 text-lg font-semibold">Pack size and view</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{view.packOptions.map(option=>{const selected=option.mode===view.selectedMode;return <Link key={option.mode} href={option.url} className={`rounded-2xl border p-5 ${selected?"border-cyan-400 bg-cyan-500/10":"border-slate-800 bg-[#0B0F16]"}`}><div className="font-semibold">{option.label}</div><p className="mt-2 text-sm text-slate-400">{option.description}</p>{selected&&<span className="mt-3 inline-flex text-xs text-cyan-200">Selected</span>}</Link>})}</div></section>
<section className="rounded-2xl border border-violet-500/30 bg-violet-500/5 p-6"><h2 className="text-lg font-semibold">Pack compare actions</h2><div className="mt-4 flex flex-wrap gap-3"><Link href={view.legacyCompareUrl} className="inline-flex rounded-lg bg-violet-300 px-4 py-2 text-sm font-semibold text-slate-950">Open legacy compare view</Link><Link href={view.recruiterResultsUrl} className={button}>Open recruiter results</Link>{view.clientReportUrl?<Link href={view.clientReportUrl} className={button}>Generate client report from selected</Link>:<span aria-disabled="true" className={`${button} cursor-not-allowed text-slate-500`}>Generate client report — select IDs first</span>}{view.quickCompareUrl?<Link href={view.quickCompareUrl} className={button}>Quick Compare selected</Link>:<span aria-disabled="true" className={`${button} cursor-not-allowed text-slate-500`}>Quick Compare — select IDs first</span>}</div></section>
<section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-slate-800 bg-[#0B0F16] p-6"><h2 className="text-lg font-semibold">Choose the right comparison depth</h2><ul className="mt-4 space-y-3 text-sm text-slate-300"><li><strong>Top 5:</strong> best shortlist to review first.</li><li><strong>Top 10:</strong> deeper shortlist matrix.</li><li><strong>Top 20:</strong> longlist and market mapping.</li><li><strong>Executive Compare:</strong> client-ready comparison view.</li></ul></article><article className="rounded-2xl border border-slate-800 bg-[#0B0F16] p-6"><h2 className="text-lg font-semibold">Recruiter-native bridge</h2><p className="mt-3 text-sm leading-6 text-slate-300">This shell preserves your Talent Search context and safely opens the established legacy scoring and comparison engine. Complex comparison scoring is not duplicated here.</p><p className="mt-3 text-sm text-slate-400">Current selection: {view.selectedMode} · Top {view.selectedPackSize}</p></article></section>
<section className="rounded-2xl border border-amber-500/30 bg-amber-500/5 p-6"><h2 className="font-semibold text-amber-100">Safety note</h2><p className="mt-2 text-sm text-slate-300">This page does not write to the database. Add to shortlist remains preview-only. Client report generation remains draft/read-only. No OpenAI calls are made.</p>{view.warnings.length>0&&<ul className="mt-3 space-y-1 text-xs text-amber-100">{view.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul>}</section>
</div></main>}
