import Link from "next/link";import {buildStagingAuthImplementationRunbook} from "../../../lib/stagingAuthRunbook";
const card="rounded-2xl border border-slate-800 bg-[#0B0F16] p-5",badge="rounded-full border border-slate-700 px-3 py-1 text-xs";
export default function StagingRunbookPage(){const r=buildStagingAuthImplementationRunbook();return <main className="min-h-screen bg-[#05070A] text-slate-100"><header className="border-b border-slate-800 px-6 py-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap gap-2">{["Read-only","Commands not executed","Manual approval required","Staging only","Production blocked"].map(x=><span className={badge} key={x}>{x}</span>)}</div><h1 className="mt-5 text-4xl font-semibold">Staging Auth Implementation Runbook</h1><p className="mt-2 text-slate-300">Review the staging-only implementation sequence, evidence gates, command previews, validation checks, and rollback checkpoints before execution.</p></div></header><div className="mx-auto max-w-7xl space-y-8 px-6 py-8">
<section className={card}><h2 className="text-xl font-semibold">Staging Auth Preflight CLI available</h2><p className="mt-3">Execution gate remains authoritative � Implementation not started � Production blocked</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-execution-gate">Open preflight guidance</Link></section><section className={card}><h2 className="text-xl font-semibold">Execution gate available</h2><p className="mt-3">Locked by default � Commands executed: 0 � Production blocked</p><Link className="mt-3 inline-block text-cyan-300" href="/admin/staging-execution-gate">Open Execution Gate</Link></section><section className={card}><h2 className="text-xl font-semibold">Runbook status</h2><p className="mt-3">Current: {r.status} · Phases: {r.phases.length} · Completed: 0 · Blocked: {r.phases.filter(x=>x.status==="blocked").length} · Evidence pending: {r.evidenceRequirements.filter(x=>x.manualConfirmationRequired).length} · Approvals pending: {r.approvalRequirements.length} · Implementation started: no · Production blocked: yes</p></section>
<section><h2 className="text-xl font-semibold">Phase navigator</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.phases.map(p=><article className={card} key={p.phaseKey}><div className="flex justify-between"><h3>{p.order}. {p.label}</h3><span className={badge}>{p.status}</span></div><p className="mt-2 text-sm text-slate-400">{p.objective}</p><p className="mt-2 text-xs">Prerequisites: {p.prerequisites.join("; ")}</p><p className="mt-2 text-xs">Completion: {p.completionCriteria.join("; ")}</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Phase details</h2><div className="mt-4 space-y-4">{r.phases.map(p=><article className={card} key={p.phaseKey}><h3 className="text-lg font-semibold">{p.order}. {p.label}</h3>{p.steps.map(s=><div className="mt-3 text-sm" key={s.stepKey}><p>{s.description}</p><p className="mt-2 text-slate-400">Evidence: {s.requiredEvidence.join(", ")||"None"} · Approvals: {s.requiredApprovals.join(", ")||"None"}</p><p className="mt-2 text-slate-400">Repository changes: {s.expectedRepositoryChanges.join(", ")||"No change"} · Commands: {s.commandPreviews.join(", ")||"None"}</p><p className="mt-2 text-slate-400">Validation: {s.validationChecks.join(", ")||"Review only"} · Rollback: {s.rollbackCheckpoint}</p><p className="mt-2 text-rose-200">Stop on any listed critical condition. {s.productionProtection.join(" · ")}</p></div>)}</article>)}</div></section>
<section><h2 className="text-xl font-semibold">Repository change preview</h2><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Path","Change type","Purpose","Staging only","Status","Production impact"].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{r.repositoryChanges.map(x=><tr className="border-t border-slate-800" key={x.changeKey}><td className="p-3 font-mono">{x.path}</td><td>{x.changeType}</td><td>{x.purpose}</td><td>Yes</td><td>{x.implementationStatus}</td><td>{x.productionImpact}</td></tr>)}</tbody></table></div></section>
<section><h2 className="text-xl font-semibold">Display-only command previews</h2><p className="mt-2 text-amber-200">Do not execute until approved · Staging only · No secret values</p><div className="mt-4 grid gap-3 md:grid-cols-2">{r.commandPreviews.map(x=><article className={card} key={x.commandKey}><h3>{x.label}</h3><code className="mt-3 block whitespace-pre-wrap rounded bg-black/40 p-3 text-xs text-cyan-200">{x.commandText}</code><p className="mt-2 text-xs">Display only · Execution disallowed · Production disallowed · Expected: {x.expectedResult}</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Validation matrix</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.validationChecks.map(x=><article className={card} key={x.checkKey}><h3>{x.label}</h3><p className="text-sm text-slate-400">Expected: {x.expectedResult} · Blocking: {x.blocking?"yes":"no"} · Status: not started</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Stop conditions</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.stopConditions.map(x=><article className="rounded-2xl border border-rose-500/40 bg-rose-500/10 p-5" key={x.conditionKey}><span className={badge}>{x.severity}</span><h3 className="mt-3 font-semibold">{x.label}</h3><p className="text-sm text-rose-100">{x.reason}. {x.requiredAction}</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Rollback checkpoints</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.rollbackCheckpoints.map(x=><article className={card} key={x.checkpointKey}><h3>{x.phaseKey}: {x.label}</h3><p className="text-sm text-slate-400">Evidence: {x.evidenceStatus} · {x.rollbackActionPreview} · Execution: not executed</p></article>)}</div></section>
<section><h2 className="text-xl font-semibold">Next actions</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{r.nextActions.map(x=><article className={card} key={x.actionKey}><span className={badge}>{x.priority}</span><h3 className="mt-3">{x.label}</h3><p className="text-sm text-slate-400">{x.reason}</p>{x.route&&<Link className="text-cyan-300" href={x.route}>Open preview</Link>}</article>)}</div></section>
<section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5"><h2 className="font-semibold">Safety panel</h2><p className="mt-2 text-sm">Commands executed: 0 · No secret values inspected · No environment files modified · No Supabase calls · No SQL/migration/RLS executed · No middleware created · No sessions/cookies · No DB writes · No emails · No OpenAI calls · Implementation not started · Production blocked</p></section></div></main>}

